KSP-CKAN/CKAN

packages.config

You currently can't build with Cake on Mono 6.8, due to a complex issue I don't want to explain here, you can read it up in https://github.com/cake-build/cake/issues/2695 and all the other issues that are linked there :P
Cake 0.37.0 fixed this.
This PR updates the Cake dependency from 0.36.0 to 0.37.0, now that it is released. This allows us to build CKAN using the build script on Mono 6.8 again.
(I guess Kate also automatically removed a BOM)
Note that I don't change back the Mono versions that we're using for the NetCore build on Travis. There's still the other problem, which makes Mono 6 compiled binaries not work on Windows or Mono 5, see #2976. Although we're not using that for anything release-related, let's play it conservatively for now.
I tested the compilation on Mono 6.8 and …

Update Cake to 0.37.0

---

Spec.md

The spec has a `tags` section, but it's mostly inaccurate and misleading. Now it's brought up to date with how the tags actually work.

Update tags section of spec

---

Netkan/CmdLineOptions.cs
Netkan/Processors/QueueHandler.cs
Netkan/Program.cs
Netkan/Transformers/CurseTransformer.cs
Netkan/Transformers/GithubTransformer.cs
Netkan/Transformers/ITransformer.cs
Netkan/Transformers/JenkinsTransformer.cs
Netkan/Transformers/SpacedockTransformer.cs
Tests/NetKAN/MainClass.cs
Tests/NetKAN/NetkanOverride.cs
Tests/NetKAN/Transformers/AvcKrefTransformerTests.cs
Tests/NetKAN/Transformers/AvcTransformerTests.cs
Tests/NetKAN/Transformers/CurseTransformerTests.cs
Tests/NetKAN/Transformers/DownloadAttributeTransformerTests.cs
Tests/NetKAN/Transformers/EpochTransformerTests.cs
Tests/NetKAN/Transformers/GeneratedByTransformerTests.cs
Tests/NetKAN/Transformers/GithubTransformerTests.cs
Tests/NetKAN/Transformers/HttpTransformerTests.cs
Tests/NetKAN/Transformers/InternalCkanTransformerTests.cs
Tests/NetKAN/Transformers/MetaNetkanTransformerTests.cs
Tests/NetKAN/Transformers/SpacedockTransformerTests.cs
Tests/NetKAN/Transformers/StripNetkanMetadataTransformerTests.cs
Tests/NetKAN/Transformers/VersionEditTransformerTests.cs

#2681 gave us the great option to inflate multiple releases with netkan.exe.
But sometimes you don't want to begin with the latest release, for example if the folder structure has changed in the history of the mod, and you have to adjust the netkan file for the older releases. Or if one release is failing inflation and you have to skip it.
I had to deal with both of these cases in https://github.com/KSP-CKAN/CKAN-meta/pull/1786, so I finally decided to implement this feature.
This PR gives netkan.exe a new commandline option, `--skip-releases <int>`.
This commandline option is fed into the `TransformOptions`, which has a new `int? SkipReleases` property.
It is set with the constructor, the queue handler passes `null`.
Each kref source transformer now skips the given number of releases, …

Create skip-releases option for NetKAN

---

GUI/Main/MainChangeset.cs
GUI/Main/MainInstall.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.resx

When there's an exception thrown during the installation of mods, we catch the usual ones and log an explanation message on the WaitTabPage.
However in `PostInstallMods()` which is called when the background worker completes `InstallMods()`, the message `An unknown error occurred, please try again!` is written to the "log".
This message is actually not true most of the time, because e.g. download errors or inconsistency problems are all catched and a nice explaining error message has already been printed out.
Now `PostInstallMods()` distinguishes catched and uncatched errors (the second one will result in `RunWorkerCompletedEventArgs.Error` being set).
It keeps the old message for uncatched errors, but displays a new one for known ones:
```
If the above message indicates a download error, …
```

Don't report an unknown error if it is known

---

Core/Types/GameComparator/StrictGameComparator.cs
Core/Versioning/KspVersionRange.cs
GUI/Main/Main.cs
Tests/Core/Versioning/KspVersionRangeTests.cs

#2902, which was fixed for KSP 1.8 in #2931, still applies to KSP 1.9 unfortunately:
```
Set current directory to /HDD/KubuntuSteamGames/steamapps/common/Kerbal Space Program
Found path: /HDD/KubuntuSteamGames/steamapps/common/Kerbal Space Program/KSP.x86_64
Speicherzugriffsfehler (Speicherabzug geschrieben)
```
(Now you know the German translation for a segmentation fault)
The version range for which we remove the `-single-instance` command has been extended to include 1.9.
I created a new helper function which allows to create a `KspVersionRange` from two `KspVersion` objects. The resulting version range extends from the lowest possible version of the first argument to the highest possible version of the second argument.
It uses the `KspVersion`->`KspVersionRange` logic from …

Extend -single-instance fix to 1.9

---

Core/Registry/CompatibilitySorter.cs

In a KSP 1.9.0 install with no additional versions marked compatible, 115 modules are shown as compatible, but 21 of them can't be installed due to missing dependencies.
SVE-HighResolution has a bit of a crazy history. It currently **depends on** StockVisualEnhancements, but in versions 1:104–2:1.1.6 it **provided** StockVisualEnhancements.
The compatibility resolver from #2963 is confused by this. It tries to allow any compatible version of a module to satisfy a dependency, but circular dependencies are treated as tentatively compatible because otherwise they'd be impossible to resolve. This might be OK, except it *also* uses the provides-index from #2354 to resolve `"provides"`-based relationships, and that index is compatibility-agnostic; incompatible providing modules are included. …

Check compatibility of providing modules

---

Core/KSP.cs

Normally if you launch CKAN, the "default install" is loaded.
If you install `ckan.exe` inside a game folder and launch it from there, that game folder is loaded instead.
For users who work with multiple installs but run CKAN from a single system install point (fewer copies of `ckan.exe` means fewer updates for a new release), it has been suggested that it would be nice to also check the current directory.
Now if you run CKAN from a game dir (currently defined by the "portable" logic as a directory having a `GameData` directory inside of it), we will open it as a "portable" install. This works for CmdLine, ConsoleUI, and GUI.
Fixes #2956.

Check current dir for portable install

---

ConsoleUI/DependencyScreen.cs
ConsoleUI/InstallScreen.cs
Core/ModuleInstaller.cs
Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
Core/Relationships/RelationshipResolver.cs
Core/Relationships/SanityChecker.cs
GUI/Main/MainInstall.cs
GUI/Main/MainModList.cs
Tests/Core/ModuleInstaller.cs
Tests/Core/Relationships/SanityChecker.cs

Found out thanks to [this comment](https://forum.kerbalspaceprogram.com/index.php?/topic/159443-12-181-spectra-v124-visual-compilation-10th-february-20/&do=findComment&comment=3739637) on the Spectra forum thread.
Currently when uninstalling dependencies of a mod and installing a new mod that also provides these dependencies, CKAN will remove the dependent mod, even though its dependencies will be satisfied after the process completed, thanks to the new mod.
Scatterer depends on Scatterer-config and Scatterer-sunflare.
Spectra provides both of these modules.
When you have Scatterer installed with its default config + sunflare and mark Spectra for installation, CKAN correctly reports conflicts.
Then you de-select the default config + sunflare so they get uninstalled.
Even though Spectra …

Respect installing modules during dependency resolution

---

Core/Net/Repo.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Dialogs/YesNoDialog.cs
GUI/Main/Main.cs
GUI/Main/MainDialogs.cs

My Mono does a hard crash when CKAN tries to ask the user whether to reinstall a changed mod after a refresh:
```
at <unknown> <0xffffffff>
at System.Windows.Forms.X11Keyboard:XCreateFontSet <0x000ce>
at System.Windows.Forms.X11Keyboard:CreateOverTheSpotXic <0x000e7>
at System.Windows.Forms.X11Keyboard:CreateXic <0x00117>
at System.Windows.Forms.X11Keyboard:CreateXicForWindow <0x00053>
at System.Windows.Forms.X11Keyboard:FocusIn <0x000c3>
at System.Windows.Forms.XplatUIX11:SetFocus <0x000ef>
at System.Windows.Forms.XplatUI:SetFocus <0x0003c>
at System.Windows.Forms.ContainerControl:SendControlFocus <0x000bf>
at System.Windows.Forms.Form:SetVisibleCore <0x004f3>
at System.Windows.Forms.Control:set_Visible <0x0004b>
at System.Windows.Forms.Control:set_Visible <0x00083>
at …
```

Fix reinstall prompt crash

---

Core/ModuleInstaller.cs
Core/Relationships/RelationshipResolver.cs
GUI/Controls/ThemedTabControl.cs

If you install a `depends`-based modpack, its mods will be queued for removal automatically:
This may also cause a crash:
```
System.ArgumentOutOfRangeException: InvalidArgument=Verdi 2 er en ugyldig for index.
Parameternavn: index
ved System.Windows.Forms.TabControl.GetTabPage(Int32 index)
ved System.Windows.Forms.TabControl.TabPageCollection.get_Item(Int32 index)
ved CKAN.ThemedTabControl.OnDrawItem(DrawItemEventArgs e)
ved System.Windows.Forms.TabControl.WmReflectDrawItem(Message& m)
ved System.Windows.Forms.TabControl.WndProc(Message& m)
ved System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
ved System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) …
```

Treat metapackage depends as not auto installed

---

Netkan/Transformers/StagingTransformer.cs

The auto-staging from #2970 has been triggering when the corresponding value is `"any"`:
- KSP-CKAN/CKAN-meta#1790
- KSP-CKAN/CKAN-meta#1797
- KSP-CKAN/CKAN-meta#1839
This isn't aligned with the intentions of this feature; a module compatible with all versions is much less likely to change compatibility than a module with specific compatible versions.
Now we only auto-stage if at least one of the present properties isn't `"any"` or `null`.

Don't auto-stage if version is "any"

---

Core/Versioning/ModuleVersion.cs
Netkan/Transformers/EpochTransformer.cs

In #2824 we added the ability to automatically increment the epoch of a module during inflation, if needed to preserve in-order versioning; for example, if a module releases version `2` followed by version `1`, we would automatically change the latter to `1:1` to ensure that the later version is sorted later. To ensure that this did not go haywire, we turned on staging of such a module to allow for manual review before merge when it occurs.
Since this was working out reasonably well so far, in #2947 we made the staging more permissive by suppressing it when an auto-epoch'd version was equal to an existing version. This allowed previously created files to be updated without manual review, since our intention is to monitor the creation of new versions.
A significant fraction of auto-epoch …

Only stage auto-epoch if epoch changed

---

macosx/CKAN

Before a few minutes ago, if you tried to run the CKAN.app bundle for Mac without Mono installed, your browser would open a missing page in the CKAN wiki.
The page was renamed to reflect the name change from OSX to macOS, but the launch script still used the old URL.
- https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-macOS
Hooray for pointlessly renaming long established products to freshen up their brands.
I just added back the old page with a link to the new.
- https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-OSX
And now the script is updated to use the new URL.
Fixes #3017.

Update macOS wiki URL

---

Netkan/Transformers/StagingTransformer.cs

As of #2970 we stage modules into CKAN-meta for manual review/merge when their netkans include `ksp_version_*` properties, since these may have changed since the last release and should be manually verified.
There's a case where this isn't necessary: When the netkan is already hard coded to be compatible with the current latest game version. If the current latest game version is 1.9.1, and your `ksp_version` or `ksp_version_min` or `ksp_version_max` properties only reference 1.9.1, then any new release is going to be a bug fix release for the same game version.
Examples in which 1.9.1 was the latest game version:
- KSP-CKAN/CKAN-meta#1868
- KSP-CKAN/CKAN-meta#1888
The author isn't going to change the compatibility to some future or past game version if the previous release was already …

Don't stage if compatible with current game version

---

Core/Registry/RegistryManager.cs
Core/Types/Identifier.cs
GUI/Controls/EditModpack.Designer.cs
GUI/Controls/EditModpack.cs
GUI/Properties/Resources.resx

Discord user Silverlight pointed out some issues with Export Modpack:
- The default value for the identifier field can be invalid, since the KSP instance name is used and may contain characters that are not valid for identifiers
- The error message says `Identifier must contain one or more letters, numbers, and dashes, and must start with a letter or number`, which could be interpreted to mean that other characters are allowed as long as one or more of the indicated characters are present. ~~I don't know whether the German translation has this problem.~~ The German translation does not have this problem.
The export function always generated invalid identifiers going way back, but only with #2971 did we start validating the string, since the user can now edit it. I think most of my testing …

Improve modpack identifier validation

---

GUI/Main/Main.cs

If you install a mod manually, the Reinstall right click option is enabled:
It doesn't work though:
```
CKAN.ModNotInstalledKraken: Module Astrogator is not installed!
at CKAN.ModuleInstaller.UninstallList(IEnumerable`1 mods, HashSet`1& possibleConfigOnlyDirs, RegistryManager registry_manager, Boolean ConfirmPrompt, IEnumerable`1 installing)
at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
The reinstall logic tries to uninstall the specified mod first, which we can't do for a manually installed mod.
Now the Reinstall option is only enabled for mods installed by CKAN.
Fixes #3033.

Disable reinstall option for AD mods

---

GUI/Controls/ChooseRecommendedMods.resx
GUI/Localization/de-DE/ChooseRecommendedMods.de-DE.resx
GUI/Localization/de-DE/Main.de-DE.resx
GUI/Main/Main.resx
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.resx

In #2960 we added a "Supported By" section to the GUI recommendations screen. Unlike the recommendation and suggestion sections, which show mods mentioned by the mods chosen for install, this section is based on relationships in which **other** mods mention the chosen mods. This provides better support for certain scenarios:
- If I install a tech tree, I would be able to see which mods integrate with that tech tree
- If I install RPM, I would be able to see mods that provide MFD pages
- If I install TweakScale, I would be able to see part mods that allow scaling
The orange marks highlight places in the current UI that incorrectly state or imply that "supported by" mods are recommended or suggested by the chosen mods (because that was how the screen worked after #2744 and the text was not …

Consider supports in recommendations screen descriptions

---

Cmdline/Action/Update.cs

```
$ mono ckan.exe update
Downloading updates...
Updated information on True compatible modules
```
"True"?...
#2963 unintentionally reverted part of #2617 that updated the format of this line.
Now it prints the number of compatible modules again.

Restore cmdline update message

---

Netkan/Sources/Spacedock/SDVersion.cs
Netkan/Transformers/SpacedockTransformer.cs

This is #2337, but for SpaceDock.
Needs KSP-SpaceDock/SpaceDock#195 to be merged to SpaceDock's production. Currently it's still being tested on the alpha server.

Purge stale cache entries for SpaceDock

---

Core/ModuleInstaller.cs
Core/Registry/Registry.cs
Core/Types/Kraken.cs
GUI/Dialogs/YesNoDialog.Designer.cs
GUI/Dialogs/YesNoDialog.cs
GUI/Main/MainInstall.cs

Most new KSP users start out by installing mods manually and find out about CKAN later, at which point they already have an install with some mods and would like to have CKAN take over.
Currently this user's only option is to manually clean out their game folders and start from scratch with CKAN. Some of the manually installed mods will show up in the GUI as "AD", but CKAN can't remove/install/upgrade them. Other manually installed mods will simply show up as not installed, but error out if you try to install them.
Now you can:
1. Select an AD mod
2. Go to the Versions tab
3. Check the box for one of the versions (usually you'd want the most recent)
(Or instead of steps 1-3, select a manually installed mod that doesn't show up as AD and add it to be installed normally)
The apply button …

Prompt user to overwrite manually installed files

---

Core/Relationships/RelationshipResolver.cs

In KSP-CKAN/NetKAN#7891, Spectra removed `PlanetShine-Config` from its `provides` list because it no longer ships with a PlanetShine config. Versions v1.2.5 and earlier were released before that change, and v1.3 and later were released after.
If you install Spectra v1.3.1 (after the above change):
... and then install the PlanetShine suggestion, you will be prompted to choose between PlanetShine's default config and Spectra v1.2.5:
If you choose Spectra v1.2.5, this fails because you're already installing Spectra v1.3.1, and you can't install two different versions of the same mod at the same time.
```
System.ArgumentException: Already contains module:Spectra
at CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
at …
```

Don't try to install multiple versions of the same mod

---

debian/Makefile
debian/changelog
debian/ckan-consoleui.desktop
rpm/Makefile
rpm/ckan.spec

The current DEB and RPM packages install a `ckan.desktop` file that launches GUI, but some users may not always wish to run the GUI.
Now the DEB and RPM packages install a `/usr/share/applications/ckan-consoleui.desktop` file that runs `ckan consoleui` in a terminal:

Create a system menu entry for ConsoleUI

---

Netkan/CKAN-netkan.csproj
Netkan/Processors/Inflator.cs
Netkan/Processors/QueueHandler.cs
Netkan/Program.cs
Netkan/QueueAppender.cs
Netkan/Services/IModuleService.cs
Netkan/Services/ModuleService.cs
Netkan/Transformers/AvcKrefTransformer.cs
Netkan/Transformers/AvcTransformer.cs
Netkan/Transformers/CurseTransformer.cs
Netkan/Transformers/GithubTransformer.cs
Netkan/Transformers/HttpTransformer.cs
Netkan/Transformers/JenkinsTransformer.cs
Netkan/Transformers/NetkanTransformer.cs
Netkan/Transformers/SpacedockTransformer.cs
Netkan/Validators/CkanValidator.cs
Netkan/Validators/ModuleManagerDependsValidator.cs
Netkan/Validators/NetkanValidator.cs
Netkan/Validators/PluginCompatibilityValidator.cs
Netkan/Validators/VrefValidator.cs
Tests/NetKAN/Validators/CkanValidatorTests.cs

See KSP-CKAN/NetKAN-Infra#160, it would be nice to be able to capture non-fatal warnings in netkan.exe to discover opportunities to improve the metadata.
- `AvcTransformer` now prints a warning via `Log.Warn` if a version file's `URL` property contains an invalid URL, or if the URL can't be downloaded
- A new `PluginCompatibilityValidator` prints a warning via `Log.Warn` if a module contains a DLL file and claims to be compatible with all future versions, since plugins always break eventually
- A new `VrefValidator` prints a warning via `Log.Warn` if a module contains a version file and has no vref, OR if a module has a vref and no version file
- A new `ModuleManagerDependsValidator` prints a warning via `Log.Warn` if a module's cfg files use ModuleManager syntax but the module doesn't …

NetKAN warnings

---

GUI/Main/Main.Designer.cs

https://github.com/HebaruSan/CKAN/blob/d36da4ddabc016dc0b9de4f1615cb8913c1eeb63/GUI/Controls/ManageMods.cs#L908-L911
The mod list control needs to ask the main app code to switch over to installer mode, and this was meant to be done via the `StartChangeSet` event. However, there was no event handler for this event in #3041.
Now the event handler is set and it works again.

Unbreak reinstall right click

---

Netkan/Processors/QueueHandler.cs
Netkan/Validators/DownloadVersionValidator.cs
Netkan/Validators/VrefValidator.cs

When mods include multiple version files (often due to bundling other mods), we use the last part of the vref to determine which one to use. In #3045 we added a new call to `GetInternalAvc`, but with the vref Id left out because initially I thought we would not have it available by that point in the processing. Due to more recent changes this isn't an issue, but we do need the call to work for modules with _no_ vref, to see if we should add one, so it needs to work and not throw regardless of what the vref is or how many version files there are. Now we pass a vref matching string of `"."`, to force it to match any version file at all without throwing, since we only care if any exist.
Jenkins doesn't provide a version at all; it comes from the .version file via the `$vref`. But this is …

Fix errors caused by warnings changes

---

Netkan/Transformers/InternalCkanTransformer.cs
Netkan/Validators/VrefValidator.cs

A bunch of files that used to inflate fine before #3045 now fail:
And there's this special one with its own unique error:
The `VrefValidator` uses `ModuleService.GetInternalAvc` to scan a ZIP for version files.
| Case | Outcome |
| --- | --- |
| No version files found | Returns `null` |
| At least one valid version file found | Returns an `AvcVersion` object |
| At least one version file, but with syntax errors | Throws a `Kraken` |
Prior to #3045 and #3056, we only called `GetInternalAvc` when the netkan had a `$vref`, and if we've specified to use the version file, it makes sense to fail on syntax errors. But now we want to call it for mods that don't have a `$vref` so we can find out if we should add one, so the inflation should not be interrupted.
I found the other one kind of …

Ignore internal krefs, don't error on unused version file syntax errors

---

Core/Net/IDownloader.cs
Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
GUI/Controls/ManageMods.cs
GUI/Controls/Wait.Designer.cs
GUI/Controls/Wait.cs
GUI/Main/MainInstall.cs

If you try to install lots of mods that you haven't previously downloaded, you'll likely get errors like this (possibly in a different format since we've changed them a bunch recently):
> Failed to download "https://github.com/jrossignol/ContractPack-AnomalySurveyor/releases/download/1.6.0/ContractPack-AnomalySurveyor_1.6.0.zip" - error: The remote server returned an error: (403) Forbidden.
GitHub doesn't like it when you try to download multiple things from it at the same time, which CKAN aggressively does. GitHub sometimes responds to such attempts with 403-Forbidden statuses (the precise rules are not publicly known).
The GitHub _API_ works similarly, except it has [defined](https://developer.github.com/v3/#abuse-rate-limits) (and [queryable](https://api.github.com/rate_limit)) …

Non-parallel GitHub downloads, one progress bar per download

---

Core/KSP.cs
GUI/Dialogs/SettingsDialog.cs

I recently noticed that opening the settings window is pretty slow from time to time. When profiling it, I found out that we save the registry on settings startup, and it seems to be the culprit (the serialization, to be precise).
In `RefreshReposListBox>()`, the registry is saved after the we sort the list of repositories in the registry to how they are sorted in the GUI.
This is also done when the settings are just opened. In this case there are no repositories listed in the GUI (and the user couldn't have changed the sorting yet), so the whole operation is not doing anything.
However we still save the registry afterwards, which takes a long time.
THe costly operation is put behind an if-clause. When `_sortedRepos.Count == 0`, we just pull the  list of repositories from the registry …

Don't save registry when opening settings

---

Netkan/Model/Metadata.cs
Netkan/Services/CachingHttpService.cs
Netkan/Services/IHttpService.cs
Netkan/Transformers/AvcTransformer.cs
Netkan/Transformers/DownloadAttributeTransformer.cs
Netkan/Transformers/InternalCkanTransformer.cs
Netkan/Transformers/LocalizationsTransformer.cs
Netkan/Validators/InstallsFilesValidator.cs
Netkan/Validators/ModuleManagerDependsValidator.cs
Netkan/Validators/PluginCompatibilityValidator.cs
Netkan/Validators/VrefValidator.cs
Tests/NetKAN/Transformers/DownloadAttributeTransformerTests.cs
Tests/NetKAN/Transformers/InternalCkanTransformerTests.cs

If you submit a CKAN-meta pull request for a module that currently relies on its archive.org fallback URL for download, the pull request validation will fail, even though the module can be installed by the client.
Netkan uses a downloading service separate from the client's, which does not know about fallback URLs.
- Now `Metadata` provides a `FallbackDownload` property that returns an archive.org `Uri` if we have enough info to do so and `null` otherwise.
- Now `CachingHttpService` takes `Metadata` as input when downloading instead of a `Uri`, identifier, and timestamp separately.
- Now if a download fails, `CachingHttpService` attempts to get `FallbackDownload` if it is set, and propagates the exception otherwise.
This will allow `netkan.exe --validate-ckan` to access fallback URLs and …

Support fallback URLs for netkan validate-ckan

---

Netkan/Services/CachingHttpService.cs
Netkan/Sources/Github/GithubRepo.cs
Netkan/Transformers/GithubTransformer.cs
Netkan/Validators/ModuleManagerDependsValidator.cs

A GitHub repo can be "archived", meaning that it's effectively read-only and very unlikely to ever be updated. Currently some of the netkans that we crawl every 2 hours are probably archived, so it's not necessary to keep checking them, but we don't know about it.
There's a `resources.bugtracker` property in the spec, but it's only populated manually. Many mods are hosted on GitHub repos where issues can be submitted, but we don't check that.
- Now if a GitHub repo is archived, Netkan will print a warning suggesting that we freeze that netkan, which will be visible on the status page
- Now if a GitHub repo has issues enabled (not all of them do), `resources.bugtracker` will automatically be set to that repo's issues list
- The duration of caching of strings from #2950 is extended from 2 …

Netkan warning for archived repos, set bugtracker for GitHub

---

Netkan/Services/ModuleService.cs

Two mods have vrefs and version files with non-lowercase file name extensions:
They're not being picked up.
The search for .version files is case sensitive.
- Now the search for .version files is case insensitive, so these version files will be found
- Both of them have severe syntax errors, so we'll need to remove the vrefs to inflate them, but that's better than having vrefs with version files that get silently ignored
- `Regex`es for checking file extensions are replaced with `string.EndsWith` calls, which ought to be faster given the complexities of each operation (the runtime can jump to the common parts based on the string lengths and compare character by character, rather than building and running a finite state machine and feeding in the entire string character by character until …

Check mixed case version files

---

Core/Net/NetAsyncModulesDownloader.cs

Download errors look like this currently:
```
Downloading "https://spacedock.info/mod/1805/Whirligig%20World/download/0.10.0"
System.Net.WebException: The remote server returned an error: (404) NOT FOUND.
at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x00146] in <88f564ea69dd4dc8ba9bf979e48d5996>:0 
at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <88f564ea69dd4dc8ba9bf979e48d5996>:0 
at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in …
```

Move WebException stack trace from User error to verbose log

---

Core/Types/ModuleInstallDescriptor.cs
Netkan/Services/ModuleService.cs

[The spec](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md) says:
```markdown
- `find`: (**v1.4**) Locate the top-most directory which exactly matches
the name specified. This is particularly useful when distributions
have structures which change based upon each release.
```
In #3064 we attempted to relax the "top-most" requirement and allow multiple folders matched by `find` to be installed.
For most of those, the conflict is only a directory, but it's fine to install a directory multiple times (they can even be shared between modules).
However, GPP's problem cannot be solved with #3064 as it is. Its ZIP includes multiple instances of "GameData/GPP", one that is the main install, and two more in paths under "Optional Mods":
Even if we were hypothetically to create an automatic …

Multi-find fixes

---

GUI/Controls/ManageMods.cs

0. Have some upgradeable mods (you can install old versions in the Versions tab for testing)
1. Switch to the "Newly compatible filter" when it's empty (i.e., nothing is newly compatible)
2. Click "Add available updates"
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.Collections.ArrayList.get_Item (System.Int32 index) [0x0000d] in <a5e6a8b38be74ec1b9abd482cb076c8a>:0 
at System.Windows.Forms.DataGridViewRowCollection.get_Item (System.Int32 index) [0x00000] in <5e01e3d59bfc48e1a1ea0509bb585d97>:0 
at CKAN.ManageMods.MarkAllUpdates () [0x000fb] in <1e9e6cc7a1124c26a7e978a1dd44c3d6>:0 
at CKAN.ManageMods.MarkAllUpdatesToolButton_Click (System.Object sender, System.EventArgs e) …
```

Fix crash on marking all updates

---

Core/Net/NetFileCache.cs

#2940 sped up the Inflator by caching hashes to RAM, but this only helps on the second-and-later passes; the first pass after redeployment still takes a long time.
Now when we store a ZIP to the cache, we store two additional files next to it, with the same name plus `.sha1` and `.sha256` appended:
- FFA1EF94-ContractsWindowPlus-9.4.zip
- FFA1EF94-ContractsWindowPlus-9.4.zip.sha1
- FFA1EF94-ContractsWindowPlus-9.4.zip.sha256
When we need to retrieve the hash, we check for these files in between checking our in-memory cache and computing the hashes based on the ZIPs.
This should speed up the first passes of the Inflator.

Cache hashes on disk

---

Core/Net/Net.cs
GUI/Main/Main.Designer.cs

See #3083 for in-depth explanation.
In addition to issues noted there, the Curl fallback attempts **do not** use the bot's GitHub token, so they are prone to running out of rate limiting. They're bad news all around.
Now we don't fall back to Curl if we get a response from the server, even if it's a failure. This will allow the first 404 to "stick", and the Discord spam will end. The Curl fallback will only happen if a problem occurs that prevents communication with the server.
Fixes #3083.
Now the GUI window is allowed to be smaller, because I had this change sitting in my working copy and it's so minor.

Don't fallback to Curl on 404, allow smaller GUI

---

.github/workflows/build.yml

Replacement of #2994, re-pushed to a branch directly in the KSP-CKAN/CKAN repo to be able to test the workflows with this PR.
While Travis is a great tool, it has its difficult times. Currently almost every CI run fails in one instance because of some network problems.
We already discussed this in the Discord a bit, and I think no one was really bound to Travis and the move to GitHub Workflows was generally supported.
This PR removes the .travis.yml file from the repository, so Travis is no longer triggered on merges.
Instead, there are now three workflow files according to the [documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-workflows):
1) The standard build workflow.
* It is triggered with [pull …

Move Travis CI to GitHub Workflows

---

.github/workflows/deploy.yml

While we decide about the home for our build artifacts, we should move to using our own bucket.
https://ksp-ckan.s3-us-west-2.amazonaws.com/
This will only contain the artifacts from this process, so the bucket policy has already been set accordingly.

Change Bucket Upload

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml

In the last PR I missed that the deploy username for S3 was still the old one, which caused the S3 deploy failure.
I also noticed NetCore failing, which is likely due to a stale apt cache. Converted to apt-get to remove this warning `WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

Use Secrets for Usernames

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml
Tests/NetKAN/Sources/Spacedock/SpacedockApiTests.cs

Since #3085 we run CKAN's CI with GitHub Actions. An advantage of this is that they also run in forked repositories automatically, without the need to set up an external service.
However, this also leads the workflows trying to execute all the deployment steps and the Discord notification, which doesn't make sense in forked repos and will ultimately fail since the secrets needed to run these steps aren't available.
This PR adds `if`s to all the steps that need secrets to work. These `if`s check whether the needed secrets are set, and if not, skip the step.
Also fixed one network test failing since #3084.

Don't run workflow steps that require secrets on forks

---

Core/Net/Curl.cs
Core/Net/Net.cs
Tests/Core/Net/Net.cs

During investigation of #3084, I noticed that the Curl fallback has no support for auth tokens. If Curl is to serve a useful role as a fallback, it should be able to handle the Inflator's network traffic without running into rate limiting issues, and that means auth tokens.
Now Curl calls set the Authorization header just like the WebClient ones.

Use authToken for Curl

---

GUI/Model/GUIConfiguration.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.resx

Apparently this message is confusing:
Now 'it' is replaced with the file name and 'the folder' is replaced with the folder path. Hopefully this gives folks a clearer idea of what to do. I _think_ I got the change right for German, but maybe a "zum" needs to become a "zur" or something.
> CKAN.Kraken: Error trying to parse "/home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/GUIConfig.xml": Data at the root level is invalid. Line 2, position 1.. Try to move GUIConfig.xml out of /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN and restart CKAN.

Be more specific in GUI config parse error

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml

The CI builds still take quite a long time to finish, since installing Mono takes around 10 minutes.
@techman83 had the excellent idea of running the builds in Docker containers from the images published [here](https://hub.docker.com/_/mono/?tab=tags&page=1).
Downloading the images should be way faster than installing and pre-compiling it.
There exists a `container` keyword for workflow jobs: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
If I understood the documentation correctly, it makes all steps of this job run in the specified container after pulling it from the Docker hub.
Let's see if it works.
Also realized that I messed up the Discord notifications in #3089 since the env var is named differently.

Run workflows in Mono Docker containers

---

.github/workflows/deploy.yml

Currently the Cake task to redeploy the Inflator rebuilds netkan.exe, after it has already been built in previous tasks.
In a Makefile, filesystem timestamps are used to determine whether dependencies need to be rebuilt. For example, if we have this:
```Makefile
a: b
cat b | sed -e s/b/a/g > a
```
And then we run `make a`, the `cat`/`sed` pipeline will only run if `b` is newer on disk than `a`. This is a really powerful feature for optimizing build times, since you can build up the tree of all of your project's dependencies and then a simple `make` command will only rebuild what needs to be rebuilt after your latest changes.
Cake instead seems to see each dependency as always needing to be executed, so when we do this:
https://github.com/KSP-CKAN/CKAN/blob/82587f5d61d4a6a7c75447abf83bed1b5 …

Deploy already built netkan.exe in CI

---

GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ManageMods.resx
GUI/Localization/de-DE/ManageMods.de-DE.resx
GUI/Model/ModList.cs
Tests/GUI/GH1866.cs

One of my earliest memories of chatting on the CKAN thread is suggesting that a release date column shouldn't be that hard to add:
- https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1272-chandrasekhar/page/14/&tab=comments#comment-3076850
This is a pretty popular request and would allow users to see which mods have been updated recently. Here's another time it came up:
- https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1272-chandrasekhar/page/72/&tab=comments#comment-3624808
After #3059 the Netkan Inflator has collected a full round of release date metadata from GitHub and Jenkins, and SpaceDock is in progress pending the next run of the webhooks only pass. The only thing …

Release date column

---

.github/workflows/release.yml
build.cake

Initial builds of v1.28.0-PRE1 failed in the step that deploys the RPM file, because RPM doesn't allow dashes in version names.
However, the RPM build step itself succeeded when it should have failed. The deploy only failed because the RPM file didn't exist.
`StartProcess` returns the failed exit code, but `.Does(() => ...)` simply ignores it. Cake expects us to throw exceptions when builds fail.
```cake
.Does(() => StartProcess("make",
new ProcessSettings { WorkingDirectory = "rpm" }));
```
- Now we throw an exception if our `make` commands return an exit status other than 0, which will stop everything
- For a small performance gain, we no longer re-build ckan.exe every time for the dmg, deb, and rpm tasks; instead we build once and then use the same artifact for all three, using the …

Stop release Action if build of dmg, deb, or rpm fails

---

Core/ModuleInstaller.cs
Core/Net/Repo.cs
Core/Registry/InstalledModule.cs
Netkan/QueueAppender.cs
Netkan/Services/CachingHttpService.cs
Netkan/Sources/Github/GithubApi.cs

1. Install an incompatible module
2. Wait for it to be changed in CKAN-meta
3. Get this popup:
4. Click Yes
5. It seems to reinstall
6. However, the next time there's a change to the metadata, it'll give you the same prompt for the same mod again, and again, and again...
The repo update code has a specific `CkanModule` that it wants to re-install, but it only passes the identifier to force the relationships to be resolved, crossing its fingers that the same `CkanModule` will be found. But if the module is incompatible, then the attempt to find it via the identifier fails, and the relationship resolver falls back to the installed version:
https://github.com/KSP-CKAN/CKAN/blob/d0902a9c9c5cae5b1657161912528afe154ac39a/Core/ModuleInstaller.cs#L964-L965
⇒ …

Fix reinstallation of updated incompatible modules

---

Cmdline/Action/Import.cs
Cmdline/Action/Install.cs
ConsoleUI/InstallScreen.cs
Core/ModuleInstaller.cs
GUI/Main/MainInstall.cs
Tests/Core/ModuleInstaller.cs
Tests/Core/ModuleInstallerDirTest.cs
Tests/GUI/GH1866.cs

1. Install SCANsat v20.1
2. Use it; it will create `GameData/SCANsat/PluginData/Settings.cfg`
3. Upgrade to v20.2
4. You'll be asked whether to remove the PluginData folder, even though the mod is still installed
SCANsat creates PluginData as an empty folder and only uses it for saving its Settings.cfg, so it naturally meets the criteria for a removable config-only dir at uninstall. When we upgrade, we:
1. Remove the older version, which flags PluginData as potentially removable
2. Install the newer version, which creates the PluginData folder if it doesn't already exist but leaves it in the list of possibly removable dirs
Now when we install a directory, we remove it from the list of empty directories to ask the user about. This removes the prompt from the upgrade flow but still presents …

Don't prompt to delete SCANsat's settings at upgrade

---

GUI/Controls/ChooseRecommendedMods.cs

If you try to install RP-0 from before KSP-RO/RP-0#1303 and KSP-CKAN/CKAN-meta#2099, the install will fail on the conflict between RealAntennas and RemoteTech. But this happens in the install flow; the recommendations screen seems to think everything is fine, when it should be catching this conflict.
The recommendations view was only checking for conflicts after the user clicked, presumably on the assumption that mods won't recommend conflicting modules. But they have!
Now we check for conflicts right after we finish loading the recommendations. For those old RP-0 revisions, the rows are red right at the start.

Mark conflicts in initial recommendations

---

Cmdline/Main.cs
Netkan/Program.cs

`Curl.CreateEasy` requires that `Curl.Init()` be called; if it hasn't been, it will be at that point. Supposedly `Curl.Init()` isn't thread-safe, so `CreateEasy` will print a warning about this since it can't guarantee that it's not being executed in some complicated threading scenario.
Netkan falls afoul of this by not calling `Curl.Init()` till it's needed.
Now we init Curl at netkan and ckan startup, which isn't in a complicated threading scenario, so the message won't appear anymore.
Fixes #1441.

Init Curl at netkan.exe and ckan.exe startup

---

Core/Net/Curl.cs

https://ci.ksp-ckan.space/job/NetKAN/9883/console
```
Fetching latest ckan.exe
System.DllNotFoundException: libcurl assembly:<unknown assembly> type:<unknown type> member:(null)
at (wrapper managed-to-native) CurlSharp.NativeMethods.curl_global_init(int)
at CurlSharp.Curl.GlobalInit (CurlSharp.CurlInitFlag flags) [0x00001] in <5257a4b91e0a46648a337ec8fa636dea>:0 
at CKAN.Curl.Init () [0x00017] in <5257a4b91e0a46648a337ec8fa636dea>:0 
at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00091] in <5257a4b91e0a46648a337ec8fa636dea>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: libcurl assembly:<unknown assembly> type:<unknown type> member:(null)
at (wrapper managed-to-native) CurlSharp.NativeMethods.curl_global_init(int)
at …
```

Ignore missing DLL for libcurl

---

policy/Opt-out-list.md

This author has requested to be added to the opt-out list.
- https://forum.kerbalspaceprogram.com/index.php?/topic/164035-110-knes-180-time-to-build/&do=findComment&comment=3818259
First mentioned in passing in KSP-CKAN/NetKAN#7398, but it wasn't done at that time.
KSP-CKAN/NetKAN#8031 and KSP-CKAN/CKAN-meta#2104 froze Knes by this author.
~~KSP-CKAN/NetKAN#4868 seemingly indexed KrakenScience by the same author without permission (4 months after the big forum blow-up), so we'll need to follow up on that as well.~~
Permission for KrakenScience was given here:
- https://forum.kerbalspaceprogram.com/index.php?/topic/146110-110-krakenscience-10-2020-01-15/&do=findComment&comment=2833230
And then retracted here:
- https://forum.kerbalspaceprogram.com/index.php?/topic/146110-110-krakenscience-1 …

Add Well to opt-out list

---

CKAN.schema
Spec.md
Tests/NetKAN/Validators/CkanValidatorTests.cs
Tests/NetKAN/Validators/ObeysCKANSchemaValidatorTests.cs

Currrently the `author` property isn't required by the metadata schema. This doesn't make sense, a mod should _always_ have an author listed with it, for several reasons:
1) Users have a starting point finding a place for help if there's no forum thread or repo or anything in the resources.
2) It's without question that we should always give attribution to whoever made a mod. It's a thing of fairness and respect to list the mod author. And if we mirror the mod to archive.org, we are redistributing the mod, and almost all licenses require attribution to the author of some sort.
3) Authors might understandably get very upset if they see that their own mods don't list themselves as authors.
Add `"author"` to the list of required properties for .ckan files.
This makes sure our indexer and the …

Add author to list of required properties in CKAN.schema

---

GUI/Controls/ManageMods.cs
GUI/Model/GUIMod.cs

If you sort by Max KSP version, 1.10 comes between 1.1 and 1.2, which is wrong.
Currently this column sorts as a string, which only works if the lexicographical sort order of the strings corresponds to the true sorting of the versions, which it doesn't.
This gets a bit tricky. We need to expose the `GUIMod`'s `KspVersion` object, but we can't just sort _by_ that object naïvely, because `KspVersion.CompareTo` sorts undefined values inappropriately for upper bounds; it considers 1.8 < 1.8.0, and `any` < everything. We want the opposite, so we can't use `.OrderBy` or `.OrderByDescending` for this.
Instead, `ManageMods` now has an alternate `Sort` overload that takes a `Comparison<DataGridViewRow>`, which can handle comparisons _between two objects_ rather than just returning a sort key for …

Sort GUI KSP version column correctly

---

build.ps1

On Windows 7, delete the `_build` folder and try to build:
Same as #2293, the script uses `WebClient` to download an HTTPS URL, but it doesn't support TLS1.2 by default, and nuget.org requires TLS1.2 as of April.
- https://dist.nuget.org/win-x86-commandline/v5.6.0/nuget.exe
- https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/
Now we perform the PowerShell equivalent of #2297's change in the build script. This allows `WebClient` to download a modern HTTPS URL.

Fix build from scratch on Windows 7

---

Core/Configuration/JsonConfiguration.cs

When deleting an auth token it sets the token itself to `null` but keeps it in our config which keeps it showing in the list.
**config.json :**
```
"AuthTokens": {
"GitHub": null
},
```
**Settings dialog :**
Now when pressing "Delete" or setting the token to `null` properly deletes the auth token.

Delete authtoken when setting to null

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml

- Now all build actions cache `_build/tools`
- NuGet
- NUnit
- ILRepack
- Now all build actions cache `_build/cake`
- Cake.SemVer
- semver
- Cake.Docker
- Now the release build step caches `_build/tools`, `_build/cake`, `_build/lib/nuget`, and `~/.nuget/packages`
- Indenting in the yml files is more consistent
This should allow quicker builds with fewer downloads.

Cache build tools

---

Core/Net/NetFileCache.cs

See #3066 and #3123; if Mono users in a non-en_US locale don't install `mono-complete`, this exception can be thrown:
```
System.NotSupportedException: Encoding 852 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
at System.Text.Encoding.GetEncoding (System.Int32 codepage) [0x0024d] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToString (System.Byte[] data, System.Int32 count) [0x00017] in <29fa7683355b471a9cc202367184a830>:0 
at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToStringExt (System.Int32 flags, System.Byte[] data, System.Int32 count) [0x00032] in <29fa7683355b471a9cc202367184a830>:0 
at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries () [0x00312] in …
```

Better message when ZipFile throws NotSupportedException

---

Core/Registry/Registry.cs

Up until a few minutes ago, the v1.28.0 client thought nobody on KSP 1.10.x had any DLCs installed.
KSP-CKAN/CKAN-meta#2130 added the new DLC metadata to fix this, but in the meantime the client should have fallen back on mocked-up CkanModules to represent the DLC.
The fallback code only runs in case the DLC **identifier** isn't found. If the identifier exists but the DLC version found on disk isn't available (99.99% of real world usages), then `RegisterDlc` does nothing.
Now `RegisterDlc` **always** adds _something_ to the installed modules list. First it looks for the identifier and version in the available modules list, and if _either_ isn't found, then it makes the fake module, as intended.
Fixes #3135.

Fix missing DLC registration gap

---

Core/Relationships/RelationshipResolver.cs
Core/Types/Kraken.cs

If you force-install an incompatible module (with no compatible versions), then try to install a mod with a recommendation that depends on it, you get this in the recommendations screen:
```
CKAN.DependencyNotSatisfiedKraken: Exception of type 'CKAN.DependencyNotSatisfiedKraken' was thrown.
at CKAN.RelationshipResolver.ResolveStanza (System.Collections.Generic.IEnumerable`1[T] stanza, CKAN.SelectionReason reason, CKAN.RelationshipResolverOptions options, System.Boolean soft_resolve, System.Collections.Generic.IEnumerable`1[T] old_stanza) [0x0038f] in /home/DasSkelett/git/CKAN/Core/Relationships/RelationshipResolver.cs:434 
at CKAN.RelationshipResolver.Resolve (CKAN.CkanModule module, CKAN.RelationshipResolverOptions options, System.Collections.Generic.IEnumerable`1[T] old_stanza) …
```

Satisfy dependencies with installed incompatible modules

---

GUI/Main/Main.cs

Continuation of #3001 
Forum user steve_v reported that this is still needed for KSP 1.10, and testing confirmed that.
The user also complained about CKAN eating stderr, and for some reason the line about the directory change and the line about the segfault we saw previously is now longer printed, but I don't think this due to a change on our side, is it?
```
Found path: /NAS/games/KubuntuGames/steamapps/common/Kerbal Space Program/./KSP.x86_64
```
Anyways, we now filter `-single-instance` for KSP 1.10 too.

Extend -single-instance fix to 1.10

---

GUI/Controls/ManageMods.Designer.cs
GUI/Model/GUIConfiguration.cs
GUI/Model/ModList.cs

Ampersands (`&`) in mod names or abstracts in the mod list are currently interpreted as hint to create automatic keyboard shortcuts (visualized through underscores), instead of printing them as literal.
See for example the mod `DumpAndBurn`, with the name `Dump&Burn!`:
Error messages of krakens thrown while trying to load the `GUIConfig.xml` have a mix of `/` and `\` as path seperators on Windows, like:
```
CKAN.Kraken: Error trying to parse "c:/program files(x86)/steam/SteamApps/common/Kerbal Space Program/CKAN\GUIConfig.xml": Root element missing.
```
The texts in the name, author and abstract are now escaped using `&&` in `ModList.MakeRow()`. I didn't spot another location where they would need escaping (tested recommendation tab and modpack export tab).
The …

Escape '&' in mod list, consistent path separators in exception

---

Netkan/Services/CachingHttpService.cs
Netkan/Transformers/NetkanTransformer.cs

Invalid zip files that fail the `ZipValid` check fill up the bot's disk over time. The tempfiles but never get removed or moved into the cache, thus filling the disk with every indexer run.
In contrast, files failing to download at all get removed immediately, and files failing inflation later on are still stay in the cache and don't get redownloaded for the next try.
Simply remove the file if it fails the `ZipValid` check.
This has a downside when using netkan manually, if one would want to investigate the zip file after netkan fails (I remember [my comment](https://github.com/KSP-CKAN/CKAN/pull/2903#issuecomment-546433290)...). Now you have to download the file manually again to check it out.
I tried to think of an easy solution, like keeping the file if `--debug` is set, but as of …

Remove invalid zip files in NetKAN

---

Netkan/Model/Metadata.cs

Trying to inflate HumanStuff locally shortly after a new version got uploaded, I noticed netkan.exe being stuck in a download loop. Running it with debug logging showed, that the freshly downloaded file got repeatedly purged from the cache again because it was "stale".
The check happens here:
https://github.com/KSP-CKAN/CKAN/blob/0195a054c6dec35ea01d59da0aad28d1d5fccf65/Core/Net/NetFileCache.cs#L208-L211
However the `release_date` property contained the correct time with the correct timezone, and the file modification time C# got was also correct with the correct timezone.
Turns out: Microsoft went once again completely insane, and decided comparisons of timezone-aware DateTime objects should ignore the timezones.
>To determine the relationship of t1 to t2, the Compare method compares the …

Convert remote timestamp to UTC in NetKAN to fix comparisons

---

Core/Net/Net.cs
Core/Types/CkanModule.cs
Core/Types/ModuleInstallDescriptor.cs
Netkan/Transformers/AvcTransformer.cs

- Since #3074, a mod with a bad install stanza says, "Sequence contains no elements" instead of explaining that the stanza didn't match any files
- Even if the previous point is fixed, a mod using the default install stanza will throw a null reference error if it doesn't match any files
- Warnings about fetching remote version files don't print the remote URL (which would have been convenient for the following point)
- Prior to the recent flood of SpaceDock "The request was canceled" spam, after #3118, the netkan-bot channel was plagued with these errors:
This is mostly harmless, _unless_ a mod author is actually using the remote version file to update compatibility after release, in which case it can cause CKAN's metadata to temporarily revert to the at-release state.
- The code to find …

Retry failed web requests, fix install stanza error

---

GUI/Main/MainInstall.cs

We have had a few reports of installation failing without any info about the reason for the failure (see #3143, #3144, #3150):
That should never happen. Either the install should succeed, or we should see an indication of the reason it failed.
An exception is thrown during install, but `PostInstall` only prints messages for certain specific exception types. If the exception is something else, it won't be logged.
Unfortunately when we've sent a test build, the error went away, so the actual error is probably already fixed in master HEAD. We just don't know when or what it was, due to the lack of an error message.
Probably caused by the refactor of the install flow in #3041, when error printing was moved from `InstallMods` to `PostInstall` and `PostInstall` was simplified. I tried to keep …

Print message for unknown install exception

---

Netkan/Services/CachingHttpService.cs

The Inflator's `/tmp` partition filled up:
```
netkan@945a9d40d33e:/tmp/CdFileMgr$ du -hs *
1.6G    136049aa-d02d-4a.tmp
1.6G    190528d6-ffe7-44.tmp
1.6G    197cb16c-7bd8-49.tmp
91M    241da6c0-ee1f-45.tmp
91M    283785f4-c7a7-4e.tmp
91M    28df1ab1-cafd-4b.tmp
1.6G    2fabe926-dd25-46.tmp
91M    322b5b76-38b6-46.tmp
91M    3892e70d-d10d-41.tmp
1.6G    3d4376f1-748f-4f.tmp
1.6G    45782341-d73b-4c.tmp
91M    4c1f0f27-b592-4c.tmp
1.6G    5803da08-e7fb-4b.tmp
91M    610da03d-dba6-49.tmp
91M    67901f4e-6360-4a.tmp
91M    9e59cf92-ea96-48.tmp
91M    b8ec7a18-6db6-4e.tmp
1.6G    bcd5650b-fc6c-47.tmp
1.6G    c3fceeff-78d4-48.tmp
91M    c44a1bbb-b313-42.tmp
1.6G    c68dc340-e109-4b.tmp
1.6G    cc9752a0-ce66-4d.tmp
91M    d34b2f4a-ab1b-49.tmp
91M    e115d711-0f3f-44.tmp
1.6G …
```

Delete netkan tmp files if cache fills up

---

GUI/Controls/EditModSearch.cs

GUI search currently works slightly differently per platform: On Mac, it waits 700 milliseconds after you stop typing to update the filters, but on Windows and Linux it updates immediately after each keystroke.
On Linux:
- Sometimes (exact conditions unclear) if you type a search quickly, the characters appear out-of-order in the search box, which obviously searches for something other than what you intended
- Even if you don't suffer from the above problem (I had seen it happen previously but was not able to reproduce it while working on this fix), the UI updates are kind of slow and unreliable; there's an impression of repeated flickering and the cursor moves before the characters appear.
The `DataGridView` updates more slowly on Mono than on Windows, and it happens on the GUI thread, …

Search timer for Linux

---

ConsoleUI/ModInfoScreen.cs
ConsoleUI/ModListScreen.cs
Core/Registry/Registry.cs

- If you have a DLC installed, and there is no `"kind": "dlc"` module for it, ConsoleUI throws an exception when searching
- ConsoleUI thinks it can install and uninstall DLC (you can add them to the change set), but if you try it, an exception is thrown
- The mod info page for a DLC shows an exception where it would normally say where the mod is hosted
- The `store` and `steamstore` resources aren't shown anywhere in ConsoleUI
- The `CkanModule.Searchable*` properties are null because we create a fake DLC CkanModule without calling `CalculateSearchables`
- The "+"/"-" key binds and screen tips were not DLC-aware
- `CkanModule.download` is null for DLC, but `ModInfoScreen.HostedOn` did not allow for this
- Now we call `CalculateSearchables` when we make a fake DLC CkanModule
- Now …

ConsoleUI fixes for DLC

---

CKAN.schema
Core/KSP.cs
Core/KSPPathUtils.cs
Core/ModuleInstaller.cs
Core/Types/ModuleInstallDescriptor.cs
Netkan/Services/ModuleService.cs
Netkan/Validators/InstallValidator.cs
Spec.md

- kOS stores scripts in the `Ships/Script` folder under the game root. Currently CKAN doesn't allow this, and KSP-CKAN/NetKAN#7967 is in stasis because it needs to install kOS scripts to that folder.
- `ShipSaveSplicer` is being installed into `GameData/veSplicer` because it starts with `Ships`
- Now we allow installation into `Ships/Script`, including creation of new directories.
**Since this requires an update of the schema, the next release of CKAN will need to be v1.29.0 if this is merged.**
- Now we require a path to start with `Ships/` with a slash to trigger that truncation, so `ShipSaveSplicer` will be installed correctly.
Fixes #3187.

Allow installation into Ships/Script

---

Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
Core/Registry/RegistryManager.cs
GUI/Controls/EditModpack.cs
GUI/Main/Main.cs

When you have mods or mod versions installed that are not in the list of available modules ("DarkKAN modules"), the modpack export tab freezes.
This is caused by `registry.LatestAvailable()` in `AddGroup()` throwing an `ModuleNotFoundKraken` for unknown mods when trying to fetch the abstract for each installed mod.
Now we search the registry for an `InstalledModule` with the given identifier, and use its abstract property. We should always have an `InstalledModule` for each module we're handling in the export logic, and if for some reason we haven't, it shouldn't break anything.
Fixes #3138 
...maybe, hard to say without the registry or any information about installed mods, but it solved it for me.
@mgalyean if you can still reproduce the problem and want to try a debug build of ckan.exe …

Don't fail modpack export when having unindexed mods installed

---

Cmdline/Action/Upgrade.cs
Cmdline/ConsoleUser.cs
ConsoleUI/ModListScreen.cs
Core/KSP.cs
Core/ModuleInstaller.cs
Core/Registry/IRegistryQuerier.cs
GUI/Main/Main.cs
GUI/Model/GUIMod.cs
GUI/Model/ModList.cs

A very longstanding enhancement request is the ability to have CKAN take over management of mods that were manually installed. We took a first step towards this in #3043 by prompting the user if we need to overwrite manually installed files to install a module, which meant the user could use the Versions tab to have CKAN install a mod on top of a manual install. Now it's time to take this further.
Benefits:
- New users can more easily migrate their pre-CKAN installs to CKAN-managed
- Recovery from a corrupted registry will be easier
If you install a mod and then upgrade to a newer version of it that has new dependencies, the `ckan upgrade modname` command doesn't install them. (`ckan upgrade --all` _does_ install them.)
The `ckan upgrade modname` command doesn't resolve relationships. We …

Allow upgrading manually installed modules

---

GUI/Controls/EditModSearch.Designer.cs
GUI/Controls/EditModSearch.cs
GUI/Controls/EditModSearchDetails.Designer.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Controls/HintTextBox.cs

I force-pushed some Windows UI fixes for #3175, but when code review was finished, I mistakenly merged the original Linux branch instead, resulting in the release of some annoyances that users might eventually complain about.
This was why GitHub did not automatically close that PR or the issue it fixed upon merge. I thought it was due to something else. Lesson learned, listen to GitHub!
Luckily I still had the Windows branch sitting around.
- The search dropdown button is flat style instead of 3D to better fit in to the other UI elements
- The dropdown window is no longer always-on-top
- Pressing Esc in the dropdown will first clear the focused text box, if not empty, otherwise close the dropdown
- The labels in the search dropdown are 10 pixels wider to give enough space for all the text

Search UI fixes

---

Core/ModuleInstaller.cs
Tests/Core/ModuleInstaller.cs
Tests/Core/ModuleInstallerDirTest.cs

If you install a mod that installs a file to GameRoot (e.g. [AdvancedFlyByWire](https://github.com/KSP-CKAN/CKAN-meta/blob/master/AdvancedFlyByWire/AdvancedFlyByWire-1.8.3.2.ckan)), and then remove it, the removal fails:
```
About to remove:
* Advanced Fly-By-Wire (Windows) 1.8.3.2
* Toolbar Controller 1:0.1.9.4
* ClickThrough Blocker 1:0.1.10.14
* Zero MiniAVC 1:1.1.0.1
Removing AdvancedFlyByWire...
/ is already absolute
```
In #3180 we fixed …

Fix error when removing file from GameRoot

---

.github/workflows/deploy.yml
.github/workflows/release.yml
debian/Makefile
debian/Release.in

Currently we provide `.deb` packages, but somewhat ironically (given what CKAN is for), the user must download a new `.deb` file and install it manually when a new version is released.
Now when we build the `.deb` file, we also create a `_build/deb/apt-repo` folder containing the `.deb` file, a `Release` file, and a `Packages.gz` file, modeled on Mono's:
- https://download.mono-project.com/repo/ubuntu/dists/stable-bionic/main/binary-amd64/
For releases, these are uploaded to: `https://ksp-ckan.s3-us-west-2.amazonaws.com/deb/dists/stable/main/binary-all`
For other builds, these are uploaded to: `https://ksp-ckan.s3-us-west-2.amazonaws.com/deb/dists/nightly/main/binary-all`
This should allow users to add one of the following lines to their `sources.list` and get ckan releases automatically: …

Generate APT repo for releases and under dev builds

---

.github/workflows/deploy.yml
.github/workflows/release.yml
debian/Makefile

The APT repo doesn't work yet.
```
Fehl:22 https://ksp-ckan.s3-us-west-2.amazonaws.com/deb nightly Release
404  Not Found [IP: 52.218.233.33 443]
Paketlisten werden gelesen... Fertig
E: Das Depot »https://ksp-ckan.s3-us-west-2.amazonaws.com/deb nightly Release« enthält keine Release-Datei
```
We're supposed to have a file at `/deb/dists/nightly/Release`:
```
s3-us-west-2-r-w.amazonaws.com	http	HTTP		250		GET /deb/dists/nightly/InRelease HTTP/1.1 
s3-us-west-2-r-w.amazonaws.com	http	HTTP		248		GET /deb/dists/nightly/Release HTTP/1.1 
```
Mono has this.
- https://download.mono-project.com/repo/ubuntu/dists/stable-bionic/
Now we copy the Release file into an additional folder at `_build/deb/apt-repo-rel`, and sync that folder to `deb/dists/nightly` and/or `deb/dists/stable`.

Put Release file in stable/nightly folders of APT repo

---

ConsoleUI/ConsoleCKAN.cs
ConsoleUI/KSPAddScreen.cs
ConsoleUI/KSPEditScreen.cs
ConsoleUI/KSPListScreen.cs
ConsoleUI/KSPScreen.cs
ConsoleUI/RepoScreen.cs
Core/KSP.cs
Core/KSPManager.cs
Core/KSPPathUtils.cs
Core/Types/Kraken.cs

Mac users have been struggling with how to start using Console UI, see #3047, #3185, and recent discussions in the macos support channel in Discord. On close inspection, not all the on-screen prompts are as clear or helpful as they could be.
If you start ConsoleUI with no instances and you don't have KSP installed in Steam, you get the KSP instance list screen:
- There's not much of a hint of what to do (the right answer is to press <kbd>a</kbd> to add an instance.)
- "Select a game instance" is incomplete on a screen where you can also add instances
When adding an instance:
- The fields have the default `<Enter a value>` ghost text, which could be more helpful
- Not all users may necessarily know what a path is, and if they do, they might not be sure about what format to use (macOS uses …

Streamline Mac onboarding

---

.github/workflows/deploy.yml
.github/workflows/release.yml
debian/Makefile

The repo from #3197 is closer to working after #3201, but still has some issues, including this when attempting to install ckan:
```
Fehl:3 http://ksp-ckan.s3-us-west-2.amazonaws.com/deb nightly/main all ckan all 1.29.1                                  
404  Not Found [IP: 52.218.240.57 80]                           
E: Fehlschlag beim Holen von http://ksp-ckan.s3-us-west-2.amazonaws.com/deb/./ckan_1.29.1_all.deb 404  Not Found [IP: 52.218.240.57 80]
---
Err:3 http://ksp-ckan.s3-us-west-2.amazonaws.com/deb nightly/main all ckan all 1.29.1                                  
404  Not Found [IP: 52.218.240.57 80]                           
E: Error while fetching http://ksp-ckan.s3-us-west-2.amazonaws.com/deb/./ckan_1.29.1_all.deb 404  Not Found [IP: 52.218.240.57 80]
```
The …

Put .deb file in root of APT repo

---

Core/ModuleInstaller.cs
Core/Relationships/RelationshipResolver.cs
Core/Types/CkanModule.cs

Upgrading mods that previously provided a module and depend on it in the next version currently fails:
```
About to upgrade...
Downloading "https://github.com/R-T-B/Kopernicus/releases/download/UBE-release-46/KopernicusBE_1101_Release46.zip"
Module "Kopernicus Bleeding Edge Beta - DEV RELEASE" successfully installed
The following inconsistencies were found:
* Kopernicus-BE UBEE_1101_46 missing dependency ModularFlightIntegrator 1.2.7.0 or later
ModularFlightIntegrator …
```

Fix dependency resolution in mod upgrades

---

Cmdline/Action/Install.cs
Cmdline/Action/Remove.cs
Cmdline/Action/Replace.cs
Cmdline/Action/Upgrade.cs
Core/ModuleInstaller.cs

CmdLine's `upgrade` command is pretty inconsistent with `install` and `remove`:
- It doesn't describe the changes and present a yes/no prompt to confirm the user wants to proceed
- It prints double messages "Upgrading modules..." and "About to upgrade..." at the start
- It prints double messages "Done!" and "Done!" at the end
```
Upgrading modules...
About to upgrade...
Installing previously uninstalled mod Kopernicus-BE
Installing "Kopernicus-BE UBEE_1101_44"
Updating registry
Committing filesystem changes
Done!
Done!
```
- It says `Removing "CKAN.InstalledModule"` for each installed module being upgraded
Other problems:
- #3200 doesn't work for `ckan upgrade --all`
- `ModuleInstaller.InstallList` prints "Rescanning GameData" even if it's not doing that
- The fix from #3200 only affects …

Confirmation prompt for Cmdline upgrades

---

.github/workflows/build.yml
Core/CKAN-core.csproj
Core/Configuration/JsonConfiguration.cs
Core/Extensions/EnumerableExtensions.cs
Core/KSPManager.cs
Core/ModuleInstaller.cs
Core/Types/CkanModule.cs
Tests/Core/Relationships/SanityChecker.cs
Tests/Tests.csproj
build.cake
packages.config

Mostly because I already have the changes and because @HebaruSan said I should do a PR :D
Also [.NET 5 has been released yesterday](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/) as "the first release in [Microsoft's] .NET unification journey."
The Core DLL isn't really used anywhere on its own, especially in its .NET (Core) form, so this shouldn't break anything either.
One day we want to create a new GUI based on MAUI, so it's not a bad idea to keep the Core up to date.
* Changed the `netstandard2.0` `TargetFramework` to `net5.0` in `CKAN-core.csproj`. The `net45` one is untouched.
* Changed the `netcoreapp3.1` `TargetFramework` to `net5.0` in `Tests.csproj`. The `net45` one is untouched.
* Put our own `IEnumerable.TohashSet()` implementation between `#if NET45 ... #endif`, …

Upgrade DLL build to .NET 5

---

GUI/Main/MainInstall.cs
GUI/Model/ModChange.cs

#3204 added a yes/no prompt in `ModuleInstaller.Upgrade`, but I thought GUI only used `UninstallList` and `InstallList`. No, it does call `Upgrade`.
Now the confirmation prompt is suppressed.
- Now GUI passes `ConfirmPrompt=False`
- This is only available on the `CkanModule`-based version of `Upgrade`, and GUI previously used the `string`-based version, so now we've switched to the other

Suppress confirmation prompt for GUI upgrades

---

GUI/Controls/ManageMods.cs
GUI/Model/GUIConfiguration.cs

Request from Discord:
Now the main mod list in GUI supports multi-column sorting. If you shift-click a column header, instead of replacing the previous sort, it is added as a secondary sort.
Note that the previous saved sort setting is replaced with a new, multi-column one, without a migration. This means the value of the old setting will be lost on upgrade, and users will be presented with the default view of the grid sorted by mod name. Users can restore their old setting by clicking the column header.

Allow sort by multiple columns

---

Netkan/CKAN-netkan.csproj
Netkan/Services/IModuleService.cs
Netkan/Services/ModuleService.cs
Netkan/Validators/CkanValidator.cs
Netkan/Validators/CraftsInShipsValidator.cs
Netkan/Validators/PluginCompatibilityValidator.cs

Mods commonly distribute craft files, sometimes in a separate Ships folder, but sometimes in GameData. They are available to the user in-game if and only if they're installed into `Ships/VAB` or `Ships/SPH`. We can create custom install stanzas to handle this, but currently we lack guardrails in case we miss a chance.
Now a new Netkan validator prints a warning if any craft files are installed outside the Ships folder. These warnings will appear in Discord and the status page so we can update the affected mods.

Netkan warning for craft files installed outside Ships folder

---

Netkan/Validators/CraftsInShipsValidator.cs

These are all programmatically detectable false positives:
ContractConfigurator and the stock (DLC) Missions framework both incorporate craft files into their folder structures, so these files should be installed where they are.
Now we don't print the warning if the path starts with `Missions/` or `GameData/ContractPacks/`.

Skip warnings for craft files in missions and contract packs

---

GUI/Dialogs/NewRepoDialog.Designer.cs
GUI/Dialogs/NewRepoDialog.cs
GUI/Dialogs/NewRepoDialog.resx
GUI/Dialogs/SettingsDialog.Designer.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Dialogs/SettingsDialog.resx

The repo and auth token sections of the GUI Settings use pipe characters to fake multiple columns:
The popup to add a repo:
- has title "Settings"
- is enormous compared to how much space its content requires
- isn't resizable
- also uses pipe characters to fake multiple columns in the list
- requires the user to type pipe characters in a special format to enter a custom repo
- has no label for its text field
- has the text field, cancel, and OK buttons inside the "Official repositories" frame even though these controls are not related to official repositories
- The repo table in Settings is a ListView with two columns
- The auth token table in Settings is a ListView with two columns
- Title is now "Add Repository"
- The blank space in the repo list is reduced
- The form is resiable
- The …

Manage repos with separate name and URL fields

---

debian/Makefile

In #3197 (and subsequent fixes), we added a deb repo with `stable` and `nightly` builds.
If you install a `nightly` build, and then we merge new changes the next day, the resulting build will have the same version number as what you have installed (currently v1.29.1), and so APT packaging tools won't prompt you to update.
(`sudo apt-get update && sudo apt-get reinstall ckan` does work, though.)
Now the versions for the .deb files have the 2-digit year and the day-of-year appended as the build number, as in:
- v1.29.1.20333
This way you will be prompted to update if your installed version is a day or more older than the latest version in the dist you chose. Note that both `nightly` and `stable` releases are affected by this change, but only `nightly` is updated with each merge to `master`; …

Distinguish deb packages with build numbers

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml
GUI/Controls/ManageMods.resx
GUI/Localization/de-DE/ManageMods.de-DE.resx
GUI/Localization/zh-CN/EditModSearch.zh-CN.resx
GUI/Localization/zh-CN/EditModSearchDetails.zh-CN.resx
GUI/Localization/zh-CN/Main.zh-CN.resx
GUI/Localization/zh-CN/ManageMods.zh-CN.resx
GUI/Main/Main.resx

Before #2964, we built releases on Mono 5.16, then that PR changed it to Mono 6.6. This broke things (see below), so as 
a workaround, #2976 changed it back to Mono 5.20 in a panic. Here we attempt to address the root cause.
When we build on Mono 6, running the GUI on Windows throws an exception at startup:
```
Unhandled Exception: System.ArgumentException: Object of type 'System.Globalization.CalendarId[]' cannot be converted to type 'System.Int32[]'.
at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
at System.Reflection.RtFieldInfo.UnsafeSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, …
```

Make Mono 6 builds work on Windows

---

GUI/Properties/AssemblyInfo.cs
GUI/SingleAssemblyComponentResourceManager.cs
Tests/GUI/ResourcesTests.cs

#3218 fixed a problem with Mono 6 generating builds that don't work on Windows, but there's a risk that Visual Studio will create the problem again by setting the `$this.Language` property of a `.resx` file. If this happens, the current maintainers may not remember or may never have known that this is a problem, and a broken release could happen.
Now a new Test checks that `$this.Language` is not set in any known resource file, which will prevent this problem from recurring in the future. To achieve this, `SingleAssemblyComponentResourceManager` is marked as `internal` and the Tests project is given internals-visibility into the GUI project.

Add test for Control.Language property resource

---

.github/workflows/deploy.yml
Dockerfile.metadata
build.cake

Deprecating or Jenkin's CI infrastructure has been on the road map for some time. To support this path we can build a container with the ckan/netkan tools for use during GitHub Actions.

Metadata GitHub Actions Container

---

Dockerfile.netkan

As of #3218 we know what the problem was with our Mono 6 builds: a serialization problem that only affected GUI and is now fixed.
Now we build the Inflator on `mono:latest` since it is safe to do so.

Build Inflator on latest Mono

---

Cmdline/Action/Install.cs
Cmdline/ConsoleUser.cs
Netkan/ConsoleUser.cs

If metadata pull request validation (see KSP-CKAN/xKAN-meta_testing#61) fails at the installation stage, errors are printed but aren't recognized as errors by the GitHub workflow framework, so they're not highlighted or pinned to the affected file:
- https://github.com/KSP-CKAN/CKAN-meta/runs/1572305201
Error messages are just passed to `IUser.RaiseMessage`, despite reporting error conditions, which in turn just outputs via `System.Console.WriteLine`. GitHub actions require special formatting to recognize error messages.
- Now one call per error is made to `RaiseError`, the one that's most likely to be helpful if pinned to a file
- Now if we're in `Headless` mode, `RaiseError` prints via `log.ErrorFormat`, and also replaces all line break sequences with `%0A` so multi-line messages can be …

Format installation errors for GitHub Actions in headless mode

---

Netkan/Model/Metadata.cs

This is a spiritual successor to #3157.
A Discord user and I saw the same issue described in #3157: `netkan.exe` repeatedly purging and re-downloading a cache entry that it thought it was stale. The file was uploaded less than an hour previously, and I'm in the western hemisphere.
Here `updatedToken` will be a `JToken` object representing the (correct) value of `release_date` in the .ckan file, which includes timezone info:
https://github.com/KSP-CKAN/CKAN/blob/90fdf7a898c57e66b84689c56f2df8d0b1c30e84/Netkan/Model/Metadata.cs#L112-L118
To convert it to a `DateTime`, we:
1. Cast it to a `string`, which internally results in something like `12/21/2020 7:53:07 PM`, lacking timezone info
2. Parse that `string` into a `DateTime`, which also lacks timezone info
3. Call `ToUniversalTime()`, …

Fix Netkan timezones again

---

Netkan/Services/IModuleService.cs
Netkan/Services/ModuleService.cs
Netkan/Transformers/LocalizationsTransformer.cs
Netkan/Validators/ModuleManagerDependsValidator.cs
Netkan/Validators/PluginCompatibilityValidator.cs

This from KSP-CKAN/NetKAN#8275 is a false positive:
And there are probably several related false negatives (i.e. missing errors that should be there).
When Netkan looks for files with a particular suffix in a ZIP, it looks at the source filename in the ZIP, not the destination filename that will be installed. But what matters at run time is the destination file name, and the above PR renames many .txt files to .cfg. Currently they're not checked for MM syntax.
Now Netkan looks at the destination file name when listing files from a ZIP by suffix, so files that are renamed from .txt to .cfg will be checked for MM syntax.
This will probably have some fun conflicts with #3223. Will rebase that one later.
I'm planning to merge quickly this so I can try revalidating that PR.

Validate renamed files by their new names in Netkan

---

GUI/Util.cs

On certain multi-monitor configurations (mine looks like  ![image](https://user-images.githubusercontent.com/1559108/103468141-c5a03a00-4d1b-11eb-87fb-994e0c292070.png)), the tray icon menu appears offscreen (this is monitor 1, the one on the lower right):
There may also be some related problems with the entire window appearing offscreen, but I haven't observed that directly.
We have logic to "clamp" the menu's area to be on-screen (see #2587, shared with the window position restoration code, see #2677), but currently the `Top` and `Left` properties are switched, so the position won't get adjusted if the `Y` value is greater than the `Left` position of the screen.
Now we compare `X` to `Left` and `Y` to `Top`, and the menu appears onscreen:

Fix screen clamping logic

---

Core/Configuration/JsonConfiguration.cs
Netkan/Validators/VrefValidator.cs

If your install stanzas don't match any files, netkan will falsely report that you have a version file:
- https://github.com/KSP-CKAN/NetKAN/runs/1654148422
A bad install stanza is most likely to be submitted by an inexperienced netkan user, to whom it's not good to send misleading messages, since they might take the advice and get frustrated.
`VrefValidator` is catching the `BadMetadataKraken` thrown by Core as a `Kraken` generated by `GetInternalAvc` and interpreting it as a problem with a found version file.
Exceptions are a blunt instrument reliant on guessing and interpretation and prone to surprises.
Now `VrefValidator` catches `BadMetadataKraken` separately and ignores it. Install stnazas are checked more rigorously in other validators, which will print the error (that's why one of …

A bad install stanza is not a version file

---

CKAN.schema
Core/Types/ResourcesDescriptor.cs
GUI/Controls/ModInfo.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.resx
Netkan/Transformers/AvcTransformer.cs
Spec.md

When investigating issues with mods' compatiiblity, the one piece of info that isn't readily available on http://status.ksp-ckan.space/ is the remote version file URL, which is important because it contains the latest compatibility data that is used for inflation. To get this, we have to download the ZIP and read the internal version file.
Now `resources.remote-avc` is populated with the remote version file URL when available and displayed in GUI. I believe this will also flow through to the status page with no further changes, see KSP-CKAN/NetKAN-status#9.
The spec and schema are updated to support this new property, but I don't think we need to bump the minor version of the next CKAN release for this.
```json
"resources": {
"homepage": …
```

Store remote version file URL in metadata resources

---

Cmdline/Action/Update.cs
Cmdline/ConsoleUser.cs
ConsoleUI/ModListScreen.cs
Core/Net/Repo.cs
Core/Registry/Registry.cs
GUI/Main/Main.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRepo.cs

After KSP-CKAN/CKAN-meta#2159, many users opted in to the Kopernicus Bleeding Edge repo to use Kopernicus on recent game versions.
This PR attempts to modernize repo updates somewhat.
- In the last few days, @R-T-B's server went down and those users saw errors:
- The stack trace is big and scary and doesn't help users
- There's no obvious way back to the normal app screens. Cancel is available but does nothing; if you're extremely clever, clicking the Manage mods tab works.
- There's not a lot of info shown about what's going on during a repo update
- CmdLine's `IUser` implementation always prints `\r\n` before `RaiseProgress` and after `RaiseMessage` (implicitly via `WriteLine`). This means that if you alternate them, you end up with separate messages combined onto one line or extra …

Repo update usability fixes

---

Netkan/Services/ModuleService.cs
Netkan/Transformers/AvcTransformer.cs
Netkan/Transformers/VersionedOverrideTransformer.cs
Tests/NetKAN/Transformers/AvcTransformerTests.cs

See KSP-CKAN/NetKAN#8291; if mod authors only track compatibility on SpaceDock (i.e. don't use a KSP-AVC version file), then the handy prompt to update compatibility when a new version is released just ends up changing the single compatible game version, so that for example compatibility with 1.11 is gained while compatibility with 1.10 is lost, when they may be expecting the total compatibility with prior versions to be remembered over the long term. All of @KSPSnark's mods have been subject to this forever, see KSP-CKAN/NetKAN#6629 and KSP-CKAN/NetKAN#6639 for the last time we tried wrestling with it.
The most natural thing is to add this:
```json
"x_netkan_override": [ {
"version": "1.10",
"override": {
"ksp_version_min": "1.8"
}
} ],
```
But that currently errors out:
```
2194 [1] …
```

Better version overrides in Netkan

---

GUI/Controls/ManageMods.cs

Fixed KSP-CKAN/CKAN#3241 where application would err when using certain keyboard controls on an empty filter

Added null check in ManageMods.cs to prevent crash on an empty filter

---

GUI/Controls/ManageMods.cs
GUI/Dialogs/EditLabelsDialog.Designer.cs
GUI/Dialogs/EditLabelsDialog.cs
GUI/Dialogs/EditLabelsDialog.resx
GUI/Labels/ModuleLabel.cs
GUI/Labels/ModuleLabelList.cs
GUI/Localization/de-DE/EditLabelsDialog.de-DE.resx
GUI/Main/MainLabels.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.resx

Sometimes a user doesn't want to upgrade an upgradeable mod for the foreseeable future:
Now a new "Don't upgrade" checkbox is added to the Edit Labels form:
If checked, mods with this label will not be upgraded by the "Add available updates" button (though the Update column will still appear to let users know an update exists and isn't being installed, and the user can still choose to upgrade manually):
A user installing CKAN for the first time will have a default label "Held" created with this feature enabled; existing users will have to create their own labels.

Allow label to pin installed mod version

---

.github/workflows/build.yml

From time to time there are PRs that need a ckan.exe to be provided to users who don't have a dev environment for CKAN set up yet, and can't or don't want to run `./build`.
Some examples:
* #3272, which adds a new translation to CKAN. Someone adding or improving CKAN's localizations doesn't necessarily want to bother with setting up everything that's needed to compile CKAN, but still needs to check a client compiled with the changes to check whether everything works and makes sense.
* #3025 where a user reported a bug on Discord, and we wanted the user to test the changes
In the second case it's quite simple for us to provide a build, but it would still be nice to have a build provided by the isolated build system, in its release configuration. 
In the first case it's possible that all …

Upload ckan.exe artifact on pull requests

---

Netkan/CKAN-netkan.csproj
Netkan/Model/Metadata.cs
Netkan/Sources/Github/GithubApi.cs
Netkan/Sources/Github/GithubRef.cs
Netkan/Sources/Github/GithubRelease.cs
Netkan/Sources/Github/GithubReleaseAsset.cs
Netkan/Transformers/GithubTransformer.cs
Netkan/Transformers/VersionEditTransformer.cs
Spec.md
Tests/NetKAN/Sources/Github/GithubApiTests.cs
Tests/NetKAN/Transformers/GithubTransformerTests.cs

Kopernicus is a complex mod usually breaking between KSP releases. It used to only support one "primary" KSP version and some older ones in a separate [backports repository](https://github.com/Kopernicus/Kopernicus-Backport/releases).
Now that @R-T-B has taken over development, he introduced a new build system which allows him to easily support multiple KSP versions at the same time in the same repo.
Preferably he would want to release all assets/zips for every supported KSP version in a single release tag, like he does for his [bleeding edge repo](https://github.com/R-T-B/Kopernicus/releases), where the metadata is currently [maintained by hand](https://github.com/R-T-B/CKAN-meta-dev-Kopernicus_BE).
However, NetKAN currently doesn't support this. With `/ckan/github` $krefs, it always …

 Support indexing mulitple release assets on GitHub 

---

CHANGELOG.md
bin/ckan-merge-pr.py
bin/requirements.txt

In #3263 we created a Python script to merge pull requests more easily.
The script is very procedurally-oriented; it's one long function containing a sequence of complex steps that aren't always clearly related to one another, and not much structure or abstraction. This makes it harder to isolate one particular operation and check that it works properly.
The script seems unable to merge branches that aren't rebased on current master, even if the conflicts are trivial. It is inconvenient to have to rebase every pull request before merging.
`repo.index.merge_tree` doesn't do well with conflicts, but it's what you'll find if you go looking for ways to merge with GitPython. I think it is intended to be a low-level tool for apps that intend to re-implement parts of the `git merge` command …

Refactor merge script into classes, don't require rebase

---

AutoUpdate/CKAN-autoupdate.csproj
AutoUpdate/Main.cs
Core/Net/AutoUpdate.cs
GUI/CKAN-GUI.csproj
GUI/Dialogs/NewUpdateDialog.Designer.cs
GUI/Dialogs/NewUpdateDialog.cs
GUI/Main/Main.cs
GUI/Main/MainAutoUpdate.cs

- If anything goes wrong with the AutoUpdater, it doesn't tell the user anything about what happened.
- One of the things that can go wrong is that it's possible (though _very_ unlikely) for the old ckan.exe to be deleted without the new one being renamed or launched, see #3245.
- Users have reported truncated registries and other issues when an auto-update happens
- The auto-update window uses black text on a dark background if you're using a dark theme
- The auto-update window positions itself at the absolute upper-left of your overall screen space, which may be quite far away from where you're working or where CKAN will appear
- AutoUpdater just exited and never printed anything on errors, presumably because it was intended as a very simple small tool that would never have any problems …

Report AutoUpdater errors to user, fix rare failure

---

GUI/Controls/ModInfo.cs
GUI/Main/Main.Designer.cs

We continue to get questions about why a mod is shown as incompatible when the user expects it to be compatible. The answer is that there is a conflict or an unsatisfied dependency, but this is generally not obvious.
Now if a mod is incompatible because of the KSP versions, `<!>` is added to its Versions tab, which shows the range of compatible versions:
And if a mod is incompatible because of a conflict or an unsatisfied dependency, `<!>` is added to its Relationships tab, which shows those relationships:
Ideally these would have been big red stop sign icons instead, but Mono's `TabControl` does not display icons (it _makes room_ for them if you set `TabPage.ImageIndex` or `TabPage.ImageKey`, but they're never _drawn_ :roll_eyes:).
Priorities in choosing these characters:
- They should …

Visual cues for incompatibility reasons

---

Netkan/Transformers/GithubTransformer.cs

#3279 made it possible to inflate multiple assets per GitHub release, which KSP-CKAN/NetKAN#8338 then enabled for Kopernicus.
- There might be other mods out there that could benefit from this, either now or in the future
- Mods that upload mulitple assets may be generating bad metadata if their authors expected #3279 to exist before it existed
Now if Netkan notices a multi-asset release and isn't configured for it, it prints a warning.

Netkan warning for multiple assets

---

Core/GameInstance.cs
Core/ModuleInstaller.cs
Core/Registry/Registry.cs

If you manually install a version of ModuleManager different from the one CKAN would install for you (e.g., I install MM 4.1.0 but CKAN knows that 4.1.4 is current), trying to convert it to CKAN control by upgrading as per #3043 fails with this error:
> Module Manager 4.1.4 (cached)
> DLL for module ModuleManager found at GameData/ModuleManager.4.1.0.dll, but it's not where CKAN would install it. Aborting to prevent multiple copies of the same mod being installed. To install this module, uninstall it manually and try again.
Error during installation!"
We created that warning to catch cases where the manual install is incorrect, as it says. But the logic of the check is too strict; for a smooth automatic upgrade, we require that the old and new file names match _exactly_. That won't be the …

Upgrade AD mods with mismatched version in filename

---

Core/DLC/StandardDlcDetectorBase.cs
Core/ModuleInstaller.cs
Core/Registry/RegistryManager.cs
GUI/Controls/AllModVersions.cs
GUI/Controls/Changeset.Designer.cs
GUI/Controls/Changeset.cs
GUI/Controls/Changeset.resx
GUI/Controls/EditModpack.Designer.cs
GUI/Controls/EditModpack.cs
GUI/Controls/EditModpack.resx
GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Controls/Wait.cs
GUI/Localization/de-DE/Changeset.de-DE.resx
GUI/Localization/de-DE/EditModpack.de-DE.resx
GUI/Main/Main.cs
GUI/Main/MainChangeset.cs
GUI/Model/ModList.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.resx

@kerbal-propulsion-laboratory (ezee on Discord) presented us with the idea of a metapackage in a custom repo. It works, with quirks.
- The Download button in mod info is enabled for metapackages
- The right click menu download option is enabled for metapackages
- Exporting a modpack doesn't populate the author and release date
- The changeset tab has only two options, Clear and Apply, neither of which lets you go back to the modlist with the same changeset intact
- The column headers on the changeset tab sometimes disappear on Mono
- The "release status" and "replaced by" fields in mod info are always shown even when they're not set, cluttering the display
- The version of the current Breaking Ground expansion is not detected, so its other metadata (such as the store links) isn't …

Modpack usability fixes

---

Core/Relationships/RelationshipResolver.cs
GUI/Controls/ChooseRecommendedMods.cs
GUI/Controls/EditModSearch.Designer.cs
GUI/Controls/EditModSearch.cs

Two ways to observe these bugs:
1. Open GUI
2. Install these mods: [Jesscah03.zip](https://github.com/KSP-CKAN/CKAN/files/5940449/Jesscah03.zip)
3. File → Audit recommendations
4. Scroll down to the two nearly identical rows for Not So Simple Construction
5. Check both of them
6. Get an exception:
```
28701 [1] ERROR CKAN.RelationshipResolver (null) - Assertion failed: Adding NSSC twice in relationship resolution
System.ArgumentException: Already contains module: NSSC
at CKAN.RelationshipResolver.Add (CKAN.CkanModule module, CKAN.SelectionReason reason) [0x0007b] in <6a47e5b996604b7ea227275020b13b34>:0 
at CKAN.RelationshipResolver.AddModulesToInstall (System.Collections.Generic.IEnumerable`1[T] modules) [0x00144] in <6a47e5b996604b7ea227275020b13b34>:0 
at CKAN.RelationshipResolver..ctor …
```

Fix crashes in audit recommendations

---

GUI/Controls/ManageMods.cs

If you have an AD mod and sort by the Installed column, the AD mod will be shown after all the non-installed compatible mods. This is bad because the installed mods should be listed together at the top.
Originally the sort order of a checkbox column was:
- Checked checkboxes
- Text not containing "-"
- Unchecked checkboxes
- Text containing "-"
In #3205 the checkbox column sort logic was rewritten and the original logic was lost; it is now:
- Checked checkboxes
- Unchecked checkboxes
- Text of any kind, regardless of content
Now the sort order for a checkbox column is restored to what it was.

Fix checkbox sorting

---

GUI/Controls/ChooseRecommendedMods.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs

1. Find an incompatible mod that has a compatible recommendation or suggestion that depends back on the original mod.
(One example is RasterPropMonitor and RasterPropMonitor-Core, which are not compatible with KSP 1.11, and recommend ASETProps, which depends on RasterPropMonitor-Core.)
2. Use the Versions tab checkboxes to add the incompatible mod(s) to the change set.
3. Click Apply to go to the recommendations/suggestions screen
4. Check the checkbox for the mod that depends on the incompatible mods you're force-installing.
(In our example, this is ASETProps)
5. On Windows:
On Linux, the same exception is printed to stdout.
```
CKAN.DependencyNotSatisfiedKraken: ASETProps dependency on RasterPropMonitor-Core 1:v0.30.2 or later version (any) not satisfied
at …
```

Handle incompatible force-installed dependencies of recommendations

---

Core/Registry/InstalledModule.cs
Core/Registry/Registry.cs
GUI/Main/Main.cs
GUI/Model/ModList.cs

Similarly, this can appear for a mod that was incompatible when you installed it but has since become compatible (because it's on SpaceDock and someone put in a `ksp_version_min` override).
Also if you have any DLC installed and you click to install two conflicting mods, they aren't highlighted red.
SQUAD didn't update the MH version number correctly (flashbacks to the extra whitespace for the other DLC in #3243). Current `GameData/SquadExpansion/MakingHistory/readme.txt`:
```
*****************************************************************************************************
__ _______ ____     __  ___      __   _               __  ___      __ 
/ //_/ ___// __ \   /  |/  /___ _/ /__(_)___  ___  _  / / / (_)____/ / ____ 
/ ,<  \__ \/ /_/ /  / /|_/ / __ `/ //_/ / __ \/ __ `/ / /_/ / / …
```

Don't warn about incompatible DLCs, fix conflict highlighting with DLC installed

---

Cmdline/Action/Prompt.cs

This is the remnant of #3224 that survived a sanity check. (I debated whether to submit a PR or just push it to master, since it's so short and only what we saw earlier, but the work flow really isn't that onerous.)
Currently `ckan prompt` just drops you to a prompt, which you may or may not expect. There's a `help` command, but you might not think to try that if you don't already know about it.
Now `ckan prompt` prints a little greeting message at startup. It suggests trying the `help` command to get help.

Greeting for ckan prompt

---

ConsoleUI/ConsoleCKAN.cs
ConsoleUI/ModListScreen.cs
Core/ModuleInstaller.cs
Core/Net/NetAsyncDownloader.cs
Core/Registry/IRegistryQuerier.cs
Core/Relationships/RelationshipResolver.cs
GUI/Controls/AllModVersions.cs
GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Controls/Wait.Designer.cs
GUI/Controls/Wait.cs
GUI/Controls/Wait.resx
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/Main/Main.Designer.cs
GUI/Main/MainChangeset.cs
GUI/Main/MainInstall.cs
GUI/Main/MainWait.cs
GUI/Model/GUIMod.cs

* If you cancel an installation too late and can't be stopped anymore and finishes successfully, the changeset doesn't get cleared.
* Clearing the changeset on the changeset tab doesn't remove incompatible mods checked using the `AllModVersiions` tab. Neither does it remove mods queued for removal because they've been checked as auto-installed without any dependent mods.
* A Discord user from the r/KerbalSpaceProgram server who tends to find every bug and glitch in CKAN, likes to double-click the "Accept" button in the changeset tab. This throws an exception:
```
System.InvalidOperationException: This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.
at System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
at …
```

Fixes for GUI and .ckan-installed modules

---

GUI/Dialogs/AskUserForAutoUpdatesDialog.Designer.cs
GUI/Dialogs/AskUserForAutoUpdatesDialog.resx
GUI/Dialogs/NewUpdateDialog.Designer.cs
GUI/Localization/de-DE/AskUserForAutoUpdatesDialog.de-DE.resx
GUI/Localization/fr-FR/AskUserForAutoUpdatesDialog.fr-FR.resx
GUI/Localization/fr-FR/Main.fr-FR.resx
GUI/Localization/fr-FR/NewUpdateDialog.fr-FR.resx
GUI/Localization/zh-CN/AskUserForAutoUpdatesDialog.zh-CN.resx

Since this dialog only shows up on updating, I had no way to check if it worked.
When updating to 1.30, I noticed that the "not now" button wasn't big enough.
I made it bigger, and I shortened the text, but I don't know how to test my changes.

Update dialog was too small for French localization

---

.github/workflows/deploy.yml
.github/workflows/release.yml

Upgrading the stable .deb to v1.30.0 isn't working:
```
The following packages will be upgraded:
ckan
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 775 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable/main amd64 ckan all 1.30.0.21065 [775 kB]
Err:1 https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable/main amd64 ckan all 1.30.0.21065
File has unexpected size (774308 != 774780). Mirror sync in progress? [IP: 52.218.184.25 443]
Hashes of expected file:
- SHA256:20bd6bbfe1132e3656e696f4e77bce8a5e0ae7e605563814b2f149ace96dbd0b
- SHA1:24241c129cf0b4478706b430362568df35d55cd5 [weak]
- MD5Sum:3bd7a5896c00e81b1bcd1ebe19c34909 [weak]
- …
```

Suppress nightly debs with even builds, push release debs to s3 first

---

GUI/Controls/ManageMods.cs
GUI/Model/GUIConfiguration.cs

#3223 renamed the `KSPCompatibility` column to `GameCompatibility`.
If you had the mod list sorted by this column (be it the only one or one of many) while upgrading from v1.29.2 to v1.30.0, the GUI crashes due to a NullReferenceException with a rather useless stacktrace:
```
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at CKAN.ManageMods._UpdateModsList(Dictionary`2 old_modules)
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at …
```

Handle renamed modlist columns in sort list  gracefully

---

Netkan/CKAN-netkan.csproj
Netkan/Validators/CkanValidator.cs
Netkan/Validators/HarmonyValidator.cs

See KSP-CKAN/NetKAN#8288, we are attempting to prevent mods that bundle conflicting versions of Harmony from clashing with each other.
Before that PR, all Harmony-based mods in CKAN bundled Harmony 1, and CKAN installed them as-is. They may continue to do so, but only if they are appropriately flagged in the metadata:
```json
"provides": [ "Harmony1" ],
"x_netkan_staging": true,
"x_netkan_staging_reason": "Bundles Harmony. Please check the DLL's version, and if it's 2 or later, remove the provides and add a depends on Harmony2.",
```
A mod with this metadata will be treated as incompatible with `Harmony2`, and each time it releases a new version, it will be staged for manual review so we can check whether the author has upgraded to Harmony 2.
Mods that use Harmony 2 will share a common …

Netkan errors and warnings for Harmony bundlers

---

Netkan/Services/IModuleService.cs
Netkan/Services/ModuleService.cs
Netkan/Validators/VrefValidator.cs

The "$vref absent, version file present" errors are hard to monitor because many of them are false positives:
http://status.ksp-ckan.space/
(x44 lines)
Many of these are caused when a mod with no version file of its own bundles a mod with a version file. In such cases it would be incorrect to add a `$vref` to the bundling mod's metadata. Unfortunately the only way we can determine that at present is to inspect the ZIP manually.
The only public interface for finding version files is `IModuleService.GetInternalAvc`, which just returns either null or the fully parsed AVC object (or throws an exception). It doesn't tell us where it found the file or whether it would even be installed by this module (non-installable version files are checked as a fallback for cases where multiple modules share …

Print path of unused version file

---

Netkan/Services/ModuleService.cs
Netkan/Validators/VrefValidator.cs

In #3327 we eliminated some false positives for the "vref absent" warnings.
KSP-CKAN/NetKAN#8429 attempted to address the remaining warnings, which revealed that they were mostly version files with syntax errors.
We can't use a version file with a syntax error, so those are still false positives in a sense, but in case one of those mods releases a new version with a fixed syntax error, it would be nice to know about it.
Now we try to parse the version file, and if there's a syntax error, we don't print the warning. This will cut down on non-actionable warnings on the status page.
If the syntax error ever gets fixed, the warning will come back, which will trigger the usual Discord notification.

Exclude version files with syntax errors from warnings

---

.gitignore
Core/CKAN-core.csproj
Netkan/CKAN-netkan.csproj
Tests/Tests.csproj
bin/requirements.txt

https://github.com/KSP-CKAN/NetKAN/issues/8425 and https://github.com/KSP-CKAN/NetKAN/issues/8315 show some weird errors when trying to extract certain zips with special characters on Windows systems with CJK locales.
_Maybe_ this is a bug of `SharpZipLib`, and _maybe_ it is already fixed in a newer versions. It's a total stab in the dark, but worth a try. I've asked affected users to try a debug build with an updated version of the package, we should know when we get an answer.
In any case, there have been some improvements to that library in the releases since, the usual performance enhancements, and support for BZip2 compression.
We have been using a "Patched" version of this library, which has been deprecated now. Its [NuGet page](https://www.nuget.org/packages/ICSharpCode.SharpZipLib. …

Switch from outdated SharpZipLib.Patched to newer SharpZipLib

---

Core/GameInstanceManager.cs
Tests/Core/CKANPathUtils.cs
Tests/Core/GameInstance.cs
Tests/Core/GameInstanceManager.cs

If the download cache folder disappears, and the user can't write to its previous location anymore, CKAN refuses to start:
We try to create the cache path at startup to handle onboarding for new users and users upgrading to the version of CKAN after the cache was unified. `Directory.CreateDirectory` throws if this fails, which mostly makes sense because we can't really operate without a valid download cache.
Note that this happens in the CmdLine startup code before we attempt to load GUI, so improving the error message UI isn't a viable option.
Now if the configured cache path doesn't exist and we can't create it, we revert it to the default setting and try again. This will work seamlessly if the only thing that's happened is that the user's name has changed, because the default setting …

Reset cache dir to default if creation fails

---

Core/Net/Repo.cs
GUI/Dialogs/ManageGameInstancesDialog.cs
Netkan/Validators/VrefValidator.cs

If a user tries to add a game instance for which they lack filesystem write privileges, it fails silently, and an exception appears in the terminal:
```
System.UnauthorizedAccessException: Access to the path '/ram/Fake-1.11.1/CKAN' is denied. ---> System.IO.IOException: Keine Berechtigung
at System.IO.FileSystem.CreateDirectory (System.String fullPath) [0x00191] in <673b2a9c49de4736b9b01249f8d6d6b1>:0
at System.IO.Directory.CreateDirectory (System.String path) [0x0002c] in <673b2a9c49de4736b9b01249f8d6d6b1>:0
at ChinhDo.Transactions.FileManager.TxFileManager.CreateDirectory (System.String path) [0x0001b] in <bd256a5f4bd9434c90d5e776dca9de7b>:0
at CKAN.GameInstance.SetupCkanDirectories (System.Boolean scan) [0x0006e] in …
```

Tell user if instance addition fails

---

Core/ModuleInstaller.cs

If you try to overwrite a manually installed file with the current dev build, an unhandled exception is thrown:
```
Unhandled Exception: System.NotSupportedException: InflaterInputStream Length is not supported
at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.get_Length()
at CKAN.ModuleInstaller.StreamsEqual(Stream s1, Stream s2)
```
icsharpcode/SharpZipLib#84 changed the zip lib to throw an exception if you ask it for the length of a file in a ZIP. Before that I think it would have returned the correct length, because `ModuleInstaller.StreamsEqual` correctly reported whether files were the same.
We upgraded to that version of the lib in #3329, so users are not yet affected by this.
Now `ModuleInstaller.StreamsEqual` compares its input streams without checking their …

Fix crash when overwriting manually installed files

---

bin/ckan-merge-pr.py

Initially I only wanted to fix this one:
```
$ python bin/ckan-merge-pr.py 3340
Fetching origin...
Fetching https://github.com/gsantos9489/CKAN.git PTBR_Translation...
Traceback (most recent call last):
File "C:\git-reps\CKAN\bin\ckan-merge-pr.py", line 122, in <module>
merge_pr()
File "C:\git-reps\CKAN\bin\venv\lib\site-packages\click\core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "C:\git-reps\CKAN\bin\venv\lib\site-packages\click\core.py", line 782, in main
rv = self.invoke(ctx)
File "C:\git-reps\CKAN\bin\venv\lib\site-packages\click\core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\git-reps\CKAN\bin\venv\lib\site-packages\click\core.py", line 610, in invoke
return callback(*args, **kwargs)
File …
```

Use git cmd to add CHANGELOG.md in merge script

---

Core/Registry/AvailableModule.cs

1. Refresh the registry with CKAN v1.30.0
2. Close CKAN
3. Launch CKAN v1.29.2 or earlier
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> CKAN.BadMetadataKraken: The license SomethingWeird is invalid
at CKAN.License..ctor(String license)
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at …
```

Skip modules with parse errors in deserialization

---

ConsoleUI/ModListScreen.cs
Core/Types/Repository.cs

If you edit your current instance's repositories in ConsoleUI, the new module list is not fetched.
If you edit your current instance's compatible versions in ConsoleUI, the mod list is not updated to reflect the new compatibility.
We refresh the mod list if you switch instances, but not otherwise.
Now if you add or remove a repo, we update the registry upon returning to the mod list.
Now if you change the compatible versions, we refresh the mod list upon returning to it.
Fixes #3352.

Update or refresh ConsoleUI mod list after repo or compat changes

---

bin/ckan-merge-pr.py

I was getting this when trying to run the PR merge script on Windows:
```
$ python bin/ckan-merge-pr.py 3353
Fetching upstream...
Fetching https://github.com/HebaruSan/CKAN.git fix/consoleui-refresh...
Traceback (most recent call last):
File "bin/ckan-merge-pr.py", line 123, in <module>
merge_pr()
File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 717, in main
rv = self.invoke(ctx)
File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 555, …
```

Merge script fix for Windows

---

Cmdline/Action/Update.cs
Cmdline/Action/Upgrade.cs
ConsoleUI/InstallScreen.cs
ConsoleUI/ModListScreen.cs
Core/ModuleInstaller.cs
Core/Net/Repo.cs
Core/Types/Kraken.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRepo.cs

When you refresh the registry, if the metadata for one of your installed modules has been changed upstream, CKAN will ask whether you want to reinstall those modules, and if you say Yes, it will reinstall them.
```
The following mods have had their metadata changed since last update:
- Buffalo v2.9.0
- WildBlueTools v1.81.5
- ExtraPlanetaryLaunchpads 6.8.3.0
- ClassicStockResources v1.1.4
You should reinstall them in order to preserve consistency with the repository.
Do you wish to reinstall now?
```
If one of your installed modules has been updated to have a new dependency on a virtual module, the reinstall fails:
```
Failed to connect to repository. Exception: Too many mods provide Buffalo-PlayMode:
* Buffalo-PlayMode-CRP v2.10.2
* Buffalo-PlayMode-ClassicStock v2.10.2
* …
```

Replace repo-reinst with kraken, handle in UIs

---

Cmdline/Action/Import.cs
Cmdline/Action/Install.cs
Cmdline/Action/Remove.cs
Cmdline/Action/Replace.cs
Cmdline/Action/Upgrade.cs
ConsoleUI/DependencyScreen.cs
ConsoleUI/DownloadImportDialog.cs
ConsoleUI/InstallScreen.cs
ConsoleUI/ModInfoScreen.cs
Core/ModuleInstaller.cs
GUI/Controls/AllModVersions.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Main/MainImport.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs
Tests/Core/ModuleInstaller.cs
Tests/Core/ModuleInstallerDirTest.cs
Tests/GUI/GH1866.cs

1. Install something
2. Change the cache path
3. Install something else; the download will succeed but the install will fail:
```
Downloading "https://spacedock.info/mod/1466/FuelEfficientPilots/download/0.2"
Trying to install FuelEfficientPilots 0.2, but it's not downloaded or download is corrupted
```
`ModuleInstaller` is a singleton (per game instance). It stores a reference to the cache object that it is given when created; if the user changes the cache path, that …

Make ModuleInstaller a non-singleton

---

Core/GameInstance.cs
Core/Registry/RegistryManager.cs
GUI/Controls/ManageMods.cs
GUI/Dialogs/CloneFakeGameDialog.cs
GUI/Main/Main.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.fr-FR.resx
GUI/Properties/Resources.pt-BR.resx
GUI/Properties/Resources.resx
GUI/Properties/Resources.zh-CN.resx

If your `CKAN/registry.json` file gets truncated somehow, CKAN won't start.
```
Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing object. Path 'available_modules.WindowShineTR.module_version['1:2.0'].download_hash.sha256', line 979045, position 0.
```
```
Newtonsoft.Json.JsonReaderException: Unexpected end of content while loading JArray. Path 'available_modules.RP-0.module_version['v1.6'].recommends[21]', line 648536, position 8403726.
in Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
in Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
in Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
```
``` …
```

Better recovery when registry.json is corrupted

---

Core/ModuleInstaller.cs

When trying to install metapackages from cmdline, using `ckan.exe -c metapackage.ckan`, it doesn't actually install any mods:
```
$ mono ckan.exe install --instance "Fake-1.11.2" -c asdf.ckan 
About to install:
Updating registry
Committing filesystem changes
Rescanning GameData
Done!
```
whereas the GUI installs them correctly.
In ` InstallList(List<string> modules, ...)`, we are running the `RelationshipResolver` for the identifier list, to get back a list of `CkanModule` to install. Then we filter out all modules installed as dependencies, to make sure the resolver running in `InstallList(ICollection<CkanModule> modules, ...)` can re-detect them as dependencies, so we can mark them as auto-installed.
https://github.com/KSP-CKAN/CKAN/blob/72c4a569ec59ef6998b256ac89e345e83 …

Fix installation of metapackages on cmdline

---

Core/ModuleInstaller.cs
Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
Core/Relationships/RelationshipResolver.cs
Core/Types/RelationshipDescriptor.cs
GUI/Main/MainInstall.cs
GUI/Model/ModList.cs
Tests/Core/Relationships/RelationshipResolver.cs

Or: Fix resolution of circular dependencies when conflicts are involved.
Or: Another open heart surgery of the relationship resolver.
Have EnvironmentalVisualEnhancements with its default configs EnvironmentalVisualEnhancements-HR installed.
Now deselect EnvironmentalVisualEnhancements-HR and select AVP.
See this double error message:
```
AVP-8kTextures v1.12 depends on AstronomersVisualPack, which is not compatible with the currently installed game version
```
The issue goes down to `MightBeInstallable()`  returning false for any AstronomersVisualPack,
because `LatestAvailableWithProvides()` can't find any provider for `AVP-Textures`,
because they all depend on AstronomersVisualPack again,
which `LatestAvailableWithProvides()` / `AvailableModule.Latest()`  sees as incompatible 
due to …

Fix installation of AVP while removing EVE default configs

---

GUI/Model/ModSearch.cs

You can't search for a label with a space in its name.
We use spaces to split up search terms.
- When we generate a search string, we combine the words in a label with the spaces removed, so `label:Label with a space` becomes `label:Labelwithaspace`
- When we parse a search string, we remove spaces from the labels' names when we check whether they match.

Handle searches for labels with spaces

---

doc/apt-repo.md

Our release notes template needs to be revised, and one of the things that should go somewhere else is the APT repo instructions. However, the instructions involve several `sudo` commands, including one that adds CKAN's key to the system's trusted APT keys, so if we put this on a wiki page, there is a small risk that a random GitHub user would make an edit that would change the instructions to install a malicious key. We would revert that as soon as we noticed it, but there would be a risk to user systems as long as the edit was live.
We could lock down the wiki:
... but then it's not really a wiki anymore, and we would lose the benefits of user interaction and general editability.
As far as we have been able to determine, GitHub wikis cannot lock down individual pages, nor can they hold …

Create APT repo documentation

---

GUI/Controls/ManageMods.cs

With the restructuring to the search done in #3323 we added a call to `SetupDefaultSearch()`, which indirectly modifies GUI controls through other functions it calls.
As we all know, updating GUI components from another thread basically doesn't work.
In this case it manifests itself through freezes at the end of the repository update for some users.
Now `ManageMods.Filter()` and `ManageMods.SetSearches()`, both called in `SetupDefaultSearch()`, wrap every GUI-related work and call in a `Util.Invoke()`.
The diff looks worse than the actual change :smile: 
I wonder if there's some static code analysis tool that can catch this? At least my IDE doesn't :/
I can't confirm the effectiveness of this patch, as my low core count tablet/laptop/convertible doesn't reproduce the hang/freeze (the …

Invoke GUI update calls in SetupDefaultSearch() descendants

---

ConsoleUI/ModListScreen.cs

We just saw this in Discord:
The referenced pinned message is:
It's there because this is the top FAQ for ConsoleUI by a large margin. People want/need to edit the compatible versions, and it's very non-obvious how to do that.
Now a new "Game instance settings..." option is added as a shortcut to the screen to which the longer directions lead:
Just like in #3353, if you add or remove a repo, we will force a registry refresh after you save, and if you add or remove compatible versions, we will update the mod list.

Make current instance settings easier to find in ConsoleUI

---

Netkan/Transformers/NetkanTransformer.cs
Netkan/Transformers/SpacedockTransformer.cs
Tests/NetKAN/Transformers/SpacedockTransformerTests.cs

The `resources.bugtracker` property links to a place where users can report problems with a mod. It is available in the GUI and the status page. It can be set manually in a netkan or automatically for mods hosted on GitHub (see #3061).
It would be nice to set this for mods on SpaceDock as well so we can jump to issues lists conveniently for more mods.
Now if a mod on SpaceDock has a source code link of the form `https://github.com/owner/repo/whatever`, we will call out to the GitHub API to check whether that repo has issues enabled. If so, then `resources.bugtracker` will be set to the repo's issues link.

Set bugtracker resource for SpaceDock mods with GitHub repos

---

Core/GameInstance.cs
Core/Registry/RegistryManager.cs
GUI/Dialogs/ErrorDialog.cs
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/Main/Main.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.resx
debian/ckan.1

If you have multiple game instances, you've selected one as the default instance, and you open that instance in CKAN, then opening another copy of CKAN will cause it to print an error about the instance being locked and quit.
However, if you have no default instance, then in the same flow you will be prompted to choose an instance. The user shouldn't lose options because they've selected a default instance.
Now if the default instance is locked by another process but there are other unlocked instances, the Manage Game Instances popup appears. Instances that have a `CKAN/registry.locked` file will have "(LOCKED)" appended to their names, so you can tell which ones are open in other instances of CKAN:
Also the Linux man page's documentation for the `ckan ksp` subcommand is updated to the …

Choose game instance if default is locked

---

Core/Net/Net.cs

Since the merge of #3384, the bot has been spamming mysterious errors about rate limits:
There is also some substantial metadata "churn" as the intermittent (un)availability of files causes properties to toggle back and forth between values or existence and non-existence:
This has happened before, so we knew that these were for files in repos that had been moved or renamed. Previously we addressed this by updating enough of our references to such files to make the errors stop, see KSP-CKAN/NetKAN#8488, KSP-CKAN/NetKAN#8489, KSP-CKAN/NetKAN#8490, KSP-CKAN/NetKAN#8491, KSP-CKAN/NetKAN#8492. However, this time the culprits are all remote version file URLs contained inside of mod downloads; we have submitted pull requests to update them, but it will take a while for enough authors to merge …

Pass token for moved files on GitHub

---

Core/Net/Net.cs

This is a follow-up to #3387. Passing the token after a redirect solved the error spam, but the Inflator will still attempt to retrieve out of date URLs even after the server tells us it is out of date.
Now we save HTTP redirects that we receive in a `Dictionary` and use them to skip the old URL if it is needed again. This will somewhat reduce our GitHub API usage, leaving more slack to index more mods.

Cache permanent redirects

---

Netkan/CKAN-netkan.csproj
Netkan/Extensions/YamlExtensions.cs
Netkan/Model/Metadata.cs
Netkan/Processors/QueueHandler.cs
Netkan/Program.cs
Netkan/Services/ModuleService.cs
Netkan/Transformers/MetaNetkanTransformer.cs
Spec.md
Tests/NetKAN/Extensions/YamlExtensionsTests.cs
Tests/Tests.csproj

Currently all metadata is in JSON. This is fine/great for machine-written metadata, but for humans it can be a bit tricky, as we have to worry about proper usage of quotes, commas, braces, brackets, etc.
YAML is a JSON superset format used for GitHub Actions and many other administrative/automation contexts. It is somewhat more human-friendly than JSON, as quotes, commas, braces, and brackets are assumed based on the structure and indenting of the data. For example, this JSON:
```json
{
"spec_version": "v1.4",
"identifier": "Cosmogator",
"$kref": "#/ckan/github/HebaruSan/Astrogator",
"license": "GPL-3.0",
"tags": [
"plugin",
"information",
"control"
],
"install": [
{
"find": "Astrogator",
"install_to": "GameData"
}
]
}
```
is equivalent to this YAML:
```yaml
spec_version: v1.4
identifier: …
```

Allow YAML for human-edited metadata (YAMLKAN)

---

Netkan/Transformers/SpacedockTransformer.cs

#3384 added the ability to set `resources.bugtracker` for SpaceDock mods with a source code link to a GitHub repo with the issues list enabled. This is nice, but there is more we can do.
Now if a SpaceDock mod has a source code link that points to GitHub, we do a little more with the GitHub API info:
- `resources.repository` will be set to the proper URL of the repo, so the CKAN metadata will be current in case it has been moved or renamed (I think this will also remove suffixes like `/releases` from repo links that have them, which is probably good)
- If the SpaceDock mod entry has no homepage, then the homepage from GitHub will be populated into `resources.homepage` (this will probably be very rare, people usually set the homepage on SpaceDock and rarely set it on GitHub)
- If the …

Fill more info from GitHub for SpaceDock mods

---

Core/Registry/Registry.cs
Netkan/Validators/PluginsValidator.cs

1. Open [the status page](http://status.ksp-ckan.space/)
2. In the filter field, type an underscore (`_`)
3. Some of the warnings for "no plugin matching the identifier" are for cases where the DLL name has an underscore, which isn't allowed in an identifier anyway, and the corresponding identifier has a dash in the same place:
NetKAN | Warning
:-- | :--
KSP-PartVolume | No plugin matching the identifier, manual installations won't be detected: GameData/KSP_PartVolume/Plugins/KSP_PartVolume.dll
KerbalWeatherProject-Lite | No plugin matching the identifier, manual installations won't be detected: GameData/KerbalWeatherProject_Lite/KerbalWeatherProject_Lite.dll
NASA-CountDown | No plugin matching the identifier, manual installations won't be detected: …

Match underscore in DLL to dash in identifier

---

ConsoleUI/ModInfoScreen.cs
GUI/Controls/ManageMods.resx
GUI/Localization/de-DE/ManageMods.de-DE.resx
GUI/Localization/fr-FR/EditModSearch.fr-FR.resx
GUI/Localization/fr-FR/ManageMods.fr-FR.resx
GUI/Properties/Resources.fr-FR.resx

Mac users somewhat regularly ask why their mods are not installed after using this option:
That hotkey is the equivalent of "Download Contents" in GUI; it's not supposed to install the mod, it just downloads the ZIP file into the cache, from which it can be installed later.
Now the screen tip explains the option more verbosely, which hopefully will help to set more accurate expectations:
GUI's right click menu is updated the same way for the following locales:
- English
- French
- German
Changes for other locales may follow...

Clarify that downloading to cache does not install

---

Cmdline/Action/Search.cs
Cmdline/Action/Show.cs
Cmdline/Options.cs

After KSP-CKAN/CKAN-meta#2389 updated the compatibility of 17 old modules and its parent PR used this illustration:
... I said this and got a :+1: :
There are also lots and lots of things I don't like about the current `ckan show` command.
- Only allows one mod to be searched at a time
- The format is almost but not quite YAML-like
- Extra blank line after description if it exists
- Always shows "Status" field even if it isn't set, even though it's optional, non-functional, and usually not set
- Always shows "Provides" section and includes the mod's own identifier in the list, introducing visual clutter
- Missing tags and localizations data
- Missing manual and version file links
- Resource URLs not aligned the same as the "module info" section above
Now you can use `ckan show …

Add versions table option to ckan show command

---

Core/Registry/RegistryManager.cs

DLC have been making mischief for modpacks.
(We did **not** make a change to exclude DLC by default; I was thinking of #3139, which did this for modules from custom .ckan files.)
When we generate a modpack, installed DLC modules are included by default. This doesn't make sense because CKAN can't install DLC, and modpacks should be lists of mods for CKAN to install.
Now DLC appear in the Ignored list by default instead of Depends. If a user really wants them included in the pack, they can be moved to one of the other groups with the buttons. If any of the mods have a dependency on a DLC, this will already work normally.

Don't include DLC in modpacks by default

---

CKAN.schema
Cmdline/Action/Install.cs
Cmdline/Action/Upgrade.cs
ConsoleUI/InstallScreen.cs
Core/Converters/JsonRelationshipConverter.cs
Core/ModuleInstaller.cs
Core/Relationships/RelationshipResolver.cs
Core/Types/Kraken.cs
Core/Types/RelationshipDescriptor.cs
GUI/Controls/ChooseProvidedMods.cs
GUI/Main/MainInstall.cs

The RSS/RO/RP-0/RP-1 team reached out to discuss ways to streamline their installation process, see KSP-CKAN/NetKAN#8615 and KSP-CKAN/NetKAN#8688. They hope to reduce the number of decisions the user has to make and provide more information to help the user make good choices.
We're still brainstorming options for improvements, but a few ideas seem to be clear wins so far. This is the first of possibly/hopefully several changes resulting from that discussion.
- When a `depends` clause matches multiple modules (via either `provides` or `any_of`), only a standard prompt based on the identifier(s) is shown (and it varies between CmdLine/ConsoleUI/GUI). The RSS/RO/RP-0/RP-1 team would like to be able to override that prompt in order to give users additional help and clues about which module to …

Override provides prompt with relationship property, check first recommendation in any_of group

---

Netkan/Validators/LicensesValidator.cs
Netkan/Validators/RelationshipsValidator.cs
Spec.md

In #3426 we added the ability to set `choice_help_text` for a relationship to change the prompt the user sees when choosing between multiple modules.
However, if you add `choice_help_text` to an `any_of` relationship, the current client will throw exceptions. So if any metanetkan does this, old clients could be disabled until we clean it up. This kind of incompatibility is usually managed with `spec_version` bumps.
Now if Netkan finds `choice_help_text` in an `any_of` relationship, it requires the `spec_version` to be at least v1.31. This will ensure that the old clients will not attempt to load such metadata. This will require the next release to be v1.31.0.
The spec is updated to explain `choice_help_text`, since it now has a version-specific component.
The "Set `x_netkan_license_ok` to …

More Netkan validation for any_of

---

Dockerfile.metadata

See https://github.com/KSP-CKAN/NetKAN/pull/8704 and https://github.com/KSP-CKAN/xKAN-meta_testing/pull/80, those directories have been moved into the working directory in the container (which is a volume mounted to `/github/workspace`), so we can access them after the xKAN_meta-testing action finished and the container exited.
Thus, there's no need to create them in the Dockerfile anymore.
As `/github/workspace` is mounted during runtime, we can't create `.ckans` and `.repo` beforehand (or better: the created directories would be lost). Instead they are created at runtime.

Don't create no longer used directories in Dockerfile.metadata

---

GUI/Localization/ru-RU/ManageMods.ru-RU.resx
GUI/Localization/ru-RU/ModInfo.ru-RU.resx
GUI/Properties/Resources.ru-RU.resx

A question I have: are empty strings allowed?
Asking specifically for the `"ModSearchYesPrefix"` string. Russian doesn't use copulas in the way English does, which means (besides the obvious) I can't find a translation that will also agree with mod state adjectives.

Update Russian localization

---

GUI/Localization/de-DE/Main.de-DE.resx
GUI/Localization/fr-FR/Main.fr-FR.resx
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/Main.resx

CKAN has a pretty detailed user guide that answers most questions users might have. We frequently handle support questions by posting links to it:
- https://github.com/KSP-CKAN/CKAN/wiki/User-guide
However, GUI's help menu shows only:
This means the user guide isn't discoverable, and the help menu doesn't provide help!
Now new menu items in the Help menu link to the user guide and CKAN Discord:
Hopefully this will mean that users seeking help will find the user guide and see their questions answered within it. If not, they can ask questions on Discord.
Is "User guide" clear enough that a user would click on it? Checking a few older Windows applications, they use Help → View Help to open their main help documentation, which we could do as well.

Add user guide and Discord to GUI help menu

---

Spec.md

In #3367, we enabled YAML format for human-edited metadata, but most of the relevant documentation still uses JSON. This may be leading advanced users to submit JSON format netkans instead of YAML (see KSP-CKAN/NetKAN#8720).
Now the Spec.md documentation uses YAML format when discussing netkans.
The wiki page for adding a mod was updated here, in case you would like to review the changes:
https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN/_compare/9e902784ae698b6f1f1fe8fca6e3b82bcead4e2e...2f5cacc582c207b8ffa3d1988f5e89ad17ef374f
Also the long-broken link to ksp.marce.at is replaced.

YAMLize netkan spec

---

Core/ModuleInstaller.cs
Core/Types/CkanModule.cs
Core/Types/ModuleInstallDescriptor.cs
Netkan/Validators/InstallValidator.cs
Netkan/Validators/InstallsFilesValidator.cs
Spec.md
Tests/Core/ModuleInstaller.cs

In KSP-CKAN/NetKAN#8735, this metadata:
```yaml
install:
- find: GameData/InterstellarTechnologies
- install_to: GameData
```
caused this error:
```
Error: 1459 [1] FATAL CKAN.NetKAN.Program (null) - Object reference not set to an instance of an object
```
`install_to` is [required by the spec](https://github.com/KSP-CKAN/CKAN/blame/2a2b12e399818e39534070ccf888e3ac08fd47af/Spec.md#L292-L303), and `NetKAN.Validators.InstallValidator` assumes `install_to` will be set. In this instance, it wasn't, because that YAML translates to:
```json
"install": [
{
"find": "GameData/InterstellarTechnologies"
},
{
"install_to": "GameData"
}
]
```
We should catch this explicitly rather than throwing a NRE.
That PR's changes were essentially trying to make the default install stanza's behavior more …

Default install stanza multi-game support, catch missing install_to

---

GUI/Controls/ModInfo.cs

If a mod has `&` in its abstract, it is hidden and the next character is underlind in the mod info abstract label:
A similar issue with the mod list was fixed in #3149.
WinForms `Labels` (and some other controls) treat `&` as a hotkey indicator; the next character in the text is used as the hotkey such that if you press Alt and that key, the control (or the next control in the tab order) receives focus. This is indicated visually by hiding the `&` and underlining the next character.
Usually it's not a good idea to expose this functionality to external data sources such as abstracts entered into SpaceDock; they generally just want the `&` to display normally, which is accomplished by doubling it to `&&`.
Now we double any ampersands in the abstract when populating them into the mod info …

Escape ampersands in mod info abstract label

---

Netkan/CKAN-netkan.csproj
Netkan/Transformers/NetkanTransformer.cs
Netkan/Transformers/StagingLinksTransformer.cs

This staging reason explicitly mentions "the forum thread" but fails to provide it:
KSP-CKAN/CKAN-meta#2460
That makes these PRs somewhat annoying to review, since you have to find that link yourself (probably via the status page or by checking the metadata).
Now we append a table of the mod's `resources` links to the body of any staging pull request:
KSP-CKAN/CKAN-meta#2462 (manually inserted)
Behind the scenes:
- We add a new, later Netkan transformer because `StagingTransformer` has to run _before_ the `$kref` processors to be able to detect hard coded versions, but we usually only have the resources available _after_ those transformers run
- We use Markdown's `<link>` syntax for links because otherwise GitHub excludes a trailing `*` from the URL, which we use to abbreviate a lot of …

Append resource links to staging PRs

---

Core/Registry/AvailableModule.cs

A module that tries to filter an option out of the "Too many mods provide" prompt with a conflict just ends up complaining to the user after the fact:
```yaml
depends:
- name: CustomBarnKit
conflicts:
- name: CustomBarnKit-RO
```
```
$ ckan compat add 1.7
$ ckan install Komplexity
Module CustomBarnKit is provided by more than one available module. Please choose one of the following:
1) CustomBarnKit-RO (Custom Barn Kit - RO build)
2) CustomBarnKit (Custom Barn Kit)
Enter a number between 1 and 2 (To cancel press "c" or "n".): 
1
The following inconsistencies were found:
* CustomBarnKit-RO 1.1.20.0 conflicts with Komplexity 0.9.3.0
Install canceled. Your files have been returned to their initial state.
```
Noticed while investigating KSP-CKAN/NetKAN#8656.
The relationship resolver relies …

Don't prompt user to choose conflicting modules

---

.github/workflows/build.yml
Dockerfile.metadata
Dockerfile.netkan

We are seeing hundreds of SSL errors from our indexer for SpaceDock mods, and metadata CI is broken for those as well.
An old root certificate used by Let's Encrypt (DST Root CA X3) has expired. It has largely been replaced by the ISRG Root X1, which is in the certificate trust stores of most modern systems.
However, to enhance compatibility with older clients (especially Android phones, which don't check whether root certs have expired), the X1 cert has a cross-signature from the old X3.
More information:
- https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
- https://scotthelme.co.uk/lets-encrypt-old-root-expiration/
- https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/
(The below is my best guess at where the exact issue with Mono is, I might be …

Remove expired Let's Encrypt root certificate from Mono containers

---

Core/GameInstance.cs
Core/SuppressedCompatWarningIdentifiers.cs
GUI/Dialogs/YesNoDialog.Designer.cs
GUI/Dialogs/YesNoDialog.cs
GUI/Main/Main.cs
GUI/Main/MainDialogs.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.fr-FR.resx
GUI/Properties/Resources.resx

In #2601 we added a pop-up that appears at game launch if the user has incompatible modules installed:
The goal was to alert users that some previously compatible mods may stop working after Steam auto-updates the game (e.g., this would have happened with the upgrade from KSP 1.7 to 1.8), similar to what KSP-AVC and MiniAVC do. It was also hoped that prompting users in this way would have positive side effects for metadata accuracy (i.e., if they know a mod is compatible but not yet marked as such, they might submit pull requests for that mod's version file to update it), but for the most part that seems not to have happened.
Some power users install incompatible mods on purpose and experience alert fatigue with this popup. They would like to be able to suppress it, especially after they …

Suppress incompatibility warning at game launch

---

Cmdline/Action/Show.cs
Cmdline/Options.cs

`ckan show` uses a fairly lengthy hard-coded output format. Some users may wish to only see some parts of it, for example if they're processing the output with other tools.
Now `ckan show` has several new options for hiding sections (`--with-versions` was already there but lacked help text, which is now added):
```
$ ckan show --help
CKAN 1.30.5+d398f2e236d6
Copyright © 2014-2020
show - Show information about a mod
Usage: ckan show [options] module
--without-description      Don't show the name, abstract, or description
--without-module-info      Don't show the version, authors, status license,
tags, languages
--without-relationships    Don't show dependencies or conflicts
--without-resources        Don't show home page, etc.
--without-files            Don't show contained files …
```

Options for ckan show to hide sections

---

ConsoleUI/Toolkit/ConsolePopupMenu.cs
ConsoleUI/Toolkit/ConsoleScreen.cs
ConsoleUI/Toolkit/Keys.cs
ConsoleUI/Toolkit/ScreenContainer.cs
GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Dialogs/AboutDialog.Designer.cs
GUI/Dialogs/AboutDialog.cs
GUI/Dialogs/ManageGameInstancesDialog.Designer.cs
GUI/Dialogs/ManageGameInstancesDialog.cs

Most keyboards have a key to open a context menu (mine requires pressing Fn+PrintScrn, but it's there). Currently this does nothing in CKAN, to the detriment of keyboard users.
The mod list context menu is implemented in the grid's `MouseDown` event, and pressing the menu key triggers `KeyDown` and does nothing.
Now the code to manage the menu is moved a new `ShowModContextMenu` function, which is called from `MouseDown` on a right click and `KeyDown` for `Key.Apps` (the code for the menu key).
Similar changes are also made for the URL link labels in mod info and the About dialog, as well as the list of instances in the manage game instances dialog. And this key also now opens and closes the F10 menu in ConsoleUI.
Fixes #3445.

Show context menu on menu key press

---

GUI/Model/ModList.cs
GUI/Model/ModSearch.cs

If you manually type a search for `is:compatible` (or various other similar searches like `not:compatible`, `is:cached`, etc.) rather than clicking the check/X buttons in the dropdown, the UI responds very sluggishly on Windows.
Notably, this doesn't happen for something like `dep:kopernicus` or searching for fragments of a name, where each keystroke is pretty snappy.
A search for `is:compatibl` (note the missing `e` at the end) or any shorter substring is the same as an empty search, because we parse the `is:` prefix first and check whether the suffix matches any of our known strings, and if it doesn't, we just discard that part of the search. However, the UI still treats this as if it was a new search that needs a refresh at each keystroke, so we call `ManageMods.UpdateFilters` and …

Suppress filter updates for unchanged semantic search meaning

---

.gitattributes

We do already have a line break there:
https://github.com/KSP-CKAN/CKAN/blob/41a0143b5cfb48b5767db306f045ae1640143e0a/GUI/Properties/Resources.resx#L272-L274
[It seems that `.resx` files are supposed to use CRLF line endings](https://github.com/dotnet/msbuild/issues/2206), but we have them as normalized to LF in the repo and OS-specific in the working dir (CRLF when checked out on Windows, LF on Linux and Mac), so it would be LF when we build in an Ubuntu container:
https://github.com/KSP-CKAN/CKAN/blob/41a0143b5cfb48b5767db306f045ae1640143e0a/.gitattributes#L31
Refresher for `.gitattributes` usage:
- `text` means to treat the matching files as text format. LF will be stored to the server, LF will be used on Linux and Mac, CRLF will be used on Windows.
- `text=auto` means to run git's …

Use CRLF for resx files

---

Core/Registry/InstalledModule.cs
Core/Registry/Registry.cs

Recently, Windows users have been encountering weird install/uninstall errors relating to Scatterer:
In its [latest release](https://spacedock.info/mod/141/scatterer/download/0.0825b), Scatterer renamed its install folder from `scatterer` to `Scatterer` (capitalizing the S), but the metadata was unchanged until KSP-CKAN/NetKAN#8862. There was no inflation error because install stanza matching is case insensitive, so `find: scatterer` matched a path in the ZIP of `Scatterer`:
https://github.com/KSP-CKAN/CKAN/blob/35927bcc70dd3febb62f34cbb0e2bbb5ab24bbee/Core/Types/ModuleInstallDescriptor.cs#L230-L245
One user who encountered these errors shared a screenshot confirming that the mod was installed into `GameData/scatterer`:
But their `registry.json` has it as `GameData/Scatterer` in the …

Case insensitive installed file lookup on Windows

---

Dockerfile.netkan

CKAN and Netkan both use a default `User-Agent` of `Mozilla/4.0 (compatible; CKAN)`.
This `User-Agent` does not identify the Inflator as a bot, which it most certainly is.
See KSP-SpaceDock/SpaceDock#436 for why we might want to do that.
I don't know if there's a comprehensive reference on how to create a `User-Agent` string; the best reference I was able to find was:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent#crawler_and_bot_ua_strings
Based on the examples presented there, the Inflator's `User-Agent` is now:
`Mozilla/5.0 (compatible; Netkanbot/1.0; CKAN; +https://github.com/KSP-CKAN/NetKAN-Infra)`
I think parsers will just check whether `bot` occurs in the browser family.
The `HyperEdit` and `Graphotron` mods use a combination of strange URLs:
- …

Set bot useragent for Inflator

---

Netkan/Services/ModuleService.cs
Netkan/Transformers/AvcTransformer.cs
Netkan/Transformers/LocalizationsTransformer.cs
Netkan/Validators/CraftsInShipsValidator.cs
Netkan/Validators/HarmonyValidator.cs
Netkan/Validators/InstallsFilesValidator.cs
Netkan/Validators/ModuleManagerDependsValidator.cs
Netkan/Validators/PluginsValidator.cs

It was a surprise to see this for an established mod that probably isn't changing much from one release to the next:
It seems like the warning should remain the same and therefore not be sent to Discord.
Same files, different order. The order of the list in the message depends on the order in the ZIP file, so if a succession of releases has the same warnings but the ZIP is created slightly differently, we get extra warning messages sent to Discord:
This could happen for any warning that contains a list of multiple things.
Now the following messages are sorted alphabetically. This will probably cause a one-time cascade of new warnings sent to Discord as they all switch over to the proper sorted order:
- Multiple version files
- Craft files in wrong path
- Found copies of the Harmony DLL
- …

Sort Netkan warning lists

---

Core/GameInstanceManager.cs

If you have no `config.json` file, and your Window registry has the `KSPInstanceCount` key set to a positive value but no `KSPInstancePath_<number>` properties, CKAN fails to start:
```
Unhandled Exception: System.ArgumentException: The path is not of a legal form.
at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
at System.IO.Path.GetFullPathInternal(String path)
at CKAN.GameInstance..ctor(IGame game, String gameDir, String name, IUser user, Boolean scan)
at CKAN.GameInstanceManager.LoadInstances()
at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
at CKAN.CmdLine.MainClass.Main(String[] args)
```
`Win32RegistryConfiguration.GetInstance` calls `GetRegistryalue` with a default …

Log error and recover on instance loading exception

---

Cmdline/ConsoleUser.cs
Core/GameInstanceManager.cs
Core/User.cs
GUI/Dialogs/CloneFakeGameDialog.cs
GUI/Dialogs/SelectionDialog.cs
GUI/Main/Main.cs

A user reported a problem when trying to clone a KSP instance, they're getting a `Clone failed: Object reference not set to an instance of an object` error.
We couldn't quite figure out what the user was doing exactly, the messages were kinda vague:
> I remember I was messing around with the specific path, and I changed it, but the changes didn't show up, so I figured it hadn't saved my changes or something
But after looking at the clone UI logic, these lines stood out as a possible cause for a NRE:
https://github.com/KSP-CKAN/CKAN/blob/2564dfb3a0784cf82cedaf9cac1c0064a2b6b58a/GUI/Dialogs/CloneFakeGameDialog.cs#L149-L156
They were refactored in #3223 and didn't account for the possibility of a path being entered that didn't already belong to a known instance, which would result in a …

Properly determine the game when cloning instances

---

Netkan/Validators/InstallValidator.cs

The spec says:
https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#install
>- `filter_regexp` : (**v1.10**) A string, or list of strings, which are treated as case-sensitive C# regular expressions which are matched against the full paths from the installing zip-file. If a file matches the regular expression, it is *not* installed.
>- `include_only` : (**v1.24**) A string, or list of strings, of file parts that should be installed. These are treated as literal things which must match a file name or directory. Examples of this may be `Settings.cfg`, or `Plugin`. These are considered case-insensitive.
>- `include_only_regexp` : (**v1.24**) A string, or list of strings, which are treated as case-sensitive C# regular expressions which are matched against the full paths from the installing …

Enforce spec version requirements for more install properties

---

GUI/Controls/AllModVersions.Designer.cs
GUI/Controls/AllModVersions.cs
GUI/Controls/AllModVersions.resx
GUI/Localization/de-DE/AllModVersions.de-DE.resx
GUI/Localization/fr-FR/AllModVersions.fr-FR.resx
GUI/Localization/ja-JP/AllModVersions.ja-JP.resx
GUI/Localization/pt-BR/AllModVersions.pt-BR.resx
GUI/Localization/ru-RU/AllModVersions.ru-RU.resx

The existing translations of the Release date column header in the mod grid are copied to the new column. Also changed the English capitalization of these column headers to match the mod grid (sentence capitalization instead of title capitalization) and removed "Compatible" to save space.
Fixes #3480.

Add Release Date column to GUI modinfo versions list

---

ConsoleUI/Toolkit/ConsoleTextBox.cs

- ConsoleUI's textbox (used on the progress screen and mod info) wraps lines longer than its width at word boundaries, but unbroken words longer than its width (e.g. URLs) underlap the scrollbar if there is one, hiding one character from view
- If you resize ConsoleUI and press <kbd>Ctrl+L</kbd>, the text within the textbox is still formatted according to its previous layout, which may leave big gaps or allow the text to overflow the box
Noticed while testing RP-1 express install in ConsoleUI for #3512, because [a Mac user asked about RP-1 on the forum](https://forum.kerbalspaceprogram.com/index.php?/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1304-hubble/&do=findComment&comment=4075886).
`ConsoleTextBox` performs word wrap on each line as it is added, using the full width …

Rewrap ConsoleUI textbox for scrollbar and resize

---

Core/Registry/RegistryManager.cs

When you export a modpack into a `.ckan` file, the mods are in a non-deterministic order. Since the ordering changes from one export to the next, it is difficult to notice changes or track them with code tools like git or diff.
First reported here:
https://forum.kerbalspaceprogram.com/index.php?/topic/205890-%D1%81%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D1%89%D0%B8%D0%BA-ckan-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0/
(Found while searching the forum for "CKAN" because I don't have the official CKAN forum thread bookmarked.)
The order is the order of `Registry.Installed()`, which is a `Dictionary` with the identifiers as keys. This is non-deterministic.
Now we perform a case-insensitive sort by identifier after filtering the sequence and before making the `RelationshipDescriptor` objects. This …

Sort exported modpack relationships by identifier

---

Netkan/Validators/InstallValidator.cs
Netkan/Validators/LicensesValidator.cs
Netkan/Validators/RelationshipsValidator.cs
Tests/NetKAN/Validators/LicensesValidatorTests.cs

#3494 and KSP-CKAN/NetKAN#8943 were fun, so I double checked the spec and found a few more requirements we aren't checking yet:
- Installing to Scenarios requires spec version v1.14
- Installing to Missions requires spec version v1.25
- `licenses` as an array requires spec version v1.8
- `supports` requires spec version v1.2

Enforce a few more spec version requirements

---

Spec.md

The spec's summary of the available options for the `$kref` field includes a list of the properties that they can set automatically. A few were missing:
- `release_date` (see #3059)
- `resources.bugtracker` (see #3061 and #3384)
- `resources.metanetkan` (see #2913)
Now they're added.

Document which krefs set bugtracker, release_date, and metanetkan

---

Spec.md

Noticed a few more minor issues after #3519:
- The `resources.homepage` in the example CKAN file broke due to forum updates and is now updated to AJE's current thread
- "version ordering" should use sentence case capitalization because it's not a metadata property, unlike the other lowercase headings
- The link to Jenkins was using HTTP and is now updated to HTTPS
- The link to the KSP-AVC spec broke when Cybutek removed it from ksp.cybutek.net, so it now points to the `README.md` file in the current maintainer's repo, which should offer the same content (and the URL is now shared between the two places where it's used via Markdown magic, for easier maintenance)
- The documentation for `$vref` now mentions that it sets `resources.remote-avc` (see #3259)

Fix KSP-AVC links and other small issues in spec

---

Netkan/Transformers/AvcTransformer.cs
Spec.md

There are a lot of mods that have remote version files but a bad `URL` property in the version file such that the remote version file isn't found/used. This clutters our warnings list and potentially deprives CKAN of better metadata if any of them have been updated since release:
Currently these can only be resolved by submitting a pull request to the mod's repo, having it merged, and then a new release being made.
As of #3259, the `resources.remote-avc` property is set to the URL of the remote version file by the AVC transformer.
Now if the `reources.remote-avc` property is set upstream of the AVC transformer (i.e. in the netkan or by a previous transformer), we use that value to override the remote version file to check. This will allow us to suppress these warnings and get the most …

Allow overriding resources.remote-avc

---

Core/CkanTransaction.cs
Core/GameInstance.cs
Core/ModuleInstaller.cs
Core/Registry/Registry.cs
GUI/Main/Main.cs
GUI/Main/MainRepo.cs
Netkan/Validators/PluginsValidator.cs

I've been investigating several transaction-related issues lately.
- Something about trying to enlist in multiple transactions (see #3502)
- The manually installed DLL scan, which happens in a tx (see #3506)
- `Registry.DllPattern` is compiled for every call to `RegisterDll`, which is not great because this regex will be evaluated on every DLL in GameData
- A comment says the regex `works great for things like GameData/Foo/Foo-1.2.dll`, but that's wrong, it's for `GameData/Foo/Foo.1.2.dll`, the former would detect the identifier as `Foo-1`
- `EnlistTransaction` is called in `RegisterDll` even if one of its validation checks decides we don't need to make any changes
- Cloning an instance can throw an exception if it takes more than 10 minutes
- Installing mods can throw the same exception …

Disable tx timeouts, add tx debug logging, static DLL pattern, fix docs

---

Core/ModuleInstaller.cs

1. Reboot into Windows
2. Install `LTechContinued 1:0.5.2.2` or earlier
3. Try to uninstall it
```
Kan een gedeelte van het pad C:\Games\Kerbal Space Program\GameData\LTech\Parts\Science\SkyLab niet vinden.
```
Up until its latest release (see linuxgurugamer/L-Tech#2), this mod had a `Skylab` folder and a `SkyLab` folder right next to each other:
On Windows, these install into a single `SkyLab` folder, but the `Registry` remembers the different names.
At uninstall, CKAN …

Only delete diversely capitalized directories once on Windows

---

Core/CKAN-core.csproj
Netkan/CKAN-netkan.csproj
Tests/Tests.csproj

#3529, #3530, and #3531 all failed to build due to dependabot's dumb practice of creating multiple pull requests for the same repo (the three projects need to use the same version).
Now they're merged together here.

Bump SharpZipLib from 1.3.1 to 1.3.3

---

CKAN.schema
Core/CKAN-core.csproj
Core/Converters/JsonLeakySortedDictionaryConverter.cs
Core/Converters/JsonSimpleStringConverter.cs
Core/Converters/JsonSingleOrArrayConverter.cs
Core/Registry/AvailableModule.cs
Core/Registry/Registry.cs
Core/Types/License.cs
Core/Types/Schema.cs
Netkan/CKAN-netkan.csproj
Netkan/Validators/ObeysCKANSchemaValidator.cs

- Every time we add a new license, the previous version of the CKAN client is unable to read modules that use it. This is supposed to be handled by `spec_version`, but the user can bypass this protection by updating the registry with a new client and then running an old client, and they have actually done this (see #3331 and #3410 and a reply on the forum thread).
- We currently maintain the list of valid licenses in three places, which is annoying:
- `CKAN/Core/Types/License.cs`
- `CKAN/CKAN.schema`
- `NetKAN-Infra/netkan/netkan/mirrorer.py`
- Now if any `CkanModule` in the available modules list throws an exception during deserialization, including but not limited to an unsupported license, we log a warning and omit that module from its `AvailableModule` collection. This allows the user …

Get licenses from embedded schema, skip bad modules in deserialize

---

Netkan/Processors/QueueHandler.cs
Netkan/Program.cs
Netkan/Transformers/EpochTransformer.cs
Netkan/Transformers/ITransformer.cs
Netkan/Transformers/StagingLinksTransformer.cs
Netkan/Transformers/StagingTransformer.cs
Tests/NetKAN/MainClass.cs
Tests/NetKAN/NetkanOverride.cs
Tests/NetKAN/Transformers/AvcKrefTransformerTests.cs
Tests/NetKAN/Transformers/AvcTransformerTests.cs
Tests/NetKAN/Transformers/CurseTransformerTests.cs
Tests/NetKAN/Transformers/DownloadAttributeTransformerTests.cs
Tests/NetKAN/Transformers/EpochTransformerTests.cs
Tests/NetKAN/Transformers/GeneratedByTransformerTests.cs
Tests/NetKAN/Transformers/GithubTransformerTests.cs
Tests/NetKAN/Transformers/HttpTransformerTests.cs
Tests/NetKAN/Transformers/InternalCkanTransformerTests.cs
Tests/NetKAN/Transformers/MetaNetkanTransformerTests.cs
Tests/NetKAN/Transformers/SpacedockTransformerTests.cs
Tests/NetKAN/Transformers/StripNetkanMetadataTransformerTests.cs
Tests/NetKAN/Transformers/VersionEditTransformerTests.cs

Since about 2022-02-23 (earliest example I found was KSP-CKAN/CKAN-meta#2585), we have been getting auto-epoch pull requests from the bot indicating that it inflated an older release from GitHub instead of the latest release. The reason for this is unknown, but we presume the GitHub API is acting weird. We currently have no ideas for how to address this (but it would be nice!).
That phenomenon generated these pull requests:
- KSP-CKAN/CKAN-meta#2620
- KSP-CKAN/CKAN-meta#2621
- KSP-CKAN/CKAN-meta#2622
- KSP-CKAN/CKAN-meta#2623
I thought these were for a new release, but in fact they were auto-epochs for an old release.
Also, they don't have the link table, which would be nice for investigating what happened.
The pull request description was populated from the netkan's staging reason only. …

Combine staging reasons

---

Core/Net/NetAsyncDownloader.cs

In #3054 we changed the async downloader to sequentialize downloads from GitHub to avoid triggering GitHub's download throttling. Only one GitHub download will ever be active concurrently, and this seems to have solved the problems we were having with throttling.
- I have been installing big groups of mods to test #3525, and I've found that even SpaceDock does not seem to like having a lot of parallel downloads; any beyond 2 or 3 seemed to fail and fallback to archive.org or require retrying the installation. #3314 may be a report of this same problem, if the hosts of the affected downloads were mainly SpaceDock.
- In addition, `Mono.Unix.UnixIOException` can be thrown if there are many concurrent downloads in progress (see #3343 and #3555).
- It's hard to know for sure, but I suspect …

One concurrent download per host for all hosts

---

Cmdline/Action/Filter.cs
Cmdline/CKAN-cmdline.csproj
Cmdline/Main.cs
Cmdline/Options.cs
ConsoleUI/CKAN-ConsoleUI.csproj
ConsoleUI/InstallFilterAddDialog.cs
ConsoleUI/InstallFiltersScreen.cs
ConsoleUI/ModListScreen.cs
Core/Configuration/IConfiguration.cs
Core/Configuration/JsonConfiguration.cs
Core/Configuration/Win32RegistryConfiguration.cs
Core/GameInstance.cs
Core/ModuleInstaller.cs
GUI/CKAN-GUI.csproj
GUI/Dialogs/InstallFiltersDialog.Designer.cs
GUI/Dialogs/InstallFiltersDialog.cs
GUI/Dialogs/InstallFiltersDialog.resx
GUI/Localization/de-DE/InstallFiltersDialog.de-DE.resx
GUI/Localization/de-DE/Main.de-DE.resx
GUI/Localization/fr-FR/InstallFiltersDialog.fr-FR.resx
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/Main.resx
Tests/Core/Configuration/FakeConfiguration.cs

As of some recent API changes, users might install somewhat older mods that _would_ work except that they bundle `MiniAVC.dll`, which crashes the game on startup. Even before the crashes, MiniAVC was annoying and unnecessary thanks to CKAN's own compatibility checking. It would be nice to prevent MiniAVC from being installed.
> NOTE: The crash was specific to KSP 1.12.2, and was fixed in 1.12.3.
Similarly, some power users may wish to customize the details of how certain mods are installed, often a cfg file that patches how two or more mods interact. Currently they can only do this by deleting them manually after installation, which means they will re-appear after upgrades.
A new menu option under Settings opens a window with text boxes for installation filters that apply to all mods:
If …

Global install filters

---

GUI/Controls/Changeset.cs
GUI/Model/ModList.cs

1. Install xScience 5.26
2. Upgrade to the latest version
3. The change set shows just the upgrade:
4. However, the install screen shows that new dependencies will be installed:
The user should be told about this in the change set screen.
The change set screen has always only looked for dependencies for modules being installed, not upgraded.
I think the expectation was that all of the complicated stuff would happen for installs, while upgrades would be simple replacements of one version of a module with a newer version, even though the underlying relationship logic in Core can handle more complicated scenarios.
Now upgrades will be treated more like installs, in that any new dependencies they introduce will be displayed:
To make this work, we also need to fix `ComputeChangeSetFromModList` …

Show dependencies of upgrading mods in change set

---

GUI/Model/ModSearch.cs

The GUI search currently supports a limited disjunctive normal form in which only some terms can be negated (the ones using the tri-state toggle control). It would be nice to be able to negate the remaining ones.
Now if you add `-` to the start of any of the following search terms (_before_ the prefix), that term will be flipped so it matches only the mods that it didn't match previously:
- Name (no prefix)
- Description (`desc:` prefix in English)
- Authors (`@` prefix)
- Localizations (`lang:` prefix in English)
- Depends (`dep:` prefix in English)
- Recommends (`rec:` prefix in English)
- Suggests (`sug:` prefix in English)
- Conflicts (`conf:` prefix in English)
- Tag (`tag:` prefix in English)
For example, while `@HebaruSan` would include my mods, `-@HebaruSan` would exclude them. …

Negated search for name, desc, author, lang, relationships, tags

---

Core/Relationships/RelationshipResolver.cs
Core/Types/RelationshipDescriptor.cs

During the addition of RP1 Express (see KSP-CKAN/NetKAN#8701), we observed some unexpected quirks with how dependencies were resolved. We had to restructure the modules in that pull request to fit the peculiar way the relationship resolver works.
I think it's highly likely that the WildBlue play modes (see KSP-CKAN/NetKAN#8275) are also affected by these quirks, but I do not know of a specific example of this.
Consider this set of mods:
Mod | Provides | Depends | Conflicts
:-- | :------- | :------ | :--------
A   |          | B, C    |
B   |          | C1      |
C1  | C        |         | C
C2  | C        |         | C
When the user tries to install A:
1. The relationship resolver first tries to satisfy A's dependency on B, which succeeds trivially by finding the real module B.
2. Then …

Resolve virtual module dependencies in same order as non-virtual

---

GUI/CKAN-GUI.csproj
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/Localization/de-DE/Main.de-DE.resx
GUI/Localization/de-DE/PlayTime.de-DE.resx
GUI/Properties/Resources.de-DE.resx

#3543 introduced play time tracking and tries to conditionally display it in the "Manage game instances" dialog only if any instance has a playtime > 0.
This is broken, because the `0,0` string for the playtime is added to the `ListViewItem` contents array all the time, and if the column is removed it shows under `Path`:
Now the string array for the column contents is factored out into a separate function. It includes the play time string only if the column (header) will actually be present in the end.
The same is applied to the "Game" column now as well, for those that only have instances of a single type of game registered with CKAN (currently the case all the time for everyone as we don't support another game yet).
The auto-resizing needs to be done after removing columns as it applies …

Fix play time column if no playtime, hide game column if single game

---

Netkan/Sources/Github/GithubApi.cs
Netkan/Sources/Github/GithubRelease.cs

For several months now the bot has been submitting bogus auto-epoch pull requests, about 0.7 times per day:
<https://github.com/KSP-CKAN/CKAN-meta/pulls?q=is%3Apr+author%3Anetkan-bot+is%3Aunmerged+is%3Aclosed>
This seems to happen completely randomly, only for GitHub krefs, as if the most recent release for that mod has disappeared. However, when we check the repo, it is still there. So somehow the wrong release is being inflated.
We don't know for sure why this happens (it's very hard to investigate something that only happens once out of 297 unique unfrozen GitHub krefs * 2 inflations per hour * 24 hours per day / 0.7 per day = 20366 attempts), but I have two main guesses at this point:
1. The GitHub API somehow glitches out and skips the most recent release completely, so the most …

Sort GitHub releases

---

.github/workflows/deploy.yml

Currently we need to trigger the `deploy` workflow manually anytime the `xKAN-meta_testing` repo changes or if `NetKAN-Infra` changes in a way that affects the metadata validation image, because it uses both the `ckan.exe` and `netkan.exe` files and the Python code from `NetKAN-Infra` and `xKAN-meta_testing`:
https://github.com/KSP-CKAN/CKAN/blob/d724a0f28e827954cae0de98ec5aa8d480a11c47/Dockerfile.metadata#L8-L12
See c1a41d545fa7fb691d0bfcf9d64a4393ab8dd61d for a previous effort to deal with this by making it easier to trigger manually; before that we had to find the most recent `deploy` workflow run from a push to `master` and re-run it (which isn't viable if they're all too old for that).
GitHub provides a mechanism to trigger workflows via a web hook: …

Trigger deploy workflow on repo dispatch deploy event

---

Core/ModuleInstaller.cs

If you install `MrScienceMeistersNuclearWarfare` (latest version is for KSP 1.0.5) and then try to uninstall it, you get this error:
```
About to remove:
* MrScienceMeister's Nuclear Warfare 0.5.1
Could not find a part of the path 'D:\SteamLibrary\SteamApps\common\Kerbal Space Program\GameData\NuclearWarfare\Parts\freeFallNukeBrake'.
```
The path can't be found because the `installed_files` entry in `registry.json` doesn't match the path on disk.
`ModuleInstaller` …

Fix tracking of paths with trailing spaces on Windows

---

build.cake
debian/Makefile
rpm/Makefile

If you run `./build rpm` in a fresh checkout, the build fails.
```
========================================
rpm
========================================
make: *** No rule to make target '/home/user/Downloads/KSP/CKAN/rpm/../_build/repack/Release/ckan.exe', needed by '/home/user/Downloads/KSP/CKAN/rpm/../_build/rpm/RPMS/noarch/ckan-1.31.1-1.noarch.rpm'.  Stop.
An error occurred when executing task 'rpm'.
```
(Found in the early stages of investigating how to set up a yum repo.)
The default configuration for the `.exe` file is Debug, but the `.deb` and `.rpm` Makefiles assume the configuration will be Release. `debian/Makefile` has a rule to generate the Release `.exe` if it's missing by running `./build --configuration=Release` in the parent dir, but this isn't present for RPM (and it's …

Ability to build .deb and .rpm package in Debug config

---

.github/workflows/deploy.yml
.github/workflows/release.yml
build.cake
debian/copyright
doc/rpm-repo.md
rpm/Makefile
rpm/ckan_nightly.repo
rpm/ckan_stable.repo

Currently we provide `.rpm` packages, but somewhat ironically (given what CKAN is for), the user must download a new `.rpm` file and install it manually when a new version is released.
See #3197 for when we did this for APT/deb, and #2757 for when we started making RPMs.
Now a new `./build rpm-repo` command creates a `_build/rpm/repo` folder containing the `.rpm` file (signed with our GPG key) and the additional metadata files needed to host an RPM repo. Just like we did with APT, the test builds (odd build number in version) go into a `nightly` repo, and the releases go into a `stable` repo.
I followed these instructions:
- https://earthly.dev/blog/creating-and-hosting-your-own-rpm-packages-and-yum-repo/
User instructions will be in …

Generate RPM repo for releases and under dev builds

---

.github/workflows/deploy.yml
rpm/Makefile

After #3605, the build failed:
Ubuntu and Debian have `createrepo-c` for generating RPM repos. I hoped that `mono:latest` would be the same :crossed_fingers:, but it was not to be.
```
$ docker run -it --entrypoint sh mono:latest
createrepo - tool to generate the metadata for a yum repository
```
- The `deploy.yml` file is updated to install `createrepo` instead of `createrepo-c`
- The RPM `Makefile` now uses `createrepo` if you have it, or `createrepo_c` if you don't, so local dev will still work
I'll merge this shortly.

Switch build from createrepo-c to createrepo

---

rpm/Makefile

#3609 worked, but the nightly repo only has `ckan-1.31.1-1.noarch`, which lacks a daily incrementing version number part, so all the builds until the next release will share the same version number and RPM won't update them.
Now the version has a new piece added to it made up of the year concatenated with the day of the year, just like we did for the `.deb`s in #3215.
I'll merge this as soon as the validation scripts finish.

Add year and day of year to RPM versions

---

Core/ModuleInstaller.cs
Core/Types/ModuleInstallDescriptor.cs
Netkan/Services/IModuleService.cs
Netkan/Services/ModuleService.cs
Netkan/Transformers/InternalCkanTransformer.cs
Tests/Data/TestData.cs
Tests/NetKAN/Services/ModuleServiceTests.cs
Tests/NetKAN/Transformers/InternalCkanTransformerTests.cs

If a mod author puts a file with a `.ckan` extension in a mod's ZIP, Netkan automatically parses the file as YAML or JSON and merges its properties into the inflated output .ckan file, as if they were part of the .netkan (but the main .netkan takes precedence). This is extremely convenient for properties that can change from one release to the next, such as relationships, since no NetKAN pull request is needed and the concerns about whether to merge a pull request before or after the release is uploaded are mooted. In effect, the main netkan tells us how to download the mod, and the internal .ckan file describes what's inside it. It's a nice model, and I use it for most or all of my own mods, if I'm not mistaken.
For more details:
- …

Internal .ckan file compatibility with bundled mods

---

Cmdline/Action/Cache.cs
Cmdline/Action/Compat.cs
Cmdline/Action/GameInstance.cs
Cmdline/Action/Mark.cs
Cmdline/Action/Prompt.cs
Cmdline/Action/Repair.cs
Cmdline/Action/Repo.cs
Cmdline/CKAN-cmdline.csproj
Cmdline/Main.cs
Cmdline/Options.cs

Currently with CmdLine you have to type everything, including all the commands and subcommands and the full identifier of every mod. This is inconvenient.
Now if you run `ckan prompt`, you can use tab completion for commands/subcommands, `--` options, module identifiers, instance names:
Press tab:
Type part of an identifier, case insensitive:
Press tab:
To make this work:
- A project reference for `ReadLine` 1.2.0 is added to CmdLine (more recent versions require .NET Core)
- All of the subcommands' option classes are now publicly available and used in `Options.cs` to describe the options of the corresponding subcommands
- New attributes `[AvailableIdentifiers]`, `[InstalledIdentifiers]`, and `[GameInstances]` are defined and used to tag options that use each kind of input
- `Prompt` uses …

Tab completion for `ckan prompt`

---

Core/HelpURLs.cs
Core/Net/Net.cs
Core/Types/Kraken.cs
GUI/CKAN-GUI.csproj
GUI/Controls/DeleteDirectories.cs
GUI/Controls/EditModpack.cs
GUI/Controls/PlayTime.cs
GUI/Dialogs/CloneFakeGameDialog.Designer.cs
GUI/Dialogs/CloneFakeGameDialog.cs
GUI/Dialogs/CompatibleGameVersionsDialog.Designer.cs
GUI/Dialogs/CompatibleGameVersionsDialog.cs
GUI/Dialogs/EditLabelsDialog.Designer.cs
GUI/Dialogs/EditLabelsDialog.cs
GUI/Dialogs/InstallFiltersDialog.Designer.cs
GUI/Dialogs/InstallFiltersDialog.cs
GUI/Dialogs/ManageGameInstancesDialog.Designer.cs
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/Main/Main.cs

We had somebody stop by the Discord asking how to use the Manage Game Instances popup, which appears by itself, blank, if you have no game instances and CKAN can't find one in Steam.
We added some help menu options in #3437, but these not accessible from the Manage Game Instances popup. (And that pull request's changes have not been released yet.)
- Now [`.HelpButton`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.helpbutton?view=netframework-4.7.2) is `true` for most of our popup dialogs
- Now `.MinimizeBox` and `.MaximizeBox` are `false` for Manage Game Instances and Install Filters, which they probably should have been anyway because maximizing and minimizing these popups is not useful
- Now we override …

Context sensitive help

---

Netkan/Transformers/SpacedockTransformer.cs

This mod:
https://spacedock.info/mod/2992/SRB%20Waterfall%20Effects%20(SWE)
... gave me this inflation error locally after fixing the `install` to match the latest download:
```
Schema validation failed: #/author: NotOneOf
```
The co-author was added twice:
... which we simply dumped into a `List<string>`, but it's not allowed in the schema (note `uniqueItems`):
https://github.com/KSP-CKAN/CKAN/blob/4f3da572f14a3a46e9ca7ddf3190f341574f7dc0/CKAN.schema#L47-L57
Since neither the simple string format nor the unique-array format matched, the validator considered the `oneOf` to be the thing that failed.
Now the SpaceDock translator ensures co-author uniqueness with `.Distinct()`. Initially I looked at using a `HashSet`, but then we would lose the ordering of the authors. I wanted to avoid …

Filter duplicate co-authors from SpaceDock

---

GUI/CKAN-GUI.csproj
GUI/Controls/Changeset.Designer.cs
GUI/Controls/ChooseProvidedMods.Designer.cs
GUI/Controls/ChooseRecommendedMods.Designer.cs
GUI/Controls/DeleteDirectories.Designer.cs
GUI/Controls/EditModpack.Designer.cs
GUI/Controls/LeftRightRowPanel.cs
GUI/Controls/ModInfo.Designer.cs
GUI/Controls/PlayTime.Designer.cs
GUI/Controls/Wait.Designer.cs
GUI/Controls/Wait.cs
GUI/Dialogs/NewRepoDialog.Designer.cs
GUI/Main/MainRepo.cs

- The bottom right button in Delete Directories is supposed to say "Delete Checked," since only the folders with checked checkboxes will be deleted, but on Windows it only says "Delete":
https://github.com/KSP-CKAN/CKAN/blob/4f3da572f14a3a46e9ca7ddf3190f341574f7dc0/GUI/Controls/DeleteDirectories.resx#L126
- This potentially can happen anywhere, especially if a translator picks a long string for a button
- The text of the progress bar screen's log text box is unreadable black-on-dark when I install things in Windows using the dark theme from #3489, but readable light-on-dark for refreshing the mod list and repo updates.
- Most of our buttons use `Anchor` to position themselves and have hard coded sizes, and if those sizes aren't big enough to fit the text, it is truncated. Due to …

Auto-size buttons in bottom panels

---

CKAN.schema
ConsoleUI/ModInfoScreen.cs
ConsoleUI/ModListScreen.cs
Core/Net/Repo.cs
Core/Types/CkanModule.cs
GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ManageMods.resx
GUI/Localization/de-DE/Main.de-DE.resx
GUI/Localization/de-DE/ManageMods.de-DE.resx
GUI/Localization/fr-FR/ManageMods.fr-FR.resx
GUI/Localization/ja-JP/ManageMods.ja-JP.resx
GUI/Localization/pt-BR/ManageMods.pt-BR.resx
GUI/Localization/ru-RU/ManageMods.ru-RU.resx
GUI/Localization/zh-CN/EditModSearch.zh-CN.resx
GUI/Localization/zh-CN/EditModSearchDetails.zh-CN.resx
GUI/Localization/zh-CN/Main.zh-CN.resx
GUI/Localization/zh-CN/ManageMods.zh-CN.resx
GUI/Model/GUIConfiguration.cs
GUI/Model/GUIMod.cs
GUI/Model/ModList.cs
Netkan/CKAN-netkan.csproj
Netkan/Services/IModuleService.cs
Netkan/Services/ModuleService.cs
Netkan/Transformers/InstallSizeTransformer.cs
Netkan/Transformers/NetkanTransformer.cs
Netkan/Transformers/PropertySortTransformer.cs
Spec.md
Tests/GUI/Model/ModList.cs
Tests/NetKAN/Transformers/InstallSizeTransformerTests.cs

This looks a little silly, since each of these modules installs a different, smaller subset of the download:
And this isn't accurate because it sums the `download_size` properties of the installed modules, not their installed sizes:
- Now an `install_size` property is added to the schema, spec, and `CkanModule`, and `InstallSize` is added to `GUIModule`
- Now Netkan populates `install_size` based on the sum of the `Size` properties of the list of the `ZipEntry` objects that the module installs
- Now the `ConsoleUI` uses this property instead of and falling back to `download_size`
- Now a column for install size is added to GUI

Add install size to metadata and display in clients

---

Cmdline/Action/Prompt.cs

The metadata tester is broken. It can inflate just fine, but it hangs at the installation testing step.
In #3515 we started using a new library for reading input for `ckan prompt`, because it adds several convenient features like tab completion. Apparently it assumes an interactive input and can't read from a redirected input such as a file.
Now if the `--headless` flag is used, we use `Console.ReadLine` to get input as before #3515.

Fix headless prompt reading from pipes

---

debian/Makefile
debian/changelog
debian/ckan-cmdprompt.desktop
rpm/Makefile
rpm/ckan.spec

Now that we have integrated tab completion in #3515, it might be nice to make the `ckan prompt` UI more easily discoverable, similar to what we did for ConsoleUI in #3052.
Now a new "CKAN Command Line" option is added to the system menus when installing the .deb or .rpm packages:
Clicking it runs `ckan prompt` in a terminal.

Create a system menu entry for command prompt

---

Netkan/Transformers/EpochTransformer.cs
Netkan/Transformers/GithubTransformer.cs
Netkan/Transformers/ITransformer.cs

For many months now we have been getting hammered with bogus auto-epoch pull requests. Lately it has gotten worse, with occasional giant waves of many, many mods affected. Cleaning these up is very tedious and has by far eclipsed the usefulness of auto-epoching as a feature. #3571 didn't seem to help.
GitHub's API seems to be unreliable. We ask it for the list of releases for mods constantly, and something like 0.004% of the time it skips one or more releases (much more often if there's a "wave" in progress), and we get a bogus pull request because it looks like the versions went backwards.
Now we no longer auto-generate auto-epoch pull requests for mods on GitHub. All other mods can still benefit from this feature, but mods hosted on GitHub will now simply emit an error to the log. This …

Log errors instead of PRs for OOO mods on GitHub

---

Cmdline/Main.cs
Core/Games/KerbalSpaceProgram/GameVersionProviders/IKspBuildMap.cs
Core/Games/KerbalSpaceProgram/GameVersionProviders/KspBuildMap.cs
Core/Net/Repo.cs
Core/Properties/Resources.Designer.cs
Core/Properties/Resources.resx

My network has been a bit unreliable lately, and I've found that during periods of downtime, not only can I not download mods, but even commands like `ckan instance list` simply hang. (First noticed while working on the Electron UI project previewed in the comments of #2848, which just wraps around `CKAN.dll` without additional C# code being run.)
When CKAN starts, it loads all the game instances pretty early. To do this, it first has to load the known game versions so it can check each instance's version. Currently we always use the remote build map for this, via an HTTPS request to GitHub. If the network isn't working, it just sits there waiting for timeout.
This isn't a great model. As pointed out in #2108, CKAN should refrain from creating network connections without the user's …

Cache remote build map, fetch in registry refresh

---

Cmdline/Action/Cache.cs
Cmdline/Properties/Resources.resx
Core/CKANPathUtils.cs
Core/Extensions/IOExtensions.cs
Core/ModuleInstaller.cs
Core/Net/IDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Net/NetFileCache.cs
Core/Net/NetModuleCache.cs
Core/Properties/Resources.Designer.cs
Core/Properties/Resources.resx
Core/Types/CkanModule.cs
Core/Types/Kraken.cs
GUI/Dialogs/NewRepoDialog.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Main/MainInstall.cs
GUI/Properties/Resources.resx

Users periodically report issues with running out of disk space. (Given how cheap storage is these days, we can only credit the extremely creative developers of planet packs for taking up so many gigabytes with their beautiful textures.) This can happen at three points:
- The downloader downloads ZIP files to the `%TEMP%` folder, which can fill up
- Then it copies/moves downloaded files into the cache folder, which can fill up
- Then the installer extracts mod content from the ZIPs into the game folder, which can fill up
Currently CKAN does not attempt to handle or prevent this. The exception is simply thrown and the user gets to read a stack trace.
Last time I looked at this I hit a speedbump due to the lack of a built-in mapping from directories to drives in .NET, which is probably …

Check free space before downloading

---

Cmdline/Main.cs
ConsoleUI/InstallScreen.cs
Core/HelpURLs.cs
Core/ModuleInstaller.cs
Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Registry/AvailableModule.cs
Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
Core/Types/CkanModule.cs
Core/Types/Kraken.cs
GUI/CKAN-GUI.csproj
GUI/Controls/Wait.cs
GUI/Dialogs/DownloadsFailedDialog.Designer.cs
GUI/Dialogs/DownloadsFailedDialog.cs
GUI/Dialogs/DownloadsFailedDialog.resx
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/MainAutoUpdate.cs
GUI/Main/MainChangeset.cs
GUI/Main/MainDownload.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs
GUI/Main/MainRepo.cs
GUI/Main/MainWait.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.resx

We have had a lot of recent user frustration with how CKAN reacts when downloads fail. Such errors are hard to reproduce with the full app running because they happen randomly according to users' network conditions. However, I recently hit upon a strategy: edit `CKAN/registry.json` and change the `download` properties of the latest versions of some mods so they're invalid (I added `/BROKEN_LINK/` at the start of each URL's path). Note that this will only work for mods with non-redistributable licenses (generally `restricted`), because otherwise the downloader will fall back to `archive.org` and succeed. The ones in the screenshot below work well for this, if it saves reviewers the trouble of finding them; you can right click them to purge them from the cache if they're already downloaded. …

Many improvements for failed downloads

---

GUI/Controls/ManageMods.cs
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/MainDownload.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRepo.cs

Both refreshing the registry and updating the mod list use the `Wait` tab to log their progress, so the user can see what is happening and can tell the app hasn't frozen (see #2617).
Recently (dev builds only), if you refresh the registry in GUI, the log messages for repo update remain visible while the mod list is being refreshed. The progress tab should reset because they're separate processes.
Similarly (also dev builds only), if you use the download to cache option for a mod, we open the progress tab for the download and then refresh the mod list, which also uses the progress tab, but we jump back to the mod list in between.
In #3635 we refactored the `Wait` tab to clean up error handling and make its use more consistent. All of the many `BackgroundWorkers` were combined into one and …

Update mod list through Wait.StartWaiting

---

GUI/Controls/Wait.cs
GUI/Main/Main.cs
GUI/Main/MainAutoUpdate.cs
GUI/Main/MainChangeset.cs
GUI/Main/MainDownload.cs
GUI/Main/MainExport.cs
GUI/Main/MainImport.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRepo.cs
GUI/Main/MainTime.cs
GUI/Main/MainWait.cs

In current dev builds, if you turn on automatic registry refreshing at launch in the settings, you can sometimes end up with the main menu disabled and the close button not working at startup.
- In #3635 and #3637 we tried to improve the `Wait` tab's encapsulation and how it's used, and some of those updates must have created a state where we disable the window and don't re-enable it, but I have not been able to pin down exactly how it happened.
- `Main.SwitchEnabledState` is a toggle that keeps state in a private `_enabled` variable, but every place that calls it wants specifically to either enable or disable the window; there is no point where a toggle actually makes sense like it does with a checkbox. If that state gets out of sync unexpectedly, then those calls all flip, we disable …

Clean up window disabling

---

GUI/Controls/EditModSearch.Designer.cs
GUI/Controls/EditModSearch.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Util.cs

Mod searches in GUI that return many results can be noticeably slow on Windows. Usually this means one- or two-character searches.
The search logic that we perform is quick, but adding a lot of rows to `DataGridView` is unavoidably slow. Since WinForms requires that all UI updates happen in the foreground GUI thread, we can't improve this by simply moving logic to a background thread.
Mono platforms already have a delay between keystrokes and search, so they don't suffer as much from this today. However, the implementation of the delay is embedded within and very specific to `EditModSearch`, even though this is a generic operation that could be useful elsewhere.
- Now there is no longer anything platform-specific in the mod search logic
- Now a new `Util.Debounce` function implements a …

Debounce search events on all platforms

---

GUI/Main/Main.cs
GUI/Main/Main.resx
GUI/Main/MainInstall.cs
GUI/Main/MainTrayIcon.cs

- On Windows, the tray icon doesn't disappear at close if you kill CKAN with ctrl-C in the console. (You need to use the `--show-console` parameter to keep it visible after the GUI appears.) You can even accumulate several of them if you do it over and over:
- If you use the tray icon to open the settings while CKAN doesn't have focus, it appears at the upper left corner of your monitor
- Tray icons have the ability to display tooltips, but we don't have one
- Now the `Console.CancelKeyPress` ctrl-C event handler hides the tray icon
- Now we always pass a reference to the main form when we show the settings dialog, which will ensure it is properly centered on the main window
- Now the tray icon has a tooltip that says "CKAN"

Hide tray icon at exit via ctrl-C

---

.github/workflows/deploy.yml

Our deploy workflow can mess up our APT repos if we run multiple jobs of it at once, as can happen if multiple pull requests are approved and merged rapidly in sequence. I think what I've seen is that the checksums in the metadata files don't match the downloads. We have made a habit of waiting until the "Passed" notification appears in Discord before merging, but this is inconvenient since [this job takes about 13 minutes to run](https://github.com/KSP-CKAN/CKAN/actions/workflows/deploy.yml).
GitHub workflows can be configured to only run one instance of a given job at a time:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the …

Disable parallel runs of deploy workflow

---

Cmdline/Action/Update.cs
Cmdline/Options.cs
ConsoleUI/ModListScreen.cs
Core/Extensions/EnumerableExtensions.cs
Core/Net/Net.cs
Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Net/Repo.cs
Core/Types/Kraken.cs
GUI/Controls/Wait.cs
GUI/Dialogs/DownloadsFailedDialog.cs
GUI/Dialogs/DownloadsFailedDialog.resx
GUI/Main/MainInstall.cs
GUI/Main/MainRepo.cs
GUI/Main/MainTrayIcon.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.resx
Tests/Core/Net/NetAsyncModulesDownloader.cs
Tests/Core/Net/Repo.cs
Tests/Core/Relationships/SanityChecker.cs
Tests/Data/TestData.cs

- `Repo.Update` defines an inherently incoherent operation: Refreshing metadata from just one repository to the exclusion of any others that may be configured. This is not something you would ever want to do, because you would end up with an incomplete set of modules in your registry. Registry updates should be from all repos or none.
- Repo updates can't be cancelled, and if one fails, you can't recover
- Now the ability to update only one repo in isolation is eliminated
- `Repo.Update` is removed
- The `ckan update` command no longer takes a parameter and always update all repos
- `ckan update`'s `--all` parameter is removed (note that its documentation incorrectly described upgrading modules, which it never did)
- Now `DownloadTarget.filename` is used as the default for …

Improvements for failed repo updates

---

GUI/Controls/ModInfo.cs

The `<!>` alerts from #3271 are supposed to call user attention to the reason that an incompatible mod is incompatible; if the mod itself is incompatible, the Versions tab shows an alert, and if it's a problem with a relationship, the Relationships tab shows an alert:
In the current build (not released yet), these alerts don't appear unless you click the Metadata tab.
`UpdateModInfo` was a hybrid of general and tab-specific updates that #3638 tried to split into separate pieces, and these alerts anded up associated with the metadata tab instead of the general update where they belong.
Now the tab alerts are updated along with the header info, so they are always visible.

Fix missing mod info tab alerts

---

bin/ckan-merge-pr.py

For a very small, uncontroversial fix like #3649, it may make sense to submit a pull request with documentation of the bug and the fix (so team members know what happened), but then merge it without review, to keep the `master` branch working.
Currently the merge script from #3263 can't do this because it absolutely requires approval by at least one reviewer. I've been making a live temporary edit to add `False and` to bypass that check as needed, which is not a great solution.
Now the merge script has a `--self-review` option that skips the approval check if present. The default is `False` (obviously). This should only be used for small fixes in which we have high confidence. This has already been tested in the merge of #3649.

Self review option for merge script

---

Core/ModuleInstaller.cs

If you manually install NearFutureElectrical, CKAN detects it and shows it as "AD". If you then tell CKAN to take over management of it via the "upgrade" checkbox, it always fails with the error from #3043:
> About to install:
> 
>  * Near Future Electrical 1.2.3 (cached)
>  * B9 Part Switch v2.20.0 (cached)
>  * Module Manager 4.2.2 (cached)
>  * Community Resource Pack v112.0.1 (cached)
>  * Near Future Electrical Core 1.2.3 (cached)
>  * Dynamic Battery Storage 2:2.2.5.0 (cached)
>
> DLL for module NearFutureElectrical found at GameData/NearFutureElectrical/Plugins/NearFutureElectrical.dll, but it's not where CKAN would install it. Aborting to prevent multiple copies of the same mod being installed. To install this module, uninstall it manually and try again.
> Error during …

Only show DLL location error if installing DLL

---

crowdin.yml

The current translation process is difficult for users who that don't know or can't work with Git. The users that can, can sometimes forget some translations.
This will improve that process for those users as they just have to create an account on Crowdin and can start translating with very easy steps. Every translatable string is shown for them so none is forgotten.
Added a configuration file to upload the translatable files to Crowdin.

Improve translation process

---

Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
GUI/Controls/ModInfo.cs

If you try to install RP-1 on KSP 1.12 without following [the instructions (which call for marking KSP 1.11 compatible)](https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Express-Installation-for-1.12.3), you'll find you can't install it, and the reason is not apparent on the Relationships tab, which has increasingly become the place to investigate compatibility:
If you expand dependencies (or try to install the depending mod from the Versions tab), you can discover that RP-0 depends on SXTContinued, which depends on Firespitter, which is only compatible up to KSP 1.11:
Noted in KSP-CKAN/NetKAN#9306.
The relationships tab's red highlighting only indicates whether the mod itself is compatible, not including its dependencies. It doesn't load all relationships recursively, for performance …

Highlight incompatible mods recursively

---

GUI/Controls/ManageMods.cs
GUI/Main/Main.cs

CKAN's GUI has back/forward buttons that navigate through the mods the user recently clicked.
Some mice have extra buttons for back and forward (typically used in a web browser), and currently these do nothing in CKAN.
Now we listen for messages that contain XButton events and map them to the existing back/forward navigation. This is done via `IMessageFilter.PreFilterMessage` in order to react to events regardless of the focus or position of the mouse cursor.
Learned from this:  https://stackoverflow.com/a/67698917

Support mouse back/forward buttons

---

Netkan/Validators/RelationshipsValidator.cs

See KSP-CKAN/NetKAN#9321 and KSP-CKAN/NetKAN#9323, we inadvertently marked the latest version of Parallax as conflicting with it own dependencies by using `max_version` instead of `version_max`, which made it impossible to install (but made it easier to install the previous version correctly).
This happened previously in KSP-CKAN/NetKAN#8880 and KSP-CKAN/NetKAN#8881.
For game version requirements, `ksp_version_min` and `ksp_version_max` are the correct forms.
For mod version requirements, `min_version` and `max_version` are the correct forms. For metadata maintainers who routinely deal with game version requirements and much more rarely with mod version requirements, this is surprising and very hard to keep in mind.
Now if a relationship contains `version_min` or `version_max`, we raise …

Inflation error for version_min and version_max

---

GUI/Controls/EditModSearch.cs

1. Type a search
2. Click the `+` button to add a second search box
3. Type into the second search box
4. Second search box disappears
In #3641 we refactored the search box timer to use the same event handler for keystrokes and text change events. It uses a timer to delay the search by default, but this is bypassed for an immediate search if the user presses Enter or if the text box is empty.
The keystroke handler fires before the runtime updates the text box's contents, so it was always empty for the first keystroke, and we were firing the update immediately with an empty search string.
Now we don't bypass the delay for a keystroke event for any keys other than Enter.

Fix second search box disappearing

---

GUI/Model/ModList.cs

After #3643, upgrades are broken in the dev builds:
1. Install an old version of `KSP-Recall`
2. Click the upgrade checkbox on that mod's row
```
System.ArgumentException: Already contains module: KSP-Recall
at CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
at CKAN.RelationshipResolver..ctor(IEnumerable`1 modulesToInstall, IEnumerable`1 modulesToRemove, RelationshipResolverOptions options, IRegistryQuerier registry, GameVersionCriteria GameVersion)
at CKAN.IRegistryQuerierHelpers.FindRemovableAutoInstalled(IRegistryQuerier querier, List`1 installedModules, HashSet`1 dlls, IDictionary`2 dlc, GameVersionCriteria crit)
at CKAN.IRegistryQuerierHelpers.FindRemovableAutoInstalled(IRegistryQuerier …
```

Fix already contains module error at upgrade

---

Netkan/CKAN-netkan.csproj
Netkan/CmdLineOptions.cs
Netkan/Processors/Inflator.cs
Netkan/Processors/QueueHandler.cs
Netkan/Program.cs
Netkan/Sources/Gitlab/GitlabApi.cs
Netkan/Sources/Gitlab/GitlabOptions.cs
Netkan/Sources/Gitlab/GitlabProject.cs
Netkan/Sources/Gitlab/GitlabRef.cs
Netkan/Sources/Gitlab/GitlabRelease.cs
Netkan/Sources/Gitlab/IGitlabApi.cs
Netkan/Transformers/GitlabTransformer.cs
Netkan/Transformers/NetkanTransformer.cs
Netkan/Validators/KrefValidator.cs
Spec.md

See KSP-CKAN/NetKAN#9325, the author of a mod hosted on GitLab has requested to have it added to CKAN. Currently we don't have a way to do that without hard coding the download URL, which is bad for maintenance.
- A `netkan.exe --gitlab-token` command line option is now added and works just like `--github-token` but for GitLab
- If `PurgeDownloads` fails after a failed inflation, we ignore it so the original error can be printed
- A new kref format `#/ckan/gitlab/<account>/<project>` is added for indexing GitLab projects
- A new `GitlabTransfomer` uses a `GitlabApi` and accompanying data classes from a `Netkan/Sources/Gitlab` folder to inflate modules with GitLab krefs
- The spec is updated to describe the new kref
After this, we can inflate a netkan for the mod from KSP-CKAN/NetKAN#9325. …

GitLab kref

---

Cmdline/Action/Upgrade.cs
Cmdline/ConsoleUser.cs
ConsoleUI/ModInfoScreen.cs
ConsoleUI/Properties/AssemblyInfo.cs
ConsoleUI/Toolkit/Keys.cs
Core/Extensions/IOExtensions.cs
Core/Net/AutoUpdate.cs
Core/Registry/RegistryManager.cs
Core/Types/License.cs
GUI/Controls/HintTextBox.cs
GUI/Controls/ManageMods.cs
GUI/Controls/TransparentTextBox.cs
GUI/Dialogs/CompatibleGameVersionsDialog.cs
GUI/Dialogs/InstallFiltersDialog.cs
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/Main/Main.cs
GUI/Main/MainRepo.cs
GUI/Model/GUIConfiguration.cs
GUI/NavigationHistory.cs
GUI/URLHandlers.cs
GUI/Util.cs
Netkan/ConsoleUser.cs
Netkan/Sources/Curse/CurseApi.cs
Netkan/Sources/Spacedock/SpaceDockApi.cs
Netkan/Validators/InstallsFilesValidator.cs

I've been accumulating trivial changes while working on unrelated pull requests.
Now they've been dumped into a branch so I don't have to keep stashing and popping them.
- Redundant namespace specifications are removed
- BOMs are removed from lines where they don't belong
- Missing or misaligned `{` and `}` characters are fixed
- Some `using` statements are moved to the top of the file and split into system, third party, and CKAN sections
- The `X` icon in the `HintTextBox` is made to fit the text box rather than just being centered on top of it
I'll probably self-review this since it's so minor.

Trivial code style clean-up

---

Dockerfile.netkan

In KSP-CKAN/CKAN#3661 we added the ability to index mods hosted on GitLab. This included the ability to provide a GitLab authentication token from the command line, but the Inflator isn't using this capability yet. We should add that eventually for completeness, see https://github.com/KSP-CKAN/CKAN/pull/3661#discussion_r966544529.
Now the `$GL_Token` environment variable is passed to the inflator's `--gitlab-token` parameter.
KSP-CKAN/NetKAN-Infra#276 will handle providing this env var based on the configured secrets.
I tested `netkan.exe --gitlab-token ''` and it still worked, so I think there is no harm in setting this parameter before we create a GitLab token.

Pass GitLab token from env to inflator param

---

Core/ModuleInstaller.cs
Core/Properties/Resources.resx
Core/Relationships/RelationshipResolver.cs
GUI/Controls/Changeset.Designer.cs
GUI/Controls/Changeset.cs
GUI/Controls/Changeset.resx
GUI/Controls/ManageMods.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs
GUI/Main/MainRepo.cs
GUI/Model/GUIMod.cs
GUI/Model/ModChange.cs
GUI/Model/ModList.cs
Tests/Core/Relationships/RelationshipResolver.cs

@siimav reports that many RP-1 users have been having problems with `TexturesUnlimited` and `ROLib` when installing via CKAN, which have been attributed to some speculated property of the exFAT filesystem (generally used for thumb drives):
I suspect it's not _sorting_ by creation date per se (since why would Microsoft have bothered to do that, just for exFAT?), but rather just returning the files in disk order, which would correspond to the order in which they were created on exFAT. If that's the case, then "normal" listing behavior for other filesystems may _also_ be disk order (simpler/more consistent code in the kernel), but maybe the OS sorts the files alphanumerically **at time of creation**, since traditional hard drives don't have limits to the number of times they can be written …

Install dependencies first

---

doc/apt-repo.md
doc/rpm-repo.md

Current Debian policy guidelines state that 3rd party repositories should use the "signed-by" option and install a keyring file to `/usr/share/keyrings` named `reponame-archive-keyring.gpg` rather than using a key file in `trusted.gpg.d`, as the latter is deprecated and will no longer work in future versions of Debian and derivatives. This change updates the repo installation instructions to comply with current Debian Third-Party repository guidelines. The guidelines as currently outlined are available here: https://wiki.debian.org/DebianRepository/UseThirdParty
Additionally, there is a small change to add the `arch=amd64` option, as this prevents an error otherwise presented by APT due to the repository lacking support for i386.

update repo instructions for new Debian policy

---

GUI/Controls/EditModSearches.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.Designer.cs
GUI/Controls/ModInfo.cs
GUI/Controls/ModInfoTabs/Metadata.Designer.cs
GUI/Controls/ModInfoTabs/Metadata.cs
GUI/Main/Main.cs
GUI/Model/GUIMod.cs
GUI/Model/ModList.cs
GUI/Model/ModSearch.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.resx

Continuing recent efforts to improve mod info (see #3670), and remembering my quest to find FruitGoose's mods (see KSP-CKAN/NetKAN#9351), influenced by the "sticky" checkbox on the Relationships tab (see #3638), I thought it would be nice to be able to click author names in mod info to set the filter, like the tab/label links. And if we're going to have both tag/label links and author links, that raises the possibility of wanting to use them together somehow.
- The authors field in mod info is now an autosized wrapping flow layout collection of links that can be clicked to search by that author, similar to the tag/label links
- Since authors can contain characters that aren't allowed or don't work in searches, non-alphanumeric characters are removed before searching
- Can be Ctrl- or …

Authors as clickable filter links, combine search links w/ ctrl or shift

---

Netkan/Validators/InstallsFilesValidator.cs

KSP-CKAN/NetKAN#9396 initially had an auto-generated netkan that installed to paths like `GameData/ESA_Rocket-0.1/Gamedata/Vega/AVUM.png`:
https://github.com/KSP-CKAN/NetKAN/actions/runs/3314556923/jobs/5473995107
No error was thrown because the ZIP contains `Gamedata` instead of `GameData`, even though this is just as wrong as it would be if the author had used the standard capitalization.
Now the nested GameData check is case insensitive, courtesy of `StringComparison.InvariantCultureIgnoreCase`.
I'll self-review this since it's simple and low risk.

Make Netkan nested GameData check case insensitive

---

doc/rpm-repo.md

99% sure that apt isnt the package mangier for rpm distros

Replace apt with dnf in the docs for the RPM repo

---

Core/Registry/RegistryManager.cs

CKAN creates a `<KSP>/CKAN/registry.locked` file when it loads an instance and deletes this file at exit. If CKAN terminates abnormally (e.g., `pkill -KILL mono`), then the `registry.locked` file can be left behind without a running CKAN. To make this condition detectable, the file contains the process ID of the CKAN process that created it.
If you have a stale lock file and you start CKAN, the staleness is not detected. The lock file dialog appears even though there is no process with the process ID contained in the lock file.
#2139 was supposed to address this, but it had a bug:
https://github.com/KSP-CKAN/CKAN/blob/cd7c3a0f180d7114101b2b5cdfa8604befd6efc2/Core/Registry/RegistryManager.cs#L171
That function takes the `<KSP>/CKAN` dir path as a parameter: …

Fix stale lockfile detection

---

Core/Properties/Resources.Designer.cs
Core/Properties/Resources.resx
Core/Registry/RegistryManager.cs
Core/Relationships/RelationshipResolver.cs
Core/Types/RelationshipDescriptor.cs
Core/Versioning/GameVersion.cs
Core/Versioning/GameVersionBound.cs
Core/Versioning/GameVersionCriteria.cs
Core/Versioning/GameVersionRange.cs
GUI/Controls/EditModpack.cs
GUI/Controls/ModInfoTabs/Versions.cs
GUI/Controls/Wait.cs
GUI/Main/Main.cs
GUI/Main/MainInstall.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.resx
Tests/Core/Versioning/KspVersionRangeTests.cs

- After #3667, trying to install modpacks doesn't work in dev builds anymore, because the relationship resolver's mod list property now tries to get the reason for each mod's _parent_, and mods from a modpack have a metapackage parent, which wouldn't have its reasons stored. An exception is thrown and not caught, so it fails messily. This definitely needs to be fixed before the next release.
- The default identifier for a modpack wasn't internationalized, but instead always had an English `installed-` prefix
- The "KSP all versions" string used in many places wasn't internationalized but instead always English
I felt like assembling my own modpack that I'm calling "Stock Plus," focused on enhancing the gameplay of the stock solar system and parts; if anyone is interested, I may be …

Fix modpack installation, install incompatible with confirmation

---

.github/workflows/deploy.yml
.github/workflows/release.yml

Originally, the documented way to pass info from one GitHub workflow step to the next was to print this to stdout:
```
::set-output name=param_name::param_value
```
We used this in several places in CKAN's workflows (mainly dealing with the calculation of the version strings).
Recently GitHub decided they didn't like that anymore and added a warning message for it:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
The replacement is to append `param_name=param_value` lines to the file specified by `$GITHUB_OUTPUT`:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
We have until June 2023 to migrate.
Noted thanks to KSP-CKAN/KSPMMCfgParser#16.
Now the prescribed migration …

Switch workflows from set-output to $GITHUB_OUTPUT

---

GUI/Model/ModList.cs

When you upgrade a module, the GUI changeset shows two entries for the same module, an Update step and an Install step.
I think these extra changes existed along, but were hidden in GUI by `CreateSortedModList` until #3667 simplified the changeset UI to show what's actually being done. The `!sortedChangeSet.Any(c => c.Mod.identifier == change.Mod.identifier` check would have prevented an Install change in the changeset from being added to the list in the UI if an Update was already present:
https://github.com/KSP-CKAN/CKAN/blob/32517ba0fdc6f3116c0817572cd5ae76dfcf307d/GUI/Controls/Changeset.cs#L133-L149
Now the resolver's Install step is only added to the changeset if there isn't already an Update step for the same mod.

Remove duplicate Install changes for upgrades

---

Core/Types/CkanModule.cs
GUI/Controls/ModInfoTabs/Relationships.cs

If a mod depends on a DLC that you don't have installed, the mod will be treated as incompatible with a red stop sign on the relationships tab due to the missing dependency (since CKAN can't install DLC even if there's a version of it that's compatible with your game version). But if you look at the relationships tab of mod info to try to figure out why it's incompatible, there's no indication that this is the reason:
Now if a mod depends on a DLC that isn't installed, the relationship will be highlighted red, just like for an incompatible dependency:

Red highlight for dependencies on missing DLC

---

GUI/Controls/Changeset.cs
GUI/Controls/ManageMods.cs
GUI/Main/MainChangeset.cs

After KSP-CKAN/NetKAN#9438 and KSP-CKAN/CKAN-meta#3125, ZeroMiniAVC becomes auto-uninstallable (see #2753) for most users who have it. Unfortunately the client has problems with this.
The change set tab appears and the Apply changes button becomes enabled while the GUI is still responsive, but _clicking_ Apply changes or the change set tab froze the GUI. Multiple users have reported this on the forum and Discord.
Steps to reproduce:
1. Start CKAN
2. Install ToolbarController, ClickThroughBlocker, and ZeroMiniAVC
3. Mark ZeroMiniAVC as auto-installed
4. Close CKAN
5. Start CKAN
6. The change set tab appears and Apply changes is enabled, and using either one will freeze the GUI
GUI properties on `Changeset` are being manipulated from a background thread, rather than WinForms's designated …

Fix GUI freeze with non-empty changeset at startup

---

Netkan/Validators/InstallValidator.cs

kOS scripts are installed to `Ships/Script`. We added support for this in #3180, including a Netkan validation check that the `spec_version` was `v1.29` or later, since earlier versions of CKAN wouldn't support it.
The check only triggers for one specific case:
```yaml
install:
- install_to: Ships/Script
```
There are other ways to install into that path:
```yaml
install:
- file: some/path/Script
install_to: Ships
```
```yaml
install:
- find: some/path/Script
install_to: Ships
```
```yaml
install:
- file / find: whatever
install_to: Ships
as: Script
```
Remembered while reviewing KSP-CKAN/NetKAN#9443, which almost slipped by with a bad `spec_version` because of it.
Now the Netkan validation checks for these other cases. It may still miss some things, but it's better than no check at all.

Fix Netkan check for Ships/Script spec_version

---

GUI/Controls/Changeset.cs
GUI/Controls/ManageMods.cs
GUI/Main/Main.cs
GUI/Main/MainChangeset.cs

1. Install `xScienceContinued` (which will also install three dependencies)
2. Right-click it and select "Reinstall"
3. Click Yes in the confirmation popup
4. Click Continue on the recommendations screen
5. Install flow fails:
The changeset passed to the install flow for reinstallation includes the dependencies, so they're added to the resolver once as dependencies and then again later as user-selected, which triggers an exception.
- Now the reinstall option jumps to the changeset tab instead of popping up a confirmation dialog, so you can see what it's going to do
- Now the changeset tab saves the changeset it displays and passes it to the install flow upon confirmation, rather than re-calculating the changeset from the mod list
- Now the reinstall option generates a changeset that …

Use changeset tab for reinstall

---

GUI/Main/MainChangeset.cs

1. Launch the [current master branch build of CKAN](https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe) (bug does not exist in latest release)
2. On a fresh game instance, check the three checkboxes to install these mods:
- Parallax
- Parallax - Stock Scatter Textures
- Parallax - Stock Planet Textures
3. Click Apply changes
4. The install flow launches, but no mods are installed, and then the changeset is cleared :sob: 
Reported by @vega-star on Discord. Many thanks for trying out the dev build and contributing feedback in enough detail to pinpoint this bug!
#3726 made it so that when you click to confirm a changeset, instead of recalculating the changeset from the mod grid as we did previously, it used the data from the same changeset object that the user just viewed and approved in …

Leave user requested dependencies in changeset

---

Core/Games/KerbalSpaceProgram/GameVersionProviders/KspBuildMap.cs

If your `%LOCALAPPDATA%\CKAN\builds.json` file is empty (zero bytes), CKAN throws an exception at startup:
```
System.TypeInitializationException: The type initializer for 'CKAN.Versioning.GameVersion' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at CKAN.GameVersionProviders.KspBuildMap.get_KnownVersions()
at CKAN.Versioning.GameVersion..cctor()
at CKAN.Versioning.GameVersion.op_Equality(GameVersion v1, GameVersion v2)
at CKAN.GameInstance.Version()
at CKAN.GUI.ManageGameInstancesDialog.<>c.<UpdateInstancesList>b__8_2(KeyValuePair`2 instance)
at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
at …
```

Fix handling of empty builds.json file

---

GUI/Main/MainChangeset.cs

1. Install MiniAVC (or any other mod)
2. Check the checkbox for auto-installed
3. Click Apply changes
4. The changeset tab appears and shows the mod being removed
5. Click Continue
6. The install flow does nothing
#3726 made it so that when you click to confirm a changeset, instead of recalculating the changeset from the mod grid as we did previously, it used the data from the same changeset object that the user just viewed and approved in the changeset tab. This allows us to use the changeset tab for changesets other than the one selected on the main mod list (such as reinstallation via the right click menu, which cannot otherwise be represented by the main mod list's checkboxes).
#3728 changed it to filter out non-user-requested changes. But this means auto-removals are filtered out of …

Fix auto-removal

---

Dockerfile.metadata

See KSP-CKAN/NetKAN#9527; the metadata tester is broken, but that attempt has not fixed the problem.
Probing the docker image, I have slightly more confirmation now that this relates somehow to the permissions of the git repo (see the later comments in KSP-CKAN/NetKAN#9527).
However, there's a big gap in this explanation: **NOTHING CHANGED**. It's using the same old version of `git`, GitPython is probably the same, and our code is the same. For this to start happening when it did would imply that GitHub made some change to how Actions handle permissions right at the moment when we were rebuilding this docker image. So :shrug:.
Now the Dockerfile for the meta tester sets git's `safe.directory` setting to `*`, which should allow our code to access the repo regardless of the mess that the …

Set git safe.directory in meta tester

---

GUI/Main/Main.resx

If a user wants to install their current mod list on another computer or share it with friends, they might click File &rarr; Save installed mod list... to generate a text file with their list of mods. However, there is no way to use this file to install that same mod list somewhere else. (It's mainly useful for posting your mod list to the forum.)
Thanks to Discord user SpaceTrash67 for bringing this up.
It's not easy to tell the difference between the menu options:
In the given use case, the user would have to try to guess and maybe experiment with these options to learn what they do.
Now the English versions of these menu options have a parenthetical clarification explaining whether the files they create can be re-imported, similar to what we did in #3400:
Other locales would have to be …

Clarify mod list saving options, add menu hotkeys

---

Core/Net/NetFileCache.cs

FIPS stands for Federal Information Processing Standard, and it specifies a list of cryptographic algorithms that are considered secure enough for security:
- https://learn.microsoft.com/en-us/answers/questions/211279/sharepoint-2016-configuration-failed-this-implemen.html
- https://learn.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/federal-information-processing-standard-security-standards
- https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashing-and-signing
- https://docs.trendmicro.com/all/ent/sc/v3.0/en-US/cmcolh/t_fips.html
Windows has a setting to throw exceptions if an application tries to use one of its official crypto objects that isn't FIPS-compliant. …

Fix FIPS-mode exceptions on Windows for SHA256

---

Core/Net/NetAsyncModulesDownloader.cs
Core/Net/NetFileCache.cs
Core/Net/NetModuleCache.cs

1. Choose to install a large mod on Windows (so the validation step will take long enough that you have to wait for it)
2. Apply changes
3. Wait till the download is finished and the ZIP is being validated (you'll see the progress bar's label change)
4. Click cancel during the validation step
5. Apply changes again
6. The file will re-validate, probably with its progress bar flickering back and forth; wait till it finishes
7. An exception is thrown:
```
System.IO.IOException: The process cannot access the file 'C:\Users\danny\AppData\Local\CKAN\downloads\downloading\E4B2C9E4-Parallax-StockTextures-2.0.0.zip' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, …
```

Support cancellation of download checksums

---

GUI/Properties/Resources.pl-PL.resx

@Kalessin1 suggested a one-word Polish translation for `is:cached` here (after #3780 replaced the spaces of the previous translation with dashes):
https://forum.kerbalspaceprogram.com/index.php?/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1312-juno/&do=findComment&comment=4234435
Now this translation is used.
I'll self-review this minor l10n string change.

Single word Polish translation for is:cached

---

Core/GameInstance.cs

In `CKAN.GameInstance.PortableDir (CKAN.Games.IGame game)`:
```cs
// Find the directory our executable is stored in.
string exeDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
````
An empty string would be assigned to `exeDir` when ckan is packaged
using mkbundle. This caused following method call
`game.GameInFolder(new DirectoryInfo(exeDir))` to crash with
`System.ArgumentException: The specified path is not of a legal form (empty).`
```
mkbundle --deps -o ckan --simple --machine-config /etc/mono/4.5/machine.config --config /etc/mono/config --simple ckan.exe
```

Fix mkbundle executable crash

---

Core/Extensions/EnumerableExtensions.cs
Core/Net/Repo.cs
Core/Properties/Resources.Designer.cs
Core/Properties/Resources.resx

A user reported this exception at start-up (partially translated from Chinese):
```
System.ArgumentException: An item with the same key has already been added.
在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
在 CKAN.Repo.<>c__DisplayClass0_0.<UpdateAllRepositories>b__1(Uri url, String filename, Exception error, String etag)
在 CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error, Boolean canceled, String etag)
在 CKAN.NetAsyncDownloader.<>c__DisplayClass20_0.<DownloadModule>b__1(Object sender, AsyncCompletedEventArgs args, String etag)
在 System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
在 …
```

Skip duplicate repo URLs during update

---

Core/ModuleInstaller.cs

I upgraded Sandcastle after KSP-CKAN/NetKAN#9428, and WildBlueCore was installed as intended, but it was not marked as auto-installed. It should be, because it's only installed due to Sandcastle's dependency.
`ModuleInstaller.AddRemove`, which is called by Upgrade and Replace, sets the auto-installed flag to false for any module that isn't being removed in the same call. This was the most cautious thing to do when the auto-installed flag was being added (setting this flag to true unnecessarily could remove modules the user wants to keep), but on further investigation, it's not correct.
- Now `ModuleInstaller.AddRemove` has a `newModulesAreAutoInstalled` parameter that calling code can use to set the value of the auto-installed flag for modules that aren't being removed. Upgrade sets it to …

Mark new deps of upgrades as auto-installed

---

GUI/Controls/Changeset.cs
GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Main/Main.cs
GUI/Main/MainChangeset.cs
GUI/Model/ModList.cs
Tests/GUI/Model/ModList.cs

When a user tries to install mods that conflict with one another or with an installed mod, the apply changes button is disabled and a description of the conflict appears in the leftward part of the status bar.
It has been fairly common recently for users to ask why the apply changes button is disabled; many or most users don't notice the text in the lower left until it's pointed out.
Now when the changeset has conflicts, you can still click the apply changes button, but the conflicting mods are highlighted in red in the changeset, the conflict reasons take over the description column, and the apply button is disabled:
Hopefully this will make it more discoverable.

Show conflicts in changeset

---

GUI/Dialogs/ManageGameInstancesDialog.cs

1. Open the manage game instances dialog
2. "Forget" all instances that have hours played (see #3543), if any; the Hours Played column will disappear if it was visible
3. Now add an instance that has hours played (again see #3543 for how to set this up), you'll get an exception and the instance list will fail to populate:
Noticed during dev of #3797 (in relation to the Game column instead), but I think I recall sporadic reports of this without those changes that I couldn't pin down at the time, so it seemed worth splitting into its own fix.
The list view has two columns that are sometimes visible and sometimes hidden: Game and Hours Played. To hide them, we remove them from the list view. If they become visible again, we insert them using their `Column.Index` property, which unfortunately …

Fix index -1 exception in Manage Instances

---

Core/Extensions/IOExtensions.cs
Core/GameInstanceManager.cs
Core/Net/NetFileCache.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Dialogs/SettingsDialog.resx

If you go to the settings and try to type a valid full path with drive letters into the cache path field, it silently gets "stuck" after the drive letter behind the scenes. Upon re-opening the settings the field is blank and can't be edited:
The setting saved to disk is like:
```json
"DownloadCacheDir": "E:",
```
Installing mods then fails with some strange text about a `System Volume Information` folder:
`TrySetupCache` is supposed to determine whether a cache path is valid, but an exception was being thrown in `NetModuleCache.GetSizeInfo` when the path was `E:`, _after_ `TrySetupCache` succeeded, which corrupted the display and caused `updatingCache` to be `true` forever, which suppressed all further calls to update the setting while you typed the rest of the path.
Later, when we tried …

Cache path setting fixes

---

Netkan/Validators/InstallsFilesValidator.cs

See KSP-CKAN/NetKAN#9614; a mod using `include_only` was changed to contain different filenames than we were trying to include, and there was no inflation error or warning.
```yaml
include_only:
- Assets
- ASET_StckRplc_Mk1-2_Pod.cfg
- RPM_ASET_StckRplc_Mk1-2_Pod_Patch.cfg
```
A _different_ `include_only` list element (`Assets`) still matched, so there were still files being installed. (The other mods from that PR had no other `include_only` members, so they hit the "No files found" error).
Now the `InstallsFilesValidator` prints a warning if any `include_only`  fails to match at least one installed file.
The logic isn't super sophisticated or water tight; it can miss things in very complex setups (e.g., if two stanzas have the same `include_only` and one has a match and the other …

Netkan warning when include_only doesn't match

---

GUI/Model/ModList.cs

Originally, mod names, abstracts, and authors containing `&` characters would have them removed and the next character underlined on Mono:
#3149 fixed that by escaping the ampersands, which is done by adding another one.
Windows clients currently see `&&` in the grid:
.NET is cross-platform in principle, but not quite "write once run anywhere" in practice. Whenever Mono deviates from how .NET does something, pain ensues for application developers. In this case, Mono treats `&` as a hotkey prefix character in the data grid view, but .NET treats it as just a normal character.
Now we only double the ampersand on Mono. Windows gets the single ampersand and likes it:
Fixes #3806.

Make grid ampersand workaround platform specific

---

Dockerfile.netkan
build.cake

If the `$GAME` environment variable isn't set, the Inflator won't start, as of #3797.
Also the `docker-inflator` Cake build target tries to redeploy the `Inflator` container, but that was renamed to `InflatorKsp` in KSP-CKAN/NetKAN-Infra#284. And the `InflatorKsp2` container isn't touched at all.
- Now if it's not set, we fall back to a default value of `KSP` using `bash`'s `${ENVVAR:-defaultval}` syntax.
- <https://stackoverflow.com/questions/2013547/assigning-default-values-to-shell-variables-with-a-single-command-in-bash>
- Now we redeploy `InflatorKsp` followed by `InflatorKsp2`

Default GAME env var to KSP in Inflator Dockerfile, fix redeploy

---

Cmdline/Action/GameInstance.cs
Cmdline/Properties/Resources.Designer.cs
Cmdline/Properties/Resources.resx
Core/GameInstanceManager.cs
Core/Games/IGame.cs
Core/Games/KerbalSpaceProgram.cs
Core/Games/KerbalSpaceProgram2.cs
GUI/Main/Main.cs

As we advance toward the finish line of KSP2 support, we are getting closer to the point where we will need to be able to validate, review, and merge `KSP2-NetKAN` pull requests. This will require updating `xKAN-meta_testing` to support the new game. I started that and discovered that `ckan.exe` needs some more updates first.
`ckan instance fake` is used by the validator to generate dummy game instances, but it currently can only do this for KSP1.
- Now the `ckan instance fake` command has an optional `--game` argument that can be `KSP` (default) or `KSP2`, which determines the files and folders to be created to fake the instance according to the game. The metadata validator will eventually pass the value of a `$GAME` environment variable here to adapt itself to the right context.
- To …

Multi-game fakery

---

Dockerfile.metadata

https://github.com/KSP-CKAN/CKAN/actions/runs/4503992634/jobs/7928198047
The `deploy` workflow just started giving us weird compile errors involving Rust during the Dockerfile step that installs NetKAN-Infra. The error message suggests updating pip, which is reported to be at version 18.1, which was released on 2018-10-05.
The message says that newer pips might be able to install precompiled packages that older pips can't, so there's a chance that this could skip all those `bdist_wheel` commands that take a long time, speeding up the deploy.
Now we try updating pip as suggested.

Upgrade pip before installing NetKAN-Infra

---

GUI/Controls/ModInfoTabs/Versions.cs

If you switch to the Versions tab, then to another tab and back, the Versions tab fully refreshes itself, which it shouldn't do because it can take a long time (see #3638).
The call to `Refresh` is unconditional and is only skipped if the mod is null.
Now we don't refresh the versions list if it's already loaded for the same mod. There's already a code block checking if the mod is the same, so the call to `Refresh` is moved in there.

Only update Versions tab when the mod changes

---

Netkan/Transformers/SpaceWarpInfoTransformer.cs

See KSP-CKAN/KSP2-NetKAN#33, a dependency was missing from a KSP2 module. This dependency was documented (only) in the `swinfo.json` file, and the netkan didn't have it.
This could easily happen again with other mods, either when initially adding them or as new versions are released.
The inflator parses the `swinfo.json` file but ignores its `dependencies` property. I thought about automatically importing it into `CkanModule.depends`, but that would have trapped us if:
- The identifier was different in CKAN (there's no guarantee of matches)
- The `swinfo.json` was wrong
Now when we inflate a module with a `swinfo.json` file, if it has `dependencies` listed, we'll check them and log a warning for any identifier that isn't in the `CkanModule.depends` list. It's a warning instead of an error …

Warnings for missing swinfo.json deps

---

GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Controls/ModInfoTabs/Contents.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Main/Main.cs
GUI/Main/MainDownload.cs

If you use the purge all option in the GUI settings, an exception is thrown:
- The `Contents` tab has a poor public interface, with two ways to change the active mod, the `SelectedModule` property and `UpdateModContentsTree`
- `UpdateModContentsTree` has a `module` parameter, which is malsuited to this function's usage, which is simply to refresh the currently displayed mod after caching or purging, which requires calling code to do unnecessary work to retrieve and pass the currently shown mod
- `UpdateModContentsTree` assumes that its `CkanModule` parameter will never be `null`
- `SettingsDialog` passes that parameter as `null` after purging, to try to refresh the display in case a previously cached mod is shown, because it seemed like a natural way to request an operation on the same …

Fix NRE on purging cache in GUI

---

.github/workflows/build.yml

Builds started failing on Mono 6.6 and earlier with #3558 (which itself made no relevant changes):
The Docker images for older Mono releases seem to point to Debian repos that no longer have the data for those versions ("stretch"). I don't think we can fix this; the images are now simply too old to be used.
<http://ftp.debian.org/debian/dists/>
<https://www.mono-project.com/docs/about-mono/releases/>
- Mono 5.20 (April 2019), 6.4 (September 2019), and 6.6 (December 2019) are removed from the list of builds
- Mono 6.10 (May 2020) and 6.12 (November 2020) are added
This will allow our pull requests to build.

Stop building on Mono 6.6 and earlier

---

Netkan/Transformers/NetkanTransformer.cs
Netkan/Transformers/StagingLinksTransformer.cs

Dealing with KSP-CKAN/CKAN-meta#3183, KSP-CKAN/CKAN-meta#3184, KSP-CKAN/CKAN-meta#3185, KSP-CKAN/CKAN-meta#3186, and KSP-CKAN/CKAN-meta#3187 requires downloading the mod, but how to do this must be figured out by the PR reviewer (generally the answer is to click the spacedock or repository link and then click the download link on the host). This is inconvenient.
- The `StagingLinksTransformer` now executes after `DownloadAttributeTransformer` and `InstallSizeTransformer`, which from reviewing #3454 I think should be fine
- Before it loops over the resources, `StagingLinksTransformer` adds a row containing `metadata.Download`

Add download link to staging PRs

---

Core/GameInstance.cs
Core/HelpURLs.cs
Core/Versioning/ModuleVersion.cs
GUI/CKAN-GUI.csproj
GUI/Controls/InstallationHistory.Designer.cs
GUI/Controls/InstallationHistory.cs
GUI/Controls/InstallationHistory.resx
GUI/Controls/ManageMods.cs
GUI/Controls/UnmanagedFiles.cs
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/MainHistory.cs
GUI/Main/MainUnmanaged.cs
GUI/Model/GUIMod.cs
GUI/Model/ModList.cs

Users often ask for a way to see what they have installed previously, and when we tell them this already exists in the `<GameRoot>/CKAN/history` folder, they then request an easier way to access those files.
Now a new menu option opens an Installation History tab containing a list of all the timestamps for which there is a history entry in the `<GameRoot>/CKAN/history` folder:
The OK button closes the tab and returns the user to Manage Mods.
If the user clicks an entry at the left, the mods that were installed at that point in time are listed on the right, split into a "Not currently installed" group at the top and a "Currently installed" group below that to make it easier to see the differences:
The user can click a mod to open ModInfo:
If the user clicks the Install toolbar button, the …

Installation history tab

---

Core/GameInstance.cs

If you manually install SpaceWarp for KSP2, it will be detected. But if you then delete the `BepInEx` folder, all your mods are gone, but any that were manually installed will still show up as such.
`GameInstance.Scan` aborts its work if the primary mod dir (`BepInEx/plugins` in this case) doesn't exist. This includes clearing the list of manually installed mods.
Now the DLL scan partly happens if the primary mod dir is missing; we clear the DLL list unconditionally, and then if the primary mod dir exists, we scan it and register the DLLs. Otherwise it just stays blank, as it should.

Scan for DLLs with or without primary mod dir

---

GUI/Main/MainInstall.cs

If an upgrade's download fails, the failed downloads popup from #3635 appears, but empty:
This dead-ends any investigation of such problems.
[Originally reported by forum user jost.](https://forum.kerbalspaceprogram.com/index.php?/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1320-kepler-ksp-2-support/&do=findComment&comment=4283056)
The rows of that table are built based on the mods in the changeset, but only the mods to install were included. The mods to upgrade were not, so if one of them had an error, it wouldn't be shown.
Now the mods we're upgrading are also passed to the form, so the error appears as expected:
While investigating this, I found that the popup could cause CKAN to freeze before it opened, and that passing itself to `Util.Invoke` instead of a reference to …

Show download errors for upgrades

---

GUI/Main/Main.cs

After #3829, the GUI window title is blank at startup:
It's set later, once the instance is loaded.
The window title depends on the name, version, and path of the game instance, so it's currently not set while the instance is loading.
Now we set an initial window title in `GUI.Main.OnLoad` containing the pieces that are not dependent on having the instance loaded:
The full title is still set later when the instance is loaded.

Set window title during startup

---

Netkan/Transformers/SpaceWarpInfoTransformer.cs

#3817 added retrieval of remote `swinfo.json` files for KSP2 mods, which are very analogous to remote version files.
If the `version_check` property contains a URL that's a broken link, the error message isn't clear. It's just a generic 404 error that could be coming from anywhere:
Now that exception is caught and replaced with one indicating the context in which the error occurred:
```
$ netkan.exe --game KSP2 NetKAN/ManeuverNodeController.netkan
2233 [1] FATAL CKAN.NetKAN.Program (null) - Error fetching remote swinfo https://raw.githubusercontent.com/schlosrat/ManeuverNodeController/master/maneuver_node_controller/swinfo.json: The remote server returned an error: (404) Not Found.
```
I might self-review this since it only affects the bot and would be nice to have soon-ish.

Clarify remote swinfo network errors

---

GUI/Model/ModList.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.resx

We somewhat frequently get questions about the Auto-installed column from #2753:
- #3146
- #3826
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/16763338-a250-40c9-99ad-a00bdc1a0738)
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/f6ac569e-1758-4e21-a409-d720207df0b7)
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/714692a9-5dc8-4517-84ed-263ee0e17b85)
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/4f829ef9-e0f2-4be8-b140-27e9746b0ce6)
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/9a307210-d76f-4f63-a290-557dc7d32248)
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/7ce5984c-2acc-4657-958e-d67239763c51)
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/66d1b587-e543-4932-8adf-39cd5d400dae)
- …

Tooltip for auto-installed checkboxes

---

Core/Extensions/IOExtensions.cs
Core/GameInstanceManager.cs
GUI/CKAN-GUI.csproj

Mac and Linux users have reported spurious errors about free disk space when installing:
```
Not enough space in game folder to install modules!
Need to store 2.3 MiB to /Applications/ksp_osx, but only 0 B is available!     
Free up space on that device or change your settings to use another location.
```
```
Not enough space in game folder to install modules!
Need to store 5.6 GiB to /home/storm/GOG Games/1.12.4-oldmods, but only 537.8 MiB is available!
Free up space on that device or change your settings to use another location.
[storm@defiant 1.12.4-oldmods]$ df -h .
Filesystem            Size  Used Avail Use% Mounted on
shuttlepod/GOG Games  3.5T   12G  3.5T   1% /home/storm/GOG Games
```
Mono's `DriveInfo.GetDrives()` doesn't include mounted filesystems other than `/`, which makes it …

Stop trying to check free space on Mono

---

Core/Games/KerbalSpaceProgram2.cs

A user uninstalled KSP2 and reported this on Discord:
`FileVersionInfo.GetVersionInfo` throws an exception when the file doesn't exist.
Now we check `File.Exists` so the exception won't be thrown.

Handle missing KSP2 exe

---

Netkan/Transformers/SpaceWarpInfoTransformer.cs

Some KSP2 modules have started using a new format for the `dependencies` list in `swinfo.json`, and a few don't match the capitalization of the identifier in CKAN:
Currently we warn if the string doesn't match the identifier of any value in the `depends` list, so these will always warn even if you have `SpaceWarp` or `UITKforKSP2` in there.
Now we remove characters up to and including the final `.`, then perform a case-insensitive comparison. This will produce fewer false positive warnings.
I might self-review this since it's just a Netkan warning.

More flexible SpaceWarp dependency checking

---

Core/Extensions/CryptoExtensions.cs
Core/Extensions/IOExtensions.cs
Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Net/ResumingWebClient.cs

- Users on Linux have reported that downloads and ZIP validation both sometimes "freeze", and eventually the whole install process comes to a halt. I have seen this when trying to install RP-1; usually a few smaller mods get stuck:
- If a downloaded ZIP fails to validate (such as for a file downloaded from taniwha.org), CKAN attempts to continue the installation, which wastes time because it will ultimately fail and be rolled back (reported by @UltraJohn on Discord)
- Individual downloads and validations were not actually freezing; rather, they completed normally, and the files were moved to the main cache folder, but the *progress bars* reappeared after being completed, due to the final 100% completion progress update being reordered to occur before some of the earlier in-progress …

Linux network fixes

---

Core/Net/Repo.cs
Core/Registry/Registry.cs

In the course of investigating why available modules were missing in #3699, users shared their registries, which revealed that the server etags (see #2682) were getting out of sync with the available modules; users were ending up with old module lists but up-to-date etags. This meant that if they tried to Refresh immediately, it would say the list was already up to date, even though it wasn't.
I found this very confusing for quite a long while. That data is all part of the `Registry` object; shouldn't it all be saved to `registry.json` together or not at all? No! There is one specific scenario in which they can get out of sync:
1. Metadata retrieved from network successfully
2. Etags updated
3. Module list updated
4. **Exception thrown while still inside transaction** (any exception would …

Include repo etags in transactions

---

CKAN.schema
Core/Games/KerbalSpaceProgram2.cs
Spec.md

Currently all KSP2 mods install to `BepInEx/plugins`. However, once the official mod loader is completed, this is expected to change to `GameData/Mods`.
I was expecting to change this in a new client release when the official mod loader was released, but the modding ecosystem has already begun experimenting with using this path. See KSP-CKAN/KSP2-NetKAN#68 and KSP-CKAN/KSP2-NetKAN#70, and current versions of SpaceWarp supposedly already allow it, which means we are likely to see mods soon that require it to be installed properly.
- Now `GameData/Mods` can be used in `install_to` for KSP2, including with subfolder paths
- `BepInEx/plugins` can still be used for KSP2, but no longer with subfolder paths (no current mods use subfolder paths)
- Now the value of `install_to` for the default …

Default install_to to GameData/Mods for KSP2

---

GUI/Main/Main.cs
GUI/Model/GUIConfiguration.cs

If you have multiple game instances and no default game instance, the Manage Game Instances window appears at startup. In v1.33.0, this exception is thrown after you select an instance:
```
System.ArgumentException: Empty path name is not legal.
at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.StreamWriter..ctor(String path)
at CKAN.GUI.GUIConfiguration.SaveConfiguration(GUIConfiguration configuration)
at CKAN.GUI.Main.CurrentInstanceUpdated(Boolean allowRepoUpdate)
at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
```
There's also a "Check for updates" prompt that will happen every time.
(Everything works fine if "Set as default" is checked for some instance.) …

Fix exception at startup w/o default game inst

---

GUI/Localization/zh-CN/Changeset.zh-CN.resx

The existing Chinese translations of the "back" and "cancel changes" buttons are very similar in Chinese, and these changes can help users distinguish the difference between the two buttons.

Updated Chinese translation to reduce misunderstandings

---

Core/GameInstance.cs
GUI/Controls/UnmanagedFiles.cs
GUI/Main/MainUnmanaged.cs

If you open the Unmanaged Files tab from #3833 and try to delete a file, an exception is thrown:
```
System.IO.IOException: The directory name is invalid.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileSystemEnumerableIterator`1.CommonInit()
at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
at System.IO.Directory.EnumerateFileSystemEntries(String path, String searchPattern, SearchOption searchOption)
at CKAN.GameInstance.HasManagedFiles(Registry registry, String absPath)
at CKAN.GUI.UnmanagedFiles.DeleteButton_Click(Object sender, EventArgs e)
at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, …
```

Fix deletion of unmanaged files

---

Netkan/Transformers/SpaceWarpInfoTransformer.cs

KSP-CKAN/KSP2-NetKAN#75
If a module has no `depends` relationships, then `mod.depends` is null here, and `.Select` doesn't work:
https://github.com/KSP-CKAN/CKAN/blob/83b6e7deb0dba437947e5acda6ff78042d5293fe/Netkan/Transformers/SpaceWarpInfoTransformer.cs#L87-L89
This problem was masked by all previous mods with `swinfo.json` files having a dependency on SpaceWarp.
Now if `CkanModule.depends` is null, we substitute the empty sequence.
Will self-review so that pull request can proceed.

Fix Netkan swinfo transformer null list error

---

debian/control.in

1. On Ubuntu, install the .deb without `mono-complete`
2. `ckan consoleui`
3. Press ctrl-R to refresh the mod list
4. `System.TypeLoadException: Could not load type of field 'CKAN.ConsoleUI.Toolkit.ConsoleTextBox:lines' (5) due to: Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.`
`libmono-system-servicemodel4.0a-cil` is apparently required.
Now that package is added as a dependency of our .deb package. This fixed the exception in my Ubuntu test system.
Fixes #3871.

Add missing dependency to .deb package

---

Core/Properties/Resources.resx

I just noticed that the `ModuleInstallerUpgradeInstallingResuming` resource is declared (there's a property for it) and used but not defined (there's no actual text for it). This is used when you upgrade a module which has a new dependency that you don't have installed yet but which you have a partial download for sitting in your cache. (A quite rare scenario, which probably explains why we haven't had complaints about it yet.)
Now the string is defined for the default locale as ` * Install: {0} {1} ({2}, {3} remaining)`.

Add missing resource string for upgrading

---

Cmdline/Action/Repo.cs
Cmdline/ConsoleUser.cs
Cmdline/Properties/Resources.Designer.cs
Cmdline/Properties/Resources.resx
Core/Net/Repo.cs
Core/Properties/Resources.resx
Core/Registry/Registry.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.resx

CKAN can be configured to retrieve module metadata from multiple sources, called "repositories." The vast majority of users only use one repository. Alternate repositories are typically used to allow users to opt-in to bleeding edge releases of specific mods (e.g. MechJeb2 and Kopernicus).
- Updating the registry retrieves repositories in order of their names alphanumerically, regardless of the priorities
- The string `Loading modules from {0} repository...` was not internationalized
- You can't edit the priorities from the command line
- `ckan repo list` uses a weird format different from the tabular output of most other commands
- Progress updates were hard-coded to show percentages only for strings containing the English word "download"
- The priority of newly added repositories isn't …

Repository management fixes

---

GUI/Main/Main.cs

If you don't have a default game instance, the GUI window will always appear in its default location as if you have never run CKAN before. This can be annoying if you have a strong preference for having appear in a particular spot on the screen or at a particular size.
The window geometry is saved per-instance, and as of #3829 and #3863, we display the GUI window as early as possible, and if there's no default instance, then the window appears before you choose an instance. There was no clearly best way to load the geometry without an instance.
Now if you have no default instance, we scan your (valid) instances to find the one with the most recently written `CKAN/GUIConfig.xml` file, and then we load that configuration. This way the window will appear wherever it was when you most …

Restore window position without default instance

---

Cmdline/Action/AuthToken.cs
Cmdline/Action/GameInstance.cs
Cmdline/Action/Install.cs
Cmdline/Main.cs
Cmdline/Properties/Resources.Designer.cs
Cmdline/Properties/Resources.resx

While I was testing some edge case `install` stanzas for @JonnyOThan, this metadata:
```json
"install": {
"file": "Astrogator",
"install_to": "GameRoot/KSP_x64_Data"
},
```
gave me this error:
```
$ ckan.exe install -c Astrogator-v1.0.0.ckan
Unhandled Exception: System.FormatException: Input string was not in a correct format.
at System.Text.StringBuilder.FormatError()
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.Format(IFormatProvider provider, String format, Object[] args)
at System.IO.TextWriter.WriteLine(String format, Object[] arg)
at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
at …
```

Correctly print cmdline errors with braces

---

GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Main/Main.cs
GUI/Main/MainDownload.cs
GUI/Model/ModList.cs

- If you have no mods installed, the Auto-installed column is still displayed even though it serves no purpose:
- A Discord user confused himself by scrolling the mod list to the right and forgetting that the checkbox to install a mod had scrolled off the edge of the grid:
- This column's visibility was managed in multiple places, and they conflicted with one another; an older one was hiding the Auto-installed column while a newer one was unhiding it
- The checkbox columns are small but essential UI elements, so allowing them to scroll out of view has more disadvantages than advantages
We have a very old `TODO` item here:
https://github.com/KSP-CKAN/CKAN/blob/1a884fe056bbca120167d89cfaba61f833113537/GUI/Model/ModList.cs#L172
This is _not_ a very good place for it (it would be …

Mod list fixes and improvements

---

Core/Net/NetFileCache.cs
Core/Net/NetModuleCache.cs
Core/Registry/InstalledModule.cs
Core/Registry/Registry.cs
GUI/GUIUser.cs
Tests/Core/Cache.cs
bin/ckan-merge-pr.py

The commit script currently assumes a `master` branch, but the latest recommendation is to prefer `main`, as with the KSP2 repos.
- Now the name of the primary branch is retrieved from the repo's refs, similarly to KSP-CKAN/NetKAN-Infra#288, which removes one obstacle to renaming CKAN's `master`
- I accumulated various trivial C# style changes that didn't belong in other pull requests, which are now dumped here

Deduce primary branch name in merge script

---

ConsoleUI/ExitScreen.cs
Core/CKANPathUtils.cs
Core/CompatibleGameVersions.cs
Core/Configuration/JsonConfiguration.cs
Core/Configuration/Win32RegistryConfiguration.cs
Core/Converters/JsonPropertyNamesChangedConverter.cs
Core/Converters/JsonSingleOrArrayConverter.cs
Core/Converters/JsonToGamesDictionaryConverter.cs
Core/GameInstanceManager.cs
Core/Games/KerbalSpaceProgram/GameVersionProviders/KspBuildMap.cs
Core/Games/KerbalSpaceProgram2.cs
Core/Meta.cs
Core/Registry/Tags/ModuleTagList.cs
GUI/Controls/Changeset.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Labels/ModuleLabel.cs
GUI/Labels/ModuleLabelList.cs
GUI/Main/Main.cs
GUI/Main/MainLabels.cs
GUI/Model/ModList.cs
GUI/Model/ModSearch.cs
Tests/GUI/Model/ModList.cs

If you add a label to `ResonantOrbitCalculator` in KSP1, the different mod with the same identifier will also have that label added in KSP2, and vice versa. This is not ideal because these are two different mods, which you should be able to treat separately.
The `labels.json` file just has one list of identifiers per label, with no distinctions between games, so when both games have a mod with the same identifier, they're treated as one mod.
- Now `Meta.GetProductName()` provides a centralized way to get the string "CKAN", `CKANPathUtils.AppDataPath` uses it to provide a centralized way to get the path of the shared config folder, and code that uses either value is updated to use these properties (I did this initially because I was considering changing the path of the `labels.json` file, …

Multi-game labels

---

CKAN.schema
Tests/NetKAN/Validators/ObeysCKANSchemaValidatorTests.cs

KSP-CKAN/KSP2-NetKAN#81
```yaml
install:
- find: BetterPartsManager
install_to: GameData/Mods
```
https://github.com/KSP-CKAN/KSP2-NetKAN/actions/runs/5930964431/job/16081829297
https://cswr.github.io/JsonSchema/spec/generic_keywords/
`GameData/Mods` is _too correct_; it matches both of these:
https://github.com/KSP-CKAN/CKAN/blob/858d71fc389910fb3ce357d70fa2d4ea0de82218/CKAN.schema#L440-L444
https://github.com/KSP-CKAN/CKAN/blob/858d71fc389910fb3ce357d70fa2d4ea0de82218/CKAN.schema#L460-L463
And the tooling apparently doesn't like that. How this could ever possibly be useful is quite beyond me.
I want to keep the explicit definition of the KSP2 default folder independent of what happens elsewhere in the list, so now the `install_to` part uses `anyOf` instead of `oneOf`, which will allow …

Fix schema issue with install_to: GameData/Mods

---

Core/GameInstance.cs
Core/Games/IGame.cs
Core/Games/KerbalSpaceProgram.cs
Core/Games/KerbalSpaceProgram2.cs
Netkan/Validators/InstallsFilesValidator.cs

In KSP-CKAN/KSP2-NetKAN#84, the validation script happily installed files to `BepInEx/plugins/QuestariaAerospace/BepInEx/plugins/QuestariaAerospace` and didn't complain:
https://github.com/KSP-CKAN/KSP2-NetKAN/actions/runs/5967777987/job/16190169201
There's a "GameData within GameData" validator in Netkan that catches the equivalent issue for KSP1.
The "GameData within GameData" check is hard-coded to use the string `GameData`.
- Now `IGame.AlternateModDirectoriesRelative` defines an array of strings specifying alternative locations where mods can be installed
- This contains `BepInEx/plugins` for KSP2 and nothing for KSP1
- Now we scan both the primary and alternate mod dirs for manually installed DLLs
- Now the "GameData within GameData" checks the primary and alternate mod dirs, which …

Alternate mod dirs for validation and manual installs

---

CKAN.schema
Core/ModuleInstaller.cs
Core/Relationships/RelationshipResolver.cs
Core/Types/RelationshipDescriptor.cs
GUI/Main/MainInstall.cs
Spec.md

Currently we show only the recommendations and suggestions for the mods the user selects. The recommendations and suggestions of dependencies aren't shown, even though the user stands to benefit from seeing them.
- Now recommendations and suggestions are shown for the full changeset, including both user-selected mods and all of their dependencies, except...
- The KSP-RO folks don't want that for their modules, because the list would be very long and some of it might not be applicable to an RSS install, so modules can do this to opt out:
```yaml
depends:
- name: AMod
suppress_recommendations: true
```
With that in place, AMod would be pulled in as a dependency, but its recommendations and suggestions (and those of _its_ dependencies) won't be shown. This will allow the RP-1 install's …

Show recommendations of full changeset with opt-out

---

Core/Net/NetFileCache.cs
Core/Net/NetModuleCache.cs
Core/Types/CkanModule.cs

- Spaces aren't allowed in archive.org bucket names, and recently a few mods have put spaces in their version strings, which broke the Mirrorer. To fix that, that KSP-CKAN/NetKAN-Infra#307 replaced those spaces with underscores. This allowed the mod to be mirrored, but the client doesn't perform the same substitution yet.
- In another branch, I have some code that generates `CkanModule`s with null `download` properties, and after switching back out of that branch, trying to install such a module threw a null reference exception
- Now `Ckan.InternetArchiveDownload` replaces spaces with underscores, so the client will be able to find the fallback downloads of affected modules
- Now the `GetInProgressFileName` calls are more careful to avoid null references
I think I'll self-review this …

Fix archive.org fallback URLs for versions with spaces

---

debian/control.in

Trying to install the .deb on Debian 12 fails with a message indicating log4net is missing:
```
root@MartinPC:/home/martin/Downloads# apt install ckan
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
ckan : Depends: liblog4net1.2-cil but it is not installable
E: Unable to correct problems, you have held broken packages.
```
The latest release of Debian seems to no longer include this package; "bookworm" …

Remove log4net, newtonsoft deps from deb package

---

GUI/Controls/ManageMods.resx

On Discord, a Linux user with a 1024x768 monitor reported not being able to see the Filter dropdown button even with the GUI maximized:
Windows's toolbar has a dropdown feature to accommodate toolbar overflow, but Mono never implemented that.
Now the following buttons' English titles are shortened to allow them to fit into a smaller space:
- Launch Game → Play
- Add available updates → Update all
- Apply changes → Apply
These should be clear enough to both new and existing users.

Shorten toolbar button labels

---

Core/Net/Net.cs
Core/Net/NetAsyncDownloader.cs
Tests/Core/Net/NetAsyncDownloaderTests.cs

See #3906 for details; to sum up, one of the new `NetAsyncDownloader` tests from #3904 was failing in GitHub workflows but nowhere else.
When downloading multiple URLs, the `DownloadTarget.size` values were 0 for some of the files when `NetAsyncDownloader.DownloadAndWait` completed.
This new test found a real, pre-existing problem for us! I'm really glad I didn't give in to the temptation to add `[Category("FlakyNetwork")]` and move on. 🎉
There's a race condition with multiple extremely fast downloads (the test is using `file://` URLs to avoid spurious failures caused by server glitches, so the files are already on disk and possibly cached in memory). At the start, the main thread loops over the requested URLs and starts a thread for each one. This sets up the `downloads` list with the …

Fix race condition for multiple very fast downloads

---

Core/Registry/CompatibilitySorter.cs
Core/Registry/Registry.cs
Core/Repositories/AvailableModule.cs
Core/Repositories/RepositoryDataManager.cs
Tests/Core/Registry/CompatibilitySorter.cs
Tests/Data/TemporaryRepository.cs

The metadata validator threw a duplicate key exception while checking KSP-CKAN/NetKAN#9800:
https://github.com/KSP-CKAN/NetKAN/actions/runs/6207962451/job/16853654203?pr=9800
```
System.ArgumentException: An item with the same key has already been added. Key: [kOS-EVA, CKAN.AvailableModule]
at System.Collections.Generic.TreeSet`1[T].AddIfNotPresent (T item) [0x0001a] in <33b19a7ad5234d94abf4fd9b47566616>:0 
at System.Collections.Generic.SortedSet`1[T].Add (T item) [0x00000] in <33b19a7ad5234d94abf4fd9b47566616>:0 
at System.Collections.Generic.SortedDictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00020] in <33b19a7ad5234d94abf4fd9b47566616>:0 
at CKAN.CompatibilitySorter.PartitionModules (System.Collections.Generic.IEnumerable`1[T] dicts, …
```

Fix duplicate key exception in CompatibilitySorter

---

Core/ModuleInstaller.cs
Core/Properties/Resources.Designer.cs
Core/Properties/Resources.resx
Core/Registry/RegistryManager.cs
Core/Relationships/RelationshipResolver.cs
GUI/Controls/Changeset.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Main/MainChangeset.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs
GUI/Main/MainTrayIcon.cs
GUI/Model/GUIMod.cs
GUI/Model/ModChange.cs
GUI/Properties/Resources.Designer.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.fr-FR.resx
GUI/Properties/Resources.it-IT.resx
GUI/Properties/Resources.ja-JP.resx
GUI/Properties/Resources.ko-KR.resx
GUI/Properties/Resources.pl-PL.resx
GUI/Properties/Resources.pt-BR.resx
GUI/Properties/Resources.resx
GUI/Properties/Resources.ru-RU.resx
GUI/Properties/Resources.zh-CN.resx
Tests/Core/ModuleInstallerTests.cs

In https://github.com/KSP-RO/RP-1/commit/b9f085575debb6be46dfeed3f722f3110ce0d046, `RP-1`'s dependency on `MagiCore` was removed from its metanetkan, and this change first reached users with the indexing of `RP-1` v2.12 in https://github.com/KSP-CKAN/CKAN-meta/commit/98a346180f649c277e026a18cd69d0c3b5055ac8. When they upgraded, `RP-1-ExpressInstall` and all of its auto-installed dependencies were uninstalled (which should not have happened!). The dependency was subsequently restored pending a CKAN fix.
1. Use a fresh game instance of KSP1 1.12.5
2. In CKAN, go to the settings and replace the default repo with this URL to simulate using CKAN before the problematic upgrade (name doesn't matter):
https://github.com/KSP-CKAN/CKAN-meta/archive/0451525c2c9cefd16914032a2ca38d69c9e3f21c.tar.gz
3. …

Fix auto-remove during upgrade

---

Cmdline/Action/GameInstance.cs
Core/Extensions/EnumerableExtensions.cs
GUI/Attributes/ForbidGUICallsAttribute.cs
GUI/CKAN-GUI.csproj
GUI/Controls/ChooseProvidedMods.cs
GUI/Controls/ChooseRecommendedMods.cs
GUI/Controls/DeleteDirectories.cs
GUI/Controls/EditModpack.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfoTabs/Relationships.cs
GUI/Controls/ModInfoTabs/Versions.cs
GUI/Controls/Wait.cs
GUI/Dialogs/DownloadsFailedDialog.cs
GUI/Dialogs/ErrorDialog.cs
GUI/Main/Main.cs
GUI/Main/MainDialogs.cs
GUI/Main/MainDownload.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs
GUI/Main/MainRepo.cs
GUI/Main/MainWait.cs
Tests/GUI/ThreadSafetyTests.cs
Tests/Tests.csproj

WinForms is based on some of quite old Windows GUI libraries, from before multithreading was ubiquitous. The .NET implementation inherited a peculiar threading gotcha: All changes to the GUI must be made from the same "GUI thread", or the app will crash or freeze or worse.
If you look for ways to deal with this problem, mostly you'll find people recommending `Control.InvokeRequired`/`Control.Invoke`, which we already have in the form of `CKAN.GUI.Util.Invoke`. This is fine when you remember to use it correctly, but it's easy to forget, and when that happens, we get crashes or freezes or worse.
- https://jonskeet.uk/csharp/threads/winforms.html
A few people have created more elaborate systems that wrap the GUI objects in some kind of proxy class that calls `Invoke` as needed. These …

Add test to check GUI thread safety

---

debian/ckan-cmdprompt.desktop
debian/ckan-consoleui.desktop
debian/ckan.desktop

Fixed a typo in `debian/ckan-cmdprompt.desktop` ('propmt' -> 'prompt'), and remove all 3 .desktop files from `Utilities`.
If it's to go anywhere outside of `Games`, it would probably be better in `Database` or `Development`, I think.

Clean up Linux .desktop files

---

GUI/Dialogs/SettingsDialog.Designer.cs
GUI/Dialogs/SettingsDialog.cs

For about 3 years now, we have had sporadic reports of the CKAN GUI using an unexpected language, initially Chinese, later French, occasionally other languages.
Extensive, repeated audits of the code in search of bugs turned up a few leads that ultimately were dead ends. The code for defaulting the language initially, saving to/loading from disk, and the settings dialog are about as simple and robust as could be hoped, and we were not able to reproduce the problem with any imagined set of steps.
However, today a user shared a video that might explain what has been happening:
- [video](https://cdn.discordapp.com/attachments/601456752906469388/1175110199292469298/Settings_2023-11-17_17-26-29.mp4)
If the user thinks the dialog may be scrollable (many modern UIs hide the scrollbar until …

Don't change language setting with scroll wheel

---

Cmdline/Main.cs
Cmdline/Options.cs
Cmdline/Properties/Resources.resx
Core/Extensions/RegexExtensions.cs
Core/Platform.cs
Core/Relationships/RelationshipResolver.cs

- CKAN has a check for whether the user is privileged and an `--asroot` flag to bypass this, but it's Linux-only. Windows users are just as likely to benefit from this guardrail. It's also implemented entirely within CmdLine, even though it could in principle apply more generally.
- There's a check that prints a warning if the user is on a version of Mono before 3.1.0, which duplicates platform-specific logic from Core in CmdLine, and I'm pretty sure you need a much newer version of Mono to run current CKAN
- `Platform.IsMonoFourOrLater` and `Platform.IsOnMonoFourOrLater` have been unused since #3041
- Now the root user check is moved to `Platform.IsAdministrator()`
- Now it has an `IsWindows` section that checks for administrator or system roles
- Now the messages for the root user check …

Modernize administrator and Mono version checks

---

Core/Properties/Resources.resx
Core/Relationships/RelationshipResolver.cs
Core/Repositories/AvailableModule.cs
Core/Types/Kraken.cs
GUI/Controls/ChooseProvidedMods.Designer.cs
GUI/Controls/ChooseProvidedMods.cs
GUI/Controls/ManageMods.cs
GUI/Main/MainInstall.cs

- In current dev builds, an installed mod can show up as not installed in the mod list, which in turn can lead to unhandled exceptions if you try to "install" it, or even more confusing scenarios like a mod that looks like it isn't installed but can be upgraded (!)
- Also in current dev builds, installing Scatterer prompts regarding a recommendation for `BetterKerbol` via `TheKramsieChallengePlanetPack`, which doesn't make sense because you haven't selected to install that mod
Noticed while working on the below usability improvements for the provider choice prompt.
- #3917 got too aggressive with parallelizing the mod list load. It generated two `GUIMod` object for each installed mod, one in the list of installed mods, and another in the list of compatible or incompatible mods. These were …

Improve provides prompt usability, with bugfixes

---

Core/Registry/Registry.cs
Core/Relationships/RelationshipResolver.cs
Tests/Core/Net/NetAsyncModulesDownloaderTests.cs
Tests/Core/Registry/Registry.cs

@JonnyOThan reported the following error with the current dev build:
```
Scanning for DLCs and manually installed modules...
MakingHistory-DLC missing required field version
Repository update failed!
```
The DLC's folder was present, but its `readme.txt` file was absent. This caused its `CkanModule.version` property to be missing, which isn't allowed.
Originally this would have defaulted to `new UnmanagedModuleVersion(null)`, but this was lost in #3904's refactoring.
Now we once again default to `new UnmanagedModuleVersion(null)`, as per previous releases. A new test exercises this case to make sure `Registry.SetDLCs` doesn't start throwing again.
I'll probably self-review this since it's small and a regression.

Better handling for DLC with missing readme.txt

---

Core/Converters/JsonAlwaysEmptyObjectConverter.cs

If you install some mods with the current release of CKAN and then switch to the current dev build, it will show no mods installed.
Thanks to @JonnyOThan for reporting this on Discord.
In #3904, we retired `Registry.available_modules` and `Registry.download_counts`. However, since the old client will crash if these are absent or null, we created a `JsonAlwaysEmptyObjectConverter` to ensure they're always saved as an empty JSON object (`{}`). This converter's deserialization function worked by simply creating an empty copy of the required type (`Dictionary<string, string>` in this case).
However, a `JsonConverter`'s `ReadJson` implementation **must** call `JToken.Load(reader)` to extract the current token from the input stream! We weren't doing that, and the parse was stopping right after …

Fix loading of legacy registry.json files

---

ConsoleUI/Toolkit/ConsoleButton.cs
ConsoleUI/Toolkit/ConsoleField.cs
ConsoleUI/Toolkit/ConsoleFileMultiSelectDialog.cs
ConsoleUI/Toolkit/ConsoleListBox.cs
Core/Extensions/EnumExtensions.cs
Core/ModuleInstaller.cs
Core/Properties/Resources.resx
Core/Registry/Registry.cs
Core/Types/Kraken.cs
GUI/Controls/Changeset.Designer.cs
GUI/Controls/Changeset.cs
GUI/Controls/Changeset.resx
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Controls/ModInfoTabs/Metadata.cs
GUI/Controls/ModInfoTabs/Relationships.cs

When you launch KSP1 on Windows, it locks either many or all of the mods' files. If you then try to uninstall those mods with CKAN while the game is still running, you get a hard to understand message that mentions the file but gives no information about why the problem happened or what you can do about it:
Brought up by @JonnyOThan on Discord.
- Now the message is reformatted to be more understandable:
> Unable to overwrite or delete files for MyMod:
>
> GameData\MyMod\MyMod.dll
>
> If the game is still running, close it and try again. Otherwise check the permissions.
- The top line states simply that we were trying to delete files and could not
- The bottom line says to close the game and check permissions
- The file list is now relative to game root and uses local OS path separators …

Improve file deletion error while the game is running

---

Core/ModuleInstaller.cs
GUI/Controls/DeleteDirectories.Designer.cs

1. Install TweakScale with the current dev build (problem reported not to happen with the released version)
2. Launch the game
3. Start or load a save
4. Launch a rocket
This (or the previous step, not clear) should create a `GameData/TweakScale/Plugins/PluginData/Scale/config.xml` file
(Don't ask me why this isn't just `GameData/TweakScale/PluginData/config.xml` instead.)
5. Close the game
6. Uninstall TweakScale
7. You're prompted to delete the `PluginData` folder, but not the `Plugins` or `Tweakscale` parent folders
8. As you'd expect, clicking Delete Checked leaves the TweakScale folder there
I think #3890's changes to the the deletion logic must have affected how subdirectories are treated, but I was more focused on understanding and fixing the current logic than on the details of …

Prompt to delete dirs containing empty registered dirs

---

Core/Games/IGame.cs
Core/Games/KerbalSpaceProgram.cs
Core/Games/KerbalSpaceProgram2.cs
GUI/Controls/EditModSearch.cs
GUI/Controls/EditModSearchDetails.Designer.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Controls/EditModSearchDetails.resx
GUI/Controls/EditModSearches.cs
GUI/Controls/EditModpack.Designer.cs
GUI/Controls/HintTextBox.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Dialogs/CloneGameInstanceDialog.Designer.cs
GUI/Dialogs/CompatibleGameVersionsDialog.Designer.cs
GUI/Dialogs/EditLabelsDialog.Designer.cs
GUI/Dialogs/GameCommandLineOptionsDialog.Designer.cs
GUI/Dialogs/NewRepoDialog.Designer.cs
GUI/Dialogs/RenameInstanceDialog.Designer.cs
GUI/Dialogs/SettingsDialog.Designer.cs
GUI/Main/Main.cs
GUI/Main/MainDialogs.cs
GUI/Model/ModSearch.cs
GUI/Properties/Resources.resx

- The mod search can search all relationships except `supports`. @JonnyOThan suggested adding `supports`.
- If you click the search dropdown button on Windows and then click it again, the dropdown disappears but you have to click the button two more times to get it to reappear. (On Mono this already works perfectly.)
- Ctrl+Backspace is a common hotkey for deleting whole words in a textbox (with a dubious history as a "rogue feature" starting with early Internet Explorer releases), but the CKAN GUI currently only supports it on Mono (where it's built in to the runtime)
- While working on the rest of this, I noticed that the "Help &rarr; Report an issue with mod metadata" link assumed the game was KSP1, even if you were working with a KSP2 instance
- The search dropdown was set up to be a …

Search by supports relationship and other search improvements

---

GUI/Properties/Resources.pt-BR.resx

Fixed small typos in line 182 (appears when the user tries to install a mod in a non-supported KSP version).
accidentaly discovered this when i was trying to install a mod, so here it is 👍

Fix two small typos in Resources.pt-BR.resx at line 182

---

Core/Configuration/Win32RegistryConfiguration.cs
Core/ModuleInstaller.cs
Core/Relationships/RelationshipResolver.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Controls/ManageMods.cs
GUI/Model/ModList.cs
Tests/Core/Registry/Registry.cs
Tests/Core/Relationships/RelationshipResolver.cs

The fix for installed mods showing up as not installed from #3934 was incomplete; it addressed installed mods that can't be upgraded, but the problem can still happen for installed mods that are upgradeable. If such a mod happens to load as uninstalled and you try to upgrade it, an exception is thrown:
Reported by @jan-bures on Discord.
I used `.Except()` to filter installed mods out of the compatible and incompatible lists, but that only works when their `CkanModule.version` properties are the same. For an upgradeable mod, its version in the compatible list is newer than the installed verson, so `.Except()` doesn't filter it out, and we once again have a race condition.
- Now we filter by identifier instead. (Unfortunately, `.ExceptBy()` is not available until .NET 6+).
- Also switched a …

Protect upgradeable mods from being displayed as uninstalled

---

GUI/Controls/ManageMods.cs
GUI/Main/Main.cs

As of #3727, conflicts are supposed to be highlighted red in the changeset, but that's not working right now if you click the Apply button. (Clicking the changeset tab instead still works.)
In #3890, the Apply button was refactored to re-use the `StartChangeSet` event (previously only used by the right click reinstall option) rather than the `GUI.Main.Instance` global singleton. But that event didn't handle conflicts, so they were passed as `null`, and the changeset tab never showed them.
Now the conflicts are passed along.
Fixes #3946.
Definitely self-reviewing this one.

Restore conflict highlights in changeset

---

Core/Relationships/RelationshipResolver.cs
GUI/Controls/ManageMods.cs
GUI/Model/ModList.cs
GUI/Util.cs

- If you select to install two mods that conflict, their background color properties are set to a reddish color, but this is completely overridden by the blue row highlight color. If the other conflicting mod's row is off-screen, this usually meant that you couldn't see any red highlights at all.
- Conflict descriptions are missing from the status bar in some cases
- If you apply multiple labels to a mod, only one of their background colors is applied
- `RelationshipResolver.ConflictDescriptions` only returned descriptions of conflicts for the mod with fewer indirectly-depending mods, intended to choose the conflict closest to what the user selected, but when these values were equal, neither would appear.
- Now if two conflicting mods have equal numbers of indirectly-depending mods, both …

Conflict highlight for selected row

---

Core/ModuleInstaller.cs

1. Install a mod with CKAN
2. Delete its files manually (this isn't a good idea, so don't do it normally, but it's how the bug is reproduced, so you have to do it this once)
3. Uninstall the mod in CKAN
4. This error is displayed:
During development to improve the "inconsistencies were found / is registered to but has not been removed" message in #3938, I thought the missing-file case only needed to sneak past `File.Delete`, which explicitly says it won't throw an exception:
However, the underlying exception here is thrown elsewhere:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\program files (x86)\steam\SteamApps\common\Kerbal Space Program\GameData\AJE\RftS\Brown.dds'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at …
```

Fix uninstallation of manually deleted files and directories

---

Netkan/Model/Metadata.cs
Netkan/Program.cs
Netkan/Transformers/PropertySortTransformer.cs

After merging KSP-CKAN/NetKAN#9882, I noticed `ksp_version` was appearing out of its normal ordering:
The GitHub module has no versioning info at all, whereas the one from SpaceDock has a game version, and otherwise they're identical, so the merge code is appending just that one property from the SpaceDock module onto the GitHub module after it's sorted.
Now the merge logic reapplies sorting, so multi-host .ckans will have the same property ordering as single-host ones.

Re-sort module properties after merging

---

Cmdline/CKAN-cmdline.csproj
Core/Games/KerbalSpaceProgram.cs
Core/Net/Net.cs
Core/Net/RedirectWebClient.cs
GUI/Main/MainRepo.cs
Netkan/CKAN-netkan.csproj
Tests/Tests.csproj

Since #2682, CKAN has performed a `HEAD` request to get the ETag of each repo before retrieving the full data, to avoid re-downloading the same large metadata archive over and over. This makes the Refresh button finish very quickly if there haven't been any metadata changes since the last time you refreshed (it's basically the same as a browser cache). This was implemented with `WebRequest`, which is now obsolete according to this compiler warning:
https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0014
After the release of CKAN v1.34.0, a few users reported that repo updates were sometimes hanging with the almost provocatively unhelpful message, "One or more errors occurred" (it turned out to be just one error :face_with_spiral_eyes:):
Reported by …

Oops, `HttpClient` actually sucks

---

.github/workflows/build.yml
Dockerfile.metadata
Dockerfile.netkan
Netkan/Program.cs
doc/building.md

- After KSP-CKAN/NetKAN-Infra#322, our Docker images are updated to Python 3.11, except for the meta tester. We don't want to fall too far behind the current versions of Python.
- The meta tester contains a lot of stuff it doesn't need, weighing in at a hefty 1.23GB:
- C/C++ compilers and libraries
- Mono compilers
- Mono libraries we don't need
- Python build tools
- Flask and gunicorn
- APT and pip download caches
- Old logs
- Etc.
```
REPOSITORY         TAG       IMAGE ID       CREATED        SIZE
kspckan/metadata   latest    df95b1b2804f   20 hours ago   1.23GB
kspckan/inflator   latest    165d396574f3   20 hours ago   792MB
```
Now instead of using `mono:latest`, which is an old OS that installs Python 3.7, we start with the much more current `ubuntu:latest` and install the latest …

Update and optimize meta tester and inflator images

---

Dockerfile.netkan

Linq was missing, causing the AWS libraries to fail loading. This installs it during build

System Linq

---

.gitignore
Core/GameInstanceManager.cs
Core/Games/IGame.cs
Core/Games/KerbalSpaceProgram.cs
Core/Games/KerbalSpaceProgram/GameVersionProviders/KspBuildIdVersionProvider.cs
Core/Games/KerbalSpaceProgram2.cs
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/Model/GUIConfiguration.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.fr-FR.resx
GUI/Properties/Resources.it-IT.resx
GUI/Properties/Resources.ja-JP.resx
GUI/Properties/Resources.ko-KR.resx
GUI/Properties/Resources.pl-PL.resx
GUI/Properties/Resources.pt-BR.resx
GUI/Properties/Resources.resx
GUI/Properties/Resources.ru-RU.resx
GUI/Properties/Resources.zh-CN.resx

- When you add a KSP1 instance in GUI, you have to pick `buildID.txt` or `buildID64.txt` in the file chooser. This has always been a bit confusing, because no user knows what this file is for or why we care about it. So far nobody seems to have been confused by having to pick the game EXE for KSP2.
- It's also confusing that the file chooser says "Build metadata file," since no user knows what that means.
- The Manage Game Instances window sorts game instances by version without regard to which game it is, so KSP2 with its low version numbers always shows up before the beginning of KSP1.
- Someday, KSP2 is probably going to start installing mods into a `GameData/Mods` folder. If/when this happens, current CKAN clients will detect those instances as KSP1 game folders.
- If you install a …

Usability improvements for adding game instance

---

CHANGELOG.md
Cmdline/Options.cs
Cmdline/Properties/Resources.resx

Users attempting to run GUI as a Windows administrator have reported that the console window appears and disappears before they have a chance to see what it says (see #3956 and #3965).
- Now we use a "Press any key to exit" prompt to keep the window visible and only close it after the user presses a key.
- The message now describes the risks involved in more detail.
This should allow users to understand what's happening and make an informed decision.

Pause after administrator error message

---

Netkan/Transformers/SpaceWarpInfoTransformer.cs

> NetKAN bot: New inflation error for SpaceWarp: Schema validation failed: #/ksp_version_min: PatternMismatch
The schema supports 0.2.0 but not 0.2.0.0.
https://github.com/KSP-CKAN/CKAN/blob/3e8950af83b3e919efb1af4152deb79a8ae14c39/CKAN.schema#L380-L384
The `SpacedockTransformer` uses `GameVersion.WithoutBuild` to remove the 4th piece from the game version the user selects on SpaceDock:
https://github.com/KSP-CKAN/CKAN/blob/3e8950af83b3e919efb1af4152deb79a8ae14c39/Netkan/Transformers/SpacedockTransformer.cs#L79
But the `SpaceWarpInfoTransformer` does not do the same for the game versions in `swinfo.json`:
https://github.com/KSP-CKAN/CKAN/blob/3e8950af83b3e919efb1af4152deb79a8ae14c39/Netkan/Transformers/SpaceWarpInfoTransformer.cs#L78-L84
Now game versions from `swinfo.json` are trimmed to …

Generate schema compliant game versions from swinfo.json

---

Core/Net/NetFileCache.cs
Core/Registry/Registry.cs
Core/Registry/RegistryManager.cs
Core/Repositories/RepositoryData.cs
Core/Types/CkanModule.cs
Netkan/Services/ModuleService.cs

If a user in the eastern hemisphere tries to install a version of a mod that was released in the past X hours, where X is the number of timezones east of Greenwich (so, 3 hours for UTC+3), it fails with this error:
```
About to upgrade:
* Upgrade: Patch Manager 0.5.0 to 0.6.0 (spacedock.info, 247.0 KiB)
Downloading "https://spacedock.info/mod/3482/Patch%20Manager/download/0.6.0"
Finished downloading PatchManager 0.6.0, validating and storing to cache...
Trying to install PatchManager 0.6.0, but it's not downloaded or download is corrupted
If you suspect a …
```

Fix cache timestamp comparisons

---

Core/Games/KerbalSpaceProgram.cs
Core/Repositories/AvailableModule.cs
GUI/Dialogs/CompatibleGameVersionsDialog.cs
GUI/Model/GUIMod.cs

If you open the compatible game versions dialog and click accept (whether or not you make any changes), the values in the max game version column change in strange and hard to understand ways.
As of #3904, the max game versions column's behavior depends on the ordering of the global list of known game versions (e.g., in `KerbalSpaceProgram.KnownVersions` for KSP1), which it uses to find the latest real game version with which a mod is compatible. It's loaded in ascending order and is supposed to stay that way.
The compatible versions popup currently changes the sorting of this global list when it loads! So the next time you refresh the mod list, the versions are in descending order, so wrong versions are pulled out by the max game verison column.
- Now the compatible versions dialog no …

Fix compatible popup messing with max game version column

---

Core/Registry/RegistryManager.cs

Currently the export modpack option includes every installed module except DLC (and DarkKAN mods, but the less said of them the better).
By default, auto-installed mods are included, meaning that when you install that modpack, they won't be marked as auto-installed. We have received feedback expressing an interest in splitting these out so the auto-installed flag can be preserved.
Now auto-installed mods are put in the Ignored group by default. Users who wish to preserve the auto-installed flag can export the default modpack as-is, and the same mods will be pulled in as dependencies when the modpack is installed. Users who wish to add some of those mods to the modpack may do so by moving them to another group as usual.
I think this was something I considered doing originally, but I wasn't …

Put auto-installed mods in ignored modpack group by default

---

GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.Designer.cs
GUI/Controls/ModInfo.cs
GUI/Controls/TagsLabelsLinkList.cs
GUI/Properties/Resources.resx

The mod list header context menu provides the ability to hide all mods with particular tags, but it's easy to forget that you've done this afterwards. When people ask why some mods are missing in the support channels, it takes me a long time to remember that this feature exists.
- Now if you hide a tag, a link to it will show up under the mod list to ensure that you can tell what happened (and that a screenshot will reveal it to anyone trying to provide support).
- Similarly, if you use a label to hide mods, a link to that label will show up in the same list.

Add links to hidden tags and labels below mod list

---

GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ManageMods.resx
GUI/Controls/ModInfo.Designer.cs
GUI/Controls/ModInfo.cs
GUI/Controls/TagsLabelsLinkList.cs

#3979 added visible links so you can tell when you've hidden tags. Clicking them applies the filter for `tag:tagname`, which lets you see which mods are hidden, but doesn't help much for un-hiding them.
It would be more useful to be able to access the option to un-hide them easily.
Clicking a hidden tag link now opens the context menu where you can hide and unhide them, excluding the column options. Clicking a hidden label still searches it, because you need to be able to remove mods from it one by one. The tooltip for tag links is changed to reflect the fact that it's not searching anymore.

Show tag-hiding menu on clicking hidden tag

---

Core/GameInstanceManager.cs
Core/Games/KerbalSpaceProgram2.cs
Core/Registry/Registry.cs

Two problems came up during KSP-CKAN/KSP2-NetKAN#125:
- The meta tester always fails to install KSP2 mods that aren't compatible with the latest game version
- `ckan show --with-versions` lists multiple copies of the same version of a mod when the meta tester runs it
Initially I thought the former was caused by how the meta tester's Python code handles game version build numbers, but KSP-CKAN/xKAN-meta_testing#97 didn't fix it.
- Currently a fake KSP2 instance is always treated as the current game version, because the game version isn't saved in a way that `KerbalSpaceProgram2.DetectVersion` can retrieve. That function uses `FileVersionInfo.GetVersionInfo(path).ProductVersion` to examine the game's executable, and we can't generate an executable on the fly. The game version we pass on the …

Save and load game version for fake KSP2 instances

---

Core/ModuleInstaller.cs

If you have any DLCs installed in a KSP1 instance, the Audit Recommendations option doesn't work.
As of #3892, `ModuleInstaller.FindRecommendations` uses `RelationshipResolver` to get the recommendations and suggestions for the full dependency tree of a given group of mods. (Previously it had a lot of its own duplicative logic that has been refactored to use the shared logic in `RelationshipResolver`.)
Audit Recommendations passes the list of installed modules, which includes DLCs, and `RelationshipResolver` throws `ModuleIsDLCKraken` when it finds a DLC in its input.
Now `ModuleInstaller.FindRecommendations` filters DLCs out of the sequence of modules it passes to `RelationshipResolver`, so the exception is no longer thrown and Audit Recommendations works again.
We could have had …

Fix Audit Recommendations option

---

Cmdline/ConsoleUser.cs
ConsoleUI/Toolkit/ConsoleScreen.cs
Core/ModuleInstaller.cs
Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Properties/Resources.resx
Core/Registry/Registry.cs
Core/Repositories/RepositoryDataManager.cs
Core/User.cs
GUI/Controls/EditModSearch.cs
GUI/Controls/EditModSearches.cs
GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Controls/Wait.cs
GUI/Dialogs/SelectionDialog.cs
GUI/Dialogs/YesNoDialog.cs
GUI/GUIUser.cs
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/MainAutoUpdate.cs
GUI/Main/MainDialogs.cs
GUI/Main/MainDownload.cs
GUI/Main/MainExport.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs
GUI/Main/MainRepo.cs
GUI/Main/MainWait.cs
GUI/Properties/Resources.resx
Netkan/ConsoleUser.cs
Tests/CapturingUser.cs

- When a download of a module with multiple explicit download URLs or an implicit archive.org fallback URL fails, the downloader does not begin downloading that mod's next URL (but it does start the next queued download from the host that just failed). When the last download succeeds or fails, the installation does not proceed if there were any failed downloads.
- If you use the Preferred Hosts window to make spacedock.info lower priority than `<ALL OTHER HOSTS>`, downloads of redistributable mods will succeed but not be stored to the cache, so the installation will fail
- Related to this, `archive.org` isn't shown in the host list of that window for KSP2, even though there are redistributable mods archived there. This means that this host can't be prioritized above or below `<ALL OTHER …

Installation message usability improvements

---

Core/Games/KerbalSpaceProgram2.cs

There is no official, unique KSP2 build for Linux. We can remove this reference to and assumption about the unsupported Unix platform.
This also has the positive indirect effect of treating the executable paths for Linux and Windows as identical (which appears to be the case for Proton installations).

Detect and use Windows KSP2 executable on Linux

---

Netkan/Model/Metadata.cs

- Multi-hosted mods on both GitHub and SpaceDock can have inflation errors saying
`ksp_version mixed with ksp_version_(min|max)`. KSP-CKAN/KSP2-NetKAN#125 had to use overrides to get around this:
```yaml
x_netkan_override:
- version: 1.2.3
override:
ksp_version_max: 0.1.2
```
- Between KSP-CKAN/KSP2-NetKAN#125 and KSP-CKAN/KSP2-NetKAN#127, `Inputbinder` had a `download` property containing an array with one element. This is odd and unnecessary.
- SpaceDock adds a `ksp_version` / `ksp_version_max` based on the game version the uploader selects that isn't available on GitHub, so the GitHub branch of the netkan inflates with just `ksp_version_min`, while the SpaceDock branch has `ksp_version`, and the two branches are merged just by combining their JSON properties, which creates inconsistent …

Resolve compatibility conflicts after multi-host merge

---

GUI/URLHandlers.cs

In [a recent forum thread](https://forum.kerbalspaceprogram.com/topic/222869-is-ckan-safe/), a user reported receiving the URL handler registration prompt:
> CKAN requires permission to add a handler for ckan:// URLs.
> 
> Do you want to allow CKAN to do this? If you click no you won't see this message again.
And after clicking Yes, the admin user error appeared in a new cmd window, while the main GUI process continued normally.
The URL handler registration intentionally runs `ckan.exe gui registerUrl` as administrator, which trips the admin user check.
Now the elevated command line to register the handler includes `--asroot` to bypass the admin check. This should allow it to finish normally.

Suppress admin user check for URL handler registration

---

Netkan/Transformers/SpaceWarpInfoTransformer.cs

QuestariaAerospace had an inflation error in its previous release, see KSP-CKAN/KSP2-NetKAN#144:
```
1780 [1] FATAL CKAN.NetKAN.Program (null) - Object reference not set to an instance of an object.
1847 [1] FATAL CKAN.NetKAN.Program (null) -    at CKAN.NetKAN.Transformers.SpaceWarpInfoTransformer.<Transform>d__3.MoveNext()
at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at CKAN.NetKAN.Transformers.NetkanTransformer.Transform(Metadata metadata, TransformOptions opts)
at CKAN.NetKAN.Processors.Inflator.<>c__DisplayClass1_0.<Inflate>b__0(Metadata netkan)
at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
at …
```

Fix null reference exception in swinfo transformer

---

Core/Net/NetModuleCache.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Controls/ModInfoTabs/Contents.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Main/Main.cs
GUI/Main/MainDownload.cs

The Contents tab refreshes and shows the mod contents if you download a mod via the Download button or right click menu, but not if it is downloaded during installation.
Refreshing cache-related state (including the Contents tab) is handled (duplicatively) at the places where GUI stores or purges a mod, but when you install an uncached mod, it is downloaded and stored by `ModuleInstaller`, so GUI doesn't react.
This is a brittle approach because it has a many-to-many structure, where each place that deals with the cache must also handle all of the secondary consequences itself.
- Now `NetModuleCache` has `ModStored` and `ModPurged` events that it fires whenever mods are stored or purged, including during mod installation. If **all** mods are purged, `ModPurged`'s module parameter will be …

Refactor Contents tab refreshing

---

Core/Extensions/DictionaryExtensions.cs
Core/Games/KerbalSpaceProgram/DLC/StandardDlcDetectorBase.cs

If you disable a DLC in Steam:
... then CKAN throws an exception when it tries to refresh:
> Scanning for DLCs and manually installed modules...
> Object reference not set to an instance of an object.
> Repository update failed!
Steam apparently deletes the _files_ for that DLC but leaves behind all the folders:
This eventually makes our `DictionaryEquals` extension try to call `null.Equals()`:
```
at CKAN.Extensions.DictionaryExtensions.<>c__DisplayClass0_0`2.<DictionaryEquals>b__1(K k)
at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
at CKAN.Registry.SetDlcs(Dictionary`2 dlcs)
at CKAN.RegistryManager.ScanUnmanagedFiles()
at CKAN.GUI.Main.UpdateRepo(Object sender, …
```

Fix crash with DLC disabled by Steam

---

Cmdline/Action/Install.cs
Core/Registry/IRegistryQuerier.cs
GUI/Main/Main.cs
GUI/Main/MainInstall.cs
GUI/Main/MainWait.cs

@JonnyOThan has been working with .ckan files for mods that aren't indexed yet and finding lots of bugs:
- `ckan install -c` currently doesn't work. If you use it with a module that's in one of your metadata repos, it'll try to install the version from the repo, and for mods that aren't there, it reports that it can't find the mod even though it's right there in the file.
- If you install from a .ckan file in GUI and it depends on an identifier that doesn't exist, you end up stuck with an hourglass cursor on the mod list with an error in the status bar, and some parts of the app window are disabled.
- If you install from a .ckan file in GUI and it fails, clicking Retry takes you to the change set tab, but it's empty, and trying to install again crashes.
- If you install some modules from …

Fixes for installing .ckan files and DarkKAN mods

---

Core/Registry/Registry.cs

In #3934, we sorted the providing mods prompt by download count to make it easier for users to find the mods that they're most likely to want.
EnvironmentalVisualEnhancements recommends rather than depends on its config module, so when you install it, instead of the providing mods prompt, it uses the recommendations prompt, which is sorted by the related mod column and otherwise tries to reflect the ordering from the mods' relationships, but doesn't do any particular sorting within a group of mods satisfying a virtual module recommendation:
Now `Registry.LatestAvailableWithProvides`, which is used to satisfy virtual module recommendations, sorts its returned list by download count, which puts the most commonly used EVE configs at the top:
@JonnyOThan, does that list look right to you? I …

Sort mods satisfying the same recommendation by download count

---

Cmdline/Action/Upgrade.cs
Core/Configuration/IConfiguration.cs
Core/Configuration/JsonConfiguration.cs
Core/Configuration/Win32RegistryConfiguration.cs
GUI/Dialogs/SettingsDialog.cs
GUI/Main/MainAutoUpdate.cs
GUI/Model/GUIConfiguration.cs
Tests/Core/Configuration/FakeConfiguration.cs

The dev builds prompt from #3997 shows up the first time you open any game instance.
Since the prompt itself is part of GUI and most of the autoupdate prompting logic is governed by properties of the form `GUIConfiguration.*NoNag`, I created `GUIConfiguration.DevBuildsNoNag` to store whether the prompt had been shown. But this is stored per game instance, which means it will be false the first time you open any game instance, so the prompt will appear again.
- Now `IConfiguration.DevBuilds` is a nullable bool, which means it can be true, false, or null (the default if it's absent from `config.json`)
- When this value is used, null is treated as equivalent to false because we want stable releases to be the default
- Now `GUIConfiguration.DevBuildsNoNag` is removed and replaced by …

Remove duplicate dev build prompts

---

build.cake

The metadata tester crashed on KSP-CKAN/NetKAN#9917 despite its changes being simple and trivially correct:
https://github.com/KSP-CKAN/NetKAN/actions/runs/7749494610/job/21134148266
`FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'CKAN.SteamLibrary+<>c__DisplayClass0_0:txtParser' (0) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.`
As of #4010, we now reference `ValveKeyValue`, which is a `netstandard2.0` library. Repacking it requires resolving a reference to netstandard.dll, which I accomplished by adding `_build/lib/nuget/netstandard.library/2.0.0/build/netstandard2.0/ref/` to ILRepack's Libs argument, since a copy of netstandard.dll is placed there …

Repack netstandard facade in ckan.exe

---

Netkan/Validators/ObeysCKANSchemaValidator.cs
Netkan/Validators/RelationshipsValidator.cs

This metadata fragment:
```yaml
depends:
- BDArmoryForRunwayProject
```
... produces an obscure inflation error:
```
362 [1] FATAL CKAN.NetKAN.Program (null) - Specified cast is not valid.
```
This example is from KSP-CKAN/NetKAN#9909.
An exception is thrown on this line of `RelationshipsValidator`:
```csharp
foreach (JObject rel in json[relName].Cast<JObject>())
```
There are four main ways to loop over the children of a JSON array property:
- `.Cast<T>()`, which is a generic Linq function and throws an exception if any element isn't a `T` ("BDArmoryForRunwayProject" is a `JValue`, not a `JObject`)
- `.OfType<T>()`, which is a generic Linq function and ignores any element that isn't a `T` instead of throwing
- `.Children<T>()`, which is a `Newtonsoft.Json` function and equivalent to …

Improve netkan relationship error message

---

Netkan/Validators/RelationshipsValidator.cs

#4020 replaced the very unclear "Specified cast is not valid" message with a proper schema validation error. On further consideration, the schema error still isn't clear enough, because it doesn't explain _why_ the array item is not valid.
```
1717 [1] FATAL CKAN.NetKAN.Program (null) - Schema validation failed: #/depends[0]: ArrayItemNotValid, #/depends[1]: ArrayItemNotValid, #/depends[2]: ArrayItemNotValid, #/supports[0]: ArrayItemNotValid, #/supports[1]: ArrayItemNotValid
```
Now the `RelationshipsValidator` explicitly checks the type of the elements of relationships arrays and prints a message that hopefully will be clearer:
```
$ netkan.exe NetKAN/kOS-KerbalEngineer.netkan
507 [1] FATAL CKAN.NetKAN.Program (null) - depends elements should be Object, found String: …
```

Further improve netkan relationship error message

---

Core/ModuleInstaller.cs
Core/Registry/Registry.cs

If you manually install a module that contains a plugin that matches the "main" module's identifier but which has been separated into a separate module (e.g., `NearFutureSolar` and `NearFutureSolar-Core`, which installs `NearFutureSolar.dll`), the main module will be detected as manually installed and can be upgraded to have CKAN take control of it, and the `Core` module will be installed automatically as a dependency, but the `Core` module's DLL will be deleted during the installation and missing afterwards.
Workaround: A right-click reinstall of the `Core` module restores the DLL.
I found two specific bugs related to this:
- `Registry.installed_dlls` is only supposed to contain files that aren't registered to any installed module, but if you have CKAN take ownership of any of these …

Only auto-delete manually installed DLLs if also replacing them

---

Core/Meta.cs
Core/Repositories/RepositoryData.cs
Core/Repositories/RepositoryDataManager.cs
Core/Types/CkanModule.cs
Core/Types/ModuleInstallDescriptor.cs
Core/VersionFormat.cs
GUI/Dialogs/NewUpdateDialog.Designer.cs
GUI/Dialogs/NewUpdateDialog.resx
GUI/Dialogs/SettingsDialog.cs
GUI/Main/Main.cs
GUI/Main/MainAutoUpdate.cs
GUI/Main/MainRepo.cs
GUI/Properties/Resources.resx
GlobalAssemblyInfo.cs

- The `CkanModule.spec_version` property allows us to handle backwards incompatible changes to metadata; if it is greater than your client version for a module, then that module is hidden. When this happens, it is not apparent to the user, and users sometimes ask us or mod authors why a mod version is missing.
- If you configure CKAN to check for automated updates, you'll see the popup that shows the changelog, but if you update only via the button in the settings, you never get to see the changelog
- Now if you update your repositories and they contain one or more modules with an unsupported spec version, we print a message along those lines to the log, check for a client update, and prompt the user to update if one is found:
- Now that popup opens centered on the main window instead of …

Prompt for client upgrade when newer spec is found

---

GUI/Controls/ManageMods.cs
GUI/Main/Main.cs

`Main.LaunchGame` implicitly assumes its string argument will not be null.
`ManageMods.LaunchGameToolStripMenuItem_Click` passes `menuItem?.Tag as string`, which implicitly assumes the menu item's `Tag` will always be set.
The tag is set in `LaunchGameToolStripMenuItem_MouseHover`, which is executed when you hover the button, but _after a short delay_. If you click before the delay is over, the tag is null.
Now `Main.LaunchGame` allows a null argument and defaults to the first configured command line.

Fix exception on clicking Play before dropdown appears

---

Core/Net/Net.cs
Core/Properties/Resources.resx
Core/Repositories/RepositoryData.cs
Core/Repositories/RepositoryDataManager.cs
Core/Types/Kraken.cs
GUI/Dialogs/DownloadsFailedDialog.Designer.cs

- If you set up a custom repo of someone's ZIP on a server and then it is later removed, the 404 error will be reported in the message log instead of the Failed Downloads popup:
- If you set up a custom repo that points to a file that isn't a ZIP or .tar.gz, the error appears in the message log instead of the Failed Downloads popup:
- If a previously working repo is removed, `Net.CurrentETag` throws an exception when we try to get the latest ETag
- If a downloaded repo file is in the wrong format, `UnsupportedKraken` is thrown when `RepositoryDataManager.Update` calls `RepositoryData.FromDownload`
The Failed Downloads popup depends on `DownloadErrorsKraken`, which isn't thrown in either case.
- Now both classes of errors are redirected into `DownloadErrorsKraken` exceptions, so they show …

Show repo ETag and parsing errors in Failed Downloads

---

GUI/Controls/Changeset.Designer.cs
GUI/Controls/Changeset.cs
GUI/Controls/Changeset.resx
GUI/Controls/ManageMods.cs
GUI/Dialogs/YesNoDialog.Designer.cs
GUI/Dialogs/YesNoDialog.cs
GUI/Localization/de-DE/Changeset.de-DE.resx
GUI/Localization/fr-FR/Changeset.fr-FR.resx
GUI/Localization/it-IT/Changeset.it-IT.resx
GUI/Localization/ja-JP/Changeset.ja-JP.resx
GUI/Localization/ko-KR/Changeset.ko-KR.resx
GUI/Localization/nl-NL/Changeset.nl-NL.resx
GUI/Localization/pl-PL/Changeset.pl-PL.resx
GUI/Localization/pt-BR/Changeset.pt-BR.resx
GUI/Localization/ru-RU/Changeset.ru-RU.resx
GUI/Localization/tr-TR/Changeset.tr-TR.resx
GUI/Localization/zh-CN/Changeset.zh-CN.resx
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/MainChangeset.cs
GUI/Model/ModChange.cs
GUI/Properties/Resources.resx

The Changeset tab is shown when you choose to install, upgrade, or uninstall mods and then click Apply. If there is something in the list that you don't want, the only way to fix it is to click Back, then scroll or search through the mod list to find the affected mods, then make whatever change would undo the change, then click Apply again. This is cumbersome, especially for auto-installed mods, since the user may not know the full details of how to mark them as not auto-installed.
- Now the Changeset tab list has a "Skip?" column at the right
- Changes that would be simple to remove from the changeset (independent from other changes) have an "X" icon in this column with a tooltip like "Don't Install MyMod 1.0.0"
- Changes that are not simple to remove (other changes depend on them) have …

Ability to clear auto-installed flag from changeset tab

---

Core/CKAN-core.csproj
Core/Games/KerbalSpaceProgram2.cs

Based on how KSP1 works, if/when KSP2 is released for Linux someday, it will have a Linux executable called `KSP2.x86_64` instead of a Windows executable called `KSP2_x64.exe`.
Since KSP2 has no equivalent of KSP1's `buildID.txt` or `readme.txt` files, we currently get the game version from the Windows executable's assembly properties. This will no longer be viable once there is a Linux release, and so far there is no sign that the KSP2 devs have heard our pleas to create a `buildID.txt` equivalent.
Now we get the KSP2 game version by using Mono.Cecil to retrieve the `VersionID.VERSION_TEXT` string constant from `<GameRoot>/KSP2_x64_Data/Managed/Assembly-CSharp.dll` (the main assembly for the game). If this doesn't work, we fall back to the previous method of looking for the EXE's …

Get KSP2 version from game assembly

---

Core/Relationships/RelationshipResolver.cs
GUI/Controls/ManageMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Main/MainChangeset.cs
GUI/Model/GUIMod.cs

- If you choose to upgrade an AD mod and then use the install-all checkbox to clear the changeset, the AD upgrade will only be fully removed if the mod matches the current search filters (and is therefore visible or could be made visible with scrolling). Otherwise the row's checkbox will be cleared but the install of the mod will remain in the changeset.
- If you choose to upgrade an AD mod to have CKAN take ownership of it, the changeset removal icon from #4033 will appear but not work for that entry.
- If you use the Versions tab to replace one version of a mod with a different version, the changeset tab will say "Currently installed" for the new instead of the old version, and the changeset removal icon from #4033 won't appear for that entry.
- The install-all checkbox at the upper …

Properly clear AD upgrades from changeset

---

.github/workflows/release.yml
AutoUpdate/CKAN-autoupdate.csproj
Core/CKAN-core.csproj
Core/Extensions/EnumerableExtensions.cs
Core/Registry/IRegistryQuerier.cs
Core/Relationships/SanityChecker.cs
Core/Types/CkanModule.cs
Core/Types/License.cs
GUI/CKAN-GUI.csproj
README.md
Tests/Core/Registry/CompatibilitySorter.cs
build.cake

@cheese3660 and @jan-bures have expressed an interest in using some functionality from CKAN in a future update of the KSP2 mod [SpaceWarp](https://github.com/SpaceWarpDev/SpaceWarp). Currently this would require them to compile it themselves, which is not very convenient or maintainable.
This dovetails with a longstanding aspiration to make CKAN's core DLL available on Nuget for mods.
- Now the core DLL has a third target framework, `netstandard2.0`, because it is better for mods
- Now the core DLL has properties to autogenerate a `.nupkg` file containing DLLs for `net48`, `net7.0`, and `netstandard2.0`
- Now the Cake build script is updated to perform a separate all-platforms build for the core DLL on Linux, which is required for the `.nupkg` file to be created (Windows already handles …

Build nuget package, support netstandard2.0 build

---

Core/Types/CkanModule.cs

archive.org only allows certain characters in an upload's "bucket name", and KSP-CKAN/NetKAN-Infra#328 updated NetKAN-Infra to remove illegal characters (other than colon and space, which are already handled specially) before uploading so we could get a mod with `&` in its version string out of the bot's queues.
- `CkanModule.InternetArchiveDownload` now removes the same characters as in the above PR, so it will find the correct URL for affected mods
- The redistributable license check in NetKAN-Infra (correctly) treats a mod with multiple licenses as redistributable if _any_ of those licenses is redistributable, but the client required _all_ licenses to be redistributable. Now the client is updated to use "any" logic instead.

Use fully sanitized archive.org bucket names

---

Core/Games/KerbalSpaceProgram.cs

Originally, CKAN looked for `buildID.txt` and `buildID64.txt` to identify KSP1 instances. For KSP2, no equivalent file exists (but luckily we won't need it anymore, see #4034), so we look for the game executable instead.
It was fairly common for confused KSP1 users to ask how to add an instance, because they didn't know what `buildID.txt` was and so clicking it was a non-obvious action. Meanwhile, nobody seemed the least bit confused by choosing the KSP2 executable. So in #3964 we changed the prompting for KSP1 to also use the executable, which seems to have succeeded in improving usability so far.
Later, a Linux user submitted #3984 to _run_ the KSP2 Windows executable from Linux, which apparently can work thanks to Proton, which somehow can reach out from inside however Steam installs …

Support Windows KSP1 instances on Linux

---

Core/Extensions/EnumerableExtensions.cs
Core/ModuleInstaller.cs
Core/Relationships/RelationshipResolver.cs
Core/Types/CkanModule.cs
GUI/Controls/ModInfoTabs/Versions.cs

- The Versions tab sometimes has a delay when loading; it might sit for several seconds before starting to set the background colors of compatible rows to green.
- An extreme consequence of this can be observed by opening the Versions tab before typing a search for a mod (e.g., "ksp community fixes"): the whole app appears to hang while waiting for the Versions tab to update.
We appear to have a case of [over-parallelization](https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/potential-pitfalls-with-plinq#avoid-over-parallelization). `RelationshipResolver.ModList` is parallel (for speeding up very large changesets), and `Versions.checkInstallable` _calls it_ in parallel (via `ModuleInstaller.CanInstall`; that's what feeds the `ToList` call highlighted above).
When …

De-over-parallelize Versions tab

---

GUI/Util.cs

Windows 11 recently introduced a new virtual terminal to replace the Windows console. It behaves much more like standard Unix terminals:
- <https://learn.microsoft.com/en-us/windows/console/classic-vs-vt>
- If you open a console (old style) in Windows and then run ckan.exe without the `--show-console` flag (and none of the CmdLine commands like `list` or `install`), your console windows closes. This is not typical behavior for a command that you launch from a console and can be very surprising.
- If you double click ckan.exe in Windows 11, the virtual terminal stays open the entire time you're using the GUI
Since ckan.exe is both a console application and a GUI application, Windows always automatically opens a console for it at launch. This is not desirable when running in GUI mode, so …

Use better console hiding API

---

.gitignore
Core/Extensions/IOExtensions.cs
Core/Net/ResumingWebClient.cs

Sometimes CKAN is able to connect to a host, but the download times out without sending any data (it seems like SpaceDock does this every few weeks). Since our system for progress updates depends on traffic received, this means that no progress updates are sent. And since these progress updates drive the progress bars on the progress tab, and since they are ignored unless 3 seconds have already passed since the download group started, I'm pretty sure it's possible for such a frozen download to never show up as an empty progress bar.
- Now a frozen download will trigger progress updates every 5 seconds, even if no data is coming through. This will ensure that progress bars will appear for such downloads in the progress tab, so the user can see what's happening.
- A couple of stray folders …

Trigger progress updates for frozen downloads

---

GUI/Controls/ManageMods.cs
GUI/Model/ModList.cs

1. Set up a repo with an invalid URL as your only repo
2. Close CKAN
3. Start CKAN
4. The failed downloads window will appear. Click abort.
5. Now you have an empty mod list
(The above steps are just one specific way that I've found to get to this point. It may or may not be how other users might get here, but the below problem happens regardless of the specific path taken.)
6. Click Update all even though there are no mods to update
7. An NRE is thrown
`ManageMods.mainModList.full_list_of_mod_rows` is null when the grid is empty, and `ManageMods.MarkAllUpdates` accesses its `.Values` property.
- Now `ManageMods.mainModList.full_list_of_mod_rows` is set to an empty dictionary on initialization, so it can always be accessed safely, and clicking the button with an empty list will do …

Fix NRE on trying to update all when there's nothing to update

---

ConsoleUI/InstallScreen.cs
Core/Extensions/IOExtensions.cs
Core/ModuleInstaller.cs
Core/Registry/Registry.cs
Core/Repositories/ProgressFilesOffsetsToPercent.cs
Core/Repositories/ProgressScalePercentsByFileSize.cs
Tests/CmdLine/UpgradeTests.cs
Tests/Core/ModuleInstallerTests.cs
Tests/Core/Registry/Registry.cs
Tests/Core/Registry/RegistryManager.cs
Tests/Core/Relationships/RelationshipResolver.cs
Tests/GUI/Model/GUIMod.cs
Tests/GUI/Model/ModList.cs

- There are no UI updates while a mod is being installed, which can take a long time for a very large mod and may make it look like the GUI is frozen
- The progress bar for installing mods treats tiny mods and huge mods as an equal percentage of the install, which makes it useless for estimating how complete the install actually is
- The mod installation progress bar counts up from 0% to 60% for the actual unzipping, and then the remaining 40% reflects saving the registry (which became a lot faster in #3904) and completing the transaction (which is basically instantaneous), which likewise makes the progress bar less reflective of overall completion
- Now we generate at least one progress update per file being unzipped, and another progress update every 200 milliseconds after that for …

Proportional, granular progress updates for installing

---

Core/Repositories/RepositoryData.cs
GUI/Main/Main.cs
GUI/Main/MainAutoUpdate.cs

The new "Repositories updated, but found modules that require a new version of CKAN. Checking for updates..." message appears on every update, regardless of whether your client is outdated.
In #4026 we treated an `ArchiveEntry` tuple as indicating an unsupported spec version if its first item was null, but this is also expected for `download_counts.json`, `builds.json`, and `repositories.json`. The correct indicator is when **all** of the first four items are null.
Now we check whether all of the first four items in the tuple are null.

Fix outdated client message when up to date

---

Cmdline/Action/Upgrade.cs
Core/HelpURLs.cs
GUI/Main/MainAutoUpdate.cs

Before #3997's dev builds functionality gets released, we need to do something about Windows' malware scanner's high false positive rate. It has always been a problem (in that it falsely flags ckan.exe as malware), but for full releases we (or interested users) can submit it for manual review and whitelisting. Dev builds are generated too frequently for that too be feasible.
- A wiki has been created to explain how to configure Windows' malware scanner to stop raising these false positives (or how to switch back to the full releases if you want to keep using the malware scanner):
<https://github.com/KSP-CKAN/CKAN/wiki/Using-dev-builds-on-Windows>
- Now when a Windows user clicks "Use dev builds" in the popup from #3997 (or runs `ckan upgrade ckan --dev-build` for the first time), we …

Launch wiki when Windows users select dev updates

---

ConsoleUI/ModListScreen.cs
ConsoleUI/Properties/Resources.fr-FR.resx
ConsoleUI/Properties/Resources.it-IT.resx
ConsoleUI/Properties/Resources.pl-PL.resx
ConsoleUI/Properties/Resources.resx
ConsoleUI/Properties/Resources.ru-RU.resx

We track the download counts for mods, but currently they're only shown in GUI. A Mac user has requested to be able to see them in ConsoleUI.
Now a Downloads column is added at the right side of the mod list, containing the download counts. The column header translations are copied from the Downloads column in GUI.
Fixes #4047.

Add downloads column for ConsoleUI

---

ConsoleUI/ModListScreen.cs
ConsoleUI/Properties/Resources.resx
ConsoleUI/Toolkit/ConsolePopupMenu.cs
ConsoleUI/Toolkit/Keys.cs
Core/GameInstance.cs
Core/Properties/Resources.fr-FR.resx
Core/Properties/Resources.it-IT.resx
Core/Properties/Resources.pl-PL.resx
Core/Properties/Resources.resx
Core/Properties/Resources.ru-RU.resx
Core/Properties/Resources.zh-CN.resx
GUI/Main/Main.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.fr-FR.resx
GUI/Properties/Resources.it-IT.resx
GUI/Properties/Resources.ja-JP.resx
GUI/Properties/Resources.ko-KR.resx
GUI/Properties/Resources.pl-PL.resx
GUI/Properties/Resources.pt-BR.resx
GUI/Properties/Resources.resx
GUI/Properties/Resources.ru-RU.resx
GUI/Properties/Resources.zh-CN.resx

Currently only GUI can launch the game. A user has requested to be able to do this for ConsoleUI as well.
Now the ConsoleUI main menu has a new "Play game" submenu that lists all the default game command lines from #4010:
The first item in this list shows a "Ctrl+P" hotkey that you can press outside of the menu to launch the game in one step.
Currently neither the specific command lines nor the one to use for the hotkey are configurable, in line with ConsoleUI generally being streamlined. If someone needs more complicated functionality, we can return to this.
Fixes #3534.

Play game option for ConsoleUI

---

Cmdline/Action/List.cs
Cmdline/Action/Upgrade.cs
ConsoleUI/InstallScreen.cs
ConsoleUI/ModInfoScreen.cs
ConsoleUI/ModListScreen.cs
Core/Registry/IRegistryQuerier.cs
Core/Registry/InstalledModule.cs
GUI/Controls/Changeset.cs
GUI/Controls/ChooseRecommendedMods.Designer.cs
GUI/Controls/ManageMods.cs
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Model/GUIMod.cs
GUI/Model/ModList.cs
Tests/Core/Registry/Registry.cs
Tests/GUI/Model/GUIMod.cs
Tests/GUI/Model/ModList.cs
build.cake

Users supposedly sometimes install a mod in CKAN, then delete the files manually in GameData, then install depending mods in CKAN and complain that they don't work. We need to detect missing files and guide the user into restoring them.
It was suggested to create some kind of "clean-up" button, but I don't think users who expect to be able to delete CKAN-installed mods manually without causing problems would know to use something like that. We need something automatic and pro-active.
While working on the above, I discovered that (as expected) the major data model refactoring in #4023 broke a lot of things:
- Checking checkboxes on Mono wasn't updating the changeset or enabling the Apply button
- The changeset always displays mod info
- Metadata changes were no longer causing the upgrade …

Treat mods with missing files as upgradeable/reinstallable

---

Netkan/QueueAppender.cs

Currently, inflation warnings for multi-hosted modules are duplicated.
Now we filter duplicates, so each message will only appear once. This should produce a nice cascade of de-duplication in Discord and the status page.

Omit duplicate inflation warnings in queue

---

doc/rpm-repo.md

added zypper command, tested and works just like normal
im not really good at markdown so feel free to make changes

Add OpenSUSE zypper command for rpm repo

---

Core/Net/NetFileCache.cs
Core/Repositories/Repository.cs
Core/Repositories/RepositoryDataManager.cs
GUI/Dialogs/SettingsDialog.cs

A Discord user reported an exception at startup:
```
5393 [1] ERROR CKAN.GUI.Main (null) - Object reference not set to an instance of an object.
at CKAN.RepositoryDataManager.<>c__DisplayClass7_0.<Update>b__1(Repository r)
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at CKAN.RepositoryDataManager.Update(Repository[] repos, IGame game, Boolean skipETags, NetAsyncDownloader downloader, IUser user)
at CKAN.GUI.Main.UpdateRepo(Object sender, DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
at …
```

Tolerate null repo URLs

---

Core/Repositories/RepositoryDataManager.cs

The Discord user from #4077 gave us more information about that exception. Eventually we discovered that `%LOCALAPPDATA%\CKAN\repos\etags.json` was corrupted, containing only 275 null bytes. Since it does not contain a JSON object, such a string deserializes to `null`, which caused that NRE.
Now when we deserialize `etags.json`, we fall back to an empty `Dictionary` if it's null, so an NRE won't be thrown.

Recover from corrupted etags.json

---

Dockerfile.metadata
Dockerfile.netkan

There are a number of changes within 24.04 which upset the apple cart, for now 22.04 is still supported for another year, so we can pin while we give ourselves some time to update things.

Ubuntu 24.04 breaks build

---

ConsoleUI/AuthTokenListScreen.cs
ConsoleUI/DeleteDirectoriesScreen.cs
ConsoleUI/DependencyScreen.cs
ConsoleUI/ExitScreen.cs
ConsoleUI/GameInstanceListScreen.cs
ConsoleUI/GameInstanceScreen.cs
ConsoleUI/InstallFiltersScreen.cs
ConsoleUI/InstallScreen.cs
ConsoleUI/ModInfoScreen.cs
ConsoleUI/ModListScreen.cs
ConsoleUI/ProgressScreen.cs
ConsoleUI/RepoScreen.cs
Core/Repositories/RepositoryData.cs

In ConsoleUI's recommendations screen for RP-1, <kbd>Ctrl+A</kbd>, <kbd>F9</kbd> throws an exception:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.             │
at CKAN.RelationshipResolver.AddModulesToInstall(CkanModule[] modules)
at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, RegistryManager registry_manager, HashSet`1& possibleConfigOnlyDirs, IDownloader downloader, Boolean ConfirmPrompt)
at CKAN.ConsoleUI.InstallScreen.Run(ConsoleTheme theme, Action`1 process)
at CKAN.ConsoleUI.ModListScreen.ApplyChanges(ConsoleTheme theme)
at CKAN.ConsoleUI.ModListScreen.<>c__DisplayClass0_0.<.ctor>b__27(Object sender, ConsoleTheme theme)
at …
```

Conflicting recommendations check for ConsoleUI

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml
.github/workflows/smoke.yml
.github/workflows/test.yml
build.cake

This is a complete refactor and overhaul of our actions, and either updating or changing any outdated actions we have used within our workflows.
The build workflow is now a self contained, and runs on master or via 'workflow_call'. Making a single source of truth for building CKAN/NetKAN.
Note: The build on master is intentional, I expect there we can do a small amount of work to enable [dotnet caching](https://github.com/actions/setup-dotnet?tab=readme-ov-file#caching-nuget-packages). For a cache to be available on branches, it *must* have been previously built on the default branch.
There is a new test file that calls build first. It is unnecessary to build inside the Mono containers, as we still use dotnet to build. This however ensures we are keeping the same validation as before. We …

Refactor + Modernise Actions

---

.github/workflows/deploy.yml
.github/workflows/notify.yml
.github/workflows/release.yml
.github/workflows/smoke.yml
.github/workflows/test.yml

After #4082, I wanted to look for ways to set the first parameter of the Discord notification script (`success` or `failure`) without environment variables, extra pseudo-steps ("Set Success"), or side effects. Gradually I realized that writing a `git clone` command in every place we want to notify was a bit duplicative and could use better encapsulation.
- Now our own `notify.yml` action wrapper provides the nice API that `DiscordHooks/github-actions-discord-webhook` should have.
- Inputs `name` and `success` are accepted, and the `DISCORD_WEBHOOK` secret is required.
- The somewhat awkward `git clone` logic required to use it is now centralized in one place. If the optimal notification method changes in the future, we will be able to update it in just one spot.
- Now what [the action …

Consolidate Discord notification steps

---

.github/workflows/deploy.yml
.github/workflows/notify.yml
.github/workflows/release.yml
bin/ckan_merge_pr.py

#4088 seems to work, but a `git clone` command line is not the best level of abstraction for a workflow.
- Now we use `actions/checkout` instead.
- Now the merge script is updated to prevent merging if any of the checks fail or are still pending.
- Now the notify jobs in `release.yml` and `deploy.yml` depend on their respective build/test jobs to ensure that any failures will be available in `needs.*.result`.

Use checkout action for notify workflow

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/notify.yml
.github/workflows/release.yml
.github/workflows/smoke.yml
.github/workflows/test.yml

- Dev builds are currently broken because the `version.json` file from #3997 isn't being generated anymore. I assume #4082 removed this because of some sort of Python dependency issues in the newer containers, but we still need it.
- `upload-nuget` in `release.yml` was trying to download a `Release-repack-out` artifact that doesn't exist (it's just `Release-out`)
- Several steps have incorrect names ("stable" instead of "nightly", "deb" instead of "ckan.exe and netkan.exe", etc.)
- Many other steps have no names at all, and in a few places this makes the logs less clear (e.g., two consecutive steps with the same default name)
- Still other steps have names that could be slightly clearer (e.g., "Upload XYZ release asset" instead of just "Upload XYZ" in a workflow that uploads lots of stuff …

Various fixes for the refactored workflows

---

debian/ckan-cmdprompt.desktop
debian/ckan-consoleui.desktop
debian/ckan.desktop
debian/copyright

I added keywords to the `.desktop` files of CKAN, so that they can be found easier. For example when a user forgets the name of the program they just type in `Kerbal` and it shows up as well next to the game.
See: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

Linux: Improve desktop entries

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/smoke.yml
build.cake

Currently we build the Inflator image twice when pushing to `master`, once for smoke testing and again for pushing to Docker Hub. This is a small but not tiny amount of extra time and repeated work.
Another few extra seconds are spent re-downloading build dependencies that formerly were cached in the old workflows.
- The Inflator image build / push / redeploy steps are moved out of `build.cake` and into `smoke.yml` and `deploy.yml` using the standard docker actions and commands, in order to allow the steps to be separated and smoke testing inserted before push.
<https://github.com/docker/build-push-action>
- `smoke.yml` now uploads a tar of the image as an artifact after the smoke test passes
<https://docs.docker.com/build/ci/github-actions/share-image-jobs/> …

Pass image from smoke to deploy, restore build caching

---

.github/workflows/deploy.yml

#3575, KSP-CKAN/NetKAN-Infra#267, and KSP-CKAN/xKAN-meta_testing#86 made it so the main CKAN repo would run its `deploy.yml` workflow anytime we pushed changes to the Python code from the other two repos.
Currently the entire `deploy.yml` worklow is run, including some unnecessary jobs:
- Uploading `ckan.exe` and `netkan.exe` to S3
- Building the rpm/deb packages and uploading them to S3
- Rebuilding, pushing, and redeploying the Inflator
This takes a little more time and may unnecessarily mark some files as changed when they really aren't.
Now when `deploy.yml` is triggered from `NetKAN-Infra` or `xKAN-meta_testing`, we only rebuild and push the metadata tester image (and run its dependencies). This is the only job that depends on the Python code from those other repos.

Only redeploy the metadata tester on repo dispatch

---

.github/workflows/deploy.yml
build.cake

#4093 moved the Inflator's build/upload steps from Cake to workflows, but the metdata tester was left alone.
- Now the metadata tester is built and uploaded via the standard action without use of Cake, which should be more maintainable
- Now `build.cake` no longer does anything Docker-related

Migrate metadata tester build from Cake to workflow

---

Cmdline/Action/Install.cs
Core/AutoUpdate/GithubReleaseCkanUpdate.cs
Core/AutoUpdate/S3BuildCkanUpdate.cs
Core/FileIdentifier.cs
Core/Net/NetAsyncDownloader.DownloadPart.cs
Core/Net/NetAsyncDownloader.DownloadTarget.cs
Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Net/ResumingWebClient.cs
Core/Properties/Resources.resx
Core/Repositories/RepositoryData.cs
Core/Repositories/RepositoryDataManager.cs
Tests/Core/Net/NetAsyncDownloaderTests.cs

Windows users have reported "access denied" errors with `%TEMP%\CdFileMgr` during repo updates, see #3963:
Repo updates are downloaded to temp files with paths in that folder, which are then loaded back from disk. Some users have found that their anti-virus software was stopping CKAN from accessing these temp files.
Now repo updates are downloaded into a `MemoryStream` and processed directly (instead of being saved to disk, then immediately re-loaded and parsed). Since they are around 30 MiB for the biggest repo, this should work fine for everyone, including whomever or whatever is preventing us from reading the temp files.
- `NetAsyncDownloader.DownloadTarget` is now an abstract base class with child classes:
- `NetAsyncDownloader.DownloadTargetFile` - downloads to a file on disk, …

Skip temp files for repo updates

---

Cmdline/Action/Upgrade.cs
ConsoleUI/DownloadImportDialog.cs
ConsoleUI/InstallFromCkanDialog.cs
ConsoleUI/InstallScreen.cs
ConsoleUI/ModListScreen.cs
ConsoleUI/Properties/Resources.resx
ConsoleUI/Toolkit/ConsoleFileMultiSelectDialog.cs
ConsoleUI/Toolkit/ConsoleListBox.cs
Core/Types/RelationshipDescriptor.cs
Core/Utilities.cs

GUI and CmdLine have the ability to install modules from `.ckan` files, but currently ConsoleUI doesn't. This makes modpack installation inconvenient for Mac users.
Now the main ConsoleUI menu has a new "Install from .ckan file..." option. When selected, a popup appears to let the user choose `.ckan` files. The user can press <kbd>Enter</kbd> to toggle files and <kbd>F9</kbd> to accept the selections, at which point any selected files will be loaded and installed.
Fixes #4084.

Install from .ckan file option for ConsoleUI

---

CKAN.schema
Cmdline/Action/Show.cs
Cmdline/Properties/Resources.resx
ConsoleUI/ModInfoScreen.cs
ConsoleUI/Properties/Resources.resx
Core/Exporters/DelimeterSeparatedValueExporter.cs
Core/Types/ResourcesDescriptor.cs
GUI/Controls/ModInfoTabs/Metadata.cs
GUI/Properties/Resources.resx
Netkan/Sources/Github/GithubRepo.cs
Netkan/Transformers/GithubTransformer.cs
Netkan/Transformers/SpacedockTransformer.cs
Spec.md

The KSP franchise's future status has become a bit uncertain, and the forum web site has been somewhat unreliable lately.
If the forums became unavailable, GitHub Discussions would be one possible alternate place where particular mods might be discusssed.
- <https://github.com/HebaruSan/Astrogator/discussions>
- Now the spec and schema allow `resources.discussions` to be a URL
(But no `spec_version` limitations are imposed because it's easy for the old client to just ignore the new value)
- Now Netkan checks whether discussions are enabled for GitHub repos, and if so, it sets `resources.discussions` to that repo's discussions URL, just like we do for `resources.bugtracker`
- Now CmdLine, ConsoleUI, and GUI include the `resources.discussions` link in their respective mod info displays
This …

Store GitHub Discussions links and display in UIs

---

GUI/Properties/Resources.zh-CN.resx

翻译语言 简体中文 zh-CN
此更新使用了更加简洁、有效、通俗易懂的语言，并将原本有语病的语言进行了修改，使翻译更准确，避免误解。 此更新是在原有的基础上和CKAN的使用上进行的改进，所以修改不是很大。
我是手动翻译，非机翻，所以很难有翻译问题。
请管理员（作者也行）通过这个申请，谢谢。
___
Via Google Translate:
Translation language Simplified Chinese zh-CN
This update uses more concise, effective, and easy-to-understand language, and modifies the original language with grammatical errors to make the translation more accurate and avoid misunderstandings. This update is an improvement on the original basis and the use of CKAN, so the modification is not very large.
I translated manually, not by machine, so it is unlikely to have translation problems.
Please approve this application, administrator (author is also OK), thank you.

A new translation of Resources.zh-CN.resx

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/smoke.yml

Version 4 of [SignPath/github-action-submit-signing-request](https://github.com/SignPath/github-action-submit-signing-request/tree/v0.4) required the following to be addressed:
> Id of the Github Actions artifact. Must be uploaded using the actions/upload-artifact v4+ action before it can be signed. Use {{ steps.<step-id>.outputs.artifact-id }} from the preceding actions/upload-artifact action step.
We now have outputs to be able to pass that artifact id through the workflows to the signing action. Results of this working can be seen here -> https://github.com/KSP-CKAN/CKAN/actions/runs/9804590624
- Bumped `actions/cache` to v4

Update Artifact Signing

---

Core/CkanTransaction.cs

Fixes GameInstance scanning described in #3770, switching over to a default `timeout` value of `Int32.MaxValue`.

Fix default transaction timeout

---

Netkan/Validators/HarmonyValidator.cs

`CelestialHarmony` has been having spurious inflation errors for a bit over a week.
The guardrail to catch bundled copies of the Harmony DLL from #3326 checks the entire file path, not just the file name, so a folder with a name coincidentally containing the string "Harmony" will cause a false positive if it contains a DLL.
Now this check only looks for "Harmony" in the filename by starting the search at `Math.Max(0, f.LastIndexOf('/'))`.

Allow string "Harmony" in DLL parent folder names

---

Core/CKANPathUtils.cs
Core/Extensions/IOExtensions.cs

Discord user `HB Stratos` reports that sometimes, a 20+ second delay occurs at the start of mod installation:
Based on the log file provided, the delay happens between here:
https://github.com/KSP-CKAN/CKAN/blob/1b5948faa5d254ac40aa9ca522759a526f257e40/GUI/Main/MainInstall.cs#L204
and here:
https://github.com/KSP-CKAN/CKAN/blob/1b5948faa5d254ac40aa9ca522759a526f257e40/Core/CKANPathUtils.cs#L135-L139
CKAN doesn't do any significant work itself in that interval, but I suspect that there is a hibernating external HDD attached to this user's system, and `.GetDrive()`'s loop over all the drives causes that drive to be woken up, which takes several seconds. When it's finally ready, the loop continues. That loop was implemented in #3631 because there was no property or function to get the drive …

Use DriveInfo constructor to get drive from path

---

Core/Types/CkanModule.cs

During KSP-CKAN/NetKAN#10108, we noticed that `replaced_by` is a bit janky.
- We check for the `replaced_by` property in the _installed_ module, not the available module, so if users install a module and then later we add `replaced_by` to migrate them to a new identifier, they won't see the replace checkbox unless they reinstall the mod to get the new metadata.
- Compounding this, when we decide whether to prompt for reinstallation, `replaced_by` isn't checked. So the user would have to reinstall manually, which mostly defeats the purpose.
Now if you add `replaced_by` to a module, users who already have it installed will be prompted to reinstall it with the upgrade checkbox, after which they'll be prompted to replace it with the replace checkbox.
`replaced_by` could use more streamlining …

Detect changes to `replaced_by`

---

Core/Relationships/RelationshipResolver.cs
GUI/Controls/ManageMods.cs
GUI/Main/MainInstall.cs
GUI/Model/ModList.cs

After #4127 and KSP-CKAN/CKAN-meta#3277, further testing found more issues with `replaced_by`:
- Checking and unchecking the Replace checkbox doesn't update the changeset or enable/disable the apply button
- If you fix that, changesets with a replace action look weird; they have both a Replace action and a Remove action for the installed mod, and the Install action for the new mod says the reason is "User requested", which is sort of true-ish but really should explain something to do with replacing
- If you fix _that_, changesets where one mod replaces multiple installed mods fail on the progress screen
- `ManageMods.ModGrid_CellValueChanged` doesn't react to checkbox changes when the column is `ReplaceCol`
- Replace actions were being split into Remove and Install actions without a lot …

Update changeset on Replace checkbox change, other replaced_by fixes

---

Netkan/Transformers/SpacedockTransformer.cs
Netkan/Validators/CkanValidator.cs
Netkan/Validators/NetkanValidator.cs

If you omit the `license` from a netkan, you get a `license should match spec` error from the inflator, even if the mod is hosted on a server that provides license info in its API.
Many years ago, netkan validation was much more primitive (see https://github.com/KSP-CKAN/CKAN/issues/346#issuecomment-63204526). It did not inflate netkans into .ckan files, so all validation checks had to be performed with only the netkan available. A missing license in a netkan could mean a missing or invalid license in the ckan, which would make the client throw an exception. There was no way to catch that, so the field was made required, with a `x_netkan_license_ok` override for when the person reviewing the pull request had manually confirmed that the license on the server was valid.
Since then, …

Allow licenses to be absent from netkans

---

Cmdline/Action/GameInstance.cs
Core/DirectoryLink.cs
Core/GameInstanceManager.cs
Core/Games/IGame.cs
Core/Games/KerbalSpaceProgram.cs
Core/Games/KerbalSpaceProgram2.cs
Core/Utilities.cs
GUI/Dialogs/CloneGameInstanceDialog.Designer.cs
GUI/Dialogs/CloneGameInstanceDialog.cs
GUI/Dialogs/CloneGameInstanceDialog.resx
GUI/Properties/Resources.resx
Tests/Core/GameInstance.cs
Tests/Core/Utilities.cs
Tests/Data/DisposableKSP.cs

It's common for users to make extra copies of KSP1 so they can install different mod lists in each one. CKAN supports this by tracking multiple instances and providing a clone operation, which copies an existing instance to a new folder and adds it to CKAN.
- Each game instance contains about 5.5 GiB of files that come with the game and are necessary for it to run. Copying these takes a long time, and having multiple copies of them wastes a lot of space.
- Each game instance also contains files generated during gameplay and while CKAN is operating that are relevant to that instance but not really to clones. For example, screenshots are relevant to the instance where they're created, but having multiple copies of them isn't generally desirable. Copying these into cloned instances also …

Option to clone smaller instances with junction points (Windows) or symbolic links (Unix)

---

GUI/Controls/Changeset.cs
GUI/Controls/ManageMods.cs

If you install a modpack from a .ckan file, the X icons from #4033 are available, but clicking them and confirming the popup simply closes the changeset rather than removing the selected change.
Originally reported by Discord user Tollwütige Banane after trying out the dev build for its modpack fixes.
When you click the X and confirm, it raises an event that triggers `ManageMods.RemoveChangesetItem`, which only works properly if you selected the changeset via the checkboxes in Manage Mods. The changeset for a modpack comes from elsewhere, so ManageMods was instead doing nothing and then refreshing the changeset tab with an empty changeset, which causes it to close.
- Now `ManageMods.RemoveChangesetItem` only refreshes the changeset if it actually removes the change you clicked from its …

Make X skip buttons in changelog work better for modpacks

---

Core/DirectoryLink.cs
Tests/Core/Utilities.cs

The test from #4129 is failing on Windows with an access denied exception.
Apparently you need to remove the junction info from a dir before it can be deleted.
- Now `DirectoryLink.Remove` is created to purge the junction info from a dir before deleting it on Windows
- Now the test calls this function at the end so the teardown can remove the dir

Fix symlink tests on Windows

---

Core/Relationships/RelationshipResolver.cs
GUI/Controls/EditModpack.Designer.cs
GUI/Controls/EditModpack.cs
GUI/Controls/EditModpack.resx
GUI/Controls/ModInfoTabs/Contents.cs
GUI/Controls/UnmanagedFiles.cs
GUI/Properties/Resources.resx

Currently, in order to install the exact list of mods in a modpack, the user has to deselect the recommendations of all the mods. It would be nice to be able to skip this step.
It looks like setting `suppress_recommendations` for each item in the `depends` list should work, but it doesn't because those items get added as first class members of the changeset, which causes that property to be ignored in the modpack.
A similar thing can happen in a normal changeset; if A and B are in the changeset, and both depend on C but only A has `suppress_recommendations` set, B's lack of the property will mean that C's recommendations are still shown. That probably frustrates the author of A, especially if they're from KSP-RO.
- Now `suppress_recommendations` is obeyed if it is set for _any_ `depends` …

Recommendation suppression for modpacks

---

GUI/Controls/EditModSearchDetails.Designer.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Localization/en-US/EditModSearchDetails.en-US.resx
GUI/Model/ModSearch.cs
GUI/Properties/Resources.resx

@JonnyOThan says someone wants to search for incompatible mods with licenses allowing adoption, which could help some forgotten abandoned mods to be updated by new maintainers.
Now the search dropdown has a Licence ("License" in en-US) field between Description and Language that will match mods containing at least one license containing the given string prefix (search prefix in the main search bar is `lic`). As usual, multiple licenses may be searched by separating them with spaces (though this is a pain to do in the UI), and matching licenses may be filtered out with a `-` prefix, for example adoptable mods might be found with `-restricted -unknown`.
Fixes #4146.

Search by licenses

---

Cmdline/Action/AuthToken.cs
Cmdline/Action/Available.cs
Cmdline/Action/Cache.cs
Cmdline/Action/Compare.cs
Cmdline/Action/Compat.cs
Cmdline/Action/Filter.cs
Cmdline/Action/GameInstance.cs
Cmdline/Action/Import.cs
Cmdline/Action/Install.cs
Cmdline/Action/List.cs
Cmdline/Action/Mark.cs
Cmdline/Action/Remove.cs
Cmdline/Action/Repair.cs
Cmdline/Action/Replace.cs
Cmdline/Action/Repo.cs
Cmdline/Action/Search.cs
Cmdline/Action/Show.cs
Cmdline/Action/Update.cs
Cmdline/Action/Upgrade.cs
Cmdline/Options.cs
Cmdline/Properties/Resources.resx
Core/GameInstance.cs

- Currently `ckan compat add` accepts only one version string argument, but it's common to need to add multiple versions (for example, [we do exactly this in the metadata tester](https://github.com/KSP-CKAN/xKAN-meta_testing/blob/f4845f71bd8185e4c4c3f9ac6d689c6eba65ad8b/ckan_meta_tester/dummy_game_instance.py#L38-L41), and @JonnyOThan needs it for [KSPBuildTools](https://github.com/KSPModdingLibs/Shabby/actions/runs/10286246006/job/28466437650#step:3:320)).
- The `list`, `add`, and `forget` operations of `ckan compat` do not make it easy to ["get your compatible versions into a consistent reproducible state"](https://github.com/KSP-CKAN/CKAN/issues/4150#issue-2454235252)
- Now `ckan compat add` accepts multiple version strings
- Now `ckan compat forget` accepts multiple version strings
- …

Make `ckan compat add` take multiple versions, add `clear` and `set`

---

Core/ModuleInstaller.cs
Core/Net/NetFileCache.cs
Core/Properties/Resources.resx
Core/Registry/InstalledModule.cs
Core/Registry/Registry.cs
Core/Types/Kraken.cs
Dockerfile.metadata
Dockerfile.netkan
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfoTabs/Metadata.cs
GUI/Dialogs/AskUserForAutoUpdatesDialog.resx
GUI/Main/Main.cs
GUI/Properties/Resources.resx

While setting up to reproduce KSP-CKAN/NetKAN#10157 in a fake 1.9.1 instance, I noticed some problems:
- My CKAN was trying to install the latest RealismOverhaul when I clicked its Install checkbox, which isn't compatible with KSP 1.9.1, rather than the latest compatible v13.1.1 as in that issue's screenshot
- The GUI prompts that ask the user about auto-updating CKAN and auto-updating metadata are confusing. When I first switched into the fake 1.9.1 instance, I honestly could not tell what the first one was asking me about, since it didn't specify (the second one was clearer, but by then I already had to decide what to do about the first one).
- The file conflict message says "Owning Mod: TweakScale" without the version, so I had to ask the author of the issue to check what the version …

Use latest compatible instead of latest available for Install checkboxes

---

Core/Extensions/CryptoExtensions.cs
Core/ModuleInstaller.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Net/NetFileCache.cs
Core/Net/NetModuleCache.cs
Core/Properties/Resources.fr-FR.resx
Core/Properties/Resources.it-IT.resx
Core/Properties/Resources.pl-PL.resx
Core/Properties/Resources.resx
Core/Properties/Resources.ru-RU.resx
Core/Properties/Resources.zh-CN.resx
GUI/Main/MainImport.cs
Netkan/Services/FileService.cs
Tests/Core/Cache.cs
Tests/Core/ModuleInstallerDirTest.cs
Tests/Core/ModuleInstallerTests.cs
Tests/GUI/Model/ModList.cs

During and after #4152, I noticed some issues with ZIP importing in GUI:
- It appears to freeze for quite a while before it shows a popup
- It's slow
- The progress bar for importing treats each file as the same fraction of total completion, even if one is 1 GiB and another is 1 KiB, and the updates can be infrequent
Since importing ZIPs is our go-to workaround when users report slow mod download speeds, it should be usable and performant.
- `GUI.Main.ImportModules` calls `ModuleInstaller.ImportFiles` on a foreground thread, so all UI updates pause until it finishes
- For mods that share a ZIP, the import stores the ZIP once for every such mod, which can involve deleting and re-writing the same file in the cache multiple times
- The import will copy each file into the cache and then ask …

Refactor ZIP importing

---

Core/Games/IGame.cs
Core/Games/KerbalSpaceProgram.cs
Core/Games/KerbalSpaceProgram2.cs
Core/HelpURLs.cs
GUI/Dialogs/PluginsDialog.resx
GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/Main.resx

Discord user elhsgiuloigtn clicked the `Help → Discord` menu in CKAN to visit the CKAN Discord with a support request for an in-game problem with mods, which is fairly common. It's currently not clear that it takes you to the _CKAN_ Discord which is focused on CKAN itself, and that there are better places to go for mod support.
- Now the Help menu has an item for getting mod support that opens the modded support forum subsection for KSP1 or KSP2 depending on the current game instance
- Now the menu says `Help → CKAN Discord` to make it clearer what it's for
- Now the menu says `Help → CKAN user guide` to make it clearer what it's for
- Now the `Settings → CKAN plugins` menu is renamed `Settings → Plugins`, and the same change is made to the plugin dialog's title, because what other …

Add mod support links to Help menu

---

.github/workflows/deploy.yml
Dockerfile.metadata

<https://github.com/KSP-CKAN/CKAN-ModInstaller> is a simple GitHub action consisting of CKAN installed in a Docker image with all the needed dependencies and a simple bash driver script. It should be redeployed when changes are made to CKAN.
Now a new step at the end of the `upload-deb` job of the `deploy` workflow triggers the `deploy` repo dispatch event in the CKAN-ModInstaller repo so its GitHub Action image will be rebuilt.
Note that this required adding a `REPO_ACCESS_TOKEN` secret to this repo containing a [Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with `public_repo` scope and `write` access to the CKAN repo. This has been done.

Trigger mod installer deploy after APT repo update

---

Cmdline/Action/Update.cs
Cmdline/Main.cs
Cmdline/Properties/Resources.resx
Core/Relationships/RelationshipResolver.cs
Core/Repositories/Repository.cs
Core/Repositories/RepositoryDataManager.cs

The `ckan update` command retrieves fresh metadata from repositories, but currently it requires a game instance to work. Since #3904, repositories and game instances have been decoupled somewhat, so this should not be strictly necessary anymore.
For <https://github.com/KSP-CKAN/CKAN-ModInstaller>, it would be nice to be able to pre-load the Docker image with metadata so a mod's build wouldn't have to wait for a `ckan update` command to run. Ideally we could do this without creating a temporary game instance during the docker build.
Now the `ckan update` command has several new flags:
- `-g KSP -u URL [URL2 ...]` will update the repos with the given URLs, using the `-g` parameter to determine the game to use
- `-g KSP` / `-g KSP2` without `-u` will update the default repo for the given …

Ability to update repos without a game instance

---

.github/workflows/release.yml

The release version is now available for signpath, though there are still a couple of steps to go through, this will ensure signing is working correctly with the release action.
- Successful run: https://github.com/KSP-CKAN/CKAN/actions/runs/10438536973/job/28905992320
- Signed artifact: [Release-repack-unsigned.zip](https://github.com/user-attachments/files/16647463/Release-repack-unsigned.zip)

Update Signpath Action

---

GUI/Controls/ModInfoTabs/Relationships.Designer.cs
GUI/Controls/ModInfoTabs/Relationships.cs
GUI/Controls/ModInfoTabs/Relationships.resx

When an installed module satisfies a relationship by providing an identifier, the Relationships tab shows only the installed module without its peer providing mods, which makes it look like the dependency is more specific than it is.
- Now virtual dependencies are expanded by default in the initial view of the tree so they're easier to see
- Now virtual relationships always show the full list of providing mods, even if one of them is installed
- Now installed mods are shown in bold, with a new bold "Installed" label added to the legend section at the top

Don't hide other providing mods for installed, make installed bold

---

.github/workflows/deploy.yml
Cmdline/Options.cs

CmdLine has a `--headless` flag that lets CKAN know that it is not connected to an interactive terminal to suppress certain prompts or outputs. Many other terminal programs handle this automatically by checking properties of the stdin/stdout file handles.
Now if stdin or stdout is redirected, we set `--headless` automatically.
If you pass `--verbose`, a notification is printed that also gives a little detail about which file handle was detected as redirected:
```
777 [1] INFO CKAN.CmdLine.CommonOptions (null) - Setting headless mode (input redirected)
```

Set headless mode automatically

---

Core/CkanTransaction.cs
Core/Configuration/JsonConfiguration.cs
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/Main/Main.cs
GUI/Model/ModList.cs
GUI/Properties/Resources.resx
Netkan/Transformers/InternalCkanTransformer.cs
Netkan/Transformers/MetaNetkanTransformer.cs

The popup to add a game instance is only supposed to let the user choose game executable files of known games, but it always shows all shortcuts:
If you choose one of these and try to use it to add a game instance, you get a (quite funny) "Catastrophic failure" message:
Reported by @PoofImAlex in KSP-CKAN/CKAN#4167.
This seems to be just how `OpenFileDialog` "works". I'm sure there's some obscure rationale for it in some Microsoft document somewhere, but it is truly inappropriate and in need of fixing in our case.
It seems to be impossible to hide shortcuts, so instead we hook into the `FileOk` event and reject any files that don't match the filter that _we already gave to `OpenFileDialog` but which it decided to partially ignore_:

Work around OpenFileDialog always showing all shortcuts despite filters

---

Core/Registry/Registry.cs

ConsoleUI users who had installed `CountryDoggosRandomKKBits` see this exception as of KSP-CKAN/NetKAN#8711 and KSP-CKAN/CKAN-meta#3283:
```
CKAN.ModuleNotFoundKraken: Module not found: CountryDoggosRandomKKBits
at CKAN.Registry.getAvail (System.String identifier) [0x00040] in <5619c0490fe14ea1b83e6c508f8301de>:0
at CKAN.Registry.LatestCompatibleGameVersion (System.Collections.Generic.List`1[T] realVersions, System.String identifier) [0x0000d] in <5619c0490fe14ea1b83e6c508f8301de>:0
at CKAN.ConsoleUI.ModListScreen+<>c__DisplayClass0_0.<.ctor>b__34 (CKAN.CkanModule m) [0x00016] in <5619c0490fe14ea1b83e6c508f8301de>:0
at CKAN.ConsoleUI.Toolkit.ConsoleListBox`1[RowT].Draw (CKAN.ConsoleUI.Toolkit.ConsoleTheme theme, System.Boolean focused) [0x00259] in …
```

Suppress exceptions for non-indexed mods

---

Core/Registry/RegistryManager.cs
Core/Types/SpecVersionAnalyzer.cs
GUI/Controls/EditModpack.cs
Netkan/Transformers/SpecVersionTransformer.cs

#2971 updated the spec version for modpacks from `v1.6` to `v1.18` so the license could validly be set to `Unlicense`. In principle, anytime we add a new license or change anything else that might depend on the spec version, we need to bump the generated modpacks' spec version by hand. And in fact we've already missed this once, when the `MPL-2.0` license was added in `v1.30`.
Now that we have a way to calculate spec versions automatically (see #4155), it makes sense to eliminate this as a manually maintained item.
- `SpecVersionTransformer.MinimumSpecVersion` is moved to a new static class `SpecVersionAnalyzer` in Core
- A new override of `MinimumSpecVersion` accepts a `CkanModule` parameter instead of `JObject` (converted with `JObject.FromObject`)
- `RegistryManager.GenerateModpack` …

Autogenerate spec version for modpacks

---

Netkan/Model/Metadata.cs
Netkan/Processors/Inflator.cs

Authors of multi-hosted mods don't always upload the same versions to all hosts. Currently this results in an `Out-of-order version found on unreliable server` error (about 8 of these are active currently); this message does not accurately report what the actual problem is, and but it's possible for a partially-inflated mod to be indexed first.
Now if we get more modules than requested, an inflation error is thrown that describes which versions were found on which hosts:
```
$ netkan.exe NetKAN/ZTheme.netkan --releases 3
6461 [1] FATAL CKAN.NetKAN.Program (null) - Generated 4 modules but only 3 requested: v1.1.3.1 on github.com; v1.1.3 on github.com, spacedock.info; v1.1.2 on github.com, spacedock.info; v1.1.1 on spacedock.info
```

Inflation error for multi-hosted mods with mismatched versions

---

Dockerfile.netkan

See #3490 and #4184; we use a custom useragent string for the Inflator, and it would be nice if it included the client version.
Now the Inflator's `ENTRYPOINT` passes `$(/usr/bin/mono netkan.exe --version)` as part of its `--net-useragent` argument, so remote hosts will be able to log the version of the bot that made a request.
```
Mozilla/5.0 (compatible; Netkanbot/1.0; CKAN/v1.34.5+24261; +https://github.com/KSP-CKAN/NetKAN-Infra)
```

Include version in Inflator useragent string

---

.github/workflows/deploy.yml

Dev builds have been a handy way of getting quick fixes out to specific users while [waiting for the cryptographic stars to align for a new release](https://github.com/KSP-CKAN/CKAN/pull/4162), but they're currently only available as .exe, .deb, or .rpm. To use a dev build the same way they use the usual `CKAN.dmg` release, a Mac user would have to download the .exe and insert it into the `CKAN.app` bundle him- or herself, which is not an accessible task for all users.
Now a new `upload-dmg` step is added to `deploy.yml` that plops the already generated `ckan.exe` into a `CKAN.app` into a `CKAN.dmg` and uploads the latter to s3. After this is merged, a Mac-packaged dev build will be available at this location:
- <https://ksp-ckan.s3-us-west-2.amazonaws.com/CKAN.dmg>

Dev builds for Mac

---

GUI/Controls/EditModSearch.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Controls/ManageMods.cs
GUI/Main/Main.cs
GUI/Model/ModList.cs
GUI/Model/ModSearch.cs

- In the GUI search details editing dropdown, there's a Labels field, but you can't type into it. It is only used to display labels that are already in your search via the Filters menu or clicking a link.
- Label searches can't be negated with a `-` prefix like all other searches
It has worked this way since #3323 (and #3460 even partially explained why), but no one seemed to care.
Recently we finally got a report from Discord user Epsilon:
`ModSearch` stores `string`s for tags but `ModuleLabel`s for labels. This was done because it's trivial to check whether a tag name matches a module by looking for it in the `CkanModule.Tags` property, but the _label_ object stores which mods it contains rather than the other way around. To check label membership, you need the `ModuleLabel` object, so …

Label search fixes

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml
.github/workflows/sign.yml
.github/workflows/smoke.yml
README.md

SignPath's action is ready, we have a certificate, and #4188 created a helper build target to collect assets for signing. The next step toward signing releases is updating our workflows.
- Now `build.yml` uses the build target from #4188 to upload an artifact containing the assets we need to sign for the Release configuration
- Now `sign.yml` is created to retrieve that artifact, get it signed, and upload a new `signed` artifact with the results
- Now `release.yml` calls `sign.yml` to generate signed assets for releases
- Now `deploy.yml` calls `sign.yml` to generate signed assets for uploading dev builds

Sign releases, dev builds, and nuget package

---

.github/workflows/deploy.yml
.github/workflows/release.yml

Shared workflows do not automatically get access to the secrets from the parent workflow. Either secrets must be passed through individually or you can choose to inherit them

ci: Secret Inheritence

---

Core/Configuration/Win32RegistryConfiguration.cs
Core/GameInstance.cs
Core/Games/IGame.cs
Core/Games/KerbalSpaceProgram.cs
Core/Games/KerbalSpaceProgram2.cs
GUI/Controls/ModInfoTabs/Versions.cs
GUI/Dialogs/CompatibleGameVersionsDialog.Designer.cs
GUI/Dialogs/CompatibleGameVersionsDialog.cs
GUI/Properties/Resources.resx
GUI/Util.cs
Tests/Core/Games/KerbalSpaceProgram2Tests.cs
Tests/Core/Games/KerbalSpaceProgramTests.cs

One of the top user support requests at the moment is still how to make more mods show up as installable, with the answer still being to [set compatible versions in the settings](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions) to work around still-missing compatibility metadata updates from mod authors:
New users have no concept of the history of game updates and mod updates and how they interacted; they see a more or less static landscape, and it doesn't make sense to them that they would have to change settings to install anything.
Meanwhile, a great number of mods that still work in the latest version were abandoned long before it was released, and so their compatibility still only goes up to whatever was the latest game version at that time.
- Now …

Set compat of new instances based on Unity updates and alert user

---

Core/ModuleInstaller.cs
Core/Relationships/RelationshipResolver.cs
GUI/Controls/ManageMods.cs
GUI/Main/MainChangeset.cs
GUI/Model/GUIMod.cs
GUI/Model/ModList.cs
Netkan/Transformers/GithubTransformer.cs
Tests/Core/ModuleInstallerTests.cs

- @ProgrammerFailure reported problems installing modpacks from <https://github.com/ProgrammerFailure/MyCKANMetaData>, contained in this metadata repo:
<https://github.com/ProgrammerFailure/MyCKANMetaData/archive/main.tar.gz>
The changeset appears, but when you confirm it, the install is skipped.
- Once that was fixed, I got HTTP status 415 errors trying to install a mod that was indexed based on its source archive
- Then once the modpack was finally installed, I noticed that the changeset wasn't updating when I toggled the Auto-Installed checkbox
- Metapackages and dependencies were being filtered out, so the install flow was quitting on an empty changeset
- GitHub's API documentation now says to set the `Accept` header to `application/vnd.github+json` to download a source ZIP rather …

Fix installation of metapackages from repositories

---

Core/ModuleInstaller.cs

As of #4055, progress bar updates during installation are more granular and reflective of the actual progress of unpacking mods, but removal and upgrades still treat each mod as a single unit and all mods as the same size, which makes the progress bar nearly useless.
Now for removal, we treat each file to remove as a unit of work, and mods with more files take up more progress bar space.
Now for upgrading, the removal part is treated as above and the installation part is treated as in #4055. The proportion of the progress bar devoted to removal vs installation is weighted by the number of mods in each group, so for most upgrades we will switch from removal to installation at the 50% mark, and the installation piece will expand when we're pulling in new dependencies.

Per-file progress for uninstall and upgrade

---

Core/ModuleInstaller.cs
Core/Registry/IRegistryQuerier.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfoTabs/Contents.Designer.cs
GUI/Controls/ModInfoTabs/Contents.cs
GUI/Model/GUIMod.cs
GUI/Model/ModChange.cs
GUI/Model/ModList.cs
GUI/Properties/Resources.de-DE.resx
GUI/Properties/Resources.fr-FR.resx
GUI/Properties/Resources.it-IT.resx
GUI/Properties/Resources.ja-JP.resx
GUI/Properties/Resources.ko-KR.resx
GUI/Properties/Resources.pl-PL.resx
GUI/Properties/Resources.resx
GUI/Properties/Resources.ru-RU.resx
GUI/Properties/Resources.zh-CN.resx
Tests/GUI/Model/ModList.cs

Discord user `dan` reported frequent prompts from the dev build to reinstall mods after running the game, which said "metadata changed" even though the metadata for those mods had either never changed or changed over two years previously:
This turned out to be due to ZeroMiniAVC, which deletes files that CKAN installed. The feature from KSP-CKAN/CKAN#4067 detects that as a mod with missing files and prompts the user to reinstall that mod.
This was challenging to figure out for a CKAN developer and a dev build power user. It should be understandable for anyone.
- Now if a reinstall is due to a missing folder or file, the change reason says "Re-install (missing folders or files)"
- Now the Contents tab shows missing folders and files in red, with a "Folder not found!" or "File not found!" …

Usability improvements for missing files

---

Core/Extensions/EnumerableExtensions.cs
Core/SteamLibrary.cs
Core/Utilities.cs

After the v1.35.0 release, several users reported an exception at launch:
```
Unhandled Exception: ValveKeyValue.KeyValueException: Found end of file when another token type was expected. ---> System.InvalidOperationException: Attempted to finalize object while in state InObjectBetweenKeyAndValue.
at ValveKeyValue.Deserialization.KV1TextReader.FinalizeCurrentObject(Boolean explicit)
at ValveKeyValue.Deserialization.KV1TextReader.FinalizeDocument()
at ValveKeyValue.Deserialization.KV1TextReader.ReadObject()
at ValveKeyValue.Deserialization.KV1TextReader.ReadObject()
at ValveKeyValue.KVSerializer.Deserialize(Stream stream, KVSerializerOptions options)
at CKAN.SteamLibrary.<>c__DisplayClass3_0.<LibraryPathGames>b__0(String acfFile)
at …
```

Skip corrupted .acf files in Steam library

---

GUI/Model/ModList.cs
GUI/Util.cs

If you apply multiple labels to the same mod, some weird visual artifacts can happen; the affected row can have the text of multiple mods overlapping each other:
- Apparently `DataGridView` can only handle row colors with an alpha channel of 0 or 255; if you set anything in between, it gets confused and basically seems to not paint the row
- If a label has a transparent background color, blending it with a solid color produces an alpha channel of 127, which confuses the grid as per above
- `Util.BlendColors` is implemented in terms of `Util.AlphaBlendWith`, which uses a floating point alpha channel to compute what it would look like if one color was overlaid over the other with the given level of transparency. Unfortunately, even for two colors with an alpha channel of 255, this can …

Fix label color blending

---

Core/Extensions/EnumerableExtensions.cs
Core/ModuleInstaller.cs
Core/Registry/IRegistryQuerier.cs
Core/Registry/InstalledModule.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Controls/ModInfoTabs/Contents.cs
GUI/Dialogs/EditLabelsDialog.Designer.cs
GUI/Dialogs/EditLabelsDialog.cs
GUI/Dialogs/EditLabelsDialog.resx
GUI/Dialogs/InstallFiltersDialog.cs
GUI/Labels/ModuleLabel.cs
GUI/Labels/ModuleLabelList.cs
GUI/Main/Main.cs
GUI/Main/MainLabels.cs
GUI/Model/ModList.cs
GUI/Properties/Resources.resx
Tests/Core/Registry/Registry.cs

As of #4067, manually deleting files installed by CKAN causes that mod to be shown as having an update that reinstalls the mod to restore the deleted files. This is to ensure that all CKAN-installed mods are installed correctly according to the instructions in their metadata.
- If you click Update all, the update checkbox for such mods is not checked
- If you check the Update checkbox for a mod, the changeset is updated with the corresponding action, but unchecking it does _not_ refresh the changeset
- Users may delete certain files from certain mods to disable the functionality from that file. This use case is a good fit for #3458's installation filters, and they do work for this, but the user experience is clunky and can require patience and workarounds:
- The Contents tab does not obey …

Improvements for missing file checks

---

Core/Types/CkanModule.cs

Currently we always calculate both the SHA1 and the SHA256 for all mods. This is redundant and wastes CPU time.
KSP-CKAN/CKAN#4135 began the process of making the SHA1 optional; the client now ignores `download_hash.sha1` for purposes of validating downloads if `download_hash.sha256` is set (which is always). However, it still uses the SHA1 in the archive.org fallback URLs.
Now if `download_hash.sha1` is not set, then the client uses `download_hash.sha256` for archive.org fallback URLs instead, as in KSP-CKAN/NetKAN-Infra#344.
This should be the last piece required to make it possible to drop SHA1 from the metadata completely, but note that it will still be calculated for any module with `spec_version` less than `v1.35`. We will need to make additional changes later for Netkan to actually …

Use SHA256 for archive.org fallback if SHA1 absent

---

ConsoleUI/ModListScreen.cs
ConsoleUI/Toolkit/ConsoleLabel.cs
ConsoleUI/Toolkit/ScreenObject.cs

- I saw a screenshot of ConsoleUI recently where the new mod-abstract label from 0fae2a2a763c4ffb12fbeb0c9ddf9b245ccc5d6e was overlapping the "updated X days ago" label
- The "updated X days ago" label is left aligned and wider than it needs to be
- While working on the above, I noticed that the download counts from #4063 for the DLCs were being shown as 0, which doesn't make sense
- Now the abstract label stops where the "updated X days ago" label starts so they won't overlap
- Now the "updated X days ago" label's size fits its content with a little padding, and it's right-aligned
- Now 0 download counts are left blank instead

Label spacing and alignment, show zero download counts as blank in ConsoleUI

---

Netkan/Transformers/InternalCkanTransformer.cs

@SofieBrink is testing out using internal .ckan files and hit a snag:
```
FATAL CKAN.NetKAN.Program (null) - ksp_version mixed with ksp_version_(min|max)
```
SpaceDock provides `ksp_version`, and the internal .ckan file provides `ksp_version_min`, and they're not reconciled.
Now after an internal .ckan file is merged, `ModuleService.ApplyVersions` is called to massage the compatibility metadata into consistency. This will allow mods on SpaceDock to set their compatibility in internal .ckan files.

Reconcile compatibility after internal .ckan merge

---

Netkan/Sources/Avc/JsonAvcToVersion.cs
Tests/NetKAN/Sources/Avc/AVC.cs

A mod uploaded a release today with this in its version file:
```json
"PATCH":09,
```
This causes an inflation error:
> `New inflation error for <mod name>: Error parsing version file <path to version file>.version: Input string '09' is not a valid number. Path 'VERSION.PATCH', line 9, position 12.`
Digging into this, apparently a `0` prefix for numbers isn't technically allowed at all in strict JSON (and a few online validators confirm this), but some parsers (including the most popular one for C#, Newtonsoft.Json) decided to be lenient and parse them as C-style octal literals. But `08` and `09` are not valid octal literals because only the digits `01234567` can be used in octal.
Now several new test cases are added to check and document exactly what is and is not allowed by …

Tests for Newtonsoft.Json's handling of octal literals in version files

---

Cmdline/Action/Search.cs
Cmdline/Action/Show.cs
Core/GameInstanceManager.cs
Core/ModuleInstaller.cs
Core/Registry/Registry.cs
Core/Relationships/RelationshipResolver.cs
Core/Relationships/SanityChecker.cs
GUI/Controls/Changeset.cs
GUI/Controls/ChooseRecommendedMods.cs
GUI/Controls/ManageMods.cs
GUI/Dialogs/ManageGameInstancesDialog.cs
GUI/ISearchableControl.cs
GUI/Main/Main.cs
GUI/Main/MainRecommendations.cs
Netkan/Processors/QueueHandler.cs
Netkan/Sources/Github/GithubApi.cs
Netkan/Transformers/NetkanTransformer.cs
Netkan/Validators/CraftsInShipsValidator.cs
Netkan/Validators/HarmonyValidator.cs
Netkan/Validators/InstallsFilesValidator.cs
Netkan/Validators/PluginsValidator.cs
Netkan/Validators/SpaceWarpInfoValidator.cs
Tests/Util.cs

- <kbd>Ctrl</kbd>+<kbd>F</kbd> is supposed to focus the search box, but currently it doesn't
- Even if we fix the broken <kbd>Ctrl</kbd>+<kbd>F</kbd> handler, it will only work when the mod grid has focus, not mod info or any of the other parts of the UI
- Going back to a3d96f6df90abb4b745a14b2bfa7e190fd3cad55, the focus has been set solely by setting `ActiveControl`, which doesn't always work (details unclear, but possibly related to the search control containing sub-controls?)
- <kbd>Ctrl</kbd>+<kbd>F</kbd> is currently handled by `ManageMods.ProcessCmdKey`, which is only called when that control has focus
- Now `.Focus()` is used to set the focus
- Now the handler for the <kbd>Ctrl</kbd>+<kbd>F</kbd> keystroke is moved from `ManageMods` back to `Main` so it can be global
- Now …

Set focus better on Ctrl+F

---

GUI/Main/Main.Designer.cs
GUI/Main/Main.cs
GUI/Main/Main.resx
GUI/Main/MainTrayIcon.cs

@JonnyOThan requested to have the tray icon re-open the window on single click, rather than just on double click (see #2565).
Sure, why not.
- Now single clicking the tray icon un-hides the window
- Now the tooltip of the tray icon has the game instance name, so you can tell which icon is which when there are multiple
- Now the "Open CKAN" menu option is hidden while the window is already visible
- Now the "N available updates" option is hidden while the initial game instance is loading and becomes visible once it's loaded

Minor tray icon improvements

---

Core/Net/NetFileCache.cs
Core/Registry/Registry.cs
Core/Relationships/SanityChecker.cs
GUI/Main/MainInstall.cs
Tests/Core/Relationships/SanityChecker.cs

If you try to install a mod that has a dependency, and the dependency fails to download, and you try to Skip/Retry, CKAN will try to download it again. The only option that works is Abort whole changeset.
To get the mods from the changeset that depend on the mod we're trying to skip (since we also will not be able to install them), we call `Registry.FindReverseDependencies`, but we call the version of it that only returns identifiers _that are already installed_. This means the depending mod won't be returned and won't be removed from the changeset, so when the install is retried, the dependency is pulled back in.
Now this codepath calls the static `Registry.FindReverseDependencies` that allows us to specify the overall superset of mods, which we pass as the full changeset. This allows …

Fix skipping failed dependency downloads

---

Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Repositories/RepositoryDataManager.cs
Core/Types/Kraken.cs
GUI/Main/MainRepo.cs
Tests/Core/Net/NetAsyncDownloaderTests.cs

With archive.org down, taniwha's mods hosted only there (before KSP-CKAN/NetKAN#10262 and KSP-CKAN/NetKAN#10263), and the life boat modpack depending on Extraplanetary Launchpads, our failed downloads handling has been undergoing a comprehensive stress test.
KSP-CKAN/NetKAN#10262's validation log reported a download failure for KIS, _after_ reporting that KIS downloaded successfully:
https://github.com/KSP-CKAN/NetKAN/actions/runs/11407171543/job/31743515317
```
Downloading https://archive.org/download/KerbalStats-3.1.0/0E71BD9E-KerbalStats-3.1.0.zip ...
...
Finished downloading KIS 1.29, validating and storing to cache...
0 B/sec - downloading - 3.1 MiB left - 93%           
Downloading https://spacedock.info/mod/1987/Kerbal%20Attachment%20System%20(KAS)/download/1.12 ...
Finished …
```

Fix reporting of wrong download as failed

---

Core/Properties/Resources.fr-FR.resx
Core/Properties/Resources.it-IT.resx
Core/Properties/Resources.pl-PL.resx
Core/Properties/Resources.resx
Core/Properties/Resources.ru-RU.resx
Core/Properties/Resources.zh-CN.resx
Core/Relationships/RelationshipResolver.cs
Core/Relationships/ResolvedRelationship.cs
Core/Relationships/ResolvedRelationshipsTree.cs
Netkan/Extensions/JObjectExtensions.cs
Tests/Core/Relationships/RelationshipResolverTests.cs

If you manully install RPM alongside a CKAN install of Deferred and then try to upgrade RPM to CKAN-managed, it doesn't let you:
As of #4067, a DLL can be upgraded to a full module, but the relationship resolver's consistency check still checks conflicts against the pre-upgrade DLL list.
In the case of Deferred, it conflicts with older versions of RPM, but versions can't be checked with DLLs, so the registry starts out in a conflicted state and remains that way despite the planned upgrade to a non-conflicting module.
Now the relationship resolver computes a post-install set of DLLs based on the list from the registry minus the identifiers of modules being installed. This allows upgrading a version-specifically-conflicted DLL to a module with a version that doesn't match the conflict. A …

Exclude DLLs being upgraded to full modules

---

Core/Registry/RegistryManager.cs
GUI/Controls/EditModpack.cs
GUI/Controls/Wait.cs

#3499 sorted the relationships in modpacks alphanumerically by identifier (rather than randomly). There have been some problems with this; since the ordering of a changeset matters, sorting alphanumerically means that dependencies might end up later in the changeset than their depending mods, so for instance there might be cases where a user is prompted to choose a mod and is allowed to pick one that will conflict with a dependency of something later in the changeset.
Now we use a relationship resolver to sort dependencies before depending mods in modpacks. This way when a new modpack is exported, the ordering will better reflect how the mods should be installed.
Ideally we would also give the user some options for manually reordering mods, but I discovered that WinForms's `ListView` …

Sort dependencies first in modpacks

---

Core/ModuleInstaller.cs
Core/Net/IDownloader.cs
Core/Net/NetAsyncDownloader.cs
Core/Net/NetAsyncModulesDownloader.cs
GUI/Main/MainDownload.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRepo.cs

The GUI progress screen has a Cancel button, but it only works while a download is in progress. If you try to cancel after the downloads are finished but installation is still in progress, the button disables itself and nothing else happens.
The downloaders have their own custom `CancelDownload` methods, but the `ModuleInstaller` has nothing equivalent.
- Now the downloader classes are refactored to accept `CancellationToken`s in their constructors and throw `CancelledActionKraken` in place of their proprietary APIs. The `CancelledActionKraken` causes the installation transaction to abort, which restores the original state of the game folder.
- `ModuleInstaller` is updated to work the same way and checks the token in between installing or removing files
- The Cancel button now cancels the …

Allow installs and removals to be cancelled

---

NetKAN.schema
Spec.md

We have a schema for .ckan files, which [the Inflator uses to validate metadata](https://github.com/KSP-CKAN/CKAN/blob/master/Netkan/Validators/ObeysCKANSchemaValidator.cs).
Discord user Danny2462 pointed out that you can also get vscode to autocomplete according to a JSON schema, so I set that up for .ckan files in https://github.com/KSP-CKAN/CKAN-meta/commit/1e59d3dba84cf17d4c8b2f7c1cdf97d2081f25be and https://github.com/KSP-CKAN/KSP2-CKAN-meta/commit/44090126bc2de5463be04c86d7c01fe9999dde4e.
Usually .ckans are autogenerated while hand-editing is for .netkans, so .netkans would benefit more from this. However, `CKAN.schema` doesn't have the additional `x_netkan_*` properties, and it requires properties that are optional in .netkan files, so we can't use the same schema for both repos. …

Create netkan schema

---

Core/Registry/CompatibilitySorter.cs
Core/Registry/Registry.cs

According to #4256, installing Parallax with CKAN and then Parallax Continued manually causes CKAN to enforce version-specific relationships against the manually installed DLL:
This is arguably correct behavior, since you _do_ have a manually installed DLL, for which which CKAN _cannot_ programmatically determine a version for comparison with version-specific relationships. But it's opaque and frustrating for users, who just want some way to get these paid mods integrated into the ecosystem.
This is speculation because the affected mod is not publicly available and the issue description isn't detailed enough to confirm, but it _sounds_ to me like the manually installed mod is being put in a different path than the CKAN-installed mod.
I say this because if you simply replaced the …

Ignore manually installed duplicates of installed modules

---

NetKAN.schema

Optional capture groups allowed invalid patterns like
`"$kref": "#/ckan/github/foo/foo-bar/asset_WARN_match/foo-bar-baz.zip"`
to not result in a warning by VSCode, now they are rejected correctly:
before:
after:
Note that it warns about the spacedock pattern, which is the first of the possible patterns - this unhelpful message is a limitation of VSCode / just this regex approach of JSON schemas in general 🤷‍♂️
Also added escape slashes where needed, which is superfluous for the C# flavor, but required in the JavaScript flavor of regex, just to be safe.

fix: `NetKAN.schema` not rejecting invalid pattern for `$kref` and `$vref` in VSCode

---

Core/ModuleInstaller.cs

If you install `BoringCrewServices`, `KSPCommunityPartModules` will be listed as a dependency in the changeset, but also as optional in the "Supported By" list. It doesn't make sense for it to be in both places.
Reported by @SofieBrink and @AlexSkylark in Discord.
- `BoringCrewServices` depends on `KSPCommunityPartModules`, which adds the latter to the changeset as a dependency
- `KSPCommunityPartModules` supports `BoringCrewServices`, which adds the former to the "Supported By" list
- The relationship resolver currently excludes only the mods that you directly selected from the "Supported By" list, not their dependencies (probably because this relationship structure doesn't actually make sense)
Now `ModuleInstaller.FindRecommendations` passes `recommenders` to …

Exclude dependencies in the changeset from supported by list

---

Cmdline/Action/Show.cs
Cmdline/Properties/Resources.resx

`ckan show` lists a module's relationships, except for `supports`. It would be good to see them all.
Now a new "Supports:" section appears with the `supports` relationships.

Include `supports` relationship in `ckan show`

---

Netkan/Sources/Github/GithubApi.cs

`HideEmptyFilters` currently has an inflation warning about failing to download a remote version file that most definitely exists.
Once upon a time, if you clicked the "raw" link in GitHub, it took you to a URL like this:
- <https://raw.githubusercontent.com/HebaruSan/Astrogator/master/GameData/Astrogator/Astrogator.version>
Now it does this instead:
- <https://raw.githubusercontent.com/AlexSkylark/HideEmptyFilters/refs/heads/main/GameData/HideEmptyFilters/HideEmptyFilters.version>
Note the extra `refs/heads/` substring that's been added. `GithubApi.TryGetGithubPath` tries to parse GitHub URLs in order to access the same files via the GitHub API, and this new substring messes up the existing parsing. It thinks the branch is called `refs` and that the file's path starts with `heads/main`. …

Handle raw GitHub URLs containing refs/heads/

---

Core/Registry/CompatibilitySorter.cs
Core/Registry/Registry.cs
Core/Relationships/ResolvedRelationship.cs
Tests/Core/Registry/CompatibilitySorter.cs

KSP-CKAN/NetKAN#10303 is throwing:
```
System.ArgumentException: An item with the same key has already been added. Key: RSSOrigin-TopoRevampTextures16k v1.1.2
at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x0015a] in <d636f104d58046fd9b195699bcb1a744>:0 
at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <d636f104d58046fd9b195699bcb1a744>:0 
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0002d] in …
```

Fix exception when the same module is in multiple repos

---

.github/actions/netkan/action.yml
.github/workflows/bounce.yml

The Inflators have been freezing up a bit recently. While we're still investigating why, it would be nice to have an easy way to reboot them that doesn't require recompiling and signing everything, as re-running the deploy workflow does.
Now a new bounce job can be run from the workflows list, which uses a games matrix to start two jobs in parallel, which use a new action to run a given command in the `kspckan/netkan` container. This should allow us to run just the redeploy commands easily.

Create workflow to bounce the Inflators

---

ConsoleUI/AuthTokenListScreen.cs
ConsoleUI/DeleteDirectoriesScreen.cs
ConsoleUI/DependencyScreen.cs
ConsoleUI/ExitScreen.cs
ConsoleUI/GameInstanceListScreen.cs
ConsoleUI/GameInstanceScreen.cs
ConsoleUI/InstallFiltersScreen.cs
ConsoleUI/ModInfoScreen.cs
ConsoleUI/ModListScreen.cs
ConsoleUI/ProgressScreen.cs
ConsoleUI/RepoScreen.cs
Core/CKANPathUtils.cs
Core/Meta.cs
Core/Types/CkanModule.cs
GUI/Main/Main.cs

The `spec_version` metadata property defines the earliest version of the CKAN client that can properly handle a given module. As of #4155 it is populated programmatically based on analysis of the fields that are present or absent in a module. The CKAN client ignores modules with "future" spec versions indicating that it can't handle them properly.
When we add a new feature, it goes into the dev build immediately. So at any stage of development, all of the next release's functionality is already present in the dev build. But dev builds have a version that corresponds to the same spec version as the current release (but with an odd patch version), so they'll ignore modules with higher spec versions that they can in fact handle properly.
#4260 updated the spec version analyzer to use `v1.36` …

Let dev builds use future spec versions

---

GUI/Controls/LabeledProgressBar.cs
GUI/Dialogs/ManageGameInstancesDialog.cs

After #4255, my Ubuntu VM still had problems rendering `LabeledProgressBar`. An exception was thrown and the progress bar appeared as a white background with a red X on it.
`ProgressBarRenderer` has a boolean `IsSupported` property which is set based on the capabilities and configuration of the host system. If false, then the class's drawing methods throw exceptions instead of drawing. It must have been true on my main Ubuntu system, but it's clearly false in my VM.
Now if `ProgressBarRenderer.IsSupported` is false, we draw it with the `PaintEventArgs.Graphics` object instead of `ProgressBarRenderer`.

Draw progress bar when ProgressBarRenderer.IsSupported is false

---

GUI/Controls/EditModSearch.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo.cs
GUI/Controls/ModInfoTabs/Metadata.cs
GUI/Main/Main.cs
GUI/Main/MainTrayIcon.cs
GUI/Model/ModList.cs
GUI/Model/ModSearch.cs
Tests/GUI/Model/ModList.cs

If you make a label with spaces in its name and apply it to some mods, filtering by that label finds no mods.
Reported by Discord user TEMPEST.
The search syntax uses spaces to separate parts of the search, so `label:Name With Spaces` is changed to `label:NameWithSpaces`, but the label checking logic wasn't accounting for this.
- Now the label checking logic removes spaces from a label name before checking whether it matches the query
- The repetitive parts of label searches (translating names to label objects, checking for negation) are now precalculated once, which should give such searches a tiny performance boost
- Now the Filters &rarr; Labels menu shows the label colors like the right click menu does

Optimize label searches and handle spaces in names

---

Netkan/Sources/Spacedock/SpacedockMod.cs

BeyondJool currently has this inflation error:
> No files found matching find="BeyondJool" to install!
There's a 1-MB dummy download with a version of `TEST (do not use)` sitting at the top of the list of releases:
- <https://spacedock.info/mod/3682/Beyond%20Jool#changelog>
The inflator is downloading this and discovering that it doesn't contain the mod, even though the "Set as default" button was used on SpaceDock to mark the previous download. This most likely broke when we added the `--releases` and `--skip-releases` options to Netkan because support for the default release flag was only in `SpacedockMod.Latest`, which is no longer used because it only returns one version.
Now the default release setting is used to sort the releases from SpaceDock, so it will determine which release …

Restore default version support for SpaceDock

---

Netkan/CmdLineOptions.cs
Netkan/Processors/QueueHandler.cs
Netkan/Program.cs
Netkan/Transformers/EpochTransformer.cs
Netkan/Transformers/ITransformer.cs
Tests/NetKAN/MainClass.cs
Tests/NetKAN/NetkanOverride.cs
Tests/NetKAN/Transformers/AvcKrefTransformerTests.cs
Tests/NetKAN/Transformers/AvcTransformerTests.cs
Tests/NetKAN/Transformers/CurseTransformerTests.cs
Tests/NetKAN/Transformers/DownloadAttributeTransformerTests.cs
Tests/NetKAN/Transformers/EpochTransformerTests.cs
Tests/NetKAN/Transformers/GeneratedByTransformerTests.cs
Tests/NetKAN/Transformers/GithubTransformerTests.cs
Tests/NetKAN/Transformers/HttpTransformerTests.cs
Tests/NetKAN/Transformers/InstallSizeTransformerTests.cs
Tests/NetKAN/Transformers/InternalCkanTransformerTests.cs
Tests/NetKAN/Transformers/MetaNetkanTransformerTests.cs
Tests/NetKAN/Transformers/SpacedockTransformerTests.cs
Tests/NetKAN/Transformers/StripNetkanMetadataTransformerTests.cs
Tests/NetKAN/Transformers/VersionEditTransformerTests.cs

Prereleases currently get indexed, and then in subsequent passes an inflation error `Out-of-order version found on unreliable server` occurs because only one host has the prerelease, and that host's latest release appears to be out of order by comparison.
Now the Inflator has a `--highest-version-prerelease` parameter and supports a `HighestVersionPrerelease` message attribute (to be populated by KSP-CKAN/NetKAN-Infra#352) that can specify the version of the latest prerelease separately from the regular releases. When we check for out-of-order versions, regular releases are only compared to other regular releases, and prereleases are compared to both.
Once both PRs are merged, the inflation errors associated with prereleases should drop off, which is important for minimizing the …

Don't raise inflation errors for single-hosted prereleases of multi-hosted mods

---

Netkan/Transformers/AvcTransformer.cs

Some mods' version files have a `URL` pointing to `forum.kerbalspaceprogram.com`. Now that the forum is unreliable, this sometimes causes timeouts, and the inflation warnings toggle back and forth between network errors and parsing errors.
Even when the URL is retrieved successfully, it's a waste of time and bandwidth because the forum can never contain a remote version file.
Now version files with a `URL` on the forum emit a warning and move on rather than trying to retrieve the URL.

Stop trying to get remote version files from the forum

---

Core/Registry/Registry.cs
Core/Registry/RegistryManager.cs

A user drove-by the CKAN Discord to complain loudly about load times. No actionable information was shared, but it did remind me that I'd seen delays during the DLL scanning step with a lot of mods installed.
A code audit didn't reveal any major inefficiencies, but I did spot several minor ones.
- Now `Registry.SetDlls` no longer makes an extra copy of the `installed_dlls` dictionary
- Now `IGame.StockFoders` is only called once per scanning pass rather than once per DLL, which was a potential source of slowness because it allocates an array
- Now we append `/` to each stock folder once per scanning pass rather than once per DLL
- Now the stock folders check skips stock folders that aren't inside the per-game equivalents of GameData
Together, these changes eliminate some unnecessary work …

Small performance tweaks for DLL scanning

---

.github/workflows/build.yml
.github/workflows/test.yml
GUI/Controls/ModInfoTabs/Metadata.cs
GUI/Dialogs/AboutDialog.Designer.cs
GUI/Dialogs/AboutDialog.cs
GUI/Main/Main.cs
GUI/Main/MainAutoUpdate.cs
GUI/Main/MainChangeset.cs
GUI/Main/MainExport.cs
GUI/Main/MainHistory.cs
GUI/Main/MainImport.cs
GUI/Main/MainInstall.cs
GUI/Main/MainRecommendations.cs
GUI/Main/MainRepo.cs
GUI/Main/MainTime.cs
GUI/Main/MainUnmanaged.cs
GUI/Main/MainWait.cs
GUI/Util.cs

The About dialog's version label no longer shows the version:
The labels on the About form all have hard coded sizes and are not auto-sized, and the version string is longer than it used to be (build number was added), so the version label is wrapping and then being truncated vertically.
- Now all the of the About dialog's labels have `AutoSize = true`, so they'll always show their full contents
- Now if you press the menu key while focused on a link label, the menu will appear under the link label instead of at the mouse cursor
Fixes #4276.

Fix broken version label in About dialog

---

Core/SteamLibrary.cs

Steam apparently allows `libraryfolders.vdf` to skip indexes:
```vdf
"libraryfolders"
{
"0"
{
// removed data for brevity
}
"2"
{
// removed data for brevity
}
}
```
But when we try to parse this as a `List`, an exception is thrown:
```
Unhandled Exception: System.InvalidOperationException: Cannot deserialize a non-array value to type "System.Collections.Generic.List`1".
at ValveKeyValue.ObjectCopier.MakeObject[TObject](KVObject keyValueObject, IObjectReflector reflector)
at CKAN.SteamLibrary..ctor(String libraryPath)
at CKAN.GameInstanceManager..ctor(IUser user, IConfiguration configuration)
at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
at CKAN.CmdLine.MainClass.Main(String[] args)
```
- Now instead of parsing this file as a list, we …

Handle missing indexes in Steam vdf file lists

---

Dockerfile.metadata
Dockerfile.netkan

The metadata for Skopos has `??` in the abstract where non-ASCII characters are provided by the GitHub API:
- <https://api.github.com/repos/mockingbirdnest/Skopos>
- <https://github.com/KSP-CKAN/CKAN-meta/blob/master/Skopos/Skopos-v1.0.1.0.ckan>
Notably, this does not happen for me locally.
The `LANG` environment variable is not set in the Inflator's container, so unicode characters are not handled properly. I have it set to `en_US.utf-8`, the latter part of which enables unicode.
Now our `Dockerfile`s set `LANG` to `C.utf-8` to enable unicode support. This is also the value used in the bot's Python-based containers. This causes UTF-8 strings from the GitHub API to be faithfully recorded into the metadata.
Fixes #4288.

Set unicode-aware locale in containers

---

Netkan/Transformers/SpacedockTransformer.cs

Prior to https://github.com/KSP-CKAN/CKAN/pull/4260, the release_status field was purely for user information and did not affect which versions CKAN would index or install.  The PR changed that (and we had already removed the release_status from existing netkans).  In order to prevent older clients from installing pre-release versions, these versions are now marked with spec_version 1.36.
The above PR also added a bit of logic that parsed the version string from mods hosted on spacedock; setting their release_status to "testing" if it has one of the strings "alpha," "beta," "pre."
This led to some trouble, even for older clients.  Versions of mods that are hosted on spacedock that used to be installable no longer are (some of these had their last release years ago).  Also since non-latest …

Spacedock transformer: remove version string -> release_status parsing

---

Core/DirectoryLink.cs

If you clone an instance and use the shared stock files option from #4129, and then clone the clone again, the resulting final instance's junction symlink entries are invalid.
The target path can end up with a prefix of `\??\\??\`, which is one `\??\` too many.
(Do not ask me wtf that sequence means. I have now read about five explanations of it and still have not the slightest clue. It's just Windows being Windows.)
Now when `DirectoryLink.TryGetTarget` retrieves the target of a junction on Windows, it strips `\??\` prefixes from it. This way when `ReparseDataBuffer.FromPath` adds it again, there'll be only one.
Fixes #4296.

Fix cloning instances with shared stock files on Windows

---

Netkan/Transformers/AvcTransformer.cs

If the GitHub API returns a throttling error when we request a remote version file, a warning is logged:
... and the inflation proceeds without the remote version file, which can cause temporary inaccurate metadata if the remote version file has been updated since release.
Other web errors must be treated as warnings in case the URL itself is invalid, but throttling can also happen for valid URLs.
Now if a request for a remote version file is throttled, it will be treated as an error instead of a warning, so we won't temporarily inflate a mod with partial info.
#4299 did this for repo info requests for SpaceDock mods, but I got sidetracked with all the other stuff and forgot to document it.

Treat throttled remote version file as inflation error

---

GUI/Controls/ModInfoTabs/Versions.cs
GUI/Controls/Wait.cs
GUI/Main/Main.cs

The Versions tab is available on the recommendations screen, but the checkboxes don't do anything, and the stability override dropdown throws an exception:
```
System.InvalidOperationException: This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.
at System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
at CKAN.GUI.Main.RefreshModList(Boolean allowAutoUpdate, Dictionary`2 oldModules)
at CKAN.GUI.Main.StabilityToleranceConfig_Changed(String identifier, Nullable`1 relStat)
at CKAN.Configuration.StabilityToleranceConfig.SetModStabilityTolerance(String identifier, Nullable`1 relStat)
at CKAN.GUI.Versions.StabilityToleranceComboBox_SelectionChanged(Object sender, EventArgs e)
at System.Windows.Forms.ComboBox.OnSelectionChangeCommitted(EventArgs e) …
```

Make versions tab non-interactive inside install flow

---

GUI/Controls/Wait.cs
GUI/Main/MainRepo.cs
GUI/Properties/Resources.resx

CKAN's tray icon has a notification that pops up after a refresh when there are updatable mods. Clicking this begins installation of those updates.
If you do this while an update or install is already in progress, an exception is thrown:
```
System.InvalidOperationException: This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.
at System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
at CKAN.GUI.Main.minimizeNotifyIcon_BalloonTipClicked(Object sender, EventArgs e)
at System.Windows.Forms.NotifyIcon.OnBalloonTipClicked()
at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Similar to #4302, when the progress screen is already busy doing …

Guard rail for clicking refresh with refresh already in progress

---

Core/GameInstanceManager.cs
GUI/Dialogs/CloneGameInstanceDialog.Designer.cs
GUI/Dialogs/CloneGameInstanceDialog.cs
GUI/Dialogs/CloneGameInstanceDialog.resx

In #4129, instance cloning was updated to generate smaller clones by no longer copying the contents of folders that typically have an instance-specific meaning, such as `saves` and `screenshots`.
@linuxgurugamer would like the option to copy some of those dirs anyway.
Now the clone instance dialog has a list of checkboxes for the optional paths. If you leave them unchecked (the default), they won't be copied. If you check them, they will be copied.
Fixes #4298.

Checkboxes to copy more dirs when cloning instances

---

Netkan/Sources/Github/GithubApi.cs
Netkan/Sources/Github/GithubRef.cs
Netkan/Sources/Github/GithubRelease.cs
Netkan/Sources/Github/GithubReleaseAsset.cs
Netkan/Sources/Github/GithubRepo.cs
Netkan/Transformers/GithubTransformer.cs
Tests/NetKAN/Transformers/GithubTransformerTests.cs

If a GitHub release is created by a bot (which can happen when automated tools are used, see KSPModdingLibs/KSPBuildTools#47), the bot is added to the list of authors.
We have logic to filter out bot users already, but it's only applied when we retrieve members of orgs.
Now the user filter is applied to all users retrieved from GitHub, including release creators.
Fixes #4317.

Exclude release author bots from authors list

---

Netkan/Sources/Github/GithubApi.cs
Netkan/Sources/Github/GithubRelease.cs
Netkan/Transformers/GithubTransformer.cs

If a netkan has an `asset_match` that filters out the entire first page of releases on GitHub, then releases on later pages won't be found.
At the moment this only affects RP-0, which last had a matching release (starting with `v1`) six pages (19 months) ago:
- <https://github.com/KSP-RO/RP-1/releases?page=6>
(We might want to freeze that one anyway, if it's never going to have another release and is costing us 6 API hits per inflation...)
#4318 refactored the GitHub API to make a `GithubRelease` object accurately reflect the upstream data instead of processing it, which required moving the filtering logic from `GithubRelease`'s constructor to `GithubApi.GetAllReleases`. In the process, the empty-page check was moved after the filtering instead of before, so the loop stopped at the first …

Find releases past all-filtered-out pages on GitHub

---

Core/SteamLibrary.cs

Fixes #4321 by adding a special case for .NET 8+
- <https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix>

Fix searching for Steam in .NET 8 by correcting path on macOS

---

GUI/Dialogs/EditLabelsDialog.Designer.cs
GUI/Dialogs/EditLabelsDialog.cs
build.ps1
build.sh

@udkudk sometimes uses a large TV as a monitor, on which the Edit Labels window is small and hard to read.
Now the static, `Anchor`-based layout of this dialog is replaced with a resizable `Dock`-based layout using `LeftRightButtonPanels` for the buttons and a `SplitContainer` for the main left/right divider. This will allow the user to choose the size they prefer for the dialog and its halves.
Fixes #4292.

Resizable layout for Edit Labels dialog

---

Core/GameInstance.cs
Core/SteamLibrary.cs
GUI/Controls/ManageMods.cs
GUI/Main/Main.cs
GUI/Properties/Resources.resx

@Clayell has requested some sort of visual feedback when the Play button has been clicked due to fear of accidentally clicking twice.
Now if you click Play, the button is disabled and its caption changes to "Playing...":
When the game exits, the caption resets and the button is re-enabled.
Fixes #4286.
It turns out that the `steam://` commands don't notify us at all when they exit, so if we applied this new "Playing..." behavior to them, the Play button would remain in that state forever. Since that's bad, clicking a Steam command will not change the Play button at all, as it was before.
In line with the above, the in-CKAN play time counting from #3543 now excludes `steam://` commands, since it can't be accurate without finding out when the game has closed. This should be fine because …

Disable Play button while playing game

---

Core/Relationships/RelationshipResolver.cs

If you install the pre KSP-CKAN/NetKAN#10405 versions of `RocketSoundEnhancement` and `RocketSoundEnhancement-Config-Default`, then refresh your registry with the metadata after that PR, the Update checkbox appears for you to reinstall those mods, but checking it just for `RocketSoundEnhancement` throws an exception:
```
System.ArgumentException: Already contains module: RocketSoundEnhancement-Config-Default
at CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
at CKAN.RelationshipResolver.ResolveStanza(List`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
at …
```

Allow adding already installed mod if metadata changed

---

Core/Extensions/EnumerableExtensions.cs
Core/Games/KerbalSpaceProgram2.cs

KSP-CKAN/KSP2-NetKAN#190 is failing with this error:
```
Error: 9321 [1] ERROR CKAN.CmdLine.ConsoleUser (null) - Could not find a part of the path "/game-instance/KSP2_x64_Data/Plugins/x86_64/zlib.dll".
```
However, if I save the generated metadata to a .ckan file locally, it installs without problems.
Fake instances have `KSP2_x64_Data` but not the full `KSP2_x64_Data\Plugins\x86_64` hierarchy that the full game has, so the installer can't put files there.
Now we generate `KSP2_x64_Data\Plugins\x86_64` fully so fake KSP2 instances will be more faithful to real ones, and Planety might be able to pass the tests.

Generate more plugins folders in fake KSP2 instances

---

Core/Registry/Registry.cs
Core/Registry/RegistryManager.cs
Tests/Core/ModuleInstallerDirTest.cs
Tests/Core/Net/NetFileCacheTests.cs
Tests/Core/Registry/Registry.cs
Tests/Core/Registry/RegistryManager.cs
Tests/Core/Relationships/RelationshipResolverTests.cs
Tests/GUI/Model/ModList.cs

When a new game instance is added, an empty `Registry` object is created, saved to `registry.json`, then immediately loaded from that file. Serializing an object that contains no useful data, saving it to disk, then loading it back from disk and deserializing it, is wasteful of CPU, disk throughput, and time.
One user reported an exception after adding an instance on a Mac in ConsoleUI:
```
System.IO.IOException: Sharing violation on path /volumes/tf-256/ksp files/ksp modded/CKAN/registry.json
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <207d12884485488d9288cc8cbf474289>:0 
at System.IO.FileStream..ctor …
```

Don't save registry.json at instance creation

---

Core/CKAN-core.csproj
GlobalAssemblyInfo.cs
build/BuildContext.cs
build/Program.cs
debian/copyright

The `ckan version` and `ckan help` commands are missing a `.` when they print the version:
```
$ ckan version
v1.36.125098
```
That should read `v1.36.1.25098`. You can tell because the first two digits of the last piece are supposed to represent the year.
These commands call `Meta.GetVersion(VersionFormat.Full)`, which returns the `InformationalVersion` assembly attribute:
https://github.com/KSP-CKAN/CKAN/blob/c50b77f11c6805dd6ffa9d6d8c09ccabc00c4731/Core/Meta.cs#L41-L44
This is generated based on Cake's `SemVersion.ToString()`:
https://github.com/KSP-CKAN/CKAN/blob/c50b77f11c6805dd6ffa9d6d8c09ccabc00c4731/build/Program.cs#L92-L102
Which returns `Major.Minor.PatchMeta`, with no delimiter betwen `Patch` and `Meta`:
https://github.com/cake-build/cake/blob/d6c0cc3a0eb5a1432566a9c1db2399d48ff …

Fix ckan version command and update copyrights

---

Core/Properties/Resources.resx
Core/Registry/Registry.cs
Core/Registry/RegistryManager.cs
Core/Types/Kraken.cs
GUI/CKAN-GUI.csproj
GUI/Dialogs/AskUserForAutoUpdatesDialog.Designer.cs
GUI/Dialogs/ErrorDialog.Designer.cs
GUI/Dialogs/ErrorDialog.cs
GUI/Main/Main.cs

`Registry.registry_version` was created to track changes in the format of the registry:
| `registry_version` | Effects
| -- | -- |
| 0 | The keys of `installed_files` will be renormalized after deserialization (see 1de77dd50bc606e9cd8467688a44c1e780a86b2c and #177)
| 0 or 1 | The identifier `001ControlLock` will be migrated to `ControlLock` in `installed_modules` (see #980) |
| 2 | No effect, but corresponds to when `license` became an array (see #1132) |
The current max version is 3, and it hasn't been changed in almost ten years.
If we do change the value of this property again in the future, it would be good for the registry to check it and react appropriately if it indicates a later version of the registry that we can't parse. Currently it does nothing.
Now if `registry_version` is …

Detect future registry versions

---

Core/CkanTransaction.cs

.NET 7 added a setter for the max transaction timeout, which means it's no longer necessary to use reflection on that runtime.

Use setter instead of reflection to set max transaction timeout

---

GUI/Controls/ModInfoTabs/Metadata.Designer.cs
GUI/Controls/ModInfoTabs/Metadata.cs
GUI/Controls/ModInfoTabs/Metadata.resx

- Added `DownloadCountTextBox.Text = gui_module.DownloadCount` into `Metadata.cs`
- Added `<data name="DownloadCountTextBox.Text" xml:space="preserve"><value>Downloads:</value></data>` for the Download Count to show up in the Metadata Tab
- Added `this.DownloadCountTextBox = new System.Window.Forms.Label();`
- Added `private System.Windows.Forms.TextBox DownloadCountTextBox;`
- Added `private CKAN.GUI.TransparentTextBox DownloadCountTextBox;`
- Some other changes were done too, but I didn't list them for now.

Add download count to Metadata Tab

---

Core/IO/ModuleInstaller.cs
Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
Core/Relationships/RelationshipResolver.cs
Core/Versioning/UnmanagedModuleVersion.cs
GUI/Controls/ModInfoTabs/Versions.Designer.cs
GUI/Controls/ModInfoTabs/Versions.cs
GUI/Localization/fr-FR/Main.fr-FR.resx
GUI/Main/Main.resx
GUI/Model/ModList.cs
Tests/CmdLine/UpgradeTests.cs
Tests/Core/Net/NetAsyncDownloaderTests.cs
Tests/Core/Net/NetAsyncModulesDownloaderTests.cs
Tests/Core/Registry/Registry.cs
Tests/Data/TemporaryDirectory.cs
Tests/Data/TestData.cs
build/Program.cs

If you install OuterPlanetsMod 1.6.5, KopernicusTech is automatically installed as a dependency. If you then try to upgrade to the latest OuterPlanetsMod, KopernicusTech's conflict with Kopernicus causes an `InconsistentKraken` to be thrown that prevents the upgrade from finishing.
- Now the `RelationshipResolver` no longer passes modules that are to be removed to the `ResolvedRelationshipsTree`, which would have caused them to be treated as if they were not being removed.
- Now `IRegistryQuerier.FindRemovableAutoInstalled` has a separate `installing` parameter that it passes to `Registry.FindReverseDependencies` so the relationships of installing modules won't be treated as "broken" if they're not satisfied, which would have prevented some installable modules from being treated as …

Fix upgrading with conflicts between old and new dependencies

---

Core/IO/ModuleInstaller.cs
Core/Registry/CompatibilitySorter.cs
Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
Core/Relationships/ResolvedRelationship.cs
Core/Relationships/ResolvedRelationshipsTree.cs
Core/Relationships/SanityChecker.cs
Core/Repositories/AvailableModule.cs
Core/Types/RelationshipDescriptor.cs
Tests/Core/Relationships/SanityChecker.cs

As of recently in the dev build, modules with changed metadata can be added to the changeset for reinstallation, but the reinstallation doesn't happen. The install flow completes with zero actions taken.
In #4369, this change was intended to prevent re-installation of dependencies that weren't supposed to be reinstalled:
https://github.com/KSP-CKAN/CKAN/blob/400d25cb8bef8deadc861262905b872609c36953/Core/IO/ModuleInstaller.cs#L1321-L1323
That only makes sense for modules we're not trying to reinstall. For modules that we _are_ trying to reinstall, this cancels the reinstallation.
- Now explicitly requested modules are kept in the changeset used by `ModuleInstaller.Upgrade`
- To ensure the immutability of the `modules` param of `ModuleInstaller.Upgrade`, its type signature is now `in …

Fix reinstalls, use read-only collections

---

Core/Registry/IRegistryQuerier.cs
Core/Registry/Registry.cs
GUI/Controls/ManageMods.cs
GUI/Controls/ModInfoTabs/Relationships.cs
Tests/CmdLine/UpgradeTests.cs
Tests/Core/Registry/Registry.cs
Tests/Data/TestData.cs
bin/ckan_merge_pr.py

After #4369, the dev build pauses for several seconds after you click the install or upgrade checkboxes when you have many auto-installed mods installed.
6fc2c487a05725ab881ccf2cee95acb5fd32c9d0 updated `IRegistryQuerier.FindRemovableAutoInstalled` to run a new `RelationshipResolver` for every auto-installed mod (previously only one was shared among all the mods), in order to handle complex relationship changes during upgrades. This is a non-trivial cost for an inner loop, such as for 70-ish auto-installed mods.
Now `IRegistryQuerier.FindRemovableAutoInstalled` uses just one `RelationshipResolver` to calculate the changes needed to satisfy relationships for newly installed mods, then checks the `depends` relationships of the installed mods to determine which auto-installed mods are still …

Faster logic for finding removable auto-installed

---

Core/Converters/JsonParallelDictionaryConverter.cs
Core/Extensions/EnumerableExtensions.cs
Core/Extensions/ExceptionExtensions.cs
Core/Extensions/Polyfills.cs
Core/Net/NetAsyncModulesDownloader.cs
Core/Net/NetFileCache.cs
Core/Registry/InstalledModule.cs
Core/Registry/Registry.cs
Netkan/Services/IModuleService.cs
Netkan/Services/ModuleService.cs
Netkan/Validators/InstallsFilesValidator.cs
Netkan/Validators/PluginsValidator.cs
Tests/AutoUpdate/ResourcesTests.cs
Tests/CmdLine/ResourcesTests.cs
Tests/ConsoleUI/ResourcesTests.cs
Tests/Core/Configuration/FakeConfiguration.cs
Tests/Core/IO/ModuleInstallerTests.cs
Tests/Core/ResourcesTests.cs
Tests/GUI/ResourcesTests.cs
build/Program.cs

The Inflator has been emitting `Index was outside the bounds of the array.` errors for a while now, which cannot be reproduced locally. After #4398, we captured the full stack trace:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at CKAN.NetFileCache.GetFileHash(String filePath, String hashSuffix, Dictionary`2 cache, Func`1 getHashAlgo, IProgress`1 progress, Nullable`1 cancelToken)
at CKAN.NetKAN.Transformers.DownloadAttributeTransformer.Transform(Metadata metadata, TransformOptions opts)+MoveNext()
at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 …
```

Make hash caches thread-safe, Netkan warning for uncompiled plugins

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/release.yml
Cmdline/CKAN-cmdline.csproj
ConsoleUI/Toolkit/Keys.cs
Core/CKAN-core.csproj
GUI/CKAN-GUI.csproj
Netkan/CKAN-netkan.csproj
Tests/Tests.csproj
build/MakeTasks.cs
macosx/CKAN
macosx/Makefile

- .NET Framework 4.8 was released in April 2019 and updated to 4.8.1 in August 2022. No further non-security updates are planned. We depend on it for the WinForms GUI, but for anything else it would be better to rely on code that's still supported and maintained.
- Mono, which runs .NET Framework code on Linux and Mac (and is still the _only_ way to run WinForms code on those platforms), has been all but abandoned and donated to WineHQ, who have been [maintaining it somewhat](https://gitlab.winehq.org/mono/mono/-/releases) but [not providing releases via the established channels](https://gitlab.winehq.org/mono/mono/-/issues/12).
- The last version of Mac OS X that was able to run the GUI (because it could run Mono in 32-bit mode) was 10.14, released September 2018 and ended support in …

Migrate Mac app bundle from Mono to dotnet

---

macosx/CKAN

In #4410, we updated the Mac app bundle to contain two standalone builds, for `x86_64` and `arm64`, selected at runtime by the main executable shell script based on the output of `uname -m`, which is supposed to print the system architecture.
However, [Macs apparently always launch shell scripts in app bundles as `x86_64` using a tool called Rosetta 2, even on `arm64` architectures](https://stackoverflow.com/a/77441678/2422988) (presumably for backwards compatibility with older apps), which makes `uname -m` useless for the (very ordinary and traditional) purpose for which we're using it.
Now instead of getting the arch from `uname -m`, we check the output of `sysctl -ni hw.optional.arm64`, and if it's `1`, we use `arm64`, otherwise we use `x86_64`.
(I looked into creating a universal …

Check arch with sysctl on Mac

---

Core/Extensions/YamlExtensions.cs
Core/IO/ModuleInstaller.cs
GUI/Controls/EditModSearchDetails.cs
GUI/Controls/ManageMods.cs
GUI/Main/Main.cs
Netkan/Processors/Inflator.cs
Tests/Core/IO/ModuleInstallerTests.cs
Tests/Core/Relationships/RelationshipResolverTests.cs
Tests/Data/DogeCoinFlag.netkan
Tests/Data/TestData.cs
Tests/NetKAN/Processors/InflatorTests.cs

[Coveralls](https://coveralls.io/github/KSP-CKAN/CKAN) says that the file with the most uncovered code, by far, is `Core/IO/ModuleInstaller.cs`.
Now several tests are added to cover previously uncovered parts of `ModuleInstaller`.

Add tests for ModuleInstaller

---

GUI/Controls/ManageMods.cs
GUI/Controls/ModInfo/Versions.cs
GUI/Main/MainDownload.cs
Tests/Core/IO/ModuleInstallerDirTest.cs
Tests/Core/IO/ModuleInstallerTests.cs

For a .ckan file representing a mod not in the user's configured metadata repositories:
- Installing from the .ckan file in GUI causes the Downloads Failed popup to appear with an error message of "The given key was not present in the dictionary." (Though the mod will be successfully cached after download and will install successfully if you try again.)
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at CKAN.GUI.Main.<>c__DisplayClass177_0.<UpdateCachedByDownloads>b__1(CkanModule other)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at CKAN.GUI.Main.UpdateCachedByDownloads(CkanModule module)
at …
```

Fix GUI exceptions for module not in available modules list

---

Core/GameInstanceManager.cs
Core/Games/KerbalSpaceProgram.cs
Core/IO/HardLink.cs
Core/Utilities.cs

- Some of the deduplicator tests failed for me on Linux
```
RunCommand_InstalledMissionInTwoInstances_Deduplicates (317ms): Error Message: System.ArgumentException : Byte array for Guid must be exactly 16 bytes long. (Parameter 'b')
Stack Trace:
at System.Guid..ctor(ReadOnlySpan`1 b)
at System.Guid..ctor(Byte[] b)
at CKAN.IO.HardLink.<>c.<GetFileIdentifiers>b__6_1(Nullable`1[] v) in /home/user/github/CKAN/Core/IO/HardLink.cs:line 110
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.ZipIterator[TFirst,TSecond](IEnumerable`1 first, IEnumerable`1 second)+MoveNext()
at System.Linq.Enumerable.DistinctByIterator[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)+MoveNext()
at …
```

Fix Missions folder cloning and hard link info retrieval

---

GUI/Controls/ManageMods.cs
GUI/Dialogs/CloneGameInstanceDialog.Designer.cs
GUI/Dialogs/CloneGameInstanceDialog.cs
GUI/Main/Main.cs
GUI/Main/MainDownload.cs
GUI/Main/MainHistory.cs
GUI/Model/GUIMod.cs
GUI/Model/ModList.cs
Tests/GUI/GUIConfiguration.cs
Tests/GUI/Model/GUIMod.cs
Tests/GUI/Model/ModChangeTests.cs
Tests/GUI/Model/ModList.cs
Tests/GUI/Model/ModSearchTests.cs
Tests/NetKAN/Validators/KrefValidatorTests.cs

If you clone a KSP1 instance using the "Share stock files" option from #4129, the game throws exceptions like this:
```
[LOG 11:21:03.627] ------------------- initializing flight mode... ------------------
[LOG 11:21:03.627] No save file found for path: /media/DataTrove/Games/KSP-thin-clone-5/KSP_Data/../saves/Testing symlinks/persistent.sfs
[EXC 11:21:03.628] NullReferenceException: Object reference not set to an instance of an object
FlightDriver.Start () (at <be370b73275e49439ea5e41ceef6700f>:0)
[EXC 11:21:03.635] NullReferenceException: Object reference not set to an instance of an object
KSP.UI.Screens.EditorActionGroups.CreateGroups_Action () (at <be370b73275e49439ea5e41ceef6700f>:0)
KSP.UI.Screens.EditorActionGroups.ConstructGroupList () (at <be370b73275e49439ea5e41ceef6700f>:0) …
```

Don't clone with symlinks on Linux
