KSP-CKAN/CKAN

CKAN.schema
As stated in #431, I think this should go into milestone 1.2 since it's a good opportunity to bump the spec.
Since 1.2 is feature-frozen, @pjf, feel free to close / rebase it at will :)
Closes #431.
=> Adds no-derivatives to schema

Spec.md
Strin -> String
realease -> release
=> Typo in Spec.md

bin/close-old-support-tickets.pl
Tested with my own token. :)
For #942
=> Support closing bot shows actual ticket number now.

Spec.md
2 small changes to make sure the spec is up to date with reality.
=> Small fixes to spec.md

Spec.md
=> Update versioning in spec.md to reflect behavior

Spec.md
=> Revert "Update versioning in spec.md to reflect behavior"

GUI/MainModList.cs
=> Focuses the mod list when it's updated

GUI/Main.Designer.cs, GUI/Main.cs, GUI/SettingsDialog.Designer.cs, GUI/SettingsDialog.cs
Simple implementation of #1024 without any recents list.
=> Move KSP Install selection to File menu

Cmdline/Main.cs, Cmdline/Options.cs
It is non functional and may never have been functional. It just replicates the --show-console option to GUI.
Closes #1064
=> Remove the GUI-with-console command.

Core/Platform.cs, GUI/Main.Designer.cs, GUI/MainModList.cs
See https://github.com/KSP-CKAN/CKAN/issues/224 for details.
Closes #224.
Thanks to @Valuial for help with diagnosing and testing.
=> Work around for mono bug in versions <4.0.0

policy/README.md, policy/de-indexing.md, policy/version-comparison.md
This PR provides a more permanent home for some of the policies we've discussed. By having these files in git we can more easily track changes to them and ensure appropriate peer review.
Closes #963.
Closes #1078.
=> CKAN policy documents

Netkan/Github/GithubRelease.cs
=> Filter asset_match when getting github repository

Cmdline/Action/Install.cs
=> Fix commandline install with -c to exit if it can not find the file.

Cmdline/Action/Install.cs, Cmdline/Main.cs
This allows the user to attempt to fix inconsistent installs manually.
Closes https://github.com/KSP-CKAN/CKAN/issues/421
=> Allow attempts to install files to inconsistent instances.

Cmdline/Action/Show.cs, Core/Types/Module.cs, GUI/MainModInfo.cs
By the spec a mod can have more than one.
Also make the appropriate changes to the gui and cmdline
=> Change licence in Module to be a list of licences.

Core/KSPManager.cs, Core/Registry/Registry.cs, Core/Relationships/RelationshipResolver.cs, Core/Types/Module.cs, Tests/Core/Relationships/RelationshipResolver.cs
Moved here from https://github.com/KSP-CKAN/CKAN-core/pull/116
=> Rel resolver rework

Core/Registry/AvailableModule.cs, Core/Registry/Registry.cs, Core/Relationships/RelationshipResolver.cs, Core/Types/Module.cs, Core/Types/Version.cs, Tests/Core/Relationships/RelationshipResolver.cs
Moved from https://github.com/KSP-CKAN/CKAN-core/pull/120 .
Closes #304
=> RelResolver version handling

Core/ModuleInstaller.cs, Core/Net/NetAsyncDownloader.cs
4ba407e is the actual fix - the cancel was being called on a separate instance of the downloader. 
Closes #1088
Closes #1102 
Closes #1023 
Revisit #848
=> Fix canceling mod downloads. 

GUI/GUIMod.cs, GUI/Main.cs, GUI/MainChangeset.cs, GUI/MainInstall.cs, GUI/MainModInfo.cs, GUI/MainModList.cs, GUI/Program.cs, Tests/GUI/MainModList.cs
Allows the GUI to uninstall mods that are not in the repo such as custom .ckans. 
Closes KSP-CKAN/CKAN#746
=> Mods not in repo

GUI/MainInstall.cs
=> Stop existing files from stalling the GUI on install

GUI/Main.Designer.cs, GUI/Main.cs
Tested on Windows 8.1, and Ubuntu 14.04.
fixes #1010
=> Add "Open KSP Directory" entry to the File toolstrip

GUI/SettingsDialog.cs
The gui presents the user with a simple yes / no dialog.
fixes #1137
=> ask the user if he really wants to delete their cache

Core/CKAN-core.csproj, Core/Net/AutoUpdate.cs, Core/Types/CKANVersion.cs
In the autoupdate dialog of the gui and cmd,
and also in the settings dialog
=> The fancy version name is now shown

GUI/ChooseKSPInstance.Designer.cs, GUI/ChooseKSPInstance.cs
In the "Select KSP Instance" dialog.
Closes #1194
=> Renamed the Delete Button to Forget

Core/ModuleInstaller.cs
Simply check if there is anything in the list of mods to remove before
doing anything else.
=> Fixes #1179

Cmdline/Action/Remove.cs, Cmdline/Options.cs
=> Adds a remove all option to cmdline.

GUI/Main.Designer.cs, GUI/Main.cs
=> Double click on row (de)selects mod

Core/CKAN-core.csproj, Core/Converters/JsonIgnoreBadUrlConverter.cs, Core/Types/Module.cs, Tests/Core/Types/Module.cs
Fixes #1208, which is preventing some mods from indexing correctly.
=> Bad resource links will no longer kill Module construction.

GUI/Main.cs
when clicking on the column headers of the modlist.
=> Fix for an argumentoutofrangeexception

AutoUpdate/Main.cs
=> CKAN Updater is no longer confused about spaces.

AutoUpdate/Main.cs, Cmdline/Action/Repo.cs, Cmdline/Action/Update.cs, Cmdline/Main.cs, Core/Registry/AvailableModule.cs, Core/Registry/Registry.cs, Core/Relationships/RelationshipResolver.cs, Core/Types/Module.cs, GUI/GUIMod.cs, GUI/Main.cs, GUI/MainDialogs.cs, GUI/MainModList.cs, Tests/Core/Types/Module.cs, Tests/Core/Types/ModuleInstallDescriptorTests.cs, Tests/Data/TestData.cs, Tests/Tests.csproj
Clear out some todos from the codebase.
=> Clear out multiple TODOs in the codebase

Spec.md
=> More exactly define character classes in spec

Core/Registry/Registry.cs
Sometimes I document code when I read it. :)
No code changes.
=> Documentation on GetModuleByVersion

GUI/Main.Designer.cs, GUI/Main.cs, GUI/MainModInfo.cs
=> Double click on the dependency graph navigates to the mod

GUI/GUIMod.cs
Closes #1296.
Yes, my "tidying" of the code in #1295 changed the logic. Ooops!
Thanks to @plague006 for spotting this. :)
=> Fix empty "latest" column in GUI.

GUI/Configuration.cs, GUI/Main.cs, GUI/MainRepo.cs, GUI/SettingsDialog.Designer.cs, GUI/SettingsDialog.cs
and ask the user, if it should be done everytime
also adds this option to the setting dialog
closes #1275, closes #1020
=> Refresh on first startup

GUI/Main.cs
when double clicking on AD mods
fixes #1235
=> Fix for an invalidcastexception

Cmdline/Action/Compare.cs, Cmdline/Main.cs
also made the output more user friendly
fixes #1279
=> fixed compare command throwing an ArgumentNullException

Spec.md
I'm relatively content with how I have it phrased, but I'd be happy to have someone express it better.
Closes #1119
=> Update spec.md to clarify the identifier's case sensitivity

GUI/MainInstall.cs
This allows the user to cancel them,
and also reverts the changes made to the filesystem and registry
fixes #454
=> wrap the remove, upgrade and installation in a transaction

GUI/KSPCommandLineOptionsDialog.Designer.cs, GUI/KSPCommandLineOptionsDialog.cs, GUI/Main.cs
Made the dialog accept enter and escape to accept or cancel the changes.
Also made the buttons flat and did a small code cleanup
=> Commandline argument dialog changes

Core/Registry/RegistryManager.cs, Core/Types/ExportFileType.cs, GUI/Main.cs
=> Added "ckan favourite list" as export possibility

Spec.md
=> Update spec.md to 1.12 (update install_to folders)

GUI/Main.cs
on auto refresh at startup
fixes #1368
=> Fixed marking of mods as new if they are uninstalled

CHANGELOG.md, CKAN.schema, Core/KSP.cs, Core/ModuleInstaller.cs, Spec.md, Tests/Core/ModuleInstaller.cs
Closes #1358.
This feels like it was really easy to add, but it's a fairly straightforward change.
=> Add support for installing to Scenarios

GUI/GUIMod.cs
=> Show latest version of incompatible mod

GUI/GUIMod.cs, GUI/Main.Designer.cs, GUI/Main.resx, GUI/MainModList.cs
this column shows the download_size in KB
if no download_size is given, it shows 0 KB
implements #1136 
This is how the gui Looks now:
=> Added a size column

Core/Registry/InstalledModule.cs, Core/Types/Module.cs
Here's your chance to merge a PR!! :D
=> Fixed various typos and spacing errors. No code changes.

Core/Relationships/RelationshipResolver.cs
=> Search in the previous stanza for the required mod

Core/Registry/IRegistryQuerier.cs
=> We can't update ad mods

GUI/Configuration.cs, GUI/Main.cs
=> Remember the last used filter

Cmdline/Main.cs
We just inject gui into the command :)
fixes #437
=> ckan --verbose" now starts the GUI with verbose debugging

GUI/SettingsDialog.cs
The list is already sorted, so you won't need to know them
=> removed the priorities from the repository list in the settings

.gitignore, Makefile, quotes.txt
@Dazpoet suggested it would be fun to keep a list of memorable CKAN quotes. This does exactly that.
If you're on a unix flavoured system, you can `make fortune` and then `fortune ./quotes.txt` to get a random quote.
=> Add a quotes/fortune file to the repo.

GUI/MainInstall.cs
Hoping this is the right way, got some well needed guidance from @plague006 to find the right place to put it :)
closes #1416
=> Set (de-)select mods checkbox to a more sensible value when processing recommends

CHANGELOG.md
=> Added missing pr number

Core/Types/Repository.cs, GUI/SettingsDialog.cs
=> reordering of repos isn't weird anymore

Core/KSP.cs, Core/ModuleInstaller.cs
also check for severall other directories
which should not be removed
=> Don't remove empty ship folders on uninstall 

GUI/GUIMod.cs, GUI/Main.cs, GUI/MainModList.cs
This allows the user to search by abbrevation when the modlist is focused.
=> Made the modlist searchable by abbrevation 

GUI/GUIMod.cs, GUI/Main.Designer.cs, GUI/Main.cs, GUI/MainModInfo.cs, GUI/MainModList.cs
this filter only shows already cached mods
Closes #1423
=> Added a cached filter

GUI/Main.Designer.cs
this marks the whole row blue
instead of only the cell you clicked
This change is done for the suggested, changeset and tmp list
=> Select full row

GUI/Main.Designer.cs, GUI/MainInstall.cs
For consistency, "Installing mods" doesn't really make sense since we list updates and removals in this tab as well.
=> Change the displayed text of WaitTabPage

quotes.txt
=> *chucklesnort* adding for posterity

CHANGELOG.md, GUI/Main.Designer.cs, GUI/MainModInfo.cs
Recreation of #1470 without Visual Studio designer's extra code because I'm interested to see how travis reacts.
=> Add identifier to metadata panel

Cmdline/Action/Show.cs, Core/CKAN-core.csproj, Core/ModuleInstaller.cs, Core/Registry/IRegistryQuerier.cs, Core/Registry/InstalledModule.cs, Core/Registry/Registry.cs, Core/Registry/RegistryManager.cs, Core/Relationships/RelationshipResolver.cs, Core/Relationships/SanityChecker.cs, Core/Types/CkanModule.cs, GUI/GUIMod.cs, GUI/Main.cs, GUI/MainInstall.cs, GUI/MainModInfo.cs, GUI/MainModList.cs, Tests/Core/Relationships/SanityChecker.cs
the spec_field needed some extra Attention. it was not required for module's, but for ckanmodule's..
closes #1440
=> Merged CkanModule and Module to a single class

GUI/MainModInfo.cs
when user pressed the "Download" button
We use the netasyncdownloader for this
=> show progess of cache download

GUI/MainModList.cs
in the name textbox, and by focusing the main mod list
closes #1474
=> allowed searching by mod identifier

Core/Registry/IRegistryQuerier.cs
=> Virtual mods no longer enable the update box for mods they provide

GUI/MainModList.cs
for a upgrade of a mod to the changeset
fixes #795
=> New dependencies of upgraded mods are scheduled for install by the GUI

Core/Registry/AvailableModule.cs
No code changes here. You can totally merge this now!! :)
=> AvailableModule: Documentation and spacing fixes only.

CKAN.schema
#1243 gave us the ability to install into SPH and VAB, this will reflect that in the schema (I think..)
=> Bring the schema up to date

Core/ModuleInstaller.cs, Spec.md, Tests/Core/ModuleInstaller.cs
=> Allow installation to the @thumbs folders

GUI/Main.cs
Closes https://github.com/KSP-CKAN/CKAN/issues/1571
=> Fix incorrect button text for "Not installed" filter

GUI/GUIMod.cs, GUI/Main.cs, GUI/MainModList.cs
spelling, style, and obsoleted code
=> minor housekeeping

Spec.md
The spec is woefully out of date with regards to all the nifty features we've added for NetKAN. This PR documents all of the ones I can think of.
=> Update Spec with NetKAN information

CHANGELOG.md
Includes #1573, #1581, #1582, #1538, #1584
=> Update changelog with recent changes.

Core/ModuleInstaller.cs, GUI/Main.Designer.cs, GUI/Main.cs
Fixes a thing I broke earlier, remove a redundant `//TODO`, and a redundant settings dialog update
=> Housekeeping

quotes.txt
No code additions, humour not guaranteed, I hope @plague006 is ok with the jab but to me it was a very distinct thing which we all should remember :D
=> Update quotes.txt with more quotes

Core/Types/CkanModule.cs
no code changes, I just couldn't unsee this once I tripped over it.
=> Fix a minimal spelling error

GUI/Main.Designer.cs, GUI/Main.cs, GUI/MainModList.cs
Adds new UI elements, rearranges others somewhat. Allows users to search for text strings in mod abstracts (called "description" in the UI)
The proposed UI changes can be seen here: https://dl.dropboxusercontent.com/u/10499401/FilterbyDescriptionUIChange.png
Tests run: 366, Errors: 0, Failures: 0, Inconclusive: 0, Time: 10.3875286 seconds
Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
Closes #1631
=> Add "Filter by description" to GUI

Netkan/Sources/Spacedock/SDVersion.cs
=> SpaceDock ksp_version is now game_version

CKAN.schema, Spec.md
Because it's a.. kind thing to include everyone. (I'm so sorry, I'm really tired)
Closes https://github.com/KSP-CKAN/CKAN/issues/1152
=> Add `kind` to the spec

Netkan/CKAN-netkan.csproj, Netkan/Sources/Github/GithubApi.cs, Netkan/Sources/Github/GithubRepo.cs, Netkan/Sources/Github/IGithubApi.cs, Netkan/Transformers/GithubTransformer.cs, Tests/NetKAN/Transformers/GithubTransformerTests.cs
@pjf @techman83 @KSP-CKAN/wranglers 
This PR allows the GitHub transformer to write `abstract` based upon the repository description and `resources.homepage` based upon the repository website.
=> GithubTransformer Enhancements

CHANGELOG.md, Core/Net/NetAsyncDownloader.cs, GUI/SettingsDialog.Designer.cs, GUI/SettingsDialog.cs
=> Fix unit of measure for download speed

CKAN.schema, Core/Types/License.cs
Closes https://github.com/KSP-CKAN/CKAN/issues/1113
=> Add Unlicense

CONTRIBUTING.md, README.md
Closes https://github.com/KSP-CKAN/CKAN/issues/1745
=> More clearly define how users and mod authors can contribute

CHANGELOG.md, Spec.md
Fixes/compliments https://github.com/KSP-CKAN/CKAN/pull/1737
=> Update changelog with missing info, add unlicense to spec

Spec.md
=> State requirements for metanetkans

policy/Opt-out-list.md
Seeing that this has settled down, I am ready to re-list my mods in CKAN, therefore there is no need to be on this list anymore.
=> Remove myself from opt-out

Cmdline/Main.cs
=> Ignore ksp instances if we are launching the gui anyway

README.md
It looks nice and it's good motivation.
=> Add downloads counter to readme

policy/Opt-out-list.md
Reference: https://github.com/KSP-CKAN/NetKAN/pull/4294 and forum OP's of his mods.
=> Add Angel-125 to opt-out list

GUI/Main.Designer.cs, GUI/Main.cs
I've been trying to figure out a way to write a unit test for this, since it's pretty easy for this to get clobbered by someone using the forms designer.
Closes #1891
=> Reduce MinimumSize for main window to 1280x700

Core/Relationships/RelationshipResolver.cs, GUI/MainModList.cs, Tests/GUI/MainModList.cs
Fixes and duplicates #1371 and #1373 respectively.
=> Fix TargetInvocationException and improve mod conflict GUI test

GUI/Main.Designer.cs, GUI/Main.cs
Should fix #1011, but needs some in-the-field testing because not all of the colors are necessarily mapped well under the common dark themes.
=> Use SystemColors to source various UI colors

Core/Net/NetAsyncDownloader.cs
=> Fix Chicken bits from #2023

GUI/AboutDialog.cs
Previous thread accidentally deleted
=> Update Forum Thread link to new thread

CONTRIBUTING.md
As per http://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1223-mahia/&do=findComment&comment=3143297
=> Fix forum thread link

CHANGELOG.md, GUI/GUIMod.cs, GUI/Main.cs, GUI/MainDialogs.cs, GUI/MainModList.cs
This reverts commit 85d72b64c3e2d1db1bbc5e608a52eafb82c15c5e, reversing
changes made to bcf87c20409b292f85abcb0ddeef622542ed585d.
=> Revert "Merge #1929 Allow uninstall of incompatible mods in GUI"

GUI/URLHandlers.cs
When it starts up, the CKAN GUI adds support for `ckan://identifier` URLs on Windows and Linux.
On Windows, it does this by adding this registry key:
CKAN might need to escalate privileges to make these changes. It detects this after the fact by catching an `UnauthorizedAccessException` when it attempts to set the registry key. If this exception is thrown, ckan.exe re-launches itself as administrator with the `registerUrl` command line flag, which prompts the user whether to allow the increased privileges and then sets the registry key.
The user might see this error when launching CKAN:
```
8468 [1] ERROR CKAN.URLHandlers (null) - There was an error while registering the URL handler for ckan:// - Cannot delete a subkey tree because the subkey does not exist.
8485 [1] ERROR …
```
=> Clean up url handler registration

GUI/SettingsDialog.cs
Revised error message if `AutoUpdate` is blocked with more details and better link.
@HebaruSan ; @politas 
#2407
=> Better AutoUpdate.CanUpdate Error Message

policy/Opt-out-list.md
https://forum.kerbalspaceprogram.com/index.php?/topic/149706-13-collide-o-scope-v116/&do=findComment&comment=3481874
=> adding DefiantZombie to Opt-out-list.md

GUI/MainModInfo.cs
A satisfiable dependency can be displayed as unsatisfiable if it is an incompatible real module that is also provided by some other compatible module. For example we have this situation right now in KSP 1.4.5 with RealismOverhaul's dependency on KerbalJointReinforcement, which is provided by KerbalJointReinforcementContinued:
We only check `LatestAvailableWithProvides` if `LatestAvailable` throws an exception, which only happens if the identifier doesn't exist as a real module at all in the registry:
https://github.com/KSP-CKAN/CKAN/blob/421332c3abf30e3cf52adc81d6cd77743c2592d2/GUI/MainModInfo.cs#L306-L322
Now we check `LatestAvailableWithProvides` first. If it finds only one hit with a matching identifier, we return a normal node. If it finds multiple hits or one with a non-matching …
=> Handle semi-virtual dependencies in Relationships tab

Netkan/Processors/QueueHandler.cs
See #2874; currently the Inflator sends output messages and deletes input messages one at a time as it processes each input batch of 10 messages. It would be cheaper in terms of SQS queue costs to send and delete in batches the same way we receive the input in batches.
Now all the response objects for a given batch of input message are collected together and sent in as few batches as possible, and the input messages are deleted in a batch. This should cut down the number of SQS requests used by the Inflator (hopefully by a lot).
This will delay each batch's updates until everything in the batch is finished processing, but we think this is a trade-off worth making.
Fixes #2874.
=> Batch inflator responses

GUI/Main.cs
If you set up a new instance of KSP 1.8 on Linux, launch CKAN, and click Launch KSP, nothing appears to happen. Behind the scenes if you turn on debugging output, the game is launching and immediately crashing:
```
Set current directory to /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program
Found path: /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/KSP.x86_64
Segmentation fault (core dumped)
```
CKAN's default command line for Linux is `./KSP.x86_64 -single-instance`. The `-single-instance` argument was added in #1255 to un-shoot the feet of users who double click the button, which otherwise would launch multiple game instances.
As investigated by @hinneLinks, a bug in current Unity causes a segmentation fault when `-single-instance` is passed: …
=> Don't launch KSP 1.8 with -single-instance

GUI/Localization/zh-CN/EditModSearch.zh-CN.resx, GUI/Properties/Resources.zh-CN.resx
=> Added Chinese translation of multiple search category fields.

Netkan/CKAN-netkan.csproj, Netkan/Validators/CkanValidator.cs, Netkan/Validators/TagsValidator.cs
Now that we have Netkan warnings, we can finally do something about netkans that don't set tags without blocking them from being indexed.
=> Netkan warning for tags

GUI/Localization/fr-FR/CompatibleGameVersionsDialog.fr-FR.resx, GUI/Localization/fr-FR/EditModSearchDetails.fr-FR.resx, GUI/Localization/fr-FR/Main.fr-FR.resx, GUI/Localization/fr-FR/ManageMods.fr-FR.resx, GUI/Localization/fr-FR/ModInfo.fr-FR.resx, GUI/Localization/fr-FR/SelectionDialog.fr-FR.resx, GUI/Localization/fr-FR/SettingsDialog.fr-FR.resx, GUI/Localization/fr-FR/Wait.fr-FR.resx, GUI/Properties/Resources.fr-FR.resx
Just some extra spelling fixes, nothing big
=> Fixes for French

GUI/Main/Main.cs, GUI/Properties/Resources.resx
=> Make Incompatible Mods warning dialog use newlines instead of commas

AutoUpdate/CKAN-autoupdate.csproj, AutoUpdate/Properties/Resources.ru-RU.resx, Cmdline/Properties/Resources.fr-FR.resx, ConsoleUI/Properties/Resources.ru-RU.resx, Core/Properties/Resources.fr-FR.resx, GUI/CKAN-GUI.csproj, GUI/Localization/fr-FR/SettingsDialog.fr-FR.resx, GUI/Localization/pl-PL/SettingsDialog.pl-PL.resx, GUI/Localization/ru-RU/DownloadsFailedDialog.ru-RU.resx, GUI/Localization/ru-RU/GameCommandLineOptionsDialog.ru-RU.resx, GUI/Localization/ru-RU/InstallFiltersDialog.ru-RU.resx, GUI/Localization/ru-RU/Main.ru-RU.resx, GUI/Localization/ru-RU/NewRepoDialog.ru-RU.resx, GUI/Localization/ru-RU/PlayTime.ru-RU.resx, GUI/Localization/ru-RU/Relationships.ru-RU.resx, GUI/Localization/ru-RU/RenameInstanceDialog.ru-RU.resx, GUI/Localization/ru-RU/YesNoDialog.ru-RU.resx, GUI/Properties/Resources.fr-FR.resx, GUI/Properties/Resources.pl-PL.resx
This is like #3835 without conflicts, which I suspect were caused by [Crowdin](https://crowdin.com/project/ckan) lacking many recent changes from the master branch (notified @Olympic1 about this on Discord in hopes of having it fixed). I used the `bin/git-xml-diff.sh` tool to find and remove bad changes (conflicts and attempted reversions of changes that should not be reverted) while igoring format-only changes.
=> Translation updates from Crowdin

policy/Opt-out-list.md
@AstroWell has asked to be removed from the opt-out list on Discord.
=> Remove Well from Opt-out-list

policy/Opt-out-list.md
@Angel-125 has requested to be removed from the opt-out list:
- <https://forum.kerbalspaceprogram.com/topic/202746-min-ksp-111-wip-sunkworks-maritime-technologies/?do=findComment&comment=4400429>
Your wish is granted! 🧞
=> Remove Angel-125 from opt-out list

GUI/Localization/zh-CN/NewUpdateDialog.zh-CN.resx
为什么有人会把一些梗放在这里？？？
我有点点生气，这是管理工具，不是玩梗场所啊
Translation from ChatGPT:
Why do some people put memes here??? I'm a bit annoyed; this is a management tool, not a place for jokes.
=> New Translation of NewUpdateDialog.zh-CN.resx

GUI/Localization/zh-CN/NewUpdateDialog.zh-CN.resx
Because of the length of a string was toooooooo long, I have just simplified it.
=> changed NewUpdateDialog.zh-CN.resx

Cmdline/Properties/Resources.fr-FR.resx, ConsoleUI/Properties/Resources.fr-FR.resx, GUI/Localization/fr-FR/CloneGameInstanceDialog.fr-FR.resx, GUI/Properties/Resources.fr-FR.resx
@vinix38 has created or updated several strings in the French translation.
=> French translation updates from Crowdin

Cmdline/Properties/Resources.fr-FR.resx, Core/Properties/Resources.fr-FR.resx, GUI/Localization/fr-FR/AskUserForAutoUpdatesDialog.fr-FR.resx, GUI/Localization/fr-FR/EditModSearchDetails.fr-FR.resx, GUI/Localization/fr-FR/EditModpack.fr-FR.resx, GUI/Localization/fr-FR/Main.fr-FR.resx, GUI/Localization/fr-FR/PluginsDialog.fr-FR.resx, GUI/Localization/it-IT/EditModSearchDetails.it-IT.resx, GUI/Localization/pt-BR/EditModSearchDetails.pt-BR.resx, GUI/Localization/zh-CN/EditModSearchDetails.zh-CN.resx, GUI/Properties/Resources.fr-FR.resx
More updates from @vinix38, plus three translations for which Crowdin has no attribution or record, but which seem to be correct, so I'm adding them anyway.
=> More translation updates

Cmdline/Properties/Resources.fr-FR.resx, GUI/Localization/de-DE/CompatibleGameVersionsDialog.de-DE.resx, GUI/Localization/fr-FR/CompatibleGameVersionsDialog.fr-FR.resx, GUI/Localization/fr-FR/Relationships.fr-FR.resx, GUI/Localization/it-IT/CompatibleGameVersionsDialog.it-IT.resx, GUI/Localization/it-IT/Relationships.it-IT.resx, GUI/Localization/ja-JP/CompatibleGameVersionsDialog.ja-JP.resx, GUI/Localization/ko-KR/CompatibleGameVersionsDialog.ko-KR.resx, GUI/Localization/nl-NL/CompatibleGameVersionsDialog.nl-NL.resx, GUI/Localization/nl-NL/Relationships.nl-NL.resx, GUI/Localization/pl-PL/CompatibleGameVersionsDialog.pl-PL.resx, GUI/Localization/pl-PL/Relationships.pl-PL.resx, GUI/Localization/pt-BR/CompatibleGameVersionsDialog.pt-BR.resx, GUI/Localization/pt-BR/Relationships.pt-BR.resx, GUI/Localization/ru-RU/CompatibleGameVersionsDialog.ru-RU.resx, GUI/Localization/ru-RU/Relationships.ru-RU.resx, GUI/Localization/zh-CN/CompatibleGameVersionsDialog.zh-CN.resx, GUI/Localization/zh-CN/Relationships.zh-CN.resx, GUI/Properties/Resources.fr-FR.resx
- Lots of French updates from @vinix38
- Renaming the compatible versions dialog string translations from 865f76f7ed60969a974f029c8498b7864865638c
=> I18n updates from Crowdin

Cmdline/Properties/Resources.fr-FR.resx, ConsoleUI/Properties/Resources.fr-FR.resx, Core/Properties/Resources.fr-FR.resx, GUI/Localization/fr-FR/SettingsDialog.fr-FR.resx, GUI/Localization/fr-FR/Versions.fr-FR.resx, GUI/Properties/Resources.fr-FR.resx
@vinix38 has created or updated several strings in the French translation.
<https://crowdin.com/project/ckan>
=> French translation updates

.github/workflows/sign.yml
This bumps the SignPath action tag to 1.1.
=> ci: Bumping Signing request tag

GUI/Localization/fr-FR/InstallationHistory.fr-FR.resx, GUI/Localization/pl-PL/ChooseRecommendedMods.pl-PL.resx, GUI/Localization/pl-PL/InstallationHistory.pl-PL.resx, GUI/Localization/pl-PL/Main.pl-PL.resx, GUI/Localization/pl-PL/PreferredHostsDialog.pl-PL.resx, GUI/Localization/pl-PL/SettingsDialog.pl-PL.resx, GUI/Localization/pl-PL/UnmanagedFiles.pl-PL.resx, GUI/Properties/Resources.fr-FR.resx, GUI/Properties/Resources.pl-PL.resx
Doesn't cover 100% of missing translations, but these are 99% "most visited/read" ones, I guess
=> Add some missing Polish translations

Netkan/Services/CachingHttpService.cs
I just spotted this error in the status page (for RasterPropMonitor-Core, which is not responsible for it):
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
at CKAN.NetKAN.Services.CachingHttpService.DownloadPackage(Uri url, String identifier, Nullable`1 updated, Uri primaryUrl)
at CKAN.NetKAN.Services.CachingHttpService.DownloadModule(Metadata metadata)
at CKAN.NetKAN.Validators.VrefValidator.Validate(Metadata metadata)
at CKAN.NetKAN.Transformers.AvcTransformer.Transform(Metadata metadata, TransformOptions …
```
=> Make CachingHttpService more thread-safe
