- CKAN.schema
- Spec.md
Supercedes https://github.com/KSP-CKAN/CKAN/pull/619 , as I don't know how to modify PRs from repos that don't exist anymore :blush: 
For use in the Jenkins inflator support in KSP-CKAN/CKAN#195, I want to add a "ci" property to the list of possible resources.
The current netkan.exe reads "x_ci" as a fallback, but having a properly defined property in the schema would make validation possible.
> Add ci resource to schema

- CKAN.schema
Adds a new field to the schema, called `kind`, that allows to have metapackages.
`kind` can take two values:
* `package`, for any "normal" package we've had so far;
* `metapackage`, for purely virtual packages.
See the discussion at KSP-CKAN/CKAN-core#63
> Metapackages in schema

- Spec.md
This spec seems to use the RFC 2119 terminology for standard definitions of terms like "MUST", "SHOULD NOT", etc. -- so attach the commonly-used and recommended boilerplate for it.
Not certain if this is the best place in the file for it but here it is.  I also italicized the terms rather than using the all-caps used by the RFC to match the conventions used by the rest of the spec.
See https://www.ietf.org/rfc/rfc2119.txt
> Update Spec.md with RFC 2119 reference

- bin/close-old-support-tickets.pl
You'll need a github token to run this, but it'll find and close out old support tickets for us. Best thrown in a cron job with a bot's token.
Closes #942.
> Added support ticket closer bot

- .travis.yml
- bin/build
- bin/build.lean
- t/cmdline.t
- t/lib/CkanTests.pm
This PR restores much of the old travis functionality, but with extra goodies. In particular:
- To make a new release, we just hit the 'release' button on github and fill in the release notes.
- Travis will exercise our test suite against mono 3.2.8, 3.10.x, and 4.latest
- `ckan version` will once again return the actual git commit that was used to build the executable
All the Perl code for the build script was resurrected from before the great split, and adjusted for the new repo structure.
In this should also test branches and pull-requests to the CKAN repo as well.
Closes #984.
Part of #852.
Relevant to #990.
You can see an example of the travis output at:
- https://travis-ci.org/pjf/CKAN
> Re-enable one-click releases, AND test against three mono versions!

- Makefile
https://github.com/KSP-CKAN/CKAN/wiki/Building-CKAN-on-Linux also
now has the correct info for building assuming we use this.
For #852.
> Make now uses the same script as travis.

- GUI/Main.Designer.cs
- GUI/Main.cs
Mimic the typical behavior of lists in other software; improve usability
* Start typing the name of the mod in the mod list and it will get selected
* Pressing the same key will cycle through items whose names start with that key
* Previous key presses are forgotten in 1 second
* Toggling the install checkbox by pressing space won't work unless the row is selected
* Status bar "Not found" message; cleared when a mod is selected
* Home/End keys go to top/bottom of the list respectively
> Improve typing nav usability in mod list

- GUI/ChooseKSPInstance.Designer.cs
- GUI/ChooseKSPInstance.cs
From solarshado 
> Mostly scratching a personal itch, but this adds two new ways to select a KSP instance:
>
> *    Double-clicking an instance in the list is now the same as choosing it and then clicking "Select"
> *    Pressing the 'Enter' key clicks the "Select" button, making keyboard-only navigation a little faster/easier
>
> The double-click bit feels like it might be cross-platform-finicky, but it works on my Windows 7 box and I don't have a way to test it elsewhere.
> Selection enhancements

- Core/Types/KSPVersion.cs
- Core/Types/Module.cs
- Tests/Core/Types/KSPVersion.cs
Mutating the existing copy will change its hashcode which is not permissible when it is used in a key or a dictionary.
> Change toLongMin and toLongMax to return new copies.

- GUI/Configuration.cs
- GUI/Main.cs
- GUI/MainModList.cs
Saves settings for the column sorting. Tested on Windows and mono.
> Persist column sorting settings

- .travis.yml
I like that Jenkins sends information on builds to #ckan-jenkins and think it's awesome because I like getting spammed. I think Travis should do the same thing but to #ckan-ci instead so we don't have poor Travis hang out in hostile Jenkins territory. At a later time it might be advisable to move Jenkins into #ckan-ci aswell as to centralize information. That's a problem for another day though!
As for what I did, I basically copied the proposed things from http://docs.travis-ci.com/user/notifications/#IRC-notification and added the right irc channel. I think (hope) that's all there is to it. The template might be increadibly overkill but I grabbed the default one thinking it's probably default for a reason.
> Have travis send information to #ckan-ci

- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
- Cmdline/app.config
- Core/Relationships/RelationshipResolver.cs
- GUI/App.config
- GUI/CKAN-GUI.csproj
- GUI/ErrorDialog.Designer.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainDialogs.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- Tests/Core/Relationships/RelationshipResolver.cs
- Tests/GUI/MainModList.cs
- Tests/Tests.csproj
- Tests/Util.cs
Fixes #976.
See: https://github.com/KSP-CKAN/CKAN-GUI/pull/137 for some discussion.
> Once again allow users to select dependencies when multiple provides exist

- Core/Registry/RegistryManager.cs
From https://github.com/KSP-CKAN/CKAN-core/pull/139/files
Change depends to recommends.
Allows user customization of the install in the GUI
Do not output provided versions.
They are no real mods.
Closes KSP-CKAN/CKAN#912.
Relevant to KSP-CKAN/CKAN#972.
Currently it does not output a useful .ckan file due to provided modules.
> Serialize current install

- Core/Types/Version.cs
- Tests/Core/Types/Version.cs
By the spec 1.01 should equal 1.1 while the code had them non-equal with the order depending on which was called first. Closes #1076.
> Fix edge case in version numbering.

- .travis.yml
- Fixes a bug where we'd try to upload artefacts multiple times (now
only the 3.10.0 artefacts are uploaded).
- Uploads `netkan.exe` and `ckan.exe` from any code that's been merged
into master.
- Kinda lazy because it's using pjf's bucket rather than KSP-CKAN's
bucket.
- Kinda lazy because it doesn't upload versioned artefacts.
- https://ckan-travis.s3.amazonaws.com/ckan.exe and
https://ckan-travis.s3.amazonaws.com//netkan.exe will always be the
latest artefacts from master.
- Example successful run can be found at https://travis-ci.org/KSP-CKAN/CKAN/jobs/65685362
> Have travis upload "nightly" artefacts.

- bin/build
- bin/build.lean
Closes #1074.
I don't have a good way to test this work as intended, but can confirm it doesn't cause any issues under mono.
@RichardLake, did you say you had a test machine?
> Target platform v4 (aka .NET 4.5) when building

- Netkan/AVC/JsonAvcToKspVersion.cs
- Tests/NetKAN/AVC.cs
Thanks to Tivec for reporting and Blu3wolf for diagnosing the issue.
> AVC uses -1 as a wildcard since 1.1.5.0.

- .gitignore
- Cmdline/Action/List.cs
- Cmdline/Options.cs
- Core/CKAN-core.csproj
- Core/Exporters/BbCodeExporter.cs
- Core/Exporters/DelimeterSeperatedValueExporter.cs
- Core/Exporters/Exporter.cs
- Core/Exporters/IExporter.cs
- Core/Exporters/MarkdownExporter.cs
- Core/Exporters/PlainTextExporter.cs
- Core/Types/ExportFileType.cs
- GUI/CKAN-GUI.csproj
- GUI/ExportOption.cs
- GUI/Main.cs
Fixes #1094
Allow CKAN to export the mod list in multiple formats.
- Plain Text
- Markdown
- BBCode
- CSV
- TSV
This is accomplished in the GUI by expanding the "Save as type" option. In the command line an extra option is added to the `list` command, `--export` that will output the list in the specified format (`text`, `markdown`, `bbcode`, `csv`, `tsv`) to stdout. Users can then redirect to a file as appropriate.
The exact format of the "pretty" formats is just what I came up with, suggestions welcome.
Also, I noticed that the `list` command has a `porcelain` option that's used in the [exact opposite sense that git uses that word](http://stackoverflow.com/questions/6976473/what-does-the-term-porcelain-mean-in-git). We should probably change that?
> Friendly Mod Export 

- Netkan/KS/KSMod.cs
Use Kerbal Stuff's `source_code` property to populate the repository
resource automatically.
> Populate repository resource from Kerbal Stuff

- .gitignore
`ckan.exe.config` and related files are auto-generated, so we should
ignore them when it comes to version control.
> gitignore: Don't track .exe.config files

- Core/Registry/AvailableModule.cs
- Core/Registry/Registry.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Types/Module.cs
- Core/Types/Version.cs
- Spec.md
- Tests/Core/Relationships/RelationshipResolver.cs
This is #989, with the addition of:
- A merge commit, so everything works with current master.
- An update to the spec, describing how versions should work in older clients.
> Relationship Resolver Versions w/Spec changes

- Core/KSPManager.cs
- Core/Registry/Registry.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Types/Module.cs
- GUI/MainModList.cs
- Tests/Core/Relationships/RelationshipResolver.cs
From https://github.com/KSP-CKAN/CKAN-GUI/pull/111
Based on https://github.com/KSP-CKAN/CKAN/pull/988
Should allow you to install mods which conflict with mods that will be uninstalled. Such as changing tacls configs.
> Allow conflicts if mod are to be uninstalled

- Netkan/KS/KSMod.cs
- Netkan/KS/KSVersion.cs
"x_screenshot" contains a url to a screenshot used as a icon on kerbalstuff.
A user on IRC requested a field in which mods can have a screenshot. A number of KS mods have such a screenshot accessible via the API so I thought this might encourage use of it.
> Add in new custom field for kerbalstuff mods.

- Core/ModuleInstaller.cs
- Core/Net/NetFileCache.cs
- GUI/MainModInfo.cs
Currently it would default to true. However the test is expensive - on the order of seconds as compared to retrieving the files names which is on the order of tens of miliseconds.
Given this I've set it to only run the tests before installing.
Closes #1026
> Add test_data boolean to GetCachedZip

- Netkan/Web.cs
Currently the cURL bundle file is only used if it exists in the current working directory, which isn't very convenient. This change makes it so that NetKAN will search a list of directories for the file and use the first one found. Specifically it will use in preference:
- Working Directory
- Executable Directory (wherever `netkan.exe` exists)
- `%LOCALAPPDATA%/CKAN`, which on a typical system will correspond to `C:\Users\User\AppData\Local\CKAN`
- `%APPDATA%/CKAN`, which on a typical system will correspond to `C:\Users\User\AppData\Roaming\CKAN`
- `%PROGRAMDATA%/CKAN`, which on a typical system will correspond to `C:\ProgramData\CKAN`
Basically, the more "local" the file is, the higher priority it has. I'm not entirely keen on including the working directory in the search path, but …
> More robust cURL CA bundle file resolution

- GUI/Configuration.cs
- Tests/Data/TestData.cs
- Tests/GUI/Configuration.cs
- Tests/Tests.csproj
When loading a corrupt configuration file, the exception thrown is not caught as (at least in Windows) what gets thrown is an InvalidOperationException, not a XmlException. I've changed it and also added some additional information so the user can try and repair the file, as I think it can be useful.
Greetings and thanks for your hard work with CKAN!
> Catch XML parsing error correctly

- Core/Types/Module.cs
The `Equals` method tests identifier and version. For conflicts, we only want to test identifier.
Closes #1139 (with luck)
> Prevent modules from conflicting with themselves on upgrade

- Core/Relationships/RelationshipResolver.cs
This was caused by us checking the wrong data structure to report where
our incompatible version of a mod was found.
Closes #1146.
> KeyNotFoundException fix in ResolveStanza

- CKAN.sln
- Cmdline/CKAN-cmdline.csproj
- GUI/CKAN-GUI.csproj
- Tests/Tests.csproj
I suspect during the great merge we ended up with solution files that
work for visual studio, but cause monodevelop to try and do its own
thing.
These get monodevelop to VS formatting for me.
> Enforce Visual Studio formatting.

- CKAN.sln
- Cmdline/CKAN-cmdline.csproj
- Core/Types/Module.cs
- GUI/CKAN-GUI.csproj
- Tests/Core/Types/RelationshipDescriptor.cs
- Tests/Tests.csproj
This causes AD mods to act like they did in 1.6 in terms of relationship satisfaction.
Closes #1154.
Includes tests.
> Autodetected mods now satisfy all relationships.

- GUI/Main.cs
Closes #1158.
Tested by hand. Before these changes selecting an existing file for export causes a crash.
After these changes it correctly writes the file.
> GUI: Allow overwriting of exported .ckan files

- Netkan/KS/KSVersion.cs
- Tests/NetKAN/KSMod.cs
Closes #1156.
You can test this on the current `NetKAN/UniversalStorage-ECLSS.netkan` file, which
has a '0.90' release on KS, but comes out as '0.90.0' in the metadata:
```
$ netkan.exe NetKAN/UniversalStorage-ECLSS.netkan
$ grep ksp_version  UniversalStorage-ECLSS-Deprecated.ckan 
"ksp_version": "0.90.0",
```
> netkan.exe add '.0' to two-part releases when indxing from KS

- Cmdline/Main.cs
- Cmdline/Options.cs
Adds support for detecting a `--debugger` command line argument and using `System.Diagnostics.Debugger.Launch()` to launch a debugger. On Windows this opens a dialog prompt to either start or use an existing Visual Studio instance to attach to the process for debugging. Not sure what the exact behavior on Linux is, but from some quick googling it seems it's at least supported to some degree.
This flag is checked as early as possible to ensure maximal utility, it's even done before full command line argument parsing so you could even debug that.
> Add command line option to launch debugger

- Cmdline/Action/Upgrade.cs
when one of the mods are not found.
Maybe the ModuleNotFoundKraken should be thrown for every non existant mod the user wants to update?
See #1140
> Commandline: Show a user friendly error on upgrade

- Core/Relationships/RelationshipResolver.cs
- GUI/MainChangeset.cs
RelRes was not filtering candiade dependancies by the version.
The GUI is passing incorrect versions to the installer.
For a example of the second try to install MechJeb Modules for Far in a clean 1.0.2 install. It will fail. 
Reported by @BasharMilesTeg
Needs testing.
> Fix: Issues with version handling.

- Netkan/MainClass.cs
- Tests/NetKAN/MainClass.cs
Recursively remove any properties that start with `x_netkan` from the metadata object just before writing the `.ckan` file. Also includes some tests!
Also, reformats some `TestCase` attributes cause they were annoying me. :wink: 
Fixes #1177
> Strip NetKan Properties

- Netkan/CKAN-netkan.csproj
- Netkan/MainClass.cs
- Netkan/NetkanOverride.cs
- Tests/NetKAN/NetkanOverride.cs
- Tests/Tests.csproj
This PR implements the `x_netkan_override` syntax described in #1160.
Includes test cases. Tested on live data.
Closes #1160 and brings in a new age of prosperity. :)
> Implement `x_netkan_override`

- Core/Net/NetAsyncDownloader.cs
since they may be modified
Same problem as in df9acb78778094c482149c1a6b4759358b41ffcc, same solution applied.
Fix for #1180
> Fixed exception after cancelling download of mod

- AutoUpdate/Main.cs
and also launch it with "mono ckan.exe"
Tested on Windows 8.1, and Ubuntu 14.04.
closes #788
related to #919
> Set the executable bit of the updated ckan

- Netkan/MainClass.cs
- Tests/NetKAN/MainClass.cs
@pjf  Update to the previous PR. This adds recursion into arrays to remove the properties, i.e.:
```json
{
"foo": [
{
"x_netkan": "remove me"
}
]
}
```
Test added for this case.
Changes best viewed when [ignoring whitespace](https://github.com/KSP-CKAN/CKAN/pull/1201/files?w=1).
> Recurse into arrays when removing x_netkan properties

- Spec.md
While the spec has always had strict requirements as to what characters
are allowed in versions, this has not been reflected by our software.
Indeed, we're not really able to restrict how authors version their
releases, the best we can do is hope they're sane, or bump the epoch
if they're not.
This change alters the spec to weaken the requirement on spec numbers
to be a recommendation, reflecting how we actually handle things.
This *is* changing the spec as written, but it's matching reality, so
we're not changing what users see. Even so, discussion is welcome (even
after this is merged).
Closes #1174.
Not as cool as #834.
[Our policy on versions](https://github.com/KSP-CKAN/CKAN/blob/master/policy/version-comparison.md) should be kept in mind in discussions.
> Adjust spec version requirements to match usage.

- Core/Converters/JsonIgnoreBadUrlConverter.cs
- GUI/URLHandlers.cs
Users often fixate on the warnings produced by our code, but the most
commonly seen warnings are completely harmless. This PR downgrades
two commonly seen warnings (one regarding URL handlers that's seen in
existing releases, and one regarding bad URLs that would be seen in
future releases) to the info level, as the code works perfectly fine
in the conditions which generate these.
No logic changes. Tested by hand.
> Remove spurious and harmless warnings.

- Core/Relationships/RelationshipResolver.cs
When ran with procede_with_inconsistencies the exception should never have been thrown. See https://github.com/KSP-CKAN/CKAN/pull/1175#issuecomment-115166104 for details on reproduction steps.
This fix has issues with poor communication to the user regarding why it conflicts but it is better than crashing.
> Fix for uncaught Inconsistent Kraken.

- GUI/GUIMod.cs
- GUI/MainModInfo.cs
A pet peeve of mine is seeing "N/A" in CKAN and not being able to get more information about a given mod.
This will have the GUI present the KerbalStuff or GitHub page (with the former superceding the latter) when `homepage` isn't provided in the metadata.
I suck at coding, if this can be done more efficiently please let me know.
> Make better efforts to present users with homepages for mods aka "give homes to the homeless"

- GUI/Configuration.cs
Partially addresses #1232. This won't help existing (or Mac) users, but new users moving forward will be able to click the launch button to their heart's content.
> Change default config to launch KSP with -single-instance

- Core/Types/Repository.cs
api.ksp-ckan.org is not available anymore, put the repo list on github so it enjoys the same availability as our other metada files.
> Point the repo master list to CKAN-meta on github

- GUI/GUIMod.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainModInfo.cs
- GUI/MainModList.cs
Most up to date version: http://imgur.com/a/6oJCS#0
This will allow users to see the highest version of KSP that a mod is compatible with. It lists the information as a column in the main mod listing, and as a field in the mod info pane. I removed the homepage column because it wasn't functional, and also an impractical way to view that information. All columns are resized and auto-resize is disabled. I'm running windows and tested at 1080 as well as 720 and it looked the same. I don't have the ability to check how it looks under other OSes.
All the column width changes can be reverted simply with a revert of d630fee if needed.
Test cases specifically for compatibility addition:
ksp_version set long (1.0.4): [X]Science
ksp_version set short (1.0): Action Groups Extended
ksp_version_max …
> Small GUI overhaul. Added compatibility column and to right pane, removed homepage column, resized all columns.

- bin/outdated_metadata.pl
We've already run this code and repaired the old data in KSP-CKAN/CKAN-meta#607,
but I figure it'd be good to keep the tool around just in case. This PR adds
the tool to our `bin` directory.
> bin/outdated_metadata.pl: Find and fix vague KSP version strings.

- GUI/Main.cs
- GUI/MainRepo.cs
> Client is now movable during the refresh

- Core/Types/Module.cs
- GUI/GUIMod.cs
- GUI/MainModInfo.cs
Updates #1270.
Includes human-readable MaxKSP functionality in `Module.cs`.
I wasn't sure if flipping `UpdateModInfo` to use a `GuiMod` was the
right idea, but it seems to work, so that's awesome!
I would *love* someone to check this over. It's an improved version of #1270, but I'm not well versed in how the GUI works.
> GUI: When showing Latest KSP info, do it for the latest mod (for any KSP ver)

- GUI/GUIMod.cs
fixes TMP on installation of any mod which relies on TMP
for example RSS and Planetshine
fixes #1298
> Fixed checkbox not toggling when chossing a providing mod

- Core/Net/Repo.cs
We also continue with downloading metadata from other repositories
fixes part of #1238
> Catch WebException when downloading metadata

- GUI/Main.cs
- GUI/MainModInfo.cs
The download page is now visible during a download.
Refresh the contenttree after a download.
> Download cache button fixes

- Netkan/Transformers/KerbalstuffTransformer.cs
This makes a few small changes to the `KerbalstuffTransformer`:
- Licenses we receive from KS are trimmed, I've seen a couple of cases of otherwise valid license strings being rejected because they had leading or trailing whitespace.
- The specific cases of `GPLv2` and `GPLv3` are transformed into CKAN compatible license strings, since those are two of the default options for licenses on KS.
- The `x_screenshot` property is moved from being a top-level property to a child of `resources`, which I think makes more sense.
> Update KerbalStuff Transformer

- GUI/YesNoDialog.Designer.cs
"User input required" looks clunky (not user friendly) on a window. We can stick with "CKAN" and it'll look decent for any application that uses this window.
> Improve window title when asking yes or no

- Netkan/Extensions/JObjectExtensions.cs
- Tests/NetKAN/Extensions/JObjectExtensionsTests.cs
@techman83 Fix for KSP-CKAN/NetKAN-bot#27
Problem was that converting a `null` to a `JToken` still produces a `JToken` object, but one that represents a `null` value. This makes sure that if the `JToken` is not `null`, that its underlying object is also not `null`.
Adds a regression test that fails prior to the change and passes after the change.
> Fix JObject SafeAdd to make sure underlying value is not null

- Core/Registry/AvailableModule.cs
- Core/Registry/Registry.cs
- GUI/Main.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
Profiling was started before clicking on Refresh, and stopped after.
Before my changes:
After my changes:
> Performance Enhancements

- GUI/ChooseKSPInstance.cs
This sets the name of the instance to the folder name on creation instead of "New instance".
> Use folder name as default name for instance

- Netkan/Program.cs
- Netkan/Services/CachingHttpService.cs
- Makes sure `.zip` is appended to downloaded packages
- Logs a warning if the input file does not end with `.netkan`
Fixes #1307
> Misc Netkan Fixes

- Core/KSP.cs
- Core/ModuleInstaller.cs
- Tests/Core/ModuleInstaller.cs
Fixes #1134, allowing `install_to` directives to specify `Ships/VAB` or `Ships/SPH` to install into those subdirectories. We still don't allow mods to create directories within `Ships` though.
Still needs:
This would require a bump to the `spec_version` to `v1.12`.
> Allow installation into subdirectories of Ships

- Core/Net/NetFileCache.cs
- Core/Types/Module.cs
- Tests/Core/Cache.cs
- Tests/Core/Types/Module.cs
- Tests/Data/TestData.cs
@pjf reported a slight issue with show in the cli in #1249. This should fix that by moving the renaming code further up the chain. I cannot test with the case @pjf used, since I can't seem to locate it in my registry.
Closes #1249.
> Fix bad characters in filename in module.

- Core/Net/Curl.cs
- Core/Net/Net.cs
- Netkan/Program.cs
- Netkan/Services/CachingHttpService.cs
- Netkan/Services/IHttpService.cs
- Netkan/Sources/Kerbalstuff/KerbalstuffApi.cs
This consolidates much of our network download logic into `Net`, and standardizes behavior such that:
- We always try to use a `WebClient` first
- If that fails, we attempt to use cURL
Also, moves the cURL CA file resolution logic into `Curl` so that everything that uses it benefits from it.
> Consolidate network download code

- CHANGELOG.md
- Core/Registry/Registry.cs
- Core/Types/Repository.cs
At some point, we gained the ability to read `.tar.gz` files, but the client continued to use `.zip` to download metadata. This change flips us to use tarballs, which are *an order of magnitude smaller* than the .zip files. This can make a big difference, especially on slow connections.
This change will affect both new users, and existing users if and only if they're using the default repository settings.
> Download default metadata in .tar.gz rather than .zip format

- GUI/GUIMod.cs
`protected` methods can only be accessed by the class or its derived classes, but `GUIMod` is a sealed class, which by definition can't be inherited from. Consequently, this generates a warning.
This change flips the method to `private`, which more accurately represents how this method can be accessed.
> GUIMod: Fix spurious protected method warning.

- Netkan/Sources/Avc/JsonAvcToKspVersion.cs
- Netkan/Transformers/AvcTransformer.cs
- Tests/NetKAN/Services/ModuleServiceTests.cs
- Tests/NetKAN/Transformers/AvcTransformerTests.cs
This PR makes the handling of version information found in internal `.version` files more robust. In practical experience the internal `.version` files aren't remarkably accurate, so we make the two following changes:
- If the metadata already contains a `version` field, such as from KerbalStuff or a GitHub tag, we **do not override** it with the value found in the `.version` file.
- KSP version information is calculated by "merging" the values that are already in the metadata and what we find in the `.version` file. A common example would be if some mod on KerbalStuff indicates that it's compatible with a version of KSP later than what it specifies in its `.version` file. In that case we calculate a minimum version from the `.version` file and a maximum version from the KerbalStuff …
> More Robust AVC Version Handling

- GUI/MainModList.cs
this implementation just splits the name of the mod after every space,
and uses the first letter of every word.
Kerbal Inventory System will be for example KIS
related to #1313
> Search mods by their abbreviation

- Netkan/CKAN-netkan.csproj
- Netkan/Transformers/NetkanTransformer.cs
- Netkan/Transformers/PropertySortTransformer.cs
The order of properties in the final `.ckan` output of Netkan is currently dependent on the order in which code is executed by the various transformers. This PR adds a new `ITransformer`, `PropertySortTransformer` that is added to the very end of the pipeline.
`PropertySortTransformer` has an internal list of known properties and will sort the properties in a well defined order (unknown properties are placed just before the `x_generated_by` property in alphabetical order, with `x_` properties always sorting last).
This means the output of Netkan should remain relatively stable with all sorts of changes.
Sort order was chosen based on what I feel is an intuitive reading order when looking at `.ckan` files, and mirrors the typical order found in handcrafted `.ckan` files.
> Sort Properties on Final Netkan Output

- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainInstall.cs
Used for (de)selecting all the suggested or recommended mods with one
click.
> Checkbox for recommendations/suggestions page.

- GUI/Main.cs
Reproduction steps:
1) Search for a mod that does not exists. Make sure your modlist is empty now
2) Focus the modlist
3) press some key.
4) CKAN now should throw a NRE at you
With this fix, CKAN does not throw a NRE at you anymore. :)
> Fix NullReferenceException when pressing keys on an empty modlist

- Core/Net/AutoUpdate.cs
that is for example the case, when the build of the assembly takes long,
but the upate post is already published
We just show the currently installed version
also, we don't let the user install anything,
if the autoupdater is not available
fixes #1182
> We don't show an update, if its assembly is not available

- CHANGELOG.md
- Netkan/CmdLineOptions.cs
- Netkan/Program.cs
This shows the version number we're built from and exits.
> NetKAN: Add support for `--version` diagnostic switch.

- Core/Relationships/RelationshipResolver.cs
- GUI/CKAN-GUI.csproj
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainChangeset.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- GUI/ModChange.cs
- Tests/GUI/MainModList.cs
The column "Reason for Action" shows why an action was picked for a mod change.
The columns are sorted by action in the order Remove, Update, Install.
Install changes are also sorted based on dependencies.
This pr implements a part of part 1) of #1268. 
How it looks currently:
> Show why a mod was picked for a change

- Core/ModuleInstaller.cs
previously we only showed the identifier,
which can be quit different from the actual mod name
> Show name and version of the mod we are (un)installing

- GUI/Main.cs
The install logic still  used a KeyValuePair<GuiMod, GuiModChangeTyp>
while everything else uses ModChange object's now
> Fix a castexception when installing metapackage

- GUI/MainModList.cs
This changes only the behaviour on a refresh
in every other case, we still do a full refresh of the modlist
for example, the changeset page' clear button needs this
for unticking checkboxes (sigh)
implements #1129
> Refreshing does not wipe the list of selected mods anymore

- GUI/MainModList.cs
Moved the creation of the 3 different sorter kinds into different methods for:
string based, integer based and checkbox based
fixes #1419
> GUI: Numerical columns can be sorted numerically

- CHANGELOG.md
- Cmdline/Action/Upgrade.cs
- Core/Net/AutoUpdate.cs
- GUI/Main.cs
- GUI/SettingsDialog.cs
- Tests/Core/Net/AutoUpdate.cs
This is an extension of #1410, and includes all of its commits. In addition, it:
- Has more documentation
- Has extra tests
- Fixes a bug where we could crash on malformed release notes
- Changes release notes handling so that we use everything after the first line of dashes.
I'm very happy with @Postremus' work, so I'm happy for this to be merged if anyone (including Postremus) is happy with [my extensions](https://github.com/KSP-CKAN/CKAN/compare/ab836f3...eefbdc8).
> AutoUpdate makes less calls, has better tests.

- Core/KSP.cs
- Core/Net/NetFileCache.cs
- Tests/Data/DisposableKSP.cs
`[YoDawg.jpg]`
In the past, `NetFileCache` would read the entire cache directory each time we checked to see if we had a file. That was okay, because we didn't check very often. However #1426 adds a filter on cached status, and with 900+ potential mods it can be very slow indeed.
This PR implements a number of changes to improve our cache handling, in particular:
- We now cache the list of files we read from the disk, so if we're performing lots of look-ups we are much faster.
- We clear that cache if we ever knowingly change the directory, such as by adding or removing a file.
- We use the `FileSystemWatcher` class to *also* clear the cache, so if anything else modifies the directory we should know about it.
Gotchas:
- `FileSystemWatcher` isn't necessarily reliable under mono. It's …
> NetFileCache now caches the cache directory so you can cache while you cache.

- Core/KSPManager.cs
I believe this fixes issue #1109 or at least it did on my install of OS X...
Looking at the code I changed, I have a sneaking suspicion this issue may have been more than OS X and impacted every OS, but I have no means of testing that theory currently.
I am not a C# programmer so my bad if I have made some sort of C# faux-pas.
> Fixed OS X cmdline not finding a valid KSP install

- Core/Net/NetFileCache.cs
this prevents a NullReferenceException when importing a .ckan in the gui
The gui does generate a GuiMod when importing a.ckan.
The GuiMod needs to know,if it is cached or not..
Since the .ckan most likely has no download_url, it will crash.
fixes #1465
closes #1464
> fix a NullReference when opening a .ckan

- Core/Net/AutoUpdate.cs
- GUI/Main.cs
- GUI/URLHandlers.cs
Tested on Ubuntu 14.04
-If we have no existing mimeapps.list, create it
-start ckan with mono
-make the .desktop file executable
-correctly resolve the home Directory
-focus the mod we got in the modlist
related to #1433
> Fixed protocol handler registration on linux (at least ubuntu)

- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainModInfo.cs
.net opens the windows explorer
mono uses xdg-open to open the directory
> Handle double click on the contentTree

- CHANGELOG.md
- Netkan/Transformers/PropertySortTransformer.cs
Somehow missed adding an explicit sort for `conflicts` relationships.
> Sort Conflicts Relationship

- CHANGELOG.md
- Core/KSPPathUtils.cs
This is #1444, but I've added some guards so that if our config file is corrupted we won't throw an exception from running off the end of an array.
I don't have a machine handy with a non-standard install of Steam, but the code looks right to me, so if you're reading this and anyone has reported it's working as intended, then please merge. :)
> Improved steam detection with guards

- GUI/URLHandlers.cs
Changed the AssigmentSpacer of the FileIniDataParser instance to the empty string. This removes spaces around the '=' in the kde mimeapps and .desktop files and should enable KDE to parse the files without issues. Fixes #1498 on my system.
> Configure FileInitDataParser to omit spaces around '=' when writing config files (#1498)

- Core/KSP.cs
- GUI/Main.cs
Small addition that allows CKAN to rebuild any directory structure
within the current KSP game directory on load, if the directory doesn't exist.
Currently only supports Ships/VAB, Ships/SPH, Ships/@thumbs/VAB, and
Ships/@thumbs/SPH, but can be easily extended to other paths.
Fixes #1404
> Rebuild Ships Directory on Load

- CKAN.schema
This commit makes two changes to the machine readable schema:
- It fixes v1.12 spec paths to target `Ships/(SPH|VAB)$`. Previously
there was a character class here, allowing *any* pattern starting
with `Ships/` followed by any single character from the set `ABHPS|`
to be considered valid.
- It adds the v1.16 spec that allows for installation into
Ships subfolders (added in #1448).
Pretty sure this works as all 5,212 unique `.ckan` files I ran it over validated nicely. :)
> CKAN.schema: Update targeted ship installs.

- GUI/Main.cs
- GUI/MainRepo.cs
This is a cherry-pick of 8aa8abd from #1290. Instead of assuming the `YesNoDialog` default to null, it instead caches what it previously was and restores it. At the moment this is effectively a no-op, but it may save us hassles in the future.
Code courtesy of @RichardLake, with cherry-picking and integration by me. :)
> Restore old displayYesNo instead of setting to null

- CHANGELOG.md
- CKAN.schema
- Cmdline/Action/Show.cs
- Core/Exporters/DelimeterSeperatedValueExporter.cs
- Core/Types/CkanModule.cs
- GUI/GUIMod.cs
- Netkan/CKAN-netkan.csproj
- Netkan/Sources/Spacedock/ISpaceDock.cs
- Netkan/Sources/Spacedock/SDVersion.cs
- Netkan/Sources/Spacedock/SpaceDockApi.cs
- Netkan/Sources/Spacedock/SpacedockError.cs
- Netkan/Sources/Spacedock/SpacedockMod.cs
- Netkan/Transformers/NetkanTransformer.cs
- Netkan/Transformers/PropertySortTransformer.cs
- Netkan/Transformers/SpacedockTransformer.cs
- Netkan/Transformers/VersionedOverrideTransformer.cs
- Spec.md
- Tests/NetKAN/Sources/Spacedock/SpacedockApiTests.cs
- Tests/NetKAN/Transformers/HttpTransformerTests.cs
- Tests/NetKAN/Transformers/SpacedockTransformerTests.cs
- Tests/Tests.csproj
Added `$kref` support for SpaceDock mods. Tested with multiple mods on SpaceDock (new and existing).
`netkan.exe` succesfully transformed `.netkan` files into `.ckan` files. Also compared the existing KS mods with their equivalent on SD.
The new `$kref` also shows up in the GUI.
~~The only thing I'm not sure about is [VersionedOverrideTransformer.cs - L25](https://github.com/KSP-CKAN/CKAN/pull/1593/files#diff-9c0e20a6467ef46703f2a452a0afac1cR25)~~
Closes #1592
> Support SpaceDock

- Netkan/Sources/Github/GithubApi.cs
- Netkan/Sources/Github/GithubRef.cs
- Netkan/Sources/Github/GithubRelease.cs
- Netkan/Transformers/GithubTransformer.cs
- Tests/NetKAN/Sources/Github/GithubApiTests.cs
- Tests/NetKAN/Transformers/GithubTransformerTests.cs
@pjf This PR allows GitHub "source code" archives to be used as download sources. Normally, we expect authors to upload a ZIP artifact to their GitHub release, but this can be a redundant step for mods which are pure text files such as `MK2KSPIIntegration` (see: KSP-CKAN/NetKAN#3079).
Now you can specify:
```json
{
"x_netkan_github": {
"use_source_archive": true
}
}
```
And we'll automatically use the "source code" ZIP file as the download source. (`use_source_archive` obviously has a `false` default value).
For example this `.netkan`:
```json
{
"spec_version": "v1.4",
"$kref": "#/ckan/github/ABZB/Mk2_Extended_KSPI_Integration",
"x_netkan_github": {
"use_source_archive": true
},
"license": "CC-BY-NC-SA-4.0",
"identifier": "MK2KSPIIntegration",
"ksp_version": "1.0.5",
"depends": [
{ …
```
> Allow NetKAN to use GitHub source archives as download sources

- Core/Types/Version.cs
- Tests/Core/Types/Version.cs
The NavUtilities versions were not being sorted properly. Currently the sort is
- 0.5_RC_3
- 0.5.1_RC_1_repacked
- 0.4.3
It should be
- 0.5.1_RC_1_repacked
- 0.5_RC_3
- 0.4.3
This change modifies the sort so that '.' takes precedence over all other non-digit characters. That way version parts are considered higher than other random characters tacked onto the end of the version.
All the other version tests pass.
> Fixing version sorting of _ vs .

- Netkan/Sources/Kerbalstuff/KerbalstuffMod.cs
- Netkan/Sources/Spacedock/SpacedockMod.cs
- Netkan/Transformers/KerbalstuffTransformer.cs
- Netkan/Transformers/SpacedockTransformer.cs
From KSP-CKAN/NetKAN#2980. This PR changes the datatype of KerbalStuff's `website` and `source_code` properties into `String` from `Uri`, since we have no guarantee that they're actually well-formed `Uri` strings. Now when "normalizing" the URIs (renamed the method from `Escape` to `Normalize` since we were doing a lot more in it than merely escaping characters) we do a final check to make sure the string is a well formed URI. If it is, we proceed as normal, if it isn't we spit out a warning and return `null`, preventing it from being added to the metadata (the `SafeAdd` extension method will ignore `null` inputs).
@politas @plague006 @pjf
> [NetKAN] Tolerate Malformed Author URLs from KS/SD

- CHANGELOG.md
- Netkan/CKAN-netkan.csproj
- Netkan/Sources/Spacedock/SpacedockMod.cs
- Netkan/Sources/Spacedock/SpacedockUser.cs
- Netkan/Transformers/SpacedockTransformer.cs
Fixes #1600.
Now the `SpacedockTransformer` will read the `shared_authors` property from the API (if available) and add the usernames of all those listed to the `author` property in the resultant CKAN as an array.
This `.netkan` (for [kOS](http://spacedock.info/mod/60/kOS:%20Scriptable%20Autopilot%20System)):
```json
{
"spec_version": 1,
"identifier": "kOS",
"$kref": "#/ckan/spacedock/60"
}
```
Produces the following `.ckan`:
```json
{
"spec_version": 1,
"identifier": "kOS",
"name": "kOS: Scriptable Autopilot System",
"abstract": "Fully programmable autopilot mod for KSP",
"author": [
"erendrake",
"hvacengi",
"dunbaratu"
],
"license": "GPL-3.0",
"release_status": "stable",
"resources": {
"homepage": "http://ksp-kos.github.io/KOS_DOC/",
"spacedock": …
```
> SpaceDock Multiple Authors

- GUI/Main.cs
Most users don't care about specific versions and aren't getting what they might expect when using the default option. So let's put the more advanced option below while also trying to clarify the difference.
> Make "CKAN favourites list" the default export option (no hard version requirements)

- GUI/Main.Designer.cs
- GUI/Main.cs
Fix a typo in the "Open KSP Directory" menu item and some of the associated properties.
> Fix 'directory' typo

- GUI/Main.Designer.cs
We have sources other than github, and the field definition is not GitHub specific
> Change Mod Info window label for repository

- bin/ckan-validate.py
A small modification to 'ckan-validate.py' which is used in our testing. Gets rid of the big Traceback, we can probably do more with it.
> Catch ValueErrors as in KSP-CKAN/CKAN-meta#1035

- Cmdline/Action/Compare.cs
- Core/Types/Version.cs
Otherwise a comparison of `1_0` to `1.0` will fail.
> Compare operation should check for negative/positive not -1/+1

- CKAN.schema
Found a JSON Schema friendly way of specifying that excactly one of 'file', 'find' and 'find_regexp' must be present.
> Changed schema to enforce structure of install direcitves

- CKAN.schema
- Spec.md
Reverts KSP-CKAN/CKAN#1597
I'm heading out + I don't haven't Grok'd how JSON Schema works yet. Reverting this will automatically get NetKAN indexing again.
> Revert "Add `kind` to the spec"

- CKAN.schema
- Spec.md
Tested @Zane6888's correction in #1597 and it works for ```"download": "url"``` and ```"kind": "metapackage"```.
> Metapackage schema

- CHANGELOG.md
- Netkan/Transformers/AvcTransformer.cs
- Netkan/Transformers/DownloadSizeTransformer.cs
- Netkan/Transformers/EpochTransformer.cs
- Netkan/Transformers/ForcedVTransformer.cs
- Netkan/Transformers/GeneratedByTransformer.cs
- Netkan/Transformers/GithubTransformer.cs
- Netkan/Transformers/HttpTransformer.cs
- Netkan/Transformers/ITransformer.cs
- Netkan/Transformers/InternalCkanTransformer.cs
- Netkan/Transformers/JenkinsTransformer.cs
- Netkan/Transformers/MetaNetkanTransformer.cs
- Netkan/Transformers/NetkanTransformer.cs
- Netkan/Transformers/OptimusPrimeTransformer.cs
- Netkan/Transformers/PropertySortTransformer.cs
- Netkan/Transformers/SpacedockTransformer.cs
- Netkan/Transformers/StripNetkanMetadataTransformer.cs
- Netkan/Transformers/VersionEditTransformer.cs
- Netkan/Transformers/VersionedOverrideTransformer.cs
- Spec.md
- Tests/NetKAN/NetkanOverride.cs
@pjf @Starstrider42 @Dazpoet
Prompted by #1674. The issue was that the `x_netkan_override` was overriding the `install` stanza. However, the `AvcTransformer` uses the `install` stanza to determine which files in an archive will be installed so that it can pick the correct `.version` file to use. The problem was that the `AvcTransformer` executes before the `VersionedOverrideTransformer` so the `AvcTransformer` didn't think *any* files would be installed because the appropriate override hadn't occurred yet.
What this PR does is basically allow you specify *when* an override should execute, through the use of `before` and `after` properties in the override.
To accomplish this there are three main changes:
- Each `ITransformer` must have a name which identifies it uniquely.
- …
> Omnipresent VersionedOverrideTransformers

- Core/Net/Net.cs
- Netkan/Transformers/HttpTransformer.cs
- Tests/NetKAN/Transformers/HttpTransformerTests.cs
@pjf @techman83 @plague006 @Ezriilc
This PR modifies the `HttpTransformer` to resolve redirects and output the resolved URL as the 
`download` property of the `.ckan` file, instead of value specified in the `$kref`.
[Graphotron](https://github.com/KSP-CKAN/NetKAN/blob/33eafb20f717b278e5376847e988dea1d93bfed6/NetKAN/Graphotron.netkan) and [HyperEdit](https://github.com/KSP-CKAN/NetKAN/blob/30241029a0fa7862875b97b37249452ec504222d/NetKAN/HyperEdit.netkan) are the only two `.netkan` files using the `HttpTransformer` at the moment.
Since they use a fixed URL this makes caching problematic. @Ezriilc can make it so that instead of returning the download directly in the response it can produce an HTTP redirect to a version specific URL. This should prevent caching issues (or at least reduce …
> HttpTransformer Resolves Redirects

- Netkan/Sources/Avc/AvcVersion.cs
- Netkan/Transformers/AvcTransformer.cs
@pjf @techman83 @BobPalmer
cc: @plague006 @politas @Dazpoet 
This PR modifies the `AvcTransformer` to support reading remote version files. Apparently the last few versions of the AVC addon have supported using the remote `.version` file to determine compatibility in preference to the local `.version` file, if the remote `.version` file specifies the same mod version as the local `.version` file. This PR provides the same behavior.
This should bump the compatibility of CommunityResourcePack as the [download](https://github.com/BobPalmer/CommunityResourcePack/releases/tag/0.5.1.0) specifies a maximum compatibility of KSP 1.1.1 whereas the [remote](https://github.com/BobPalmer/CommunityResourcePack/blob/master/FOR_RELEASE/GameData/CommunityResourcePack/CRP.version) specifies as maximum …
> Support reading remote AVC version files

- Core/Net/Repo.cs
While traversing possible nested exceptions (added because of #182) it is possible to reach a "leaf" where there are no more `InnerException`s. If at this point the exception hasn't been `handle`d, then `log.ErrorFormat` will try to access `exception.Message`. However, due to the `while` loop just above it, `exception` is `null`.
> Avoid unexpected null reference exception

- Netkan/Transformers/GithubTransformer.cs
@pjf @techman83 @KSP-CKAN/wranglers 
GitHub API returns an [empty string for the homepage in some cases](https://github.com/KSP-CKAN/CKAN-meta/commit/9805b7fe4edea89d0c7352d230d66c34d8546956), guard against that and adding empty descriptions as the abstract.
> GitHubTransformer shouldn't add empty data

- .travis.yml
@pjf @techman83 
#1645 is failing in Travis on the Mono 3.2.8 version because of errors like these:
```
System.TypeInitializationException : An exception was thrown by the type initializer for CKAN.Versioning.KspVersionRange
----> System.TypeInitializationException : An exception was thrown by the type initializer for CKAN.Versioning.KspVersionBound
----> System.NullReferenceException : Object reference not set to an instance of an object
```
There is no reason why a `NullReferenceException` should occur in the type initializer for `KspVersionBound`, this suggests a bug in the Mono 3.2.8 runtime:
- The error does not occur on Mono 3.10.0, Mono 4.2.3, or the .NET runtime.
- A [similar error](https://bugzilla.xamarin.com/show_bug.cgi?id=14977) was fixed in Mono in the 3.2.x era.
Do we even …
> Remove Mono 3.2.8 from Mono testing

- CHANGELOG.md
- CKAN.schema
- Core/ModuleInstaller.cs
- Core/Net/Repo.cs
- Core/Types/ModuleInstallDescriptor.cs
- Spec.md
- Tests/Core/ModuleInstaller.cs
@pjf @techman83 @KSP-CKAN/wranglers 
This PR adds supports for a feature similar to the [previously discussed](https://github.com/KSP-CKAN/CKAN/pull/1243#issuecomment-118680302) `install_as` allowing directories or files to be renamed.
Unlike the previously discussed implementation, there is no separate `install_as` which replaces `install_to`. Instead there is an optional extra property `as` which is the name to give to the matching directory or file when installed. This was done to minimize the number of changes required in the code base, especially in an area as sensitive as the install code.
For example, given the following ZIP structure:
- Foo/Bar/File1.dll
- Foo/Bar/File2.dll
- Foo/Bar/Baz/File3.dll
This install structure:
```json
{
"file": "Foo/Bar",
"install_to": "GameData/Foo", …
```
> install as

- Core/Versioning/KspVersion.cs
- Tests/Core/Versioning/KspVersionJsonConverterTests.cs
This catches and fixes corrupted version numbers in the form of `1.1.`
that can still persist in registry files (like mine).
Closes #1780, makes #1645 safer.
> Cleanse broken KSP version numbers

- GUI/Main.Designer.cs
Clears both build warnings that have been happening for some time.
Warning 1 The field 'CKAN.Main.UpdateCol' is never used D:\CKAN\GUI\Main.Designer.cs 1455 44 CKAN-GUI
Main.Designer.cs(1497,44): warning CS0108: `CKAN.Main.Update' hides inherited member 
`System.Windows.Forms.Control.Update()'. Use the new keyword if hiding was intended
Replaces #1772 - See there for details of thought processes
Possible solution for #1673 - `System.Windows.Forms.Control.Update()`'s description is "Causes the control to redraw the invalidated regions within its client area."
This orphaned declaration of UpdateCol may have been part of the fix that was implemented last time the MacOSX redraw glitch came up.
> Column rename "Update" to "UpdateCol" in GUI

- Core/Types/CkanModule.cs
- Tests/Core/Types/Module.cs
- Tests/Data/TestData.cs
At some point they'll probably be needed client-side, and this gave me an excuse to poke around exactly how the registry is created.
> Add download hashes to registry

- .travis.yml
- Tests/Core/Net/AutoUpdate.cs
These changes:
- Say it's okay for mozroots to fail.
- Avoid hitting github for something they might decline.
The test for these is that travis tests are now passing again, which I need them to do before I can make a release. :)
> Fix travis failing in third-party failures

- Cmdline/Action/List.cs
An * for status shows up whenever a mod falls through all the status tests without matching anything, thus implying an inability for CKAN to intelligently handle the mod. Since "Unknown" has been used to refer to mods that have been installed through CKAN but are now unable to be found in the registry, I have selected "Broken" as a term to describe the status of these mods.
> Add Asterisk to legend in CLI list command

- CHANGELOG.md
- Cmdline/Action/KSP.cs
@pjf 
This PR makes the KSP list in the CLI (`ckan ksp list`) prettier by printing it as a table. It also includes two extra bits of information over the previous version: the KSP version of the installation and whether or not it's the default (aka "preferred") KSP installation.
It also explicitly sorts the installations as follows:
- First by whether or not it's the default installation (default first).
- Then by the KSP version of the installation (newer versions first).
- Then by the installation name (A to Z).
The output on my machine looks like:
```
Name             Version  Default  Path
---------------  -------  -------  --------------------------
play-1.1.0.1196  1.1.0    Yes      C:/Bin/KSP/Play/1.1.0.1196
test-1.1.0.1174  1.1.0    No       C:/Bin/KSP/Test/1.1.0.1174 …
```
> Better KSP listing in CLI

- .travis.yml
- Core/Versioning/KspVersionBound.cs
> Workaround string.Format() bug in old Mono versions

- CHANGELOG.md
Added to the change log. We should also release 18.1 as 16.04 is the oldest version of Ubuntu to have a more recent version of Mono than 3.2.8.
> Add work in #1784

- .travis.yml
This updates travis/mozroots to use the `--sync` option, which requires
no user input, rather than `--ask-remove` which can request input when
removing certificates.
> Travis/Build: Prevent mozroots from asking for human input

- Cmdline/Action/Install.cs
- Cmdline/Action/List.cs
- Cmdline/Action/Show.cs
- Cmdline/Action/Upgrade.cs
- Cmdline/ConsoleUser.cs
- Cmdline/Main.cs
- Cmdline/ProgressReporter.cs
- Core/GameVersionProviders/KspBuildMap.cs
- Core/ModuleInstaller.cs
- Core/Net/Net.cs
- Core/Properties/AssemblyInfo.cs
- Core/Registry/RegistryManager.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Types/Kraken.cs
- GUI/Main.cs
- GUI/MainInstall.cs
- GUI/Program.cs
- GUI/SettingsDialog.cs
- Netkan/ConsoleUser.cs
I've replaced all the "\n"s I could find with "\r\n" except in bin/build and bin/build.lean. Should these be changed as well?
I tested with one particular error message ("overwrite a file owned by another mod") in the KSP window, and the linebreaks fine on Windows 10, Ubuntu 16.04, and OS X 10.10. I don't know how to use log4net, so I haven't tested messages printed with that, but it's probably all fine.
The two error messages with links to CKAN-meta/issues now point to CKAN/issues.
Fixes #1835
> Replace \n with \r\n and replace CKAN-meta/issues links

- README.md
There is no schema for netkan files - updated this.
The schema for ckan files is in the Schema Store - added that info.
> JSON Schema in README

- CONTRIBUTING.md
- Cmdline/Action/Install.cs
- Core/GameVersionProviders/KspBuildMap.cs
- Core/KSP.cs
- Core/KSPManager.cs
- Core/KSPPathUtils.cs
- Core/ModuleInstaller.cs
- Core/Types/Kraken.cs
- Core/Types/Version.cs
- GUI/ChooseKSPInstance.cs
- GUI/Configuration.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainChangeset.cs
- GUI/MainDialogs.cs
- GUI/MainInstall.cs
- GUI/MainModInfo.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
- GUI/MainWait.cs
- GUI/PluginsDialog.cs
- GUI/SettingsDialog.Designer.cs
- GUI/SettingsDialog.cs
- Netkan/Extensions/JObjectExtensions.cs
- Tests/Core/Types/Version.cs
This is not exhaustive, but a step in the direction of conforming all source to use the [conventions](https://msdn.microsoft.com/en-us/library/ms229045(v=vs.110).aspx) that were [suggested](https://msdn.microsoft.com/en-us/library/ms229002(v=vs.110).aspx) by Microsoft.
> Fix variable names and doc wording

- CKAN.schema
The Regexp on install "as" is not being parsed correctly. swapping the escaped \ and the / seems to work, though.
Should enable KSP-CKAN/NetKAN#4487 to build - I think this is the first time we've actually used "as".
Change tested using http://www.jsonschemavalidator.net/
> Update CKAN.schema "as" regexp

- GUI/MainInstall.cs
We don't show an empty suggested and recommended list if we can't install any of the mods.
Also don't show the recommended / suggested page if the user already cancelled the Installation.
> Don't show suggested/recommended for mods that can't be installed

- Core/CKAN-core.csproj
- Core/Extensions.cs
- Core/ModuleInstaller.cs
- Tests/Core/ModuleInstallerDirTest.cs
- Tests/Data/DisposableKSP.cs
- Tests/Tests.csproj
If the user attempts to uninstall a mod in Windows, there is a NullReferenceException where AddParentDirectories tries to compare a null to a string. It is also continuing to walk up above the GameData directory, adding my Program Files directory to the list of directories to delete.
The new code normalizes all compared paths and checks for several edge cases, improving its reliability.
I added new tests to ensure the Windows path oddities I saw don't creep back in.
> Fix Windows-only NullReferenceException and add more ModuleInstaller tests

- Tests/GUI/GH1866.cs
I have fixed up the unit test for the sorting issue #1725. It now logs a test failure if a NullReferenceException occurs during a mod install/list refresh process after sorting the list GUI by "Max KSP Version."
> Add unit test for "sort by max version" GUI crash

- CKAN.schema
- Cmdline/Action/Show.cs
- Core/Exporters/DelimeterSeperatedValueExporter.cs
- Core/Types/CkanModule.cs
- GUI/GUIMod.cs
- GUI/MainModInfo.cs
- Netkan/Transformers/AvcTransformer.cs
- Netkan/Transformers/PropertySortTransformer.cs
- Spec.md
Adds the Curse Uri to the `"resources"` stanza together with curse licenses.
```
"resources": {
"curse": "http://kerbal.curseforge.com/projects/220221"
}
```
> Add Curse to resources

- Core/Net/Repo.cs
Fix issue brought up in #1900 that @Olympic1 subsequently deleted?
Looks like this [rebase](https://github.com/KSP-CKAN/CKAN/commit/94335381e274cb07fe77ae1fa6183a2513131b8f#diff-a5b6137749fb38bca7e80257e4e5b158L144) accidentally deleted the line that updates the build mapping, thus leading to stale build mappings.
> Make sure we're updating the build mappings on repository update

- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
- Cmdline/log4net.xml
- Core/CKAN-core.csproj
- Core/Logging.cs
- GUI/CKAN-GUI.csproj
- GUI/Program.cs
- GUI/log4net.xml
- Netkan/CKAN-netkan.csproj
- Netkan/Program.cs
- README.md
- Tests/Core/Net/NetAsyncModulesDownloader.cs
- Tests/Data/DisposableKSP.cs
The logging initialization has been condensed into one class which will either load config from a log4net.xml in the app startup directory, or failing to find one tries to initialize the existing basic logging system. All of the logging entry points have been refactored to call this `Logging.Initialize()` method.
Tests are passing in the Windows/VS environment, review and feedback appreciated.
This would resolve #1452, which unfortunately has some project changes that are risky and needs a rebase.
> Add log4net.xml, refactor logging init and log to file by default

- Core/Logging.cs
Closes #1913, ref #1881 
This should get our builds working again. "prove" works on this build.
> Fix default logging on fallback when no XML file

- Netkan/Services/ModuleService.cs
Closes #1918
Shouldn't impact any existing $vref filespecs, as they all have complete paths.
> Add regexp second test for vref filespecs

- Core/Net/NetFileCache.cs
- GUI/GUIMod.cs
- GUI/MainModInfo.cs
- GUI/SettingsDialog.cs
Fixes #1928 by adding a method to GUIMod which allows the IsCached property to be updated, then calling it once when we finish caching after clicking Download and once when the cache is cleared.
> Update UI state when download cache is cleared

- Core/Registry/RegistryManager.cs
I'm not sure why the original change appended the word "locked" to create a file with "json" in the name that isn't a JSON file.
This is a tiny, tiny change from "registry.json.locked" to "registry.locked". Anyone have any reason not to make this change?
Closes #1943
> Change name of Registry lock file

- Core/Versioning/KspVersionBound.cs
- Core/Versioning/KspVersionRange.cs
- Tests/Core/Versioning/KspVersionRangeTests.cs
New method `KspVersionRange.IntersectWith(KspVersionRange)` mostly to support #1957
> Add IntersectWith method to KspVersionRange

- Cmdline/Action/CompatSubCommand.cs
- Cmdline/Action/KSP.cs
- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
- Cmdline/Options.cs
- Core/KSP.cs
@politas Support modifying KSP compatibility from the CLI.
Also fixes a bug where compatibility would be too permissive due to unitialized `version` field in `KSP`.
> Support modifying KSP compatibility on the command line

- GUI/ChooseKSPInstance.cs
This would resolve #1017 by changing the selection behavior for new instances. Instead of the `FolderBrowserDialog` we would be asking the user to select a KSP executable as a way of indicating the game root directory.
I'd like input on how safe that is - I believe that the KSP binaries are still suffixed in .exe when run in Mac/Linux environments but I haven't seen one of these installs.
The actual filter is `KSP*.exe` - so users will see 32- and 64-bit versions but can only select one.
There are also style changes in this file, variable names and changing `SetButtonsEnabled` because "Set*/Get*" methods are not C# style.
> Use OpenFileDialog instead of FolderBrowserDialog in instance selector

- GUI/Main.cs
Fixes issue #1967 by setting row background color to "Color.Empty" - the default color value for this object.
> Fix for black rows in GUI on conflicting mods.

- Cmdline/Action/Available.cs
- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
Console.WindiwWidth command was throwing an exception. Right-padding was not utilised on any other command, so code removed.
Moved available command into its own Action/Available.cs to match other commands.
Closes #359
> Remove non-functioning code on available command

- .gitignore
- Core/Net/NetAsyncDownloader.cs
Improvements in Mono and the downfall of kerbalstuff appears to have removed the necessity for curl downloads.
Closes #840
> Switch to all C# native mod downloads

- Netkan/Transformers/CurseTransformer.cs
This should allow KSP-CKAN/NetKAN#5471 to work, and will make all our Curse transforms more reliable.
> Convert spaces to %20 in Curse URLs

- Netkan/Transformers/AvcTransformer.cs
Explanation in comments in code.
> Canonicalize non-raw GitHub URIs

- Core/CKAN-core.csproj
- Core/ModuleInstaller.cs
- Core/Types/CkanModule.cs
- Core/Types/License.cs
- Core/Types/ModuleResolution.cs
- GUI/MainInstall.cs
#1935 mentions a timeout exception impacting only the GUI on large and/or slow downloads (taking longer than ten minutes). I believe this can be solved by moving the download process outside of the transaction begun in the GUI (there are additional transactions started inside Core which are not impacted by download times).
Of course, this is a terrible idea if changes to the cache are intended to be covered by the transaction, but I have not dug into the cache code deeply enough to know if this is the case. Thoughts?
To minimize the changes required (and thereby maximize my odds of not breaking anything), I have created the new download workflow *in addition to* the old one rather than replacing the old one. This is largely because the old one is in use in lots of different places …
> Move downloads outside of gui transaction

- Core/Types/ModuleInstallDescriptor.cs
ZIP files can contain entries for directories, but it's optional. Currently, CKAN behaves differently depending on whether these entries are present, which is probably bad since it may not be controllable by or even apparent to the user.
`find` and `find_regexp` currently loop through each entry in the ZIP and check whether they match against the search pattern. If file matching is turned on, the names of file entries are checked, otherwise their immediate parent folders are checked. If there are multiple matches, the shortest one is used.
This algorithm only works in two cases:
1. The directory being searched for is present as a directory entry
2. The directory being searched for does not have a directory entry but is the immediate parent directory of a file
It fails for an important …
> Check grandparent+ directories for find and find_regexp

- build.ps1
Currently, if there are spaces in the path to the CKAN source (e.g. `C:\Users\First Last\CKAN`), running build.ps1 fails with:
```
C:\Users\First : The term 'C:\Users\First' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and tr
again.
At line:1 char:1
+ C:\Users\First Last\CKAN/_build/tools/NuGet/4.1.0/nuget.exe instal ...
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\First:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
Adding an ampersand to the nuget and cake invocations fixes these errors.
> Fix build.ps1 script failing when spaces exist in source path

- Core/KSPPathUtils.cs
- Core/ModuleInstaller.cs
- Tests/Core/ModuleInstallerDirTest.cs
This should resolve most cases of #1940 without sacrificing case-sensitivity for the actual path creation/manipulation. The issue arises when ToAbsolute is called on an already-absolute path that did not have the same casing as the mod path. The StartsWith() should return false if the two directories are both absolute but have different casing.
> Perform directory root comparison in case-insensitive way

- Core/Registry/AvailableModule.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- Core/Types/CkanModule.cs
- GUI/GUIMod.cs
As per https://github.com/KSP-CKAN/NetKAN/issues/5945, the "Max KSP version" column is inaccurate for 3-4% of indexed mods:
- if the wrong version is chosen as "latest"
- if the compatible scope of the versions isn't coherent over time
This can discourage users from trusting this column, which is a problem because it should be a main tool for a common task: Determining whether it's safe to update the game.
This code change updates the column to show the actual maximum KSP version across all versions of each mod. The simplest possible strategy is used: loop over the versions and compare. The version ordering problems, accumulated bad metadata, and a few other related issues should still be addressed, so I don't consider this to be a complete fix for that issue, but now at least the column …
> Loop to find max KSP version instead of assuming ordering

- GUI/Main.Designer.cs
This change provides a Ctrl-Q hotkey for the File->Exit option, as well as an 'x' hotkey while the menu is being displayed. This makes exiting the GUI a bit more convenient for keyboard users.
> Quit on ctrl-q and alt-f,x

- Core/Types/ModuleInstallDescriptor.cs
`Path.GetDirectoryName("/a/b/c")` returns `"\a\b"` on windows, but the regexp assumes forward slashes.
On Linux it returns "/a/b", so the problem is platform-specific.
Since the regexp didn't match on Windows, the loop would fail to find the path and raise a file not found exception, as reported in #2135. I believe only `find`-based netkans were affected, but unfortunately that includes `DefaultInstallStanza`.
Renormalizing back to forward slashes ensures the regexp will match as it should.
> Fix exception installing some mods (fixes #2135)

- Core/Registry/Registry.cs
- GUI/GUIMod.cs
If a mod isn't in the registry, return null instead of raising an exception when looking for its max KSP version
When I tested this code change, I had a very recent registry, so the code only ran with identifiers that were in the dictionary. Users updating to 1.22.4 encountered newly added mods, which caused an exception as reported in #2134. Checking `ContainsKey` first will avoid this, and returning `null` signals that the mod is not in the registry, which will cause the column to default to max version of the newly added mod object.
> Fix crash on startup (fixes #2134)

- GUI/Main.Designer.cs
This change rearranges the code for the filter labels and text boxes to match the order they appear on the screen, then sets their `TabIndex` properties to consecutive increasing integers. This should make the tab order work as requested in #2007.
> Fix search box tab order (fixes #2007)

- Core/Registry/RegistryManager.cs
This code change checks whether the registry lock file is stale before attempting to acquire the lock. This eliminates the lock file popup when it's not needed as per #2075, but keeps it when CKAN is actually still running.
I think there are race conditions if the user tries to start multiple copies of CKAN simultaneously; do we care about that?
> Check for stale lock files (fixes #2075)

- Core/Types/CkanModule.cs
- Core/Types/ModuleInstallDescriptor.cs
- Netkan/Sources/Spacedock/SpaceDockApi.cs
- Netkan/Transformers/SpacedockTransformer.cs
- Netkan/Transformers/VersionEditTransformer.cs
- Netkan/Validators/InstallsFilesValidator.cs
`netkan.exe`'s error outputs are not always as clear as they could be. In some cases important details of the error are omitted, and very rarely a sentence is simply unclear.
This code change updates the following error strings to help with investigating issues.
| Error | Change |
| --- | --- |
| JSON deserialization error | Add the `Exception.Message` property produced by `PopulateObject` |
| Install stanzas must have a file an install_to | Remove "a file" since it looks non-grammatical |
| Could not get the mod from SD, reason: {upstream error}. | Change SD to SpaceDock, remove trailing period |
| Expanding {url} to full SD URL | Change SD to SpaceDock |
| Could not normalize URL: {non URL} | Add mod identifier |
| Could not match version with find pattern | Add the version and the find …
> Improve exceptions and error messages

- .travis.yml
Potential fix for #2133 
The failure in #2133 has nothing to do with our build process, but is a Ruby error generated by Travis itself:
```
No such file or directory @ rb_sysopen - _build/repack/Release/ckan.exe
```
Meaning it can't find the file to deploy. The `skip_deploy` option is necessary to prevent Travis from cleaning out the working directory according to [this](https://docs.travis-ci.com/user/deployment/#Uploading-Files). The GitHub release provider did not have yet, although the Amazon S3 provider did. My assumption is that previously *any* provider having `skip_cleanup` meant that no cleanup was done and that some change was made in Travis which causes cleanup to be done if any provider *doesn't* have it. Only way to really test this is to try another release @politas
> Add skip_deploy to GitHub release deploy provider

- CKAN.schema
- Spec.md
This patch is related to issue #1021
> Add spec/schema to implement mod tags

- .travis.yml
- AutoUpdate/CKAN-autoupdate.csproj
- AutoUpdate/packages.config
- CKAN.sln
- Cmdline/CKAN-cmdline.csproj
- Cmdline/packages.config
- Core/CKAN-core.csproj
- Core/Registry/RegistryManager.cs
- Core/packages.config
- GUI/CKAN-GUI.csproj
- GUI/packages.config
- Netkan/CKAN-netkan.csproj
- Netkan/packages.config
- Tests/Tests.csproj
- Tests/packages.config
- build
- build.cake
- build.ps1
- packages.config
General update to the build. Important new feature: The csproj files have been updated to generate the GlobalAssemblyVersionInfo file if it doesn't already exist. This should allow the project to build out-of-the-box in IDEs like Visual Studio without having to go to the command line first.
Other updates:
- Add `Release` and `Debug` targets
- Remove unused variable to fix warning
- Update Mono versions used for build
- Remove Mono 4.0.5 (breaking with newest Cake)
- Upgrade Mono 4.8.0 to 4.8.1
- Upgrade Mono 5.0.0 to 5.0.1
- Add Mono 5.2.0
- Add Mono 5.4.0
- Upgrade NuGet from 4.1.0 to 4.4.0 (and use `restore` instead of `install`)
- Upgrade Cake from 0.19.5 to 0.23.0 (and fix new breaks script)
- Upgrade Cake.SemVer from 1.0.14 to 2.0.0
- Upgrade NUnit.ConsoleRunner from 3.6.1 to 3.7.0
- …
> Build Update

- Cmdline/ConsoleUser.cs
- Core/Net/NetAsyncDownloader.cs
- Core/User.cs
- GUI/Main.cs
- Netkan/ConsoleUser.cs
Currently `IUser` has 6 public events, which makes it awkward to implement this interface. These events are only used inside `NullUser`, so at first blush, they belong inside `NullUser` as an implementation detail. However, all `NullUser` does with them is wire up the interface's functions to `NullUser`'s own equivalent `virtual` functions. This is an unnecessary and cumbersome step of indirection with no advantages over simply calling those functions directly. (Technically this structure could allow third-party classes to inject listeners to various events in other places, but no code currently does this, so the need/advantage is debatable.)
This PR replaces this structure with a much simpler one and does some additional minor clean-up:
- Remove the events from the interface, making it …
> Simplify IUser

- CKAN.schema
- Core/Types/ModuleInstallDescriptor.cs
- Spec.md
- Tests/Core/ModuleInstaller.cs
- Tests/Data/TestData.cs
This PR adds two fields which practically work as negative filter/filter_regexp.
Also includes a test and changes to the schema to make sure there are only filter or include_only fields but never both.
Also added the new "filters" to the spec.
Closes #228
Closes #1577
> Add include_only fields

- GUI/AskUserForAutoUpdatesDialog.Designer.cs
Unlike the main CKAN window, the AskforUpdates dialog that appears on initial launch of CKAN does not raise a taskbar entry. Moving this dialog to the centre of the screen minimises opportunities for the dialog to appear off-screen due to multi-monitor setups.
Closes #2164
> Move AskForAutoUpdates dialog to centre of screen

- CKAN.schema
NetKAN pull requests and the bot are currently failing at the schema validation step, and the output suggests it's something from #2170. This command can be used to reproduce the issue locally:
```
python ./bin/ckan-validate.py /path/to/existing/valid/file.ckan
```
I tried running `CKAN.schema` through the validator at https://www.jsonschemavalidator.net/ , and it flagged two places where `"type"` was used that should have been `"$ref"`. After fixing this, the validation script runs successfully.
> Fix schema validation errors

- Core/Registry/RegistryManager.cs
I have an old KSP 0.90 install that has a corrupted `registry.json` file (truncated in the middle of a string in the section about the installed files). If I try to access this instance with `RegistryManager.Instance()`, an appropriate `JsonReaderException` is thrown in the constructor of `RegistryManager` and no access is possible, but the `registry.locked` file is still in the folder (it is created by `GetLock` immediately before the parsing is attempted). Depending on exactly what the process does after that, additional exceptions can occur at random when various of the object's partially constructed resources are destroyed by the garbage collector. The lock file _does_ disappear later when the process exits.
When a constructor throws an exception, this means the requested object …
> Clean up registry lock file after parse failure

- Core/Registry/InstalledModule.cs
- Core/Types/CkanModule.cs
- Core/Types/ModuleInstallDescriptor.cs
The `registry.json` file must be loaded and parsed before CKAN can do anything (CLI, GUI, etc.). Currently this file is about 21 MB and takes about 2 seconds to load on an SSD. Nearly 6 MB of it just sets assorted properties to `null`. But guess what value the deserializer uses if the property is absent? Yep: `null`. So those properties don't need to be there.
This pull request marks all the `JsonProperty` attributes that have at least one `null` value in `registry.json` with `NullValueHandling = NullValueHandling.Ignore`, which means that if the value is `null`, it will not be printed to the file. When the properties are not `null`, they will be saved and loaded normally. The file will load the same and CKAN will work the same either way.
```
$ ls -gG
-rw-r--r-- 1 21217174 Nov  9 16:58 …
```
> Purge 6 MB of bloat from `registry.json`

- Netkan/Sources/Curse/CurseApi.cs
- Netkan/Sources/Curse/CurseError.cs
- Netkan/Sources/Curse/CurseFile.cs
- Netkan/Sources/Curse/CurseMod.cs
- Netkan/Transformers/CurseTransformer.cs
- Tests/NetKAN/Sources/Curse/CurseApiTests.cs
- Tests/NetKAN/Transformers/CurseTransformerTests.cs
Closes #2178.
This pull request updates the Curse API code to work with the latest changes to the widget.
- The base URL is changed
- No longer need json suffix in URL
- `files` is now an array rather than a dictionary
- `authors` is now moved into `members` array with `username` as property name
- The version is now embedded in `name`
After these changes, the tests all pass and `netkan.exe` generates files that match previous versions except for specifics of URLs.
> Adapt Curse API to new widget

- .travis.yml
See my comment on #2191; the `mono --version` check is now printing 5.4.0.201 instead of just 5.4.0, and our perl regex extracts that whole string. This pull request changes the perl regex to match just the 5.4.0 part, so it should match BUILD_RELEASE_MONO_VERSION again.
This should get builds deploying to S3 again, which should fix the Curse errors on the status page.
> Only check first three segments of version in ci (fixes #2191)

- Core/Registry/AvailableModule.cs
- GUI/GUIMod.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- GUI/Util.cs
- Tests/GUI/MainModList.cs
This is a possible fix for #2162, and an alternative to #2183.
That issue happens because after a failed install/upgrade attempt, `Main.PostInstallMods` rebuilds the mod list and then re-applies the `ModChanges` object's changes to the checkboxes. But one of the checkboxes may no longer be a checkbox, and trying to access it as one causes a null reference exception.
This pull request eliminates the possibility of this happening. Rather than generating the check boxes in a default state and then applying a `ModChanges` after the fact, we now pass the `ModChanges` directly to `Main.ConstructModList` and use it to control the initial checkbox state, so the row object starts out consistent with the `ModChanges`.
`ConstructModList` is cleaned up a bit to make this happen. Previously it created …
> Initialize checkboxes to desired value at creation

- Core/ModuleInstaller.cs
- Core/Relationships/SanityChecker.cs
- Core/Types/CkanModule.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
KSP-CKAN/NetKAN#6044 highlighted some issues with how dependencies are handled currently:
- If you have a mod that's installed but not available (TextureReplacer in the initial report, which is available in 1.3.0 and not in 1.3.1, and the user had upgraded), `RelationshipResolver` can cause an unhandled exception when trying to compute conflicts, which happens whenever you try to install a new mod.
- That exception says "Cannot install XYZ, module not available", which is partially correct and partially misleading; it is not available, but we were **not** trying to install it.
- If you manually delete a mod that CKAN installed, the message contains "ModuleManager but it is not listed in the index, or not available for your version of KSP", which is incorrect and misleading because …
> Avoid crash with unavailable installed mod, improve error messages

- .travis.yml
Applying the fix from #2192 to release builds in addition to per-merge builds. The same condition was used in both places, so it would have stopped a release from building as well.
> Update version regex for release builds as well

- ISSUE_TEMPLATE.md
Monitoring the new issue queue, a few patterns are apparent. There are some questions we don't ask in the issue template that we should, as well as some questions that don't generally receive productive responses. And a lot of people don't delete the instructional text at the top.
This pull request modifies the issue template:
- Put the introductory text in a comment since it's not needed after the issue is submitted
- Added link to where you can do a search of open issues
- Split into background/problem sections
- Added space between questions to encourage more consistent formatting :crossed_fingers: 
- Added question about KSP version since many issues are version-specific
- Added question about manual modifications to GameData since this is a frequent cause of issues
- "Issue you are …
> Revise issue template

- Cmdline/Action/Compare.cs
- Cmdline/Action/CompatSubCommand.cs
- Cmdline/Action/ICommand.cs
- Cmdline/Action/KSP.cs
- Cmdline/Action/List.cs
- Cmdline/Action/Repair.cs
- Cmdline/Action/Repo.cs
- Cmdline/Main.cs
- Cmdline/Options.cs
This pull request resolves several problems with CmdLine help text, first noted in #445 and again in #1490.
- Before, only the main listing of commands was shown when the `--help` parameter was used, regardless of the rest of the command line. Now, command-specific help is shown if you enter a partial command.
- When accessing help for a command, two extra lines are printed at the top, first the description from the command listing, then the format of the command.
- Subcommands' commands also have their own help listings.
- The `--ksp` and `--kspdir` options are omitted for commands that don't need an instance, such as `version`, `ksp`, or `repo available`
- Similarly, such commands now don't load the registry. This was done partially before by hard-coding a few such command names; now …
> Fix cmdline help text problems (fixes #445, fixes #1490, fixes #2105)

- Cmdline/Action/CompatSubCommand.cs
- Cmdline/Action/KSP.cs
- Cmdline/Action/Repair.cs
- Cmdline/Action/Repo.cs
- Cmdline/Main.cs
- Core/Registry/RegistryManager.cs
Since #2197 got merged, NetKAN validation is failing with `System.ObjectDisposedException`.
```
Running ckan update
Downloading updates...
Updated information on 687 available modules
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Stream has been closed'.
at System.IO.FileStream.Flush () [0x0000d] in <62f5937022004555807e6c57c33f6684>:0 
at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00094] in <62f5937022004555807e6c57c33f6684>:0 
at System.IO.StreamWriter.Dispose (System.Boolean disposing) [0x00022] in <62f5937022004555807e6c57c33f6684>:0 
at System.IO.TextWriter.Dispose () [0x00000] in <62f5937022004555807e6c57c33f6684>:0 
at (wrapper remoting-invoke-with-check) …
```
> Dispose registry managers before exit to prevent exceptions

- Cmdline/Action/Install.cs
- GUI/Main.cs
Fixes #2171; see that issue for details. To sum up, loading a .ckan file can raise exceptions, and currently they're not handled well. In Cmdline they are caught by the uncaught exception handler, and in GUI the exception handler itself causes a null reference exception.
Now in both cases we properly print out the error using an IUser reference.
> Avoid NRE in install-from-ckan (fixes #2171)

- GUI/MainDialogs.cs
#2207 pointed out that a null reference exception can occur in GUI's `TooManyModsProvide`. Auditing this function, all object references but one are either checked for null before use or initialized with `new` and never set again.
The one unsafe line is supposed to be set by a `TryPeek` call, which returns true if it sets the reference and false otherwise, but currently that return value is being ignored. Now we will use that return value to guard the remaining unsafe reference.
Fixes #2207.
> Avoid NRE in TooManyModsProvide (fixes #2207)

- Core/Registry/Registry.cs
- GUI/GUIMod.cs
- GUI/MainModList.cs
Previously, `Registry.Available` checked for the availability/compatibility of mods' dependencies, but `Registry.Incompatible` only looked at the KSP versions. This meant that mods with compatible KSP versions but with incompatible dependencies were excluded from both of those lists. Since these two lists of mods are used to generate the full list of mods to show in the All filter of GUI, such mods would simply vanish and be completely invisible to the user.
Now the dependency checking logic is refactored into a private helper function called by both `Registry.Available` and `Registry.Incompatible`. Mods with incompatible dependencies will themselves appear in `Registry.Incompatible`, and GUI's All filter will actually show all mods, as expected.
Fixes #1695.
> Available ∪ Incompatible = All

- Cmdline/Action/Install.cs
- ConsoleUI/InstallScreen.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Types/Kraken.cs
- GUI/MainInstall.cs
- Tests/Core/Relationships/RelationshipResolver.cs
Currently `ModuleNotFoundKraken` is thrown if a dependency isn't met, but this only specifies the mod that can't be installed, not the one that depends on it. This means that if the depending mod is specified indirectly somehow, the user is not told how to avoid the error.
This pull request adds a new Kraken-inheriting class that specifies both the unavailable mod as well as the depending mod, and throws it from the relationship resolver. To maintain backwards compatibility, this new class inherits from `ModuleNotFoundKraken`. We also catch this Kraken in Cmdline, ConsoleUI, and GUI, and extend the messages to the user accordingly. And an identical error-level log message is moved to verbose-level, because we're already throwing an exception.
Before (using KSP 1.3.1):
```
$ mono ckan.exe …
```
> Add depending mod to missing dependency exception

- Cmdline/Action/Install.cs
- Cmdline/Options.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Types/CkanModule.cs
`ckan install identifier=version` currently bypasses game version compatibility checks. This means that an incompatible module that you normally couldn't install at all, can be installed just by specifying any version:
```
$ mono ckan.exe install AvisorforValentina
Module AvisorforValentina required but it is not listed in the index, or not available for your version of KSP.
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules.
```
```
$ mono ckan.exe install AvisorforValentina=1.01
* A visor for Valentina 1.01
```
This makes the `identifier=version` format unsafe by default, since compatibility checking is just turned off; this could be a problem if I intend to …
> Check game version compatibility when installing specific version

- Cmdline/Action/Install.cs
- Cmdline/Action/Remove.cs
- Cmdline/Action/Search.cs
- Cmdline/Action/Upgrade.cs
- Core/Types/CkanModule.cs
Previously, Cmdline users had to type the exact capitalization of each mod identifier in the `install`, `remove`, and `upgrade` commands. This pull request adds a lookup step to convert "incorrectly"-capitalized identifiers to their correct capitalization, based on what is indexed in the registry. This allows users to type any capitalization they like as long as the letters are all the same.
Before:
```
$ mono ckan.exe install astroGATOR
Module astroGATOR required but it is not listed in the index, or not available for your version of KSP.
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules.
```
After:
```
$ mono ckan.exe install astroGATOR
* Astrogator v0.7.8(cached)
Continue? [Y/n] …
```
> Make Cmdline modules case insensitive

- .travis.yml
- Core/Net/AutoUpdate.cs
- Tests/Core/Net/AutoUpdate.cs
This pull request replaces #2204, which was closed because its approach wasn't appropriate. See that PR for details of the problem being solved.
New approach:
- Add AutoUpdater.exe to the list of downloadable files when creating a new release on GitHub
- Update client to look for this file and use it, falling back to the old URL if it's missing
This change assumes that the list of assets in the release will be in the same order as they are in the `.travis.yml` file. I believe this would be the case because it's an array rather than a dictionary, and the easiest way for Travis to implement it would be a simple `foreach` loop, but I was not able to find documentation or a concrete example to confirm this.
We should mention in the next release notes that users do _not_ need to download …
> Provide fresh auto updater in releases

- Cmdline/Action/Remove.cs
`ckan remove --all` currently tries to remove autodetected DLLs, which fails. This makes this command unusable on Steam installs, which always have two extra DLLs, `KSPSteamCtrlr` and `Steamworks`.
`ckan remove --re regularexpression` has the same problem if the regular expressions match any autodetected DLL.
`Cmdline/Action/Remove.cs` loops over `Registry.Installed`, which includes autodetected DLLs:
```
Installed: KSPSteamCtrlr autodetected dll
Installed: Steamworks autodetected dll
Installed: StockVisualEnhancements 3:1.2.7.0
Installed: SVE-LowResolution 3:1.0.2
Installed: Scatterer-sunflare 2:v0.0320b
Installed: Scatterer-config 2:v0.0320b
Installed: DistantObject-default v1.9.1
Installed: Scatterer 2:v0.0320b
Installed: EnvironmentalVisualEnhancements 2:EVE-1.2.2-1
Installed: …
```
> Don't try to remove autodetected DLLs

- GUI/Configuration.cs
- GUI/Main.cs
- GUI/MainModInfo.cs
Stores the SplitterDistance of the main window in GUIConfig.xml as PanelPosition when closing the window and restores it on opening.
Closes #2208
> Save and restore panel position

- Cmdline/Action/KSP.cs
- Cmdline/Options.cs
- ConsoleUI/KSPListScreen.cs
- Core/KSP.cs
- Core/KSPManager.cs
- GUI/ChooseKSPInstance.Designer.cs
- GUI/ChooseKSPInstance.cs
- GUI/Main.cs
If a KSP instance that CKAN knows about is removed manually (i.e., the user deletes the folder), an error message is printed at startup:
```
194 [1] WARN CKAN.KSPManager (null) - rss at /Users/lamont/ksp_rss is not a vaild install
```
But it's impossible to remove it from the list of known installs, because it's not added to the list that is manipulated to make that happen. However, if the user _adds_ another instance, then any currently invalid instances are automatically removed.
None of this is particularly desirable. It should always be possible for the user to remove any instance, but no instance should be removed without the user choosing it.
Now invalid instances are added to the list of known instances at startup; they appear in the instance selection list in Cmdline, ConsoleUI, …
> Include invalid instances in KSPManager

- build.ps1
If you run the current `build.ps1` script with PowerShell 2 or earlier, [the `$PSScriptRoot` variable isn't set](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-5.1), which means several of the build script's variables are set to either the empty string or incomplete values. This has many consequences, for example the `_build` directory is created in the root of the drive.
https://github.com/KSP-CKAN/CKAN/blob/700f70951dfaa352a288b1a70bbf5132379239bc/build.ps1#L12-L18
This pull request checks the currently running version of PowerShell and prints an error if it's less than 3.0:
We could try to make the script backwards compatible with PowerShell 2.0, but PowerShell is up to 5.1 now, so it's probably better just …
> Check version of PowerShell in build script

- Cmdline/Main.cs
- Core/KSP.cs
- Core/KSPManager.cs
- Core/ModuleInstaller.cs
- Core/Net/Net.cs
- Core/Net/NetFileCache.cs
- Core/Net/Repo.cs
- Core/Registry/RegistryManager.cs
- Core/Relationships/RelationshipResolver.cs
- GUI/MainModList.cs
Unbeknownst to many, including myself until today, [CKAN has log file capabilities](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#logging). It can use several different levels of verbosity, with DEBUG being way too slow and verbose (dozens of megabytes of excruciating detail about nothing), and WARN saying little to nothing (errors only, essentially). For purposes of this pull request, assume we're always talking about INFO, which represents a happy medium in between.
Currently the INFO log isn't as useful as it could be. It contains many details that users would not care about, and leaves out other important information about what's happening. A typical session generates a very long log file, but it's hard to figure out what actually happened from it.
This pull request aims to make …
> Add and change logging to make INFO readable

- Core/ModuleInstaller.cs
- Core/Net/AutoUpdate.cs
- Core/Net/NetAsyncDownloader.cs
- GUI/Main.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- Netkan/CmdLineOptions.cs
- For cached modules, added a space between version and "(cached)"
- For non-cached modules, added indication of download host so the user can make a more informed decision about whether to continue with the downloads
```
$ mono ckan.exe install GPP
1) DistantObject-RealSolarSystem (Distant Object Enhancement Real Solar System config)
2) DistantObject-default (Distant Object Enhancement default config)
Enter a number between 1 and 2 (To cancel press "c" or "n".): 
2
* Galileo's Planet Pack 1.5.88 (github.com)
* Distant Object Enhancement default config v1.9.1 (cached)
* Kopernicus Planetary System Modifier 2:release-1.3.1-3 (github.com)
* ModularFlightIntegrator 1.2.4.0 (cached)
* scatterer 2:v0.0320b (cached)
* scatterer - default config 2:v0.0320b (cached)
* GPP …
```
> Use shared installer code in GUI and fix reinstall problems

- Cmdline/Action/Update.cs
- Core/Net/Repo.cs
- Core/Registry/Registry.cs
- Tests/Core/Net/NetAsyncModulesDownloader.cs
- Tests/Core/Net/Repo.cs
- Tests/Core/Relationships/SanityChecker.cs
There are sporadic but repeated reports of `ModuleNotFoundKraken` being thrown in `Registry.AllAvailable`. This happens when `available_modules` is empty.
See #1994 and KSP-CKAN/NetKAN#5907 for examples.
Currently when we update the registry, we clear `available_modules` first, then request the remote repo data and parse it. If anything goes wrong with those network requests or the parsing, we can't un-clear `available_modules`; it's gone, and that's that, and we have nothing to replace it with.
This pull request refactors the relevant code to avoid clearing `available_modules` until the full new list of available modules is retrieved and non-empty. The low-level retrieval and parsing functions are changed to return the new values rather than setting them into a `Registry` object. The …
> Don't clear available modules till after the new list is ready

- GUI/MainInstall.cs
In GUI, `provides` relationships are only checked for `depends`; if a mod suggests or recommends a virtual package, it's not shown.
One example is ProceduralFairings in KSP 1.2.2; it `suggests` a virtual package called `PFTextures`, which is provided by another module. Currently this module doesn't appear in GUI as a suggestion when installing ProceduralFairings.
Now if we don't find the exact name of an optional dependency, we check for mods that provide it and add them to the recommendation/suggestion lists for the user to choose.
Fixes #1234.
> Check provides for optional dependencies in GUI

- Cmdline/Action/KSP.cs
- ConsoleUI/KSPAddScreen.cs
- ConsoleUI/KSPEditScreen.cs
- ConsoleUI/KSPListScreen.cs
- ConsoleUI/ModListScreen.cs
- Core/CkanTransaction.cs
- Core/KSP.cs
- Core/KSPManager.cs
- Core/Registry/RegistryManager.cs
- GUI/ChooseKSPInstance.cs
- GUI/Main.cs
- Tests/Core/KSP.cs
- Tests/Core/KSPManager.cs
- Tests/Data/DisposableKSP.cs
Currently if users install and uninstall lots of mods, they have no record of the changes. This can be a problem if one of the mods they install is not compatible, since they have no easy way to return to an older state or even know what the older states were.
We do create a `CKAN/installed-default.ckan` file containing the list of installed mods, but this is overwritten each time the mod list changes.
Now each CKAN folder will have a `history` subfolder created, and when the list of installed mods is changed, a new file with a name like this is created:
- `installed-steam-2018-01-02_22-21-37.ckan`
This contains the same info as the `installed-default.ckan` file, but it will not be overwritten by later changes, because the file name contains the change timestamp. This allows the user to …
> Save timestamped .ckan files after we save the registry

- Core/Registry/Registry.cs
- GUI/Main.cs
If the registry's `available_modules` list is empty while GUI is trying to use it, null reference exceptions can occur.
See #1994 and KSP-CKAN/NetKAN#5907 for examples.
The GUI already auto-refreshes the `available_modules` list at startup if `configuration.RefreshOnStartup` is true.
`available_modules` is empty by default when first adding a new instance, which we handle by setting `configuration.RefreshOnStartup` to true for such a newly added instance, so the registry will be loaded when we get to that part of the initialization.
Now the GUI performs its registry auto-refresh in one more situation: when `available_modules` is empty. This ensures that we will re-download the registry if we need to.
Closes #2115. After looking at that pull request, I don't think the approach is workable; …
> Update registry at start of GUI if available_modules is empty

- GUI/Main.cs
1. Install some mods
2. Either upgrade your game or modify your compatible KSP versions so that some of the mods from step <span>#</span>1 become incompatible
3. Change GUI filter to Incompatible
4. Try to uninstall some of your incompatible mods. The apply changes button does not become enabled.
Note that this is not an architectural limitation of Core; if you use the All filter instead, you can uninstall incompatible mods.
There was an explicit check for the Incompatible filter in `ModList_CellValueChanged`, presumably to prevent the user from _installing_ incompatible mods. However, such mods won't have checkboxes anyway. This check is removed.
Also added a few null checks to the function to be on the safe side.
Fixes #1842.
Replaces #1929, which was reverted in #2150 due to issues …
> Allow uninstallation of mods while Incompatible filter is selected

- GUI/Main.Designer.cs
- GUI/MainDialogs.cs
- GUI/MainWait.cs
CKAN's GUI has a status bar that is always empty:
And some code that tries to set it:
https://github.com/KSP-CKAN/CKAN/blob/378d12818ade7831e27a953096f531cc546a9b11/GUI/MainDialogs.cs#L23-L27
Currently they aren't connected.
Two different status bar controls are in use at the moment: the one that is visible, and the one that receives the status messages from code.
- `statusStrip1` is the control that's actually visible. It has no contained controls and none of its properties are set by code during downloads/installs.
- `StatusPanel` is a panel which is technically added to the form but not visible. `StatusLabel` is a label which is added to this and which receives the status messages from the application, but again is not visible.
The status bar code is rewritten according to the …
> Show status bar text, add progress bar

- ConsoleUI/DownloadImportDialog.cs
- ConsoleUI/InstallScreen.cs
- ConsoleUI/ModInfoScreen.cs
- ConsoleUI/ModListScreen.cs
- ConsoleUI/Toolkit/Formatting.cs
- Core/ModuleInstaller.cs
- GUI/CKAN-GUI.csproj
- GUI/GUIMod.cs
- GUI/Main.Designer.cs
- GUI/MainImport.cs
- GUI/MainModList.cs
Issues with downloading sometimes lead users to download files with a browser, but if it works, there's no way to make CKAN use the files. There should be, because they're the same files regardless of who downloads them.
This pull request adds a new "Import downloaded mods..." option to GUI's (slightly reorganized) File menu:
Clicking it brings up a file selection dialog where the user can select multiple ZIP files, starting in their profile's Downloads folder:
If the user accepts that popup, CKAN switches to the progress bar tab and displays messages about its progress in importing the files. At the end, if any of the mods are compatible and not yet installed, the user is asked whether to install them:
If the user clicks Yes, then they're taken to the install flow for those selected …
> Add import downloads menu item to GUI

- GUI/MainModInfo.cs
Many mod relationships are mutual/circular, so mod X conflicts with Y, and Y also conflicts with X.
In the 1.24 pre-release version of the GUI relationships tab, this means you can expand them in an infinite chain if you want to, back and forth forever. This causes visual clutter and is a bit silly looking. Example from #2257:
Now we omit the children of nodes that already have their children shown as part of their own ancestry. The user will have seen them already when they expanded the identical ancestor node.
This is done by walking the tree via `TreeNode.Parent` up to the root and comparing the `CkanModule` objects located in the `.Tag` property.
Fixes #2257.
> Leave out children already shown in ancestor node

- GUI/Main.cs
- GUI/MainModList.cs
If you install a .ckan file with dependencies that are virtual modules (provided by multiple mods via the `provides` metadata property), you would get one of these exceptions, depending on whether you were using CKAN 1.22 or earlier, or 1.24:
```
CKAN.TooManyModsProvideKraken: Too many mods provide Scatterer-sunflare:
Scatterer-sunflare 2:v0.0320
* AstronikiSunflareforScatterer 1.2
* CepheusSunflare 1.2
* EdenSunflare 1.2
* SVE-Sunflare 2:1.1.6
bei CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
bei CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
bei …
```
> Resolve provides for install-from-ckan-file

- Core/Net/AutoUpdate.cs
- Core/Net/Net.cs
- Core/Net/NetAsyncDownloader.cs
- Core/Net/NetAsyncModulesDownloader.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- Core/Types/CkanModule.cs
- Core/Win32Registry.cs
- GUI/MainModInfo.cs
- Tests/Core/Net/NetAsyncModulesDownloader.cs
CKAN's GitHub downloads fail with an HTTP 403 status fairly frequently. We do not know the exact details that trigger it, but it mostly affects large downloads.
It also turns out that the URLs we're using are supposed to be for users and browsers only, not applications. We should migrate to using the GitHub API.
See #2210 for details.
GitHub's normal download links are throttled to prevent abuse, and CKAN's use of them is sometimes affected by this.
GitHub prefers applications to use the GitHub API for programmatic access, which requires support for two new HTTP headers, one that specifies the MIME type of the download (without this, the API returns a JSON description of the file instead of the actual download):
```http
Accept: application/octet-stream
```
And one that contains the user's …
> Accept header and infrastructure for auth tokens

- Cmdline/Action/Import.cs
- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
- Cmdline/Options.cs
- Core/ModuleInstaller.cs
- Core/Net/NetModuleCache.cs
#2177 created the ability to import manually downloaded files to the cache, as part of ConsoleUI.
#2246 added it for GUI.
This pull request adds the same import functionality for Cmdline.
```
$ ckan import --help
CKAN 1.24.0-PRE2+d6a802f8a78c
Copyright © 2014-2017
import - Import manually downloaded mods
Usage: ckan import [options] paths
--ksp              KSP install to use
--kspdir           KSP dir to use
-v, --verbose      (Default: False) Show more of what's going on when 
running.
-d, --debug        (Default: False) Show debugging level messages. Implies 
verbose
--debugger         (Default: False) Launch debugger at start
--net-useragent    Set the default user-agent string for HTTP requests
--headless         (Default: False) Set to disable all prompts
--asroot …
```
> Add Cmdline import command

- macosx/CKAN
CKAN's GUI apparently does not work in 64-bit on OSX (see #2269 and [the wiki](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-OSX)).
This pull request adds `--arch=32` to the command line of mono in the `CKAN.app` bundle, and removes `--debug` because it's not recommended on the wiki.
(This doesn't fix #2269 because that user isn't using the app bundle.)
> Use arch=32 for OSX

- Cmdline/Action/AuthToken.cs
- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
- Cmdline/Options.cs
- ConsoleUI/AuthTokenAddDialog.cs
- ConsoleUI/AuthTokenListScreen.cs
- ConsoleUI/CKAN-ConsoleUI.csproj
- ConsoleUI/ModInfoScreen.cs
- ConsoleUI/ModListScreen.cs
- Core/Net/AutoUpdate.cs
- Core/Net/NetAsyncDownloader.cs
- Core/Win32Registry.cs
- GUI/SettingsDialog.Designer.cs
- GUI/SettingsDialog.cs
We're trying to migrate some of CKAN's downloads to use the GitHub API to solve problems with download throttling. Part of using the API is supporting authentication tokens. See #2210 for details.
#2263 added the core infrastructure for supporting authentication tokens. This allows GitHub API URLs to be accessed, but the only way the user could do the needed configuration is via `regedit` or another similar tool.
This pull request adds user interfaces for viewing and editing auth tokens.
Each UI validates input to prevent duplicate tokens for the same host and to ensure the host string is a valid host name.
Now there's a new `ckan authtoken` subcommand:
```
>ckan authtoken
CKAN 1.24.0-PRE2+c2bdd52cabf8
Copyright c 2014-2017
ckan authtoken - Manage authentication tokens
Usage: ckan …
```
> User interfaces for auth tokens

- Cmdline/Action/Install.cs
- ConsoleUI/InstallScreen.cs
- ConsoleUI/ModInfoScreen.cs
- ConsoleUI/ModListScreen.cs
- ConsoleUI/Toolkit/ConsoleFileMultiSelectDialog.cs
- ConsoleUI/Toolkit/Formatting.cs
- Core/ModuleInstaller.cs
- Core/Net/Net.cs
- Core/Net/NetAsyncDownloader.cs
- Core/Net/NetAsyncModulesDownloader.cs
- Core/Net/Repo.cs
- Core/Types/CkanModule.cs
- Core/Types/Kraken.cs
- GUI/GUIMod.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainChangeset.cs
- GUI/MainDialogs.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
- GUI/MainWait.cs
- GUI/SettingsDialog.cs
If you try to install mods in GUI and one or more downloads errors out, it's not handled well.
| CKAN version | Outcome |
| --- | --- |
| 1.22.6 and earlier | `DownloadErrorsKraken` thrown and caught by the uncaught exceptions handler, effectively crashing the app |
| 1.24.0-PRE-1 (post-#2233) | Error raised, user can cancel and retry, but retrying doesn't attempt to download or install anything |
Before #2233, GUI's downloads happened on this line:
https://github.com/KSP-CKAN/CKAN/blob/28c981e3bf71d3f596cd8f537bf33831e4e8ab36/GUI/MainInstall.cs#L123
That function can throw `DownloadErrorsKraken`s, and there's nothing there to catch them.
After #2233, that exception is handled, but the user's change set was still being lost in a few ways:
- The code to install was calling …
> Retry of failed downloads

- Cmdline/ConsoleUser.cs
- Netkan/ConsoleUser.cs
When GPP updates, Jenkins has to download 181 MB of files. Since Cmdline currently prints a download status every 3 seconds, this results in most of the log looking like this:
https://ci.ksp-ckan.org/job/NetKAN/6759/consoleText
```
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - 98 MB left - 45%           
1615 kbps - downloading - …
```
> Print fewer download updates in headless mode

- Core/Types/Kraken.cs
As #2278 points out, the error message for certificate errors is outdated:
```
Oh no! Our download failed with a certificate error!
If you're on Linux, try running:
mozroots --import --ask-remove
on the command-line to update your certificate store, and try again.
```
According to our own wiki pages, `mozroots` has been superseded by `cert-sync` since Mono 3.12.0 in early 2015, but the error message still suggests `mozroots`.
This pull request updates it to recommend the wiki page about certs instead:
- https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors
This page was created just now based on the information previously scattered across each Linux page about certs, which now link to the new page. This way instead of updating the code to keep up with changes in Mono, we can just …
> Point to wiki page about certs on cert errors

- Cmdline/Action/AuthToken.cs
- Cmdline/Action/Compat.cs
- Cmdline/Action/ISubCommand.cs
- Cmdline/Action/KSP.cs
- Cmdline/Action/Prompt.cs
- Cmdline/Action/Repair.cs
- Cmdline/Action/Repo.cs
- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
- Cmdline/Options.cs
- Core/ModuleInstaller.cs
Fixes #2161.
CKAN's Cmdline interface executes one command and then exits. Scripts can be written with CKAN, but they require CKAN to be executed once per command, with the cost of parsing `registry.json` incurred for each command.
A new `ckan prompt` command is created that:
- Prompts the user for commands as input, displaying the CKAN version and the name and game version of the active instance, if any
- Interprets them as Cmdline commands and subcommands
- Only parses `registry.json` once for a given instance across multiple commands, so you don't have to wait several seconds between operations
- Carries its `CommonOptions` flags over to the commands it runs (mainly to make a top-level `--headless` work properly)
Line break added before the `install` command to simulate having the …
> Add a read-execute-print-loop prompt for Cmdline

- Core/Net/AutoUpdate.cs
- Core/Net/Net.cs
- Core/Net/NetAsyncDownloader.cs
- Core/Net/NetAsyncModulesDownloader.cs
- Core/Types/CkanModule.cs
- Core/Types/License.cs
SpaceDock broke today, which is fun. VITAS reports that it looks like a denial of service attack.
The NetKAN bot has been uploading all permissively-licensed mods to https://archive.org/details/kspckanmods for quite a while now. Many or most of the SpaceDock downloads that are now failing, could in principle fall back to archive.org URLs. Such a feature could also help us deal with GitHub's download throttling or SpaceDock's certificate expirations.
Now if the primary download fails for a permissively licensed mod, we try to find it on archive.org as a fallback.
Internally this involves defining a `fallbackUrl` property in `DownloadTarget` and `NetAsyncDownloaderDownloadPart`, both populated from a new `CkanModule.InternetArchiveDownload` property, which itself checks a new …
> Fallback to archive.org URLs for failed downloads of FOSS packages

- Cmdline/Action/Available.cs
- Cmdline/Options.cs
Currently the `ckan available` command prints a module's identifier, latest compatible version, and full name:
```
$ ckan available | shuf -n 5
* CrewPortraits (1.3.1) - Crew Portraits
* SETI-CareerChallenge (1.3.0.0) - SETI-CareerChallenge
* JSIAdvancedTransparentPods (V0.1.15.0) - JSI Advanced Transparent Pods
* SigmaReplacements-Descriptions (D_v0.2.3) - Sigma Replacements: Descriptions
* NodeAlert (1.1.0) - NodeAlert
```
If you aren't already familiar with a given mod, this format isn't very helpful in deciding whether to install it. You would have to look up each individual mod to get more information.
Now a new `--detail` option is available to add the abstract (short description) to the end of each line:
```
$ ckan available --detail | shuf -n 5
* SearchAndRescue (1:11) - Search …
```
> Show abstracts in available command

- Core/Net/NetFileCache.cs
We continue to have occasional difficulties with ZIP file validation. #2285 highlights an issue of discrepant redundant data in the local file header versus the central directory.
These issues are difficult to diagnose. In 1.22.6, the exceptions look like:
```
CKAN.FileNotFoundKraken: Trying to install CivilianPopulation 2.0.12, but it's not downloaded or download is corrupted
```
And in HEAD, we have:
```
Unhandled Exception: CKAN.InvalidModuleFileKraken: C:\Users\User\AppData\Local\Temp\tmpF3A6.tmp is not a valid ZIP file: ZipFile.TestArchive(true) returned false
```
These are pretty generic errors, which don't tell us much other than _something_ is wrong with the ZIP. Lots of leg work is left to do to figure out what's wrong.
Now we capture more details from SharpZipLib, allowing us to …
> Capture error details from SharpZipLib for invalid ZIPs

- Netkan/Services/CachingHttpService.cs
CKAN performs several integrity checks on the ZIP files it downloads, and refuses to install or even cache files that are invalid by its standards, which are mainly the standards of `SharpZipLib.ZipFile.TestArchive`. See #2285 and #2287 for details.
However, currently netkan doesn't perform these checks. Whatever file is at the download URL, goes into the index. Netkan happily indexes files that CKAN will refuse to install.
We're caught by surprise when a ZIP has a weird problem, and users are stuck with a version they can see but not install. We won't even find out about it unless someone files an issue on GitHub.
Now netkan.exe calls the same ZIP validation check after it downloads a ZIP file that CKAN uses. If the file isn't valid, an exception is thrown:
```
$ netkan.exe …
```
> Check zip validity in netkan

- Core/Types/CkanModule.cs
#2284 added the ability to fall back to archive.org URLs, but it didn't account for the special handling of epoch formatted version numbers, which need to have colons replaced by hyphens before building the URL:
https://github.com/KSP-CKAN/NetKAN-bot/blob/81751def110ea7ecf137d2630f8e3635b35117a3/lib/App/KSP_CKAN/Metadata/Ckan.pm#L180-L185
Now this is fixed.
> Replace colons with hyphens in archive URLs

- Cmdline/Main.cs
- Netkan/Program.cs
- quotes.txt
- GitHub has sunsetted TLS 1/1.1 as of today. [They gave us one year's warning](https://githubengineering.com/crypto-deprecation-notice/), but apparently we missed it or didn't realize it applied to us (or assumed that .NET would handle it properly for us). This means the only way to access an HTTPS URL on GitHub is now via TLS 1.2.
- .NET 4.5 can support TLS 1.2, but it is not enabled by default. .NET 4.6 enables it by default.
- CKAN targets .NET 4.5. Even if you have a later version installed, the behavior of the .NET components will mimic .NET 4.5.
Released versions of CKAN can't access GitHub HTTPS URLs anymore. They cause TLS errors.
CKAN uses GitHub HTTPS URLs not just for mod downloads, but also for registry updates and application self-auto-updates. So you can't even refresh the …
> Force-allow TLS 1.2 on .NET 4.5

- Core/Win32Registry.cs
If you have never added any auth tokens (and therefore don't have the registry key `HKEY_CURRENT_USER\Software\CKAN\AuthTokens`), you may receive a null reference exception if you:
- Open the GUI settings window
- Edit the auth tokens in consoleui
- Run `ckan authtoken list`
This can be worked around by adding a fake auth token, which you may have to do from the command line with `ckan authtoken add host token`.
`Win32Registry.GetAuthTokenHosts()` returns null because `Microsoft.Win32.Registry.CurrentUser.OpenSubKey` returns null.
Now `Win32Registry.GetAuthTokenHosts()` returns a zero-element string array if `Microsoft.Win32.Registry.CurrentUser.OpenSubKey` returns null.
Fixes #2300.
> Fix crash when trying to view empty auth token list

- GUI/MainAllModVersions.cs
If your mod list is empty, it should auto refresh at launch as of #2241. However, instead an exception is thrown instead, with this stack trace:
```
CKAN.ModuleNotFoundKraken: Exception of type 'CKAN.ModuleNotFoundKraken' was thrown.
at CKAN.Registry.AllAvailable(String module)
at CKAN.MainAllModVersions.set_SelectedModule(GUIMod value)
at CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
```
You can click Continue and then Refresh to get past this, but it should be auto-refreshing instead.
`MainAllModVersions.SelectedModule` calls `Registry.AllAvailable` without handling `ModuleNotFoundKraken`.
Now we catch that exception, and the auto-refresh will work.
Fixes #2298.
> Handle mod not found in versions tab

- GUI/ChooseKSPInstance.Designer.cs
The minimum size is now:
And the checkbox is anchored to the lower left.
Fixes #2305.
> Better resizing for Select KSP Install window

- Core/Types/CkanModule.cs
If you try to install a mod that doesn't have a `download_hash` defined in its metadata, you might encounter this exception:
```
at CKAN.CkanModule.get_InternetArchiveDownload()
at CKAN.NetAsyncModulesDownloader.<>c.<DownloadModules>b__8_4(KeyValuePair`2 item)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at CKAN.NetAsyncModulesDownloader.DownloadModules(NetModuleCache cache, IEnumerable`1 modules)
at CKAN.ModuleInstaller.DownloadModules(IEnumerable`1 mods, IDownloader downloader)
at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, IDownloader …
```
> Don't crash if download_hash isn't set

- GUI/ChooseKSPInstance.cs
If you try to add a new game instance in GUI that has the same folder name as an existing instance, you get this exception:
This worked fine on previous versions.
In #2239, this function:
https://github.com/KSP-CKAN/CKAN/blob/2cc20b505476d7114a235a9313aaa67817406a00/GUI/ChooseKSPInstance.cs#L73-L80
was changed to pass the name of the instance to the constructor of `KSP` instead of `AddInstance`, because instances now know their own names. However, the `GetNextValidInstanceName` call ended up in the wrong place; it should be before we use the name, but it's after:
https://github.com/KSP-CKAN/CKAN/blob/c1d33f89758376005044426312a6b503071d44ab/GUI/ChooseKSPInstance.cs#L73-L80
Now `GetNextValidInstanceName` is called before the instance is created.
Fixes #2315.
> Fix GUI instance name checking

- bin/close-old-support-tickets.pl
There's a robot that crawls CKAN issues and closes idle support tickets. This is nice for keeping the issues list tidy.
However, users are just as likely to submit support tickets for NetKAN, and those just accumulate.
Also the definition of "idle support ticket" isn't quite fair to issue authors, since it goes purely by time elapsed since last activity, as long as there's at least one comment. Consider this sequence:
1. You submit an issue
2. We mark it as Support and say "What about workaround X?"
3. You say "No, that didn't work"
4. 7 days elapse
5. The bot closes the issue
In this case, the ball is in the dev team's court, and the user has been responsive and hasn't been helped. The ticket should remain open until the _issue author_ is idle for 7 days.
- Now the bot looks at the …
> Check NetKAN for support issues, don't close if last reply is by OP

- bin/close-old-support-tickets.pl
@techman83 , KSP-CKAN/Netkan#5172 shouldn't have been closed; I forgot to make it actually skip to the next issue when the last comment is by the OP. It prints the message _saying_ it's going to skip, but continues processing the same issue as before.
> Actually skip when last comment is by OP

- Core/KSPPathUtils.cs
If you install a module that has `"install_to": "GameRoot"`, you'll get an exception when you try to upgrade or remove it:
```
$ ckan remove KSPLogiRGB-battlemoose
About to remove:
* KSP Logitech RGB Control v1.0.3
Removing KSPLogiRGB-battlemoose...
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
at System.String.Remove (System.Int32 startIndex, System.Int32 count) [0x0004c] in <9689214c1e4645be91df75196bac3cbb>:0 
at CKAN.KSPPathUtils.ToRelative (System.String path, System.String root) [0x00064] in <cf1172f4644841da8b9b83c88c51f181>:0 
at CKAN.ModuleInstaller+<>c__DisplayClass34_0.<AddParentDirectories>b__1 (System.String dir) [0x0004f] in <cf1172f4644841da8b9b83c88c51f181>:0 
at …
```
> Fix ArgumentOutOfRangeException when removing files from game root

- Cmdline/Action/Upgrade.cs
- Core/Registry/Registry.cs
- Core/Relationships/SanityChecker.cs
- Core/Types/CkanModule.cs
- Core/Types/Kraken.cs
- Tests/Core/Relationships/SanityChecker.cs
Kopernicus has gotten into a habit of making frequent compatibility breaks with previous versions, with the expectation that planet pack makers will release updates to handle the new version. CKAN users would usually be burned by this, as we upgrade their Kopernicus before the planet packs are ready.
A conscientious planet pack maker may try to version-lock his mod to a specific version of Kopernicus to ensure that an upgrade does not take place until the dependent mod is ready for it.
If a mod depends on a specific version of another mod, such as this from @Sigma88's [StockalikeSolarSystem](https://github.com/KSP-CKAN/CKAN-meta/blob/master/StockalikeSolarSystem/StockalikeSolarSystem-v0.5.5.ckan#L14-L25):
```json
"depends": [
{
"name": "Kopernicus",
"version": "2:release-1.3.1-3"
},
{ …
```
> Obey version properties of conflicts and depends relationships in sanity checks

- macosx/CKAN
- macosx/Makefile
The currently released CKAN.app opens the wiki page about installing on Mac when it can't find Mono. Currently that is every time, even if Mono is installed.
Non-ObjC app bundles on MacOSX are not provided:
1. The proper system PATH variable for running other programs (even though there is a `/etc/paths.d/` architecture for configuring it)
2. The path to their own folder
We need both to run `mono ckan.exe`, so we have to write code to figure them out at run time.
The mono executable has lived in several different places on MacOSX, there's no way to just ask where it is, and our script previously only checked a path that was used in an older version of Mono.
The script's logic for finding its own folder was an overly complicated `awk` script that may or may not have worked.
Now we check …
> Improve CKAN.app launch script

- build
This PR tweaks the build script to make it easier to build on macOS.
`/usr/bin/sed` on macOS is a BSD sed, which was returning successfully with an empty string trying to parse the Cake version out of packages.config, thereby breaking the build. Rather than expect the user to install GNU sed, I've changed the expression to something that should work on both and (at least to me) reads more easily.
This branch now builds as-is for me on macOS. I've done minor testing that it's still OK with GNU sed on macOS and changing the build script to use `gsed`. I'm hoping CI will catch any other major problems. :)
> Fix building on macOS

- Core/Net/AutoUpdate.cs
- Tests/Core/Net/AutoUpdate.cs
We have three failing tests currently. (Travis skips them by excluding anything tagged with FlakyNetwork, which these are.)
```
1) Failed : Tests.Core.AutoUpdate.AutoUpdate.FetchCkanUrl
Expected: <CKAN.Kraken>
But was:  <System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
at System.Net.WebClient.DownloadString(Uri address)
at CKAN.AutoUpdate.MakeRequest(Uri url) in C:\Users\user\github\CKAN\Core\Net\AutoUpdate.cs:line 215
at Tests.Core.AutoUpdate.AutoUpdate.Fetch(Uri url, Int32 whichOne) in C:\Users\user\github\CKAN\Tests\Core\Net\AutoUpdate.cs:line 57
at Tests.Core.AutoUpdate.AutoUpdate.<FetchCkanUrl>b__1_0() in C:\Users\user\github\CKAN\Tests\Core\Net\AutoUpdate.cs:line …
```
> Fix autoupdater tests on TLS-fragile platforms

- Core/Net/NetFileCache.cs
- Netkan/Model/Metadata.cs
- Netkan/Services/CachingHttpService.cs
- Netkan/Services/IHttpService.cs
- Netkan/Sources/Github/GithubApi.cs
- Netkan/Sources/Github/GithubRelease.cs
- Netkan/Transformers/AvcTransformer.cs
- Netkan/Transformers/DownloadAttributeTransformer.cs
- Netkan/Transformers/GithubTransformer.cs
- Netkan/Transformers/InternalCkanTransformer.cs
- Netkan/Validators/InstallsFilesValidator.cs
- Tests/NetKAN/Transformers/DownloadAttributeTransformerTests.cs
- Tests/NetKAN/Transformers/GithubTransformerTests.cs
- Tests/NetKAN/Transformers/InternalCkanTransformerTests.cs
Both CKAN and Netkan cache module downloads to save network bandwidth and time. Downloaded files are placed in a cache folder with names like `A1B2C3D4-Modname-v1.0.zip`, with the first eight characters being the beginning of the download URL's SHA1 in hexadecimal.
In #2243, we added validation to make sure that invalid or corrupted files do not end up in the CKAN cache. This uses the `download_hash` property to check that the file we downloaded matches the file that Netkan indexed. Thanks to this change, `download_hash` properties must be correct and up to date for CKAN to work properly.
1. GPP released a new version
2. The netkan bot indexed it
3. GPP replaced the previous download in-place with an updated version (fix to the KSP-AVC file)
4. Users started getting mismatched hash errors …
> Invalidate stale cached files from GitHub in Netkan

- .travis.yml
- CHANGELOG.md
- macosx/Makefile
Implements the changes I suggested in #2355 for building the app bundle and disk image on macOS.
> Allow building CKAN.app on macOS

- GUI/Main.cs
- GUI/MainChangeset.cs
- GUI/MainInstall.cs
If you:
1. Already have some mods installed via CKAN
2. Launch the CKAN GUI
3. Right click an installed mod
4. Choose "Reinstall"
5. Click Yes
... then the progress tab does not display. Instead only the status bar reports progress. Additional odd behaviors and glitches may be observed after this as well.
If you install a mod normally first (before step 3), then it works as expected.
The sequence of calls needed to use the install flow correctly was:
https://github.com/KSP-CKAN/CKAN/blob/624839ffaa51de25c607531b23f9efb46d4ee612/GUI/Main.cs#L971-L977
Previously, the `ShowWaitDialog` call was missing from `reinstallToolStripMenuItem_Click`. This call creates or activates the progress tab, depending on whether it already exists, and also does some initialization of the progress bar.
Now the …
> Always switch to progress tab when starting a [re/un]install

- GUI/Main.cs
- GUI/MainAllModVersions.Designer.cs
- GUI/MainAllModVersions.cs
- GUI/MainInstall.cs
Currently GUI can only install the latest compatible version of a given mod. So while there may be versions 1.0, 1.1, 1.2, and 1.3 of a mod in the registry, you can only install 1.3.
It may be desirable to install older versions of a mod in some cases. For example, I need to do this to investigate a bug report involving upgrades; if I can only install the latest versions, then I would have to install a bunch of mods and then wait for one of them to upgrade, and repeating such a test would involve more waiting. (Yes, there's a way to do it in Cmdline, but it's nice to have in GUI as well.)
There's a Versions tab that lists all versions of the mod and indicates which are compatible with the current game version. It's not interactive at the moment.
Now if you double click one of the green …
> Install old versions of mods on double click from version list

- Core/Net/NetAsyncDownloader.cs
If you try to upgrade a mod and install another mod in one pass in GUI, you'll get errors about one of the downloads not having enough bytes:
```
CKAN.InvalidModuleFileKraken: C:\Users\Jasper\AppData\Local\Temp\tmpD329.tmp has length 0, should be 15924
bij CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
bij CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)
bij CKAN.NetAsyncModulesDownloader.<>c__DisplayClass8_0.<DownloadModules>b__3(Uri[] _uris, String[] paths, Exception[] errors)
bij CKAN.NetAsyncDownloader.triggerCompleted(Uri[] file_urls, String[] file_paths, Exception[] errors)
bij CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
bij …
```
> Allow downloader to be used multiple times

- Core/Net/NetAsyncModulesDownloader.cs
- Core/Net/NetModuleCache.cs
- GUI/MainWait.cs
As of #2351, I'm getting these errors when trying to install a mod on Windows:
```
System.ArgumentException: Controls created on one thread cannot be parented to a control on a different thread.
at System.Windows.Forms.Control.ControlCollection.Add(Control value)
at System.Windows.Forms.ToolStripControlHost.SyncControlParent()
at System.Windows.Forms.ToolStripControlHost.OnParentChanged(ToolStrip oldParent, ToolStrip newParent)
at System.Windows.Forms.ToolStripItem.set_ParentInternal(ToolStrip value)
at System.Windows.Forms.ToolStrip.SetDisplayedItems()
at System.Windows.Forms.StatusStrip.SetDisplayedItems()
at System.Windows.Forms.ToolStrip.OnLayout(LayoutEventArgs e)
at System.Windows.Forms.StatusStrip.OnLayout(LayoutEventArgs levent)
at …
```
> Deal with threading and download errors

- GUI/GUIMod.cs
- GUI/MainAllModVersions.Designer.cs
- GUI/MainAllModVersions.cs
- GUI/MainInstall.cs
GUI's "Max KSP Version" column isn't always accurate; it assumes that the module version that CKAN considers "latest" always has the max KSP version, which sometimes is not the case. This was originally fixed in #2131, but the fix was reverted in #2150 as part of the rollback of #1929, as reported in KSP-CKAN/NetKAN#6368.
The Versions tab only shows the highest compatible game version, even though it's very common for mods to be compatible with a range of many game versions.
The prompt to choose a mod to satisfy a virtual dependency ("provides"-based) doesn't show the download host or file size, even though other places do.
Now #2131's change is back.
Now the Versions tab will show the full range of each module version's game versions:
Now when you are prompted to select a mod to satisfy …
> More verbose and accurate version displays

- Core/Net/NetAsyncDownloader.cs
Currently in [the output for NetKAN pull request validation](https://ci.ksp-ckan.org/job/NetKAN/7091/console), the download URLs are printed with spaces unescaped:
This trips up the Jenkins site's attempt to make the URLs clickable, which could be handy if someone investigating an issue wants to inspect the downloaded files locally. Only the part leading up to the first space is detected, which isn't the full URL that's being downloaded.
Now we replace spaces in this output with `%20` as per standard URL encoding.
I looked into the proper functions for encoding URLs in C#, and none of them seemed appropriate for this. The problem is that `Uri.ToString()` outputs a _partially_ valid URL (correctly formatted but may contain spaces), which none of the various encoding functions expect. Some …
> Encode spaces in URL output

- Core/Net/Repo.cs
- Core/Platform.cs
- Core/Registry/RegistryManager.cs
- GUI/Main.cs
- GUI/MainModList.cs
- debian/control.in
The past few weeks have seen a steady trickle of obscure, difficult to investigate issues. This pull request attempts to extend CKAN's debugging capabilities in specific areas to make it possible to make progress on those issues. It also addresses a few very small or simple problems that came up.
A user reported in a random comment on unrelated issue #1817 that the .deb package should depend on the `webrequest` package. This is now added to `debian/control.in`.
`installFromckanToolStripMenuItem_Click` is marked as `async`, but it doesn't need to be, which causes a warning to be raised at compile time. This is now removed.
Fixes #2376.
#2391 contains multiple attestations that refreshing the registry sometimes fails, possibly related to how long CKAN has been running. A`WebException` is …
> Clean-up and debuggability

- Netkan/Transformers/GithubTransformer.cs
Netkan currently is double-encoding GitHub download URLs, which causes any URL that has an encoded character to fail. See #2401 for details.
The GitHub API returns the URL already encoded:
- https://api.github.com/repos/jrodrigv/DestructionEffects/releases
```json
"browser_download_url": "https://github.com/jrodrigv/DestructionEffects/releases/download/v1.8%2C0/DestructionEffects.1.8.0_0412018.zip"
```
We then encode it again, which changes any `%` characters to `%25`, which makes the URL fail with a 404 status:
https://github.com/KSP-CKAN/CKAN/blob/a495f435fff9a8e2c55ca5fdca0cb92d9a03c0e8/Netkan/Transformers/GithubTransformer.cs#L78
The `Uri.EscapeUriString` call is removed. The DestructionEffects netkan succeeds with this change.
Fixes #2401.
> Don't double encode GitHub download URLs

- Netkan/Transformers/AvcTransformer.cs
A mod that exists only as a bundled folder in another mod on SpaceDock can't have its own version number in CKAN; it must use the bundling mod's version (see #2405). This misrepresents to the user what's being installed, and makes for an awkward transition if we have to switch the source mod, often requiring an epoch bump.
A decision was made to never trust version files if we have another source of version info:
https://github.com/KSP-CKAN/CKAN/blob/a495f435fff9a8e2c55ca5fdca0cb92d9a03c0e8/Netkan/Transformers/AvcTransformer.cs#L154-L160
Now there is a way to override the above behavior. If `"x_netkan_trust_version_file"` is set to `true` in a given netkan file, then the `"version"` property will be sourced preferentially from the version file, if any.
Fixes #2405; my test version …
> Option to override SpaceDock version with AVC version

- GUI/SettingsDialog.Designer.cs
- GUI/SettingsDialog.cs
VisualStudio is very touchy to manual changes in the Designer, especially in `InitializeComponent()`.
At the moment, it throws an error every time you want to open the Design View of the Settings Form, because the `AutoUpdateGroupBox` and its members depend on `AutoUpdate.CanUpdate` via an if-statement, which checks if the exe is rewriteable.
Move the `AutoUpdate.CanUpdate`-check to `InstallUpdateButton_Click` instead of blocking some GUI labels and buttons. Throw an error (should it throw a kraken?), if it's false.
This would also make the SettingsWindow don't look as holey in this case.
> Move AutoUpdate.CanUpdate check to resolve VisualStudio Designer Error

- Tests/Core/KSPPathUtils.cs
- Tests/Core/ModuleInstallerDirTest.cs
- Tests/Core/Relationships/RelationshipResolver.cs
- Tests/Core/Relationships/SanityChecker.cs
- Tests/Core/Types/CkanModuleTests.cs
- Tests/Core/Types/GameComparator.cs
- Tests/Core/Versioning/KspVersionRangeTests.cs
- Tests/Data/TestData.cs
- Tests/GUI/GUIMod.cs
- Tests/NetKAN/Transformers/AvcTransformerTests.cs
- Tests/NetKAN/Transformers/GithubTransformerTests.cs
- Tests/NetKAN/Transformers/SpacedockTransformerTests.cs
- Tests/Tests.csproj
- Tests/packages.config
Tests are added (catching regressions unless otherwise noted):
- #2284 (archive.org URL formats)
- #2290
- #2313
- #2332
- #2339
- #2382 / #2131
- #2402
- #2406
- Game version range formats
The tests' names are of the form `MethodBeingTested_Scenario_DesiredOutcome`.
The code follows the Arrange / Act / Assert structure.
The tests for `CKAN.CkanModule` are moved from `Module` to `CkanModuleTests` so programmers familiar with `CkanModule` will have an easier time finding them.
Also courtesy of @DasSkelett (HebaruSan/CKAN#4), references are added to `Tests.csproj` to allow running the tests directly in Visual Studio.
> Add more tests

- GUI/Main.Designer.cs
- GUI/MainModInfo.Designer.cs
GUI has a vertical splitter between the mod list and the mod info pane and a horizontal splitter within one of the tabs of the mod info pane, but some users have found this to be non-obvious and ask whether information has been removed from the display (see #2412 and KSP-CKAN/NetKAN#6288).
The tab style chosen for the mod info pane is also a bit ugly and gray.
Now each pane of these splitters has a minimum size:
- The mod info pane always has enough width for all of its tabs
- The top part of the metadata tab always has enough height for both of its fields
- The bottom part of the metadata tab always has enough height for its fields
- The vertical splitter itself is widened slightly to try to make it more obvious
(I tried to enlarge the horizontal splitter as well, but setting the …
> Splitter and tabstrip visual improvements

- GUI/MainInstall.cs
If you choose multiple mods to install such that one of them recommends or suggests another mod being installed, an exception is thrown.
For example, (in KSP 1.2.2) B9AerospaceHX recommends KJR, and B9 suggests KJR. If you install both B9AerospaceHX and B9 together, then KJR is shown first as a recommendation, and if you accept the recommendation, an exception happens when the suggestions are being calculated.
To avoid showing optional dependencies multiple times, we're looping over the dictionary containing optional dependencies and modifying it here:
https://github.com/KSP-CKAN/CKAN/blob/9e71f867240d9143e53035881e59bb4fc7d34377/GUI/MainInstall.cs#L333-L339
C# doesn't like that. It considers it dangerous to continue looping over a collection that may have more or fewer elements than when …
> Fix "Collection was modified" exception for redundant optional dependencies

- Core/Registry/Registry.cs
- GUI/MainModInfo.cs
- Tests/Core/Registry/Registry.cs
Modules that depend on `MakingHistory-DLC` are treated as incompatible in mod listings, even if you have the DLC.
You are still able to _install_ such modules via CmdLine, even though they are displayed as incompatible.
Relatedly, the MakingHistory-DLC entry in the relationships tab always shows up as red and "(not indexed").
DLC checks were only added to functions that check whether an identifier is _installed_. To determine whether a module is _compatible_, we look up all of its dependencies via `LatestAvailableWithProvides` regardless of whether they're already installed, which returns a module, and there are no modules for Dlc objects, so this function doesn't find anything for `MakingHistory-DLC`.
The relationships tab in GUI also checks dependencies itself, and also wasn't updated. …
> Treat installed DLC as compatible dependency

- GUI/GUIMod.cs
- GUI/Main.cs
- GUI/MainModList.cs
It's possible for a mod with an incompatible dependency to be presented as compatible in GUI, as long as this dependency is more than one step away (i.e., a dependency of a dependency). For example, in KSP 1.4.2 currently, AJE Extended depends on AJE, which depends on FAR, which isn't compatible. So FAR and AJE are properly marked as incompatible, but AJE Extended is treated as compatible. This is covered by #2231 and not fixed here.
After you check such an incompatible checkbox, you'll get the error popup about it _every time_ you click any other checkbox, until you uncheck the incompatible one.
The only action we took in response to this condition was to raise an error message. This may partly be because we were catching `ModuleNotFoundKraken`, which doesn't indicate the depending …
> Uncheck checkbox after missing dependency error

- GUI/GUIMod.cs
If there's no max KSP version defined in a mod's metadata, CKAN GUI displays it as an empty string.
See ![maxV1](https://user-images.githubusercontent.com/28812678/39099958-28e14e26-4683-11e8-89fc-4d388e51f8fe.JPG)
It would be prettier and more informative if there is some text, so I changed the empty string to ~~"N/D"~~ "any".
This applies to the lower right metadata box and also the column in the modlist, as you can see here:
> Replace max KSP version empty string with "any" in GUI

- GUI/Main.cs
- GUI/MainModInfo.Designer.cs
- GUI/MainModInfo.cs
In #2413, I set the `Panel1MinSize` and `Panel2MinSize` properties on our splitters, because they look like a simple way to ensure that important content is visible. Of course with .NET, even something this simple has to be arduous:
This happens at start-up if our saved splitter size is no longer allowed in the current window size. You can get to such a state easily by resizing the window with no problems, but then if you close and restart this exception is thrown.
We may not be able to convince Microsoft how dumb it is to throw this exception, but now we do the next best thing and ignore it. The min sizes of the mod info pane are also reduced to about 75% of their previous values to allow them to fit a bit better into small windows.
> Ignore splitter exceptions

- Core/Relationships/SanityChecker.cs
- Tests/Core/Relationships/SanityChecker.cs
If a mod conflicts with itself, it can no longer be upgraded as of #2339; see #2428 for details of a specific example involving Scatterer.
When we upgrade, we ask the `SanityChecker` to look for missing dependencies and conflicts in a scenario in which the new versions are installed without removing the old versions. Since the old and new modules are both there, we check whether they conflict with one another, and a self-conflict is treated as a real conflict.
Prior to #2339, this was avoided by ignoring conflicts if the identifiers were the same, but when we made conflicts version-specific, we only ignored that conflict if the identifier _and version_ are the same.
Now `SanityChecker` will ignore any conflict between two mods with the same identifier, as it did historically. Other …
> Ignore conflicts between versions of same mod

- Tests/Core/Relationships/SanityChecker.cs
#2430 added a test of the sanity checker to make sure that multiple versions of a mod that conflicts with its own identifier don't conflict with one another. This is a requirement for the way upgrades work.
However, users also reported the same problem for a slightly different scenario. A mod can also self-conflict if it both `"provides"` an identifier and `"conflicts"` with that same identifier. `VesselMoverContinued` and `MechJeb2-RO` suffer from this variant of the problem (they provide and conflict with `VesselMover` and `MechJeb2`, respectively). The actual fix covers both scenarios, but the test only checks conflicts with the identifier, so it's not inconceivable that some future change might break them separately and not be caught.
This pull request adds a test to catch this case.
> Test upgrading mod with conflict on its own provides

- GUI/Main.cs
- GUI/MainModList.cs
Problem:
----------
#2428 showed, that `MarkAllUpdatesToolButton_Click()` always sets `ApplyToolButton.Enabled` to true, even without changeset. This is a very edge case of a bug which should get fixed soon (the changeset shouldn't be empty at all), but nevertheless, it would be better if the button doesn't get activated manually.
Solution:
---------
So I removed this `ApplyToolButton.Enabled` call, as it is unnecessary in addition, because `ApplyToolButton` gets always updated in `ChangeSetUpdated()` which again is called by `UpdateChangeSetAndConflicts()`, which then again is called by `ModList_CellValueChanged()`, in turn automatically called on any checkbox-changes...
_Ouf_
In short, `ApplyToolButton.Enabled` is called everywhere, anytime.
Furthermore I rearranged (and hopefully) …
> Don't Force Apply button active when no update selected

- Core/KSP.cs
- Tests/Core/KSP.cs
If you:
1. Have exactly one game instance
2. Set at least one additional compatible version in the compatible versions dialog
3. Remove `buildID.txt` and `readme.txt`, _without_ removing the KSP folder or the CKAN folder
4. Launch CKAN
... then on load, you get the compatible versions popup warning you about a version change (if in GUI), and clicking Save causes an exception:
```
************** Exception Text **************
at CKAN.KSP.SaveCompatibleVersions()
at CKAN.CompatibleKspVersionsDialog.SaveButton_Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) …
```
> Improve handling of missing game version

- Core/Registry/RegistryManager.cs
- Tests/Core/Registry/RegistryManager.cs
If your `registry.json` file is zero bytes long, CKAN crashes on load:
`RegistryManager` approaches registry creation by trying to load `registry.json` and then creating a new file if an exception is thrown during the load attempt. If the file contains a valid registry, it is simply loaded. If it doesn't exist, then a missing file exception is caught and the file is created.
If the file exists but is empty, then no exceptions are thrown, but the registry reference is set to null. Later, we attempt to use this reference, which causes an exception that isn't caught.
I was not able to figure out a way that a zero-byte file could be created. It might have something to do with the `ChinhDo.Transactions` library that CKAN uses for some filesystem access; I looked into this library at one point, …
> Handle zero byte registry.json file

- Cmdline/Main.cs
- Cmdline/Options.cs
- ConsoleUI/ConsoleCKAN.cs
- ConsoleUI/Program.cs
- ConsoleUI/SplashScreen.cs
- GUI/Main.cs
- GUI/Program.cs
If you have multiple game instances, you can choose between them with these command line options:
```
--ksp                   KSP install to use
--kspdir                KSP dir to use
```
However, these currently don't work for GUI or ConsoleUI. Instead, they will use the default instance if one is defined, or ask the user to choose an instance.
For GUI, these options are allowed and parsed (to the extent of raising an error if an invalid instance is specified), but not used to drive the UI.
For ConsoleUI, these options are not considered valid.
Now the `--ksp` and `--kspdir` flags work for both GUI and ConsoleUI.
The knowledge of which instance to use is stored into `CmdLine`'s  `KSPManager` object by `InstanceSpecificOptions.Handle`. To make GUI and ConsoleUI obey this, we pass this …
> Pass game instance from cmdline to GUI/ConsoleUI

- Core/Extensions/EnumerableExtensions.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Relationships/SanityChecker.cs
- Core/Types/CkanModule.cs
- Core/Types/Kraken.cs
- Core/Versioning/ModuleVersion.cs
- Core/Versioning/UnmanagedModuleVersion.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainDialogs.cs
- GUI/MainModList.cs
If you try to install two mods that conflict with one another, they'll be highlighted red, but there are no hints as to the cause if they're not on-screen.
If you manually install a mod, and then attempt to install or upgrade a mod in CKAN that conflicts with it, the mod is not highlighted red and there are no other clues as to what's going on, see KSP-CKAN/NetKAN#6533.
Some effort was made toward creating a popup for this in #2237, but it was not completed. Part of the challenge is that a popup can be disruptive and is not something we would want to happen every time the user clicks a checkbox.
Conflicts previously were used to mark rows red, abort the creation of a change set, and leave the Apply button disabled, but specific descriptive messages weren't shown.
The code that highlights …
> Show conflict messages in status bar

- Core/ModuleInstaller.cs
- GUI/Configuration.cs
- GUI/GUIMod.cs
- GUI/MainModList.cs
- GUI/SettingsDialog.Designer.cs
- GUI/SettingsDialog.cs
- Tests/Data/TestData.cs
```
v3.4.5-whatever → 3.4.5-whatever
V.3.4.5         → 3.4.5
Version_3.4.5   → 3.4.5
V21             → 21
vessel_5.1      → vessel_5.1
```
cons:	
```
V1deo → 1deo
```
Not sure what is `2` in `2:v3.4.5`, and why it in `LatestVersion` and not in the GUI column, I mean where `2:` is removed from `LatestVersion`, but `2:` is leaved there.
```
2:v3.4.5 → 2:3.4.5
```
> Remove "v" in "installed version" and "latest version" columns

- GUI/MainModInfo.Designer.cs
- GUI/MainModInfo.cs
Adds a Mod's "description" beneath the "abstract" in the top part of the ModInfoPanel
Closes #2458
> Add description to ModInfoTab

- Netkan/Sources/Curse/CurseApi.cs
- Netkan/Sources/Curse/ICurseApi.cs
- Netkan/Transformers/CurseTransformer.cs
- Tests/NetKAN/Sources/Curse/CurseApiTests.cs
- Tests/NetKAN/Transformers/CurseTransformerTests.cs
The format of Curse API URLs changed recently, but some old URLs are still supported; see the discussion in KSP-CKAN/NetKAN#6608 for details.
Old format:
- https://api.cfwidget.com/project/220602
New format:
- https://api.cfwidget.com/kerbal/ksp-mods/photonsail
Any old URL that had been accessed before March 2017 still works thanks to caching internal to the API, but any newly added mod must use the new format.
Netkan fails on mods added to curse after March 2017. See KSP-CKAN/NetKAN#6608 for an example; PhotonSailor can't be indexed without updating our Curse API logic.
(UPDATE: We switched that mod to SpaceDock instead, so the urgency is lower, but the problem would still affect future new mods hosted only on Curse.)
Now the `id` part of the `#/ckan/curse/id` kref string may contain …
> Support new Curse URLs with non-numeric IDs

- Core/Types/CkanModule.cs
- Netkan/Program.cs
KSP-CKAN/NetKAN#6654 got tripped up by this very confusing error message:
```
9493 [1] FATAL CKAN.NetKAN.Program (null) - Exception has been thrown by the target of an invocation.
```
The root cause was that the generated metadata had this:
```json
"ksp_version": "1.4.0",
"ksp_version_min": "1.4.0",
"ksp_version_max": "1.4.99",
```
These properties aren't supposed to be combined; either you have `ksp_version`, or you have `_min` and/or `_max`. We have a check for that with its own special exception here:
https://github.com/KSP-CKAN/CKAN/blob/4120e9b1cb60f0937a8c9fb71e6279a4d72012a2/Core/Types/CkanModule.cs#L444-L449
However, that info wasn't making it all the way to the output.
Netkan now uses `Exception.GetBaseException()` to strip away useless wrapper exceptions. …
> Fix Netkan error message when both ksp_version and ksp_version_min/_max are present

- Cmdline/Main.cs
- GUI/GUIUser.cs
- GUI/Main.cs
Starting in CKAN 1.25.2, If you run the GUI without arguments, and it needs to initialize your CKAN folder, you'll see this:
```
$ mono ckan.exe 
exception inside UnhandledException handler: Object reference not set to an instance of an object
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
at CKAN.GUIUser.DisplayMessage (System.String message, System.Object[] args) [0x00000] in <352d74f237564d2e9ff313cc9ac1989e>:0 
at CKAN.NullUser.RaiseMessage (System.String message, System.Object[] args) [0x00000] in <352d74f237564d2e9ff313cc9ac1989e>:0 
at CKAN.KSP.SetupCkanDirectories () [0x000dd] in <352d74f237564d2e9ff313cc9ac1989e>:0 
at CKAN.KSP..ctor (System.String gameDir, System.String name, CKAN.IUser user) [0x00038] in …
```
> Fix crash when initializing CKAN dirs at argumentless GUI startup

- CHANGELOG.md
- Core/Net/NetModuleCache.cs
Some old modules don't have `download_size` set:
https://github.com/KSP-CKAN/CKAN-meta/blob/master/Toolbar/Toolbar-1.7.9.ckan
But it's just a simple int, so that causes it to be set to 0:
https://github.com/KSP-CKAN/CKAN/blob/ab714c224b9b446ac4a6d9c9b209b73f14bfa752/Core/Types/CkanModule.cs#L256-L257
When that happens, we can't install the module because it thinks the size "should be 0":
https://github.com/KSP-CKAN/CKAN/blob/ab714c224b9b446ac4a6d9c9b209b73f14bfa752/Core/Net/NetModuleCache.cs#L117-L120
https://ci.ksp-ckan.org/job/CKAN-meta/939/console
```
CKAN.InvalidModuleFileKraken: Toolbar 1.7.9: /tmp/tmp44f9291a.tmp has length 63906, should be 0
at CKAN.NetModuleCache.Store (CKAN.CkanModule module, System.String path, System.String description, System.Boolean move) [0x00061] in …
```
> Allow installing modules without download_size

- Core/Versioning/KspVersion.cs
- GUI/GUIMod.cs
As of #2437, if you have an installed module that has since been completely de-indexed (e.g., MiniAVC: KSP-CKAN/CKAN-meta#561, https://github.com/KSP-CKAN/CKAN-meta/commit/6cd629492ab5c35e02137b93ecb20b9d8f3dcb1a), this exception happens at GUI startup:
```
System.NullReferenceException: Object reference not set to an instance of an object
at CKAN.GUIMod..ctor (CKAN.CkanModule mod, CKAN.IRegistryQuerier registry, CKAN.Versioning.KspVersionCriteria current_ksp_version, System.Boolean incompatible) [0x003d6] in <60e037f139274e47b1d6c0206eefe140>:0 
at CKAN.Main+<>c__DisplayClass229_0.<_UpdateModsList>b__2 (CKAN.InstalledModule m) [0x00006] in <60e037f139274e47b1d6c0206eefe140>:0 
at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00048] in …
```
> Fix GUIMod crash when module doesn't have a compatible game version

- Core/KSPManager.cs
A game folder needs a few things to be considered valid by CKAN:
- GameData folder
- Version info, from readme.txt, buildID64.txt, or buildid.txt
Without these, CKAN can't do its job, so it looks for other game folders or gives up and asks the user to specify one. (Or at least that's how it's supposed to work.)
If you have KSP installed in your Steam library, and you delete the readme.txt, buildID64.txt, and buildid.txt files, GUI should show the Select KSP Install window to let you specify a valid game folder, but instead it throws this exception:
```
CKAN.NotKSPDirKraken: Could not find KSP version in buildID.txt or readme.txt
at CKAN.KSP.CkanDir()
at CKAN.Main..ctor(String[] cmdlineArgs, KSPManager mgr, GUIUser user, Boolean showConsole)
at CKAN.GUI.Main_(String[] args, KSPManager …
```
> Fix crash on invalid portable or Steam folder

- GUI/TabController.cs
If you install a mod with recommendations, suggestions, or a `provides` dependency in GUI on Linux with a recent-ish version of Mono, you get a big red X when you accept the recommendations or `provides` selection prompt:
This was observed on Mono 5.14.0.177, but it works fine on Mono 5.10.1.20. Intermediate versions have not yet been tested.
As of some recent version of Mono, it's apparently no longer safe to hide the active tab of a `TabControl`. The control keeps the active tab index as it was, pointing to the removed tab, and then when the runtime attempts to draw the control, it tries to use that index to get the active tab, which doesn't work because it's gone:
```
System.ArgumentOutOfRangeException: ControlCollection does not have that many controls
Parameter name: index
Actual …
```
> Fix red X on HideTab

- GUI/Main.Designer.cs
- GUI/MainModList.cs
GUI's "New in repository" filter shows mods that had no versions at all in the index before the last refresh. It's pretty rare for a mod to be newly indexed, so the usefulness of this is limited. Users would prefer a filter that shows newly indexed mods plus previously-incompatible mods that just had a compatible version indexed.
"New in repository" is replaced with "Newly compatible". It now shows mods that were incompatible before the last refresh and compatible after. This is accomplished by limiting the old and new module lists that we compare to only those that are compatible.
| Compatible before? | Compatible after? | New? |
| --- | --- | --- |
| No | No | No |
| Yes | No | No |
| Yes | Yes | No |
| No | Yes | Yes |
Newly-indexed *incompatible* mods will also appear in this filter, …
> Replace New in repository filter with Newly compatible filter

- GUI/GUIMod.cs
- GUI/Main.Designer.cs
- GUI/MainModList.cs
CKAN tracks the date and time when a mod was installed, but this information is not shown in GUI. It could be useful to be able to sort installed mods so you can see the order in which they were installed.
Now a new sortable Install Date column shows when mods were installed:
To achieve this, you can now construct a `GUIMod` object from an `InstalledModule`, or a `CkanModule`, or a `string` identifier. The constructors are layered by `: this()` calls so the simplest initialization is done first, then supplemented by whatever additional info is at hand. The `InstalledModule`-based constructor populates a new `InstallDate` property.
`MainModList._UpdateModsList` is updated to generate `GUIMod` objects based on `InstalledModule` objects when they are available.
The logic for making one row …
> Add Install Date column to GUI mod list

- Netkan/Program.cs
- Netkan/Services/CachingHttpService.cs
- Netkan/Services/IHttpService.cs
CKAN and Netkan each have a download cache, which is a folder on disk containing files with names like this:
- `C43B5474-BasicDeltaV-3.0.zip`
- `A77B71AE-netkan-CraftManager.zip`
The 8 hexadecimal digits are a portion of the hash of the origin URL. When we attempt to access any URL, we first calculate that hash and look for a matching file in the cache, and if found, we use that file instead of downloading it again.
Currently the Netkan bot can get "stuck" if there is a problem with a download. As an example, this just happened with @linuxgurugamer's NIMBY mod; the 1.1.1.1 version of that mod contained one file called `NIMBY.version` and another called just `.version`, which caused this error in Netkan and prevented that release from being indexed:
```
Too many .version files located: …
```
> Purge downloads that failed to index from Netkan cache

- Core/Net/Repo.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- GUI/GUIMod.cs
- GUI/Main.Designer.cs
- GUI/MainModList.cs
KSP-CKAN/NetKAN-bot#67 created a script that updates a [download_counts.json file in CKAN-meta](https://github.com/KSP-CKAN/CKAN-meta/blob/master/download_counts.json) containing the download counts of mods. This data is available now (and already being downloaded whenever anyone clicks Refresh!), but it's not being used yet.
Now when you refresh the registry, we extract the `download_counts.json` file and parse it, then store the values it contains in a dictionary at `Registry.download_counts`.
A new Downloads column is added to GUI displaying this value for each mod. The user can sort this column to identify major mods that they haven't tried before.
~~Congrats to KIS for winning the popularity contest:~~
Correction: Congrats to EVE for winning the popularity contest (now that …
> Add download count column to GUI

- Core/Types/Kraken.cs
#2527 shows a bunch of errors along these lines:
```
Error downloading KerbalEngineerRedux 1.1.5.3: An exception occurred during a WebClient request.
```
This says "An exception" instead of specifying what the problem is because it's one of .NET's annoying wrapper exceptions. The useful info is hidden in `exception.InnerException`, or `exception.InnerException.InnerException`, or even `exception.InnerException.InnerException.InnerException`.
Now we use `GetBaseException` as we did #2480 to strip off all the wrapper exceptions and display the actual problem. This is not a fix for #2527, but it makes such problems more debuggable. We can share a test build with that issue's author if the issue happens consistently for them.
> Show innermost download exceptions

- GUI/Main.Designer.cs
Windows (and by extension .NET, and by further extension Mono) has a color theming system with two main pairs of foreground/background colors:
| Background | Foreground | Description |
| --- | --- | --- |
| `SystemColors.Control` | `SystemColors.ControlText` | For "3D" controls like buttons or tabstrips |
| `SystemColors.Window` | `SystemColors.WindowText` | For editable controls like text boxes or grids |
The mod list looks bad in Linux with a dark theme:
- The grid header has black text on a dark gray background
- The mod rows have light gray text on a white background
Mono's `DataGridView` has some bad defaults for its colors; the `WindowText` and `ControlText` colors are switched:
| Cell | Background | Foreground |
| --- | --- | --- |
| Header | `SystemColors.Control` | …
> Fix grid colors for dark themes

- GUI/AskUserForAutoUpdatesDialog.Designer.cs
- GUI/YesNoDialog.Designer.cs
- GUI/YesNoDialog.cs
When you launch CKAN for the very first time (or after clearing the relevant settings from CKAN/GUIConfig.xml), two popups appear to "nag" the user about making certain decisions:
As shown above, the second popup's buttons are cut off and unreadable if you have this setting turned on in Windows:
Since AskUserForAutoUpdatesDialog works fine regardless of the above setting, I focused on what was different between the two. There are several differences that seem to affect whether the layout is shown correctly (see next section).
Now YesNoDialog works more like AskUserForAutoUpdatesDialog:
- It's a FixedToolWindow instead of a FixedDialog
- It has a close X button
- Its StartPosition is set in its .Designer.cs file instead of the ... other? file (whatever it's called in C#)
- It calls …
> Fix YesNoDialog layout

- GUI/MainInstall.cs
If CKAN tries to use `libcurl` and doesn't find it, we get an uncaught `DllNotFoundException`:
```
System.DllNotFoundException: libcurl
at (wrapper managed-to-native) CurlSharp.NativeMethods:curl_global_init (int)
at CurlSharp.Curl.GlobalInit (CurlInitFlag flags) [0x00000] in <filename unknown>:0 
at CKAN.Curl.Init () [0x00000] in <filename unknown>:0 
at CKAN.NetAsyncDownloader.DownloadCurl () [0x00000] in <filename unknown>:0 
at CKAN.NetAsyncDownloader.Download (ICollection`1 urls) [0x00000] in <filename unknown>:0 
at CKAN.NetAsyncDownloader.DownloadModules (CKAN.NetFileCache cache, IEnumerable`1 modules) [0x00000] in <filename unknown>:0 
at CKAN.ModuleInstaller.InstallList (ICollection`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) …
```
> Handle exception for missing libcurl

- Core/Net/NetFileCache.cs
If you try to install a ZIP file that contains files with names that are illegal on your OS, an exception is thrown to the unhandled exception handler:
```
System.ArgumentException: Illegal characters in path.
at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
at System.IO.Path.IsPathRooted(String path)
at ICSharpCode.SharpZipLib.Zip.ZipEntry.CleanName(String name)
at ICSharpCode.SharpZipLib.Zip.ZipEntry..ctor(String name, Int32 versionRequiredToExtract, Int32 madeByInfo, CompressionMethod method)
at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
at CKAN.NetFileCache.ZipValid(String filename, String& invalidReason)
at CKAN.NetModuleCache.Store(CkanModule module, String path, String …
```
> Catch illegal characters in ZIP exceptions

- Netkan/Sources/Avc/JsonAvcToKspVersion.cs
CKAN has pretty excellent handling for two-part game versions (e.g., "1.3" or "1.4") thanks to #1645, but to use it with a .version file you need to use a "-1" wildcard, as in:
```json
"KSP_VERSION_MIN": {
"MAJOR": 1,
"MINOR": 3,
"PATCH": -1
},
```
Which is kind of awkward and not terribly well known. Simply leaving out PATCH will raise an error:
```
1382 [1] FATAL CKAN.NetKAN.Program (null) - One of the identified items was in an invalid format.
```
I tested that format with KSP-AVC itself, and it worked fine, so Netkan should handle it as well.
Now you can leave out PATCH, MINOR, or even MAJOR, and the wildcard will be assumed.
Fixes #1687.
> Handle two-part KSP-AVC versions

- Netkan/CKAN-netkan.csproj
- Netkan/Sources/Avc/AvcVersion.cs
- Netkan/Transformers/AvcKrefTransformer.cs
- Netkan/Transformers/AvcTransformer.cs
- Netkan/Transformers/NetkanTransformer.cs
- Netkan/Validators/KrefValidator.cs
- Spec.md
[ExtraPlanetaryLaunchpads's netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ExtraPlanetaryLaunchpads.netkan) currently uses a `$kref` property with a hard coded URL. This means that we have to update the netkan manually every time there's a new release.
This mod has a publicly hosted remote .version file at http://taniwha.org/~bill/EL.version
The [KSP-AVC spec](http://ksp.cybutek.net/kspavc/Documents/README.htm) says:
> * DOWNLOAD - Optional
> Web address where the latest version can be downloaded.
> This is only used from the remote version file.
In principle this should let us pick up new versions automatically, but currently that functionality doesn't exist.
Now Netkan will support this format:
```json
"$kref": "#/ckan/ksp-avc/http://taniwha.org/~bill/EL.version",
```
The …
> Handle KSP-AVC krefs

- Core/KSPManager.cs
- Core/Net/NetFileCache.cs
#2535 created a setting to allow the user to choose a folder to use as a download cache. For convenience, it also attempted to copy cached files from the old folder to the new when the setting changed.
This just wasn't safe. First @politas had a mishap where it tried to copy the same folder to the same folder and deleted all the cached files. Then I partly scrambled my home directory just by holding backspace to clear the field in GUI. If the two developers working on some code aren't able to use it correctly, it's too error-prone and needs to be fixed.
`MoveFrom` now will only delete a duplicate file if the creation timestamps are different. If the same timestamp is found, then we conclude that the parent folder is the same as the destination folder, and stop copying the folder …
> Stop auto-moving cached files

- GUI/Main.Designer.cs
- GUI/MainModInfo.Designer.cs
In a dark theme, the status log and parts of the mod info pane feature dark text on a dark background:
Looks fine in a normal theme:
1. A text box in .NET defaults to `WindowText` (black) on `Window` (white), but if you set its `ReadOnly=true`, as we do in this case, the background is changed to `Control` (dark gray) without changing the foreground, to give it a disabled appearance
2. We set the `ForeColor` of the mod info pane labels to `ControlDarkDark`; the meaning of this value is:
[Gets a Color structure that is the dark shadow color of a 3-D element.](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.systemcolors)
This color is not meant to be used for text foreground colors, and using it assumes a light background color.
Now these places look better.
1. The log text box's …
> Fix text colors for dark themes

- GUI/CKAN-GUI.csproj
- GUI/FlatToolStripRenderer.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
CKAN's toolbars are hideous with a dark theme:
See mono/mono#11287; Mono is trying to use `SystemColors.ButtonFace` for the left edge of a toolstrip, fading to a hard coded light color with a linear gradient. But Mono doesn't load `ButtonFace` from the system settings, instead leaving it with a compile time default.
mono/mono#11287 is trying to fix this in Mono by switching from `ButtonFace` to `SystemColors.Control`, which is set by Mono's theme loader. However, there are some downsides:
- Even with the fix, the default toolstrip renderer still uses an ugly gradient to a hard coded light color at the right edge
- That fix won't reach users until Mono puts out a new release and users upgrade to it (assuming it gets merged)
Luckily this part of Mono is 90% customization / overrides / …
> Fix toolbar background colors for dark themes

- Cmdline/Action/Cache.cs
- Core/ModuleInstaller.cs
- Core/Net/NetFileCache.cs
- Core/Net/NetModuleCache.cs
- Core/Registry/Registry.cs
- Core/Versioning/KspVersionCriteria.cs
- Core/Win32Registry.cs
- GUI/CKAN-GUI.csproj
- GUI/DropdownMenuButton.cs
- GUI/SettingsDialog.Designer.cs
- GUI/SettingsDialog.cs
- Tests/Core/FakeWin32Registry.cs
CKAN's download cache currently grows without limit. We write to it, but we don't remove files unless the user runs `ckan clean` or clicks the Clear button in the cache section of the GUI settings. This means that in order to avoid filling up a disk, the user might have to manually monitor the cache size and clear it periodically, or delete individual files. It would be nice to have something more automated.
This pull request builds upon #2535 to create a configurable cache size limit. The default is to allow unlimited cache size, as it is today. (This pull request has been rebased to show only its own changes, where formerly #2535's commit was included.)
`Win32Registry.CacheSizeLimit` now stores the maximum number of bytes allowed in the cache, or `null` if unlimited.
`ModuleInstaller` …
> Configurable cache size limit

- GUI/MainModList.cs
If you focus the mod list and press space in GUI, some surprising behaviors can occur depending on exactly where you click:
- If you click the Install checkbox, then the checkbox will toggle when you press space and then again when you let go
- If you click the Upgrade checkbox, then pressing space can toggle both checkboxes
CKAN has some special code to toggle checkboxes when you press space.
- The grid itself handles checkbox toggling in `KeyDown`, but we were doing it in `KeyPress`, which happens later
- Our code fired regardless of which cell was focused, and if that cell had a checkbox, then multiple toggles would happen at different times
- Our code only ever toggled the Install checkbox, so if you click an upgradable row and press space, it would try to remove the mod rather than …
> Clean up mod list spacebar handling in GUI

- Core/Net/NetAsyncDownloader.cs
Sometimes when downloading mods, CKAN indicates negative bytes remaining and greater than 100% progress towards completion. This problem has been reported on both CmdLine and GUI, and presumably ConsoleUI would be affected as well:
When the primary download URL for a redistributable mod fails, we fall back to its `archive.org` URL as of #2284. This is done by calling `agent.DownloadFileAsync` in the `agent.DownloadFileCompleted` event handler when it indicates failure. Notably this re-uses the same `WebClient` object.
Since the negative bytes remaining and greater than 100% progress numbers come directly from values provided by `WebClient`, I think the `WebClient` object is getting corrupted by this sequence of events. It may not be prepared for us to initiate a new download while the …
> Use fresh WebClient for fallback URLs

- GUI/ChooseKSPInstance.Designer.cs
- GUI/ChooseKSPInstance.cs
- GUI/CompatibleKspVersionsDialog.Designer.cs
- GUI/CompatibleKspVersionsDialog.cs
- GUI/Main.cs
- GUI/SettingsDialog.Designer.cs
- GUI/SettingsDialog.cs
If a KSP update happens, CKAN will alert you at launch:
This window can also be accessed via the menus, Settings &rArr; Compatible KSP Versions.
- If it auto-opens at launch, this window will be positioned at the upper left corner of your leftmost monitor, which makes it difficult to notice
- A Save button normally saves something without closing, but this one closes the window
- Capitalization of "Ksp" in the title is wrong because it's an acronym standing for Kerbal Space Program
- If the user opens this window manually and then cancels out, the mod list is regenerated needlessly
- The window will be centered on the screen at startup
- The window will be centered on its parent if the user opens it manually
- The Save button now says Accept instead, to make it clearer that it closes the …
> Clean up popup positioning in GUI

- Core/Win32Registry.cs
In the settings, if you click the Reset in the cache section twice, an exception occurs:
```
************** Tekst van uitzondering **************
System.ArgumentException: Er bestaat geen waarde met deze naam.
bij System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
bij Microsoft.Win32.RegistryKey.DeleteValue(String name)
bij CKAN.Win32Registry.DeleteRegistryValue(String name)
bij CKAN.Win32Registry.set_DownloadCacheDir(String value)
bij CKAN.KSPManager.TrySetupCache(String path, String& failureReason)
bij CKAN.SettingsDialog.UpdateCacheInfo(String newPath)
bij CKAN.SettingsDialog.ResetCacheButton_Click(Object sender, EventArgs e)
bij System.Windows.Forms.Control.OnClick(EventArgs e)
bij System.Windows.Forms.Button.OnClick(EventArgs e)
bij …
```
> Don't throw exceptions when resetting cache dir

- Spec.md
This value hasn't been updated, though the following updates are shown elsewhere in the file:
24 - include_only, include_only_regexp
25 - install_to / missions
> Bump spec version

- Core/Versioning/KspVersion.cs
[The spec](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md) allows `ksp_version` to be `"any"`:
> ksp_version
> The version of KSP this mod is targeting. This may be the string "any", a number (eg: 0.23.5) or may only contain the first two parts of the version string (eg: 0.25). In the latter case, any release starting with the ksp_version is considered acceptable.
> 
> If no KSP target version is included, a default of "any" is assumed.
58 mods currently use a value of '"any"` for this field.
KSP-CKAN/NetKAN#6791 is trying to join them, but it also features a `$vref` property. This causes an exception:
```
7796 [1] FATAL CKAN.NetKAN.Program (null) - One of the identified items was in an invalid format.
7797 [1] FATAL CKAN.NetKAN.Program (null) -   at CKAN.Versioning.KspVersion.Parse …
```
> Allow game version of "any" with a vref

- GUI/SettingsDialog.Designer.cs
If you run the master HEAD version in Windows, you get this exception at startup:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentNullException: Value cannot be null.
Parameter name: container
at System.Windows.Forms.ContextMenuStrip..ctor(IContainer container)
at CKAN.SettingsDialog.InitializeComponent()
at CKAN.SettingsDialog..ctor()
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at …
```
> Fix crash at startup on Windows

- Core/Net/Repo.cs
If you refresh the registry and the remote repo contains an empty .ckan file, you may see exceptions with stack traces like these:
```
bei CKAN.Repo.ProcessRegistryMetadataFromJSON(String metadata, Registry registry, String filename) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Net\Repo.cs:Zeile 69.
bei CKAN.Repo.UpdateRegistryFromZip(String path, Registry registry) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Net\Repo.cs:Zeile 383.
bei CKAN.Repo.UpdateRegistry(Uri repo, Registry registry, KSP ksp, IUser user, Boolean clear) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Net\Repo.cs:Zeile 161.
bei CKAN.Repo.UpdateAllRepositories(RegistryManager registry_manager, KSP ksp, IUser user) in C:\Users\Martin\Documents\Visual Studio …
```
> Fix null ref exception when repo has empty ckan file

- Core/Versioning/KspVersion.cs
- Netkan/Transformers/AvcTransformer.cs
#2553 tried to fix a problem with setting `"ksp_version": "any"` in a netkan that also has a `$vref`. The change worked insofar as netkan was able to generate a .ckan file instead of erroring out, but the script that checks the .ckan file against the schema found a problem: `ksp_version` was null, and that's not allowed.
```
"ksp_version": null,
```
```
Validating built/CommunityTerrainTexturePack-1-1.0.4.ckan.. Failed! See below for error description.
None is not of type u'string'
Failed validating u'type' in schema[u'properties'][u'ksp_version']:
{u'description': u'A version of KSP',
u'pattern': u'^(any|[0-9]+\\.[0-9]+(\\.[0-9]+)?)$',
u'type': u'string'}
On instance[u'ksp_version']:
None
```
This is blocking KSP-CKAN/NetKAN#6791.
`KspVersion.Any.ToString()` returns null because of this: …
> Avoid null ksp_version in Netkan

- GUI/GUIMod.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
After you click Refresh in GUI, the latest updates are downloaded from the repo, but only certain changes are reflected in the mod list:
- Newly added mods
- New versions
- Installation status
But if other things change, this isn't shown in the mod list until you restart CKAN:
- Game version compatibility
- Display name or abstract
- Author
- Download size or count
- Etc.
`ConstructModList` goes out of its way to cause this problem in order to avoid losing user changes. A `refreshAll` parameter is passed based on whether we're doing a repo update, in which case the previous `GUIMod` objects are mostly kept. This is kind of odd because a repo update is the only way that most of those properties can be changed.
https://github.com/KSP-CKAN/CKAN/blob/b9a91fa2a3b8780a4f8310127f13cfc6400a816c/GU …
> Show latest updates after refresh

- GUI/MainInstall.cs
If you choose to install a mod that has recommendations or suggestions, the status-bar progress bar will appear while the recommendation and suggestion lists are visible.
If you then cancel out of these screens, that progress bar will remain visible on the main mod list, effectively stuck there until you start and complete another installation.
This progress bar is shown and hidden in the `ShowWaitDialog` and `HideWaitDialog` functions that initialize and reset the log tab and its progress bar, respectively.
`ShowWaitDialog` is called too early in the install process, before recommendations and suggestions are handled. We don't need it yet at that point, so the tab sits uselessly in the background while the user deals with recommendations and suggestions, and the status bar shows a …
> Don't show status progress bar till actually installing

- Core/Registry/RegistryManager.cs
- Core/Types/CkanModule.cs
- Core/Types/ModuleInstallDescriptor.cs
The `registry.json` file nowadays is about 20 MB, 10% of which is repetitions of the following lines:
| Line | Occurrences |
| --- | ---:|
| `"ksp_version_strict": false,` | 14817 |
| `"download_content_type": "application/zip",` | 14764 |
| `"find_matches_files": false,` | 13504 |
| `"install_to": "GameData"` (without a comma) | 8378 |
| `"install_to": "GameData",` (with a comma) | 1725 |
A further 3.5 MB is tab characters indenting the JSON. While it can be useful to inspect this file from time to time, its primary function is to be read by code, so this formatting is not necessary.
This takes up disk space and increases the time to save and load the registry.
Now the above values of the above properties are treated as the default; when the property has that value, it will be left out …
> Purge more bloat from `registry.json`

- Core/ModuleInstaller.cs
- Core/Relationships/RelationshipResolver.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- Tests/Core/Relationships/RelationshipResolver.cs
If you manually install a mod that conflicts with a CKAN-managed mod that you've installed, you won't be able to remove the CKAN-managed mod:
You ought to be able to, though, because the conflict won't be present after the mod is removed.
`RelationshipResolver` is in charge of detecting conflicts in a change set. It has a `RemoveModsFromInstalledList` function to handle removal, but this is inconsistently used at the moment. In the above scenario, it's not used at all, so `RelationshipResolver` thinks you will still have the conflicting mod installed after you remove it.
At a deeper level, `RelationshipResolver`'s public interface is awkward and confusing for typical tasks. There's a constructor that accepts no modules, and there's one that accepts modules to install but not modules to …
> Allow uninstallation of conflicting mods

- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainAllModVersions.Designer.cs
- GUI/MainChangeset.cs
- GUI/MainModInfo.Designer.cs
- GUI/MainModList.cs
- GUI/MainTabControl.cs
GUI has several places where mods are listed but all the user can access is their name and abstract.
- Change set
- Recommendations / suggestions
- Providing modules
If you want to see the long description, license, home page, relationships, etc., you have to cancel whatever you're doing and then look up the mods separately on the main mod list.
Now the mod info pane is available in these lists if you click a row. This allows the user to get complete info about any mod about which they're being asked to make decisions. The mod info pane will disappear if you clear the list's selection.
Main mod list:
Provides:
Change set:
Recommendations:
To accomplish this, the structure of the main form is rearranged so the vertical splitter now contains the main tab control and the mod info:
Pre:
- …
> Show mod info for change set, recs/sugs, and providers

- Core/Net/NetFileCache.cs
In a comment in #2562, @7ranceaddic7 noted a significant performance degradation with the current master HEAD version compared to 1.25.3. I audited the changes since then and identified 3 possible causes. This is the first.
`NetFileCache` maintains a `cachedFiles` string array of files currently in the cache. This list is searched to find files matching a given module's download property.
When we consolidated the instance-specific caches in #2535, existing instance-specific cache folders were treated as a fallback if a file was not found in the main cache dir. However, the files in those fallback folders were not added to `cachedFiles` because I wasn't sure how best to do that or if it was necessary. Instead, those files were enumerated from the directories on the fly every time.
On …
> Cache listings of legacy cache dirs

- CKAN.schema
As of #2371, `"Missions"` is allowed in the `install_to` property:
https://github.com/KSP-CKAN/CKAN/blob/f641e203ade6c789881522ad0e95a9dc326c505f/Core/ModuleInstaller.cs#L493-L496
The schema requires `"Missions/"` with a slash at the end, so `"Missions"` without the slash will be flagged as invalid:
https://github.com/KSP-CKAN/CKAN/blob/f641e203ade6c789881522ad0e95a9dc326c505f/CKAN.schema#L359-L363
This is blocking KSP-CKAN/NetKAN#6827.
Now the schema is fixed to allow `"Missions"` as per the code.
**QUESTION**: Do we need to bump the spec version for this? Effectively it's a bug in the schema itself, and this syntax hasn't been used yet. The code already supports the version without the slash.
> Fix schema install_to Missions syntax

- GUI/MainModList.cs
As of #2561, if you try to remove a module that other installed modules depend on, you can't; the Apply button stays disabled and the status bar reports missing dependencies:
Before that pull request, this was allowed and would allow you to remove the module and mods depending on it. This isn't something we should break.
`MainModList.ComputeChangeSetFromModList` creates multiple `RelationshipResolver`s for different purposes. First it creates one or more in a loop to resolve all `provides` relationships (even if there are no `provides` relationships involved):
https://github.com/KSP-CKAN/CKAN/blob/8b791df8109b245f22e3fa819c003bbdf0d4dc85/GUI/MainModList.cs#L604-L616
After that it find mods with unsatisfied dependencies and queues them up to be removed: …
> Restore uninstallation of dependencies

- Netkan/CmdLineOptions.cs
- Netkan/Program.cs
- Netkan/Services/CachingHttpService.cs
If a mod author uploads a release to SpaceDock, then deletes it and re-uploads the same version with a changed file (usually because the first version had an error), the original version will remain in the Netkan bot's cache, and the metadata for that release will have an incorrect file size and hashes. Resolving this situation requires having @techman83 manually purge the files from the bot's cache.
BoyVoyage and Mk3Expansion have this problem right now, according to the latest posts on the forum; these files need to go:
- `C121BF1D-netkan-BonVoyage.zip`
- `61E04792-netkan-Mk3Expansion.zip`
- `BBB54E05-netkan-StockalikeMiningExtension.zip`
Now Netkan has a new `--overwrite-cache` command line flag. When this is present, Netkan will delete the cached file for a URL the first time that URL …
> Add Netkan option to overwrite cached files

- GUI/CKAN-GUI.csproj
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainDialogs.cs
- GUI/MainInstall.cs
- GUI/MainRecommendations.cs
When installing a mod, CKAN shows the user other mods that are recommended or suggested by that mod, and the user can choose whether to install them as well.
If the user chooses not to install these mods, but then later has second thoughts, there's no easy way to try again. They would have to remember what the mods were and choose to install them, check the Relationships tab in mod info, or uninstall and re-install the dependent mods.
Now there's a new File &rArr; Audit recommendations menu option:
If you click this and none of your installed mods have recommendations or suggestions, it'll tell you that:
Otherwise, it takes you to the Choose recommended mods tab, listing the mods that are recommended by currently installed mods.
Clicking Continue jumps to Choose suggested mods:
If you …
> Show recommendations of installed modules in GUI

- Cmdline/Action/Install.cs
- Core/ModuleInstaller.cs
I may be the only person bothered by this, but if you install mods in GUI, at the end the label above the progress bar says "(Done!" without a close parenthesis:
(I think you may even be able to see some of the rest of the message wrapped onto the next line in Mono.)
There's a `"\r\n"` in the `RaiseProgress` message at the end of the install flow:
https://github.com/KSP-CKAN/CKAN/blob/e5fc437da1a3814ee248b4c26bce671881830b3d/Core/ModuleInstaller.cs#L235
GUI inserts this string into the middle of a larger formatted string, which is then split in half at that point:
https://github.com/KSP-CKAN/CKAN/blob/e5fc437da1a3814ee248b4c26bce671881830b3d/GUI/GUIUser.cs#L40
https://github.com/KSP-CKAN/CKAN/blob/e5fc437da1a3814ee248b4c26bce671881830b3d/GUI/MainWait.cs#L99-L102
The newline was probably …
> Remove newline from Done progress message

- GUI/CKAN-GUI.csproj
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainTrayIcon.cs
#2565 added a tray icon with a context menu. On Linux, it has light text on a white background and it can be displayed mostly off-screen:
(The icon is invisible as well. I don't know why that is, so this pull request doesn't attempt to fix it.)
Mono?
Now the background matches other menus, and the position is always on screen:
In addition, the tray icon related code is moved from `Main.cs` to `MainTrayIcon.cs`.
> Fix tray icon menu position and color on Linux (Gnome)

- GUI/CKAN-GUI.csproj
- GUI/Main.cs
- GUI/X11.cs
Currently a typical Linux desktop environment doesn't know CKAN's name; here is GNOME Shell labeling it as "Unknown" in the top bar and the dash:
X11 windows have properties, including name and class, which define the identity of a window. Mono doesn't set them.
Now if we're running on Linux, we set the X11 window properties for name and class to "CKAN", which will allow desktop environments to identify it properly:
Fixes #2567.
> Set window properties on X11

- GUI/GUIMod.cs
If you:
1. Launch GUI
2. Search/filter for a mod that has a virtual dependency, for example Realistic Progression Zero
3. Check the box to install it
4. Receive the prompt to select a mod to provide a dependency
5. Select a mod that's not visible in the main mod list due to filtering
... then you'll get a crash:
```
at CKAN.GUIMod.SetInstallChecked(DataGridViewRow row, Nullable`1 set_value_to)
at CKAN.Main._MarkModForInstall(String identifier, Boolean uninstall)
at CKAN.Main.<>c__DisplayClass264_0.<MarkModForInstall>b__0()
at CKAN.Util.Invoke[T](T obj, Action action)
at CKAN.Main.MarkModForInstall(String identifier, Boolean uncheck)
at CKAN.Main.<TooManyModsProvide>d__237.MoveNext()
--- End of stack trace …
```
> Fix crash on selecting filtered-out provider module

- bin/close-old-support-tickets.pl
Our lovely netkan-bot has been doomed to spell "automatically" without a second t for longer than 3 and a half years (god bless git blame)! Time to relieve him of this disgrace!
> Fix spelling error of netkan-bot in close-old-support-tickets.pl

- Core/Platform.cs
- GUI/Main.cs
- GUI/X11.cs
Mac clients are failing currently:
```
System.DllNotFoundException: libX11.dylib
at (wrapper managed-to-native) CKAN.X11.XSetClassHint(intptr,intptr,intptr)
at CKAN.X11.SetWMClass (System.String name, System.String wmClass, System.IntPtr handle) [0x0004c] in <2c2371fb3f2949b2a6dfae930758e6ee>:0 
at CKAN.Main.<.ctor>b__37_5 (System.Object sender, System.EventArgs e) [0x00010] in <2c2371fb3f2949b2a6dfae930758e6ee>:0 
at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
at System.Windows.Forms.Control.OnHandleCreated (System.EventArgs e) [0x00019] in <7cb6368c5ba549ff8a02965fd9de701e>:0 
at System.Windows.Forms.Form.OnHandleCreated (System.EventArgs e) [0x00016] in <7cb6368c5ba549ff8a02965fd9de701e>:0 
at System.Windows.Forms.Control.WmCreate …
```
> Fix platform checks and crash on Mac OS X

- GUI/Main.Designer.cs
There's supposed to be a separator line between Audit recommendations and Exit, but it doesn't appear:
Wanting to be frugal, I re-used `toolStripSeparator3` rather than creating a new separator, since the actual separator object stores essentially no data.
That apparently doesn't work.
Now we use a new `toolStripSeparator7` object instead. This makes the separator show up:
> Fix file menu separator

- GUI/MainModInfo.Designer.cs
Someone mentioned recently that it can be inconvenient to read the relationships tab because the meaning of the icons aren't apparent, you have to hover them to see what the relationship is. It's a fair point.
Now a legend is added above the relationships tree, similar to the one above the list of versions:
> Add legend for relationships tab

- GUI/ErrorDialog.Designer.cs
If you launch CKAN with a dark theme while another copy is already running, there's an error message with black text on a dark background:
Same as #2540, the error text box has `Readonly=true`, which changes the background without updating the foreground.
Now the text color is readable on a dark theme:
> Fix error popup text for dark themes

- GUI/Main.Designer.cs
- GUI/MainChangeset.cs
- GUI/MainModList.cs
If you have a lot of mods installed, uninstalling all of them can require a lot of clicking.
Now the Installed column's header shows "Inst" and a checkbox.
If you uncheck this checkbox, all of your installed mods are queued up for uninstallation:
If you check the checkbox, the change set is reset to empty (installed mods checked, others not):
Fixes #1148.
Fixes #1945.
Fixes #1451.
Currently if you queue up a change set, click Apply, and then change your mind and click Clear, there's a noticeable delay to clear the change set because the whole grid is repopulated unnecessarily.
Now the change set is cleared much more quickly.
> Checkbox to uninstall all mods and reset changeset

- GUI/Main.Designer.cs
Some users like to launch KSP via CKAN. If they also enjoy using the tray icon, they might want to launch KSP from it as well.
The tray icon's right click menu now has a Launch KSP option that launches the game.
Fixes #2590.
> Add Launch KSP option to tray icon menu

- GUI/Main.cs
If you close and re-open GUI, the splitters between the mod list and the mod info and between the mod name/description and the mod info tabs are supposed to retain their positions. However, currently they tend to migrate rightwards and downwards rather than staying the same.
For example, across several open/close cycles where I did nothing but exit CKAN, the `ModInfoPosition` property in GUIConfig.xml took on this sequence of values:
292, 569, 891, 891, 891
Closing this window:
... results in this window at the next launch:
Forms raise events in [the following order at launch](https://docs.microsoft.com/en-us/dotnet/framework/winforms/order-of-events-in-windows-forms?view=netframework-4.7.2):
1. Load
2. Activated
3. Shown
In a typical WinForms application, a form has a hard coded layout …
> Stop splitters from migrating between sessions

- GUI/Main.cs
- GUI/MainInstall.cs
If you open a typical application, make changes, and then quit without saving, you're prompted to confirm that you really want to quit. This is done to prevent the user from losing work and having to re-do it if they click the quit button accidentally.
If you open CKAN, select mods to install or uninstall, and then quit without applying changes, it just closes.
Now if you select changes and try to quit, you get one of three prompts depending on whether there are conflicts or unmet dependencies. Clicking Yes closes CKAN, while clicking No closes the dialog and leaves CKAN running.
To avoid prompting unnecessarily after a successful installation, we now clear the change set after a successful installation. Previously we were leaving the change set intact (in the `Main.ChangeSet` variable) …
> Confirm quit with pending change set or conflicts

- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- GUI/Main.cs
If you install a bunch of mods with CKAN and then Steam auto-updates your KSP version, you might end up with mods that are incompatible and would not be possible to install from scratch if you started over. The effect of this can range from nothing to crashing the game or corrupting saves.
Many users may not notice that this has happened until it is too late, and new users may not even be aware that the risk exists.
Now if you click to launch KSP with incompatible modules installed, CKAN will show a warning that lists them along with their compatible game versions:
> Warn before launching KSP with installed incompatible modules

- Core/ModuleInstaller.cs
- Core/Relationships/RelationshipResolver.cs
- GUI/Main.cs
- GUI/MainChangeset.cs
- GUI/MainModList.cs
- GUI/MainRecommendations.cs
If you use the File &rArr; Audit recommendations option from #2577 to select one or more mods to install, those mods' recommendations will also be installed regardless of whether you selected them.
`RelationshipResolver` takes a `RelationshipResolverOptions` parameter that specifies what to do with recommendations and suggestions, among other things. Since it can be inconvenient to set 7 boolean member variables individually, a `RelationshipResolver.DefaultOpts()` function returns a default set of options.
This `DefaultOpts()` object was used for Audit recommendations. Unfortunately that object sets `with_recommends` to true, so this causes all recommendations of the specified mods to be treated as hard dependencies, which doesn't make sense to do in GUI. It's kind of awkward to have a …
> Don't auto-install recommendations when auditing recommendations

- GUI/Main.Designer.cs
If the status bar contains a string beyond a certain length in Mono, it'll be wrapped near the end, splitting off the last word and chopping off pieces of the letters, even if there's plenty of space in the status bar to fit:
I poked around in the mono source for a while trying to figure out what's going on, but I wasn't able to identify a clear cause. There are many layers of rendering code involved here:
- ToolStripStatusLabel
- ToolStripLabel
- ToolStripItem
- TextRenderer
- ToolStripRenderer
At least two of these have their own special data structure for handling fonts, padding, etc., so I suspect there's a discrepancy somewhere in all of that translation between different assumptions and contexts. Specifically, I suspect they're calculating the exact size needed for the text and then …
> Suppress wrapping of status bar in Mono

- CKAN.sln
- GUI/Configuration.cs
- GUI/Main.cs
- Tests/GUI/Configuration.cs
`Configuration.LoadOrCreateConfiguration()` gets passed a `defaultRepo` parameter.
This is a relic of the early days of CKAN it seems, when the repositories were saved in the GUI configuration, but this got moved to the registry in 536637f7fe2fded1878bf66fb9b5aabee012770f.
Since then the parameter sits there unused.
Also `SaveConfiguration()` gets passed a `path` parameter, which is redundant since there is a specific path variable in the `Configuration` class. It's a bit dangerous too, because it could lead to a difference between the real save path and the one set in the configuration.
Now SaveConfiguration() takes the value out of the according object of Configuration, which happened in `Save()` before.
I added `$2.SpaceAfterMethodCallName = False` to the solution file, because …
> Remove unnecessary parameter in Configuration methods

- GUI/MainTrayIcon.cs
There are probably situations now where the tray icon won't go away once you enable it.
#2587 made an unintentional change to the tray icon code. The line that hides it when it's already visible was commented out. I think this was done for testing and then missed when committing because the code was moved to a new file.
Now it's back as it was.
> Revert unintentional tray icon change from #2587

- GUI/MainInstall.cs
- GUI/MainWait.cs
If you cancel the installation/uninstall/update process after it's already complete, but before the Cancel button is greyed out you still get the "Error!" message and the Apply changes button is still active.
(Ignore the location of the Retry button atm, this seems to be another bug)
This is due to the entire GUI PostInstallMods() function only checking for e.Result.Key wich is set to false if the installation is canceled, despite the real result possibly being successful. This leads to those false error messages and  GUI behavior.
e.Result.Key is now set to the value of processSuccesful (if you know a better name, let me know!). PostInstallMods now also distinguishes the "installCanceled but positive processSuccesful case.
The corresponding messages and GUI actions are now handled by a …
> Show correct error messages after canceling (un)installations/upgrades

- Netkan/CKAN-netkan.csproj
- Netkan/Sources/Jenkins/IJenkinsApi.cs
- Netkan/Sources/Jenkins/JenkinsApi.cs
- Netkan/Sources/Jenkins/JenkinsArtifact.cs
- Netkan/Sources/Jenkins/JenkinsBuild.cs
- Netkan/Sources/Jenkins/JenkinsOptions.cs
- Netkan/Sources/Jenkins/JenkinsRef.cs
- Netkan/Transformers/JenkinsTransformer.cs
- Netkan/Transformers/NetkanTransformer.cs
- Tests/NetKAN/Sources/Jenkins/JenkinsApiTests.cs
- Tests/Tests.csproj
The Netkan transformers for GitHub, SpaceDock, and Curse are implemented as "sources":
- an interface defining an API
- a class implementing that interface
- classes defining objects returned by the API
See https://github.com/KSP-CKAN/CKAN/tree/master/Netkan/Sources
This provides a common, test-friendly structure for these `$kref`s.
Currently Jenkins, the `$kref` method for all of (and only) @sarbian's mods, doesn't work this way.
- It's a single monolithic class with all of the logic in the `Transform` method
- It has no tests
It also makes twice as many calls to the server as strictly necessary: one to get overall info about the job, and one to get the latest build using its build number.
Now Jenkins is implemented as a source like the others.
Now there are tests for Jenkins!
Now we get …
> Jenkins as a Netkan "source"

- Cmdline/Action/Repo.cs
- Core/Net/Net.cs
- Core/Types/Repository.cs
- GUI/MainRepo.cs
- Netkan/Services/CachingHttpService.cs
- Netkan/Services/IHttpService.cs
- Netkan/Sources/Github/GithubApi.cs
- Netkan/Transformers/NetkanTransformer.cs
- Tests/NetKAN/Sources/Github/GithubApiTests.cs
We currently have some network problems that hypothetically might be helped by transitioning from `WebClient` to some other library for network access (e.g., #2546), but currently `WebClient` code is spread through several places in the code, making it difficult to refactor cleanly.
The Netkan source `GitHubApi` now accepts an `IHttpService` parameter as the other Netkan sources do and uses it to access the GitHub API instead of making its own `WebClient`. This allows tests of this class to "mock" network accesses (though no test does this yet).
All other places that were previously using `WebClient` directly now call one of two central access points: `Net.DownloadText` or `NetAsyncDownloader`. This will make it easier to transition all of this code to some other underlying library in the …
> Encapsulate usages of WebClient

- Netkan/Sources/Curse/CurseFile.cs
- Netkan/Transformers/CurseTransformer.cs
Curse lets mod authors select multiple game versions (this list appears upon hovering the "+9" with the mouse):
This data appears in a `versions` property in the API:
https://api.cfwidget.com/project/283006
```json
"versions":["1.2","1.2.1","1.2.2","1.3","1.3.1","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4"]
```
Currently Netkan ignores those values; instead, the single game version from the `version` property in the API is used, and any broader compatibility can only be set with a `$vref` or with overrides.
I think the quirks of the selection of the value of that property somehow caused KSP-CKAN/NetKAN#6622.
Now we parse the full game version list. This is done with by adding a new `CurseFile.versions` property and extending `JsonConvertKSPVersion` to support arrays.
If there are multiple game …
> Handle multiple game versions from Curse

- Cmdline/Action/Update.cs
- Core/Net/Repo.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
Refreshing the mod list in GUI involves two steps:
1. Getting the new data from the server
2. Updating the lists and filters
Step 2 can take several seconds. While it's happening, the window freezes, because the intensive processing is done on the GUI thread (whereas step 1 has a progress bar). The freeze also happens when switching instances and changing version compatibility.
Now while the mod list is loading, the processing takes place in a background thread, and the progress bar screen is shown with messages indicating which step we're on (helpful for identifying slow pieces!):
This keeps the UI responsive and assures the user that it hasn't crashed. When finished, the tab is hidden.
While implementing this, I found out that the slowest step is `Registry.Available`, with a typical run …
> Show progress bar while loading registry

- GUI/Main.cs
- GUI/MainModList.cs
With #2610 I created a new TransparentTextBox class derived from TextBox, which allows textboxes with transparent background.
For unknown reasons, they behave different to normal textboxes when you close the GUI.
The seem to get disposed too early, because `DataGridView` wants to clear the selection before getting disposed. This triggers multiple methods one after the other, including `Main.ModList_SelectedIndexChanged()`, which finally leads to hiding the mod info tab and its included controls.
But all transparent textboxes are already disposed, so it throws the
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CKAN.TransparentTextBox'.
```
error.
----
Workaround:
Now I break the chain in `Main.ModList_SelectedIndexChanged()` by testing if the …
> Fix System.ObjectDisposedException for TransparentTextBox

- Tests/Core/Cache.cs
- Tests/NetKAN/Sources/Curse/CurseApiTests.cs
- Tests/NetKAN/Sources/Github/GithubApiTests.cs
- Tests/NetKAN/Sources/Jenkins/JenkinsApiTests.cs
- Tests/NetKAN/Sources/Spacedock/SpacedockApiTests.cs
As of recently (probably #2613), `./build test` is failing on Mono for me with this:
```
1) Failed : Tests.Core.ModuleInstaller.ModuleManagerInstancesAreDecoupled
Expected: No Exception to be thrown
But was:  <System.InvalidOperationException: object_op ---> System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached.
at System.IO.CoreFX.FileSystemWatcher.StartRaisingEvents () [0x0007b] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
at System.IO.CoreFX.FileSystemWatcher.StartRaisingEventsIfNotDisposed () [0x00019] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
at System.IO.CoreFX.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x0001d] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
at (wrapper remoting-invoke-with-check) …
```
> Dispose caches in tests

- Cmdline/Action/KSP.cs
- Core/CKAN-core.csproj
- Core/KSPManager.cs
- Core/Utilities.cs
- Core/Versioning/KspVersion.cs
- Tests/Core/KSPManager.cs
- Tests/Data/TestData.cs
~As I am a responsible developer and always test my changes on multiple systems before release...~
Because I am currently out of reach of my PC (christmas, family and useless stuff like this), I tried to work on CKAN a bit from a device with no KSP install.
But CKAN is rather bitchy about having a correct KSP install, and doesn't even let you in the GUI (which is the correct behavior in my opinion).
So to solve this issue, I added the `ckan ksp fake` command to create a dummy KSP directory, containing a GamaData folder, a `buildID.txt`, a `buildID64.txt` and a `readme.txt`.
This should also be useful for quick tests of mod related issues.
---
Following options are implemented:
Side effects:
* New `CopyDirectory()` function to properly copy a folder with all subfolders. Implemented as a …
> Add possibility to clone KSP installs and create dummy ones

- GUI/Main.cs
- GUI/SettingsDialog.cs
Since #2541, our menus have looked ugly on Windows:
We made a custom toolbar/menu renderer to work around Mono's mishandling of dark themes, but this looks bad on Windows.
Now we only apply that workaround on Mono, and Windows looks nicer:
> Don't override menu renderers on Windows

- ConsoleUI/Toolkit/Keys.cs
- ConsoleUI/Toolkit/ScreenObject.cs
Germans can't install mods in ConsoleUI, because their '+' key doesn't work.
ConsoleUI was developed under the QWERTY keyboard layout, where '+' is typed by pressing Shift-equals, and Windows reports this with the Shift modifier (Mono reports it without the modifier, so there was already a workaround for that).
However in a QWERTZ layout, '+' is an unshifted key, so it doesn't match the `ConsoleKeyInfo` object we used for key bindings.
Now we represent Plus as an array of two `ConsoleKeyInfo` objects, one with Shift and one without, to cover both cases. The framework is updated to allow `IEnumerable<ConsoleKeyInfo>` to be passed to `AddBinding`, so existing usages of `Keys.Plus` will work as-is.
Fixes #2633 (the part that can be fixed).
> Handle plus without shift in ConsoleUI

- ConsoleUI/AuthTokenListScreen.cs
- ConsoleUI/DependencyScreen.cs
- ConsoleUI/KSPListScreen.cs
- ConsoleUI/KSPScreen.cs
- ConsoleUI/ModInfoScreen.cs
- ConsoleUI/ModListScreen.cs
- ConsoleUI/ProgressScreen.cs
- ConsoleUI/RepoScreen.cs
- ConsoleUI/Toolkit/ConsoleScreen.cs
The screen tip for the main menu is always "F10 - Menu" in ConsoleUI, but sometimes a more specific string might be helpful.
Now the "F10 - Menu" tip is changed on two screens:
- "F10 - Links" on the mod info screen
- "F10 - Sort" on the game instance list screen
As a bit of side cleanup, `ConsoleScreen.LeftHeader` and `ConsoleScreen.CenterHeader` are now changed from `Func<string>` variables to virtual string functions (to be consistent with the newly added `MenuTip`). This is a cleaner way of providing a function that can be overridden in a child class.
> Allow overriding menu tip in ConsoleUI

- Cmdline/Action/KSP.cs
- Cmdline/ConsoleUser.cs
- Core/KSPManager.cs
- Core/Types/Kraken.cs
- Core/Versioning/KspVersion.cs
- Tests/Core/KSPManager.cs
@HebaruSan discovered some issues with my new two functions. This is how they behave now: 
Both functions:
Write human-readable messages if there are too few arguments provided, no error messages due to crashes.
`ckan ksp fake`:
* Creates now all subdirs requested (see https://github.com/KSP-CKAN/CKAN/pull/2627#discussion_r244621435).
* Added `--set-default` flag to make the new instance the default afterwards.
* Also, if a user inputs a version number at least with major and minor, a selection dialog is raised to select a specific version (including build) known in the build map (else a message is raised to inform him to input a version with major and Minor at least).
This logic is now added as a new method of `Versioning.KspVersion` -> `KspVersion RaiseVersionSelectionDialog(IUser)`. …
> `ckan ksp fake/clone` fixes

- Cmdline/ConsoleUser.cs
- ConsoleUI/Toolkit/ConsoleScreen.cs
- Core/ModuleInstaller.cs
- Core/User.cs
- GUI/CKAN-GUI.csproj
- GUI/ChooseKSPInstance.cs
- GUI/GUIUser.cs
- GUI/Main.cs
- GUI/MainDialogs.cs
- GUI/MainImport.cs
- GUI/MainRepo.cs
- GUI/SelectionDialog.Designer.cs
- GUI/SelectionDialog.cs
- GUI/SelectionDialog.resx
- Netkan/ConsoleUser.cs
- Tests/Core/KSP.cs
- Tests/Core/ModuleInstaller.cs
- Tests/Core/ModuleInstallerDirTest.cs
- Tests/Data/DisposableKSP.cs
Problem:
---
Our UI specific `(I)User` classes for interacting with the... user are pretty messy.
Besides to the consoleUI all of them are inheriting from `NullUser` instead of directly extending the `IUser` interface, which kinda misses the point of having an interface.
Also the `NullUser` implements a `Display...()` method for each `IUser` method _on top_ of the existing `Raise...()` methods, just to let the `Raise..()` ones call the `Display...()` ones without any reason to do so.
Solution:
---
Now all `User` classes inherit directly from `IUser`.
`NullUser` is now only used in tests. 
All `Display...()` methods are removed.
Added LOTS of code documentation, because I could have needed them...
And i implemented the selection dialog for the GUI.
> Derive User classes directly from IUser interface instead of the NullUser class.

- GUI/MainRecommendations.cs
If you use the "Install from .ckan..." menu option in GUI, as of #2577 some modules may be missing.
`CanInstall` decides whether a list of modules can be installed by creating a `RelationshipResolver` and checking whether its mod list has at least as many elements as it's trying to install:
https://github.com/KSP-CKAN/CKAN/blob/1bbd2fddcc9fc3663a62db90835d4d2d04ae2708/GUI/MainRecommendations.cs#L152
The list on the right includes the .ckan file itself, which has `IsMetapackage = true`.
Unfortunately `RelationshipResolver` excludes metapackages from `ModList()`, so such modules would **not** be included on the left:
https://github.com/KSP-CKAN/CKAN/blob/1bbd2fddcc9fc3663a62db90835d4d2d04ae2708/Core/Relationships/RelationshipResolver.cs#L490-L493
So `CanInstall`'s check will fail when …
> Show all recommendations of metapackages in GUI

- GUI/MainModList.cs
Since #2617, we occasionally get exceptions at startup:
```
at CKAN.Main._UpdateFilters()
at CKAN.Util.Invoke[T](T obj, Action action)
at CKAN.Main.UpdateFilters(Main control)
at CKAN.Main.<.ctor>b__37_0(MainModList source)
at CKAN.MainModList.set_ModFilter(GUIModFilter value)
at CKAN.Main.Filter(GUIModFilter filter)
at CKAN.Main.CurrentInstanceUpdated()
at CKAN.Main.OnLoad(EventArgs e)
at System.Windows.Forms.Form.OnCreateControl()
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl()
at System.Windows.Forms.Control.WmShowWindow(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.Form.WmShowWindow(Message& …
```
> Don't try to update filters if mod list missing

- GUI/MainModList.cs
- GUI/MainWait.cs
#2617 made `UpdateModsList()` run in a background thread.
So all accesses to `FilterToolButton` and `UpdateToolButton` are made via this new task, and not the UI thread.
This didn't throw any exception on runtime or anything, but in Visual Studio if you debug CKAN.
Now all accesses to any GUI elements in `UpdateModsList()` are done through invocation.
> Invoke control accesses in `UpdateModsList()`

- GUI/MainModList.cs
On loading GUI, the focus is somewhere invisible (the splitter or the tab control, from some debugging). It should be on the mod list.
Not clear exactly what caused this. Possibilities:
- #2617 moved the mod list loading process into a background process and switched the GUI into the progress bar screen while it runs. The extra switching between tabs may have confused WinForms.
- #2556 made the mod info sidebar show/hide when mods are focused, and also rearranged the hierarchy of controls so the main tabs are inside the splitter. Some of this happens during load, so that may also have confused WinForms.
Now we explicitly set the focus to the mod list at the end of `UpdateModsList`, after we switch back to that tab.
(I'd like to find a more generic fix, but none of the solutions I tried …
> Set focus to mod list after loading

- Core/Types/CkanModule.cs
- GUI/Main.Designer.cs
- GUI/MainModList.cs
* Align the download count number to the right
* Align the size text to the right
* Format the download count number with thousands separators.
* Change size appendages to binary prefixes following [ISO/IEC 80000-13:2008](https://en.wikipedia.org/wiki/ISO/IEC_80000) and  [IEEE 1541-2002](https://en.wikipedia.org/wiki/IEEE_1541-2002) ;)
> Small text/number formatting changes to mod list

- Cmdline/ConsoleUser.cs
- ConsoleUI/Toolkit/ConsoleScreen.cs
- Core/ModuleInstaller.cs
- Core/User.cs
- GUI/GUIUser.cs
- GUI/MainInstall.cs
- Netkan/ConsoleUser.cs
#2648 added a `IUser.ConfirmPrompt` property. This doesn't belong there because it's just a way for two core functions to avoid raising specific yes/no prompts in GUI (which prior to #2648 was done with a hack of setting `GUIUser.displayYesNo = null`). There is no general concept of "confirm prompt" that needs to be represented at this level.
Now this is removed and replaced with parameters in `ModuleInstaller.InstallList` and `ModuleInstaller.UninstallList`, where they're actually used. GUI passes false, everyone else uses the default of true.
> Remove ConfirmPrompt from IUser

- CHANGELOG.md
- ConsoleUI/ModInfoScreen.cs
- ConsoleUI/ModListHelpDialog.cs
- ConsoleUI/ModListScreen.cs
- ConsoleUI/Toolkit/Symbols.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- Core/Types/ModuleInstallDescriptor.cs
- Core/Versioning/KspVersionRange.cs
Manually installed mods (or "auto detected" or "AD") are not handled well in ConsoleUI.
- They're shown as simply installed (check mark symbol)
- You can try to uninstall them
- The mod info screen crashes if you try to view them
I tend not to use AD mods, so I didn't test it in ConsoleUI.
Now I have some symlinks set up for the dev versions of my mods, so I stumbled across this.
- AD mods now have their own status symbol in the mod list: infinity
- Added to the help screen
- The key tip and hotkey for uninstallation are disabled for AD mods
- The mod info screen now doesn't crash and shows AD mods with a "Installed manually" header and "???" for the version and game version compatibility
- Several occurrences of "identifer" in the code are corrected to "identif**i**er".
> Handle manually installed mods in ConsoleUI

- Netkan/Sources/Github/GithubRepo.cs
- Netkan/Transformers/GithubTransformer.cs
- Spec.md
The GitHub API provides license data:
https://api.github.com/repos/Starstrider42/Custom-Asteroids-Extras
```json
"license": {
"key": "mit",
"name": "MIT License",
"spdx_id": "MIT",
"url": "https://api.github.com/licenses/mit",
"node_id": "MDc6TGljZW5zZTEz"
},
```
But currently Netkan doesn't use this info.
We do use API license data from Curse and SpaceDock.
Now Netkan sets the API's `license.spdx_id` value to the module's `license` property.
Fixes #2662.
> Get license from GitHub

- GUI/GUIMod.cs
AD mods were unintentionally removed from GUI's Installed filter in #2514.
Now `GUIMod.IsInstalled` will be set to true for AD mods.
Fixes #2667.
> Add AD mods back into GUI's installed filter

- README.md
I glanced at the IRC channel and found this in the scrollback:
> Hi all.
> I'm using linux and would like to use CKAN.  I've cloned the repo and built with no errors, what do I do next?
> I can't seem to locate an obvious binary to run.
> Oh is it the debian folder (even though I'm not deb)?
> has a makefile
> hm nope, that requires dpkg-deb
> gonna try WINE with the windows executable
> 
> that doesn't work either, guess there's some requirements for certs
If you're not fluent in GitHub it may not be obvious where the releases are. There's a download button in the README, but it's kind of easy to miss. Changes:
| Before | After |
| --- | --- |
| Text said "downloads" which looks like it's just a counter | Label says "Download" to indicate an action |
| No icon | Added a unicode ⤓ symbol …
> Make the download button more obvious

- Core/ModuleInstaller.cs
- GUI/GUIMod.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- GUI/ModChange.cs
GUI lets you install an old version of a mod by double clicking in the Versions tab of mod info.
If another version of the mod is already installed, then the progress screen will appear and announce that the mod is being skipped because it's already installed. This means that to switch to a different version of an installed mod, you have to uninstall it explicitly and *then* install the other version. If other mods depend on it, they will be uninstalled, and you have to remember to re-install them afterwards.
This was a pain point recently with ModuleManager 4.0.0, which apparently broke loading of "custom tech tree and ﻿physics﻿". Impatient users who upgraded to this version and didn't want to wait for a fix (4.0.1 came out ~26 hours later) were stuck either with a broken install or with …
> Cleanly switch versions of installed mod

- Core/Registry/Registry.cs
If you:
1. Install some module manually that can be Autodetected (ModuleManager is a good choice)
2. Use CKAN to install mods that depend on that module
3. Manually delete that module
4. Attempt to install the module in CKAN GUI
... then GUI will try to remove all the reverse dependencies from step 2.
The equivalent operation in CmdLine (`ckan install modulemanager`) works without removing anything.
Now GUI won't try to remove reverse dependencies if you're not uninstalling anything. This will allow installation of missing dependencies.
Fixes #2672.
> Allow installation of missing dependencies in GUI

- GUI/Configuration.cs
- GUI/Main.cs
- GUI/MainTrayIcon.cs
- GUI/Util.cs
MacOSX users have experienced problems with CKAN's title bar appearing behind the OS menu bar, such that it cannot be used to move the window.
https://github.com/KSP-CKAN/CKAN/blob/aba8b02098f5491caa59a3fd7613e8cdc68f2a6e/GUI/Configuration.cs#L43
That value is used as the window location if the position isn't saved in `CKAN/GUIConfig.xml`. So the first time you run CKAN, it tries to appear at the upper left corner of the screen.
`Configuration` is changed to treat the default window position as -1,-1 instead of 0,0. This is so we can distinguish between the default and values the user might choose (0,0 could be either one). Some other weird workaround stuff around the `WindowLoc` property is removed.
Now if `Configuration.WindowLoc` is -1,-1, we don't bother restoring it but instead set …
> Fix window position on MacOSX

- Core/Relationships/RelationshipResolver.cs
- GUI/Main.cs
- GUI/MainChangeset.cs
- GUI/MainWait.cs
Upgrading modules in GUI is broken as of #2669. On Windows it throws an exception and crashes, on Linux the Apply changes button doesn't enable.
Cancelling out of a "recommends" based install from .ckan operation in GUI causes assorted issues. In addition to those detailed in #2676, the Apply changes button is enabled despite there being no change set.
See #2669 for details of the upgrade problem; to sum up, there's now an extra entry in an upgrade change set that throws exceptions when we try to use it. This entry says that its selection reason is `Installed`, even though the user asked us to upgrade / install it.
GUI's install-from-ckan function can add a Metapackage to the registry (if that's what's in the .ckan file), which thereafter can appear in the mod list, change sets, etc. This …
> Fix upgrading and installing from .ckan in GUI

- CKAN.schema
- Cmdline/Action/Show.cs
- ConsoleUI/DependencyScreen.cs
- ConsoleUI/ModInfoScreen.cs
- ConsoleUI/ModListScreen.cs
- Core/CKAN-core.csproj
- Core/Converters/JsonRelationshipConverter.cs
- Core/Net/Repo.cs
- Core/Registry/AvailableModule.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Types/CkanModule.cs
- GUI/MainModInfo.cs
- GUI/MainRecommendations.cs
- Spec.md
- Tests/Core/KSPManager.cs
- Tests/Core/ModuleInstaller.cs
- Tests/Core/ModuleInstallerDirTest.cs
- Tests/Core/Net/NetAsyncModulesDownloader.cs
- Tests/Core/Relationships/RelationshipResolver.cs
- Tests/Core/Relationships/SanityChecker.cs
- Tests/Core/Types/RelationshipDescriptor.cs
- Tests/GUI/GH1866.cs
- Tests/GUI/GUIMod.cs
- Tests/GUI/MainModList.cs
Sometimes a mod needs some functionality to be provided by a third party dependency, and there are several choices available, but they have different APIs, so the dependent mod has to implement support for each one separately.
For example, TextureReplacer, TextureReplacerReplaced, SigmaReplacements-SkyBox, and DiRT can all be used to replace the stock SkyBox with a custom one, but they're all mutually incompatible and so a dependent mod has to implement support for them separately one by one.
The `provides` property can't handle this (well), since there is no baseline abstract concept that they could sensibly `provide`. Consider if we had all four of the above mentioned mods `provide` something like SkyBoxReplacer; then we would not have a solution for a dependent mod that only …
> Support depends on any_of lists

- Core/Utilities.cs
- Tests/Core/KSP.cs
- Tests/Core/Utilities.cs
- Tests/Data/DisposableKSP.cs
- Tests/Data/TestData.cs
- Tests/Tests.csproj
- Tests/Util.cs
In #2627 I created a new, more robust `CopyDirectory()` than the existing one in `TestData`.
Replaced all calls to `TestData.CopyDirectory()` with `Utilities.CopyDirectory()`.
Removed `TestData.CopyDirectory()`.
All tests still run successful.
> Use Core.Utilities.CopyDirectory in tests

- GUI/SettingsDialog.Designer.cs
`RefreshPreLabel` overlaps `RefreshTextBox` in the settings window.
Moved `RefreshTextBox` and `RefreshPostLabel` some pixels to the right.
Before:
After:
> Fix RefreshPreLabel overlapping RefreshTextBox in Settings

- Cmdline/Action/Update.cs
- Core/Net/Net.cs
- Core/Net/Repo.cs
- Core/Types/Repository.cs
- GUI/MainRepo.cs
Updating the registry can be slow, as it requires downloading a 2.5 MB ZIP or tar.gz file, then extracting it and parsing the JSON of all the modules and populating the registry with them. In GUI there's a further delay as the mod list and filters are updated.
If there haven't been any metadata changes since the last time you refreshed, then all of this is done for naught. It would be nice to skip it in that case.
Now we use the `ETag` HTTP response header to determine when a repo's metadata is already up to date. This is an opaque hexadecimal string (with quotes around it) that changes when the `master.tar.gz` file does. It is returned when the file is downloaded, but it can also be retrieved with a much quicker HEAD request. In my testing, this value does indeed change when something in …
> Avoid redundant metadata downloads

- GUI/MainAllModVersions.cs
- GUI/MainModInfo.cs
If you do this under Mono:
1. Open GUI
2. Click any mod
3. Open the Versions tab in mod info
4. Open any other tab in mod info
5. Click another mod
6. Open the Versions tab
... then the column headers won't be drawn:
Unclear, but CKAN's GUI doesn't do anything particularly tricky with these controls. There's a `TabControl` with a `TabPage` that has a `ListView`, and we mostly let the runtime worry about handling them.
It looks a Mono bug, but I wasn't able to pin down exactly how or where. So we'll be going with a workaround.
Now when you switch to the Versions tab, we call `VersionsListView.EndUpdate()` on Mono. This ensures that drawing is enabled and forces a full redraw. In my testing this addresses the problem with drawing the headers.
@DasSkelett, can you please test this and report …
> Force redraw of versions ListView on Mono

- GUI/Main.cs
If you right click to reinstall an installed module, all of its recommendations will be installed even if you de-select them.
See #2604; `RelationshipResolver.DefaultOpts()` causes all recommendations to be installed. Reinstall was using this as of #2233.
Now the reinstall flow uses `DependsOnlyOpts`, which was created in #2606 for just this sort of situation. Recommendations will only be installed if the user chooses them.
Fixes #2688.
> Don't auto-install recommendations when reinstalling

- GUI/MainModList.cs
If a module conflicts with its `replaced_by` module, clicking the Replace checkbox reports the conflict and blocks installation in GUI as if we were going to install both of them:
Noted as part of KSP-CKAN/NetKAN#7027.
This call throws because it tries to resolve relationships with both conflicting modules installed:
https://github.com/KSP-CKAN/CKAN/blob/6b4cd143996f029b94162ec89a2e0cb86f9a7c3f/GUI/MainModList.cs#L689-L702
That `null` value was set in #2579, and is the parameter for modules that will be removed; previously we passed `modules_to_remove`, which caused a different exception to be thrown if you removed a module that other modules depend on.
Now the reverse dependency logic happens *first*, and adds the reverse dependencies to `modules_to_remove`. This then allows us to pass …
> Allow replacement by conflicting modules

- GUI/Configuration.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainModList.cs
**This PR adds the option to hide columns in the modlist.** as asked by @politas in #2687.
This happens via a right click context menu on the header row of the modlist:
The columns are hidden with `column.Visibility = false`, which seems to work perfectly fine in my testing. This doesn't need a reload of the modlist or anything, so it's fast.
On every change of the visibility of a column it is saved to the GUIconfig, which means it's persistend across ckan restarts.
The `Update` and the `Replace` checkbox columns are hidden by default, and only shown if an update / a replacement is available. I could only test updates yet, but replacements should work the same.
Once all updates / replacements have been done, the columns are hidden again.
This all happens in `UpdateModsList()`. …
> Customisable columns in GUI Modlist

- GUI/Main.Designer.cs
- GUI/MainModList.cs
If you have manually installed mods, the Inst column shows up as "AD" for them. If you sort by the Inst checkbox column, AD mods appear at the very end of the list, far away from the CKAN-installed mods represented by a checked box.
And the "AD" and "-" strings are left aligned while the checkboxes are centered, which doesn't look great.
Now the sort goes:
1. CKAN-installed mods (checked checkboxes)
2. AD mods
3. Non-installed compatible mods (unchecked checkboxes)
4. Incompatible mods ("-")
Also the checkbox columns are centered now so the "-" aligns better with the checkboxes.
> Sort AD above empty checkboxes

- Netkan/Transformers/CurseTransformer.cs
- Netkan/Transformers/GithubTransformer.cs
- Netkan/Transformers/JenkinsTransformer.cs
- Netkan/Transformers/SpacedockTransformer.cs
Currently running netkan for a repository with no releases generates no error message. It used to output a message like:
> No releases found for PorktoberRevolution/ReStocked
Noticed while taking a look at PorktoberRevolution/ReStocked#492.
In #2681 we updated Netkan to be able to generate multiple .ckan files in one pass. The no-release check and message were moved to the `TransformOne` functions, which are called within a `foreach` loop over the list of releases. But if that list is empty, then `TransformOne` is not called at all, so the error is never printed.
Now we explicitly check whether the list of releases is empty in the main `Transform` function and print the error in that case. This is done for Jenkins, GitHub, SpaceDock, and Curse.
> Reinstate no releases warnings for Netkan

- GUI/Main.cs
- GUI/MainRepo.cs
Currently if you enable auto repo updates at startup, GUI can exhibit some visual oddities, such as showing a blank disabled mod list for a few seconds, or flashing multiple times between the mod list and the progress bar screen.
As far as I can tell none of these cases causes a functional problem or leaves the UI unusable; they just look weird. (Except for performance, see below.)
`UpdateModsList` can be called twice at startup in this configuration, once by `Main.CurrentInstanceUpdated` during the normal load process and once by `Main.PostUpdateRepo` after updating the repo (though this can be suppressed as of #2682). When this happens, one of those updates is unnecessary. Since `UpdateModsList` is one of the longest/slowest steps we have, this represents a big performance hit.
In …
> Only update mod list once at GUI startup

- GUI/MainModList.cs
#2690 was supposed to hide the Replace column if it didn't contain any checkboxes. When we tested that PR, there were no modules with replacements. When some were added in KSP-CKAN/NetKAN#7049 and KSP-CKAN/NetKAN#7048, the column became always visible.
This line returns true if *any* mod in the list has a `replaced_by` property, including those not installed:
https://github.com/KSP-CKAN/CKAN/blob/4f3b3d7cdf9c65afd17283fd0631bd1749aa3f3a/GUI/MainModList.cs#L248
The `GUIMod.HasReplacement` property is set unconditionally alongside `HasUpdate`, so if an uninstalled module's latest version has a replacement, it will be true:
https://github.com/KSP-CKAN/CKAN/blob/4f3b3d7cdf9c65afd17283fd0631bd1749aa3f3a/GUI/GUIMod.cs#L105-L106
Now the code that hides the column first checks whether the module …
> Only show replace col if a replaced module is installed

- GUI/AboutDialog.cs
- Tests/GUI/GUIMod.cs
- debian/changelog
- debian/control.in
There were some references to the old .org url in the code, thanks @mvconners and @HebaruSan!
Now they all point to the new `http://ksp-ckan.space`.
Closes #2701.
> Update all CKAN URL references

- GUI/Main.cs
After the `MarkAllUpdatesToolButton` is clicked, the modlist scrolls to the top by selecting the third (index 2) cell of the first row.
With v1.26, this column is no longer the mod name, but the `replace` checkbox.
If this one is hidden, CKAN throws an error (because you cant select hidden cells), and it is in most cases.
Now the second cell instead of the third cell is selected, which is shown if there are updates available (otherwise you can't even click the button to mark all updatable mods), and which can't be hidden by the user, so the same error can't repeat with other columns.
Fixes #2703
> Select 2nd instead of 3rd cell on `MarkAllUpdatesToolButton_Click`

- GUI/CompatibleKspVersionsDialog.cs
CKAN treats a null KSP version in a modversion as "Any", so that a .ckan file with no version information does what we would expect.
The CompatibleKSPVersions dialog allows users to add arbitrary version strings, and then uses the same KSP version parsing that we use for calculating modversion compatibility. This results in a null return value for the text string "any", which does not get caught as an invalid string, allowing the JSON file to be saved with a <null> entry in the CompatibleVersionsList.
On next launch of CKAN, the null entry causes an error.
Now, attempts to add the string "any" to the CompatibleKSPVersionsList are captured and prevented.
Closes #2705
> Prevent Null entry in CompatibleKSPVersions

- policy/Opt-out-list.md
To protect against unwanted proliferation of hot code
> Add self to opt-out

- GUI/Main.cs
- GUI/Util.cs
If you:
1. Open CKAN with the tray icon enabled
2. Minimize it
3. Right click the tray icon
4. Exit
... then the following is saved to `GUIConfig.xml`:
And the next time CKAN runs, its window will not appear.
Apparently Windows moves minimized windows to (-32000,-32000).
https://stackoverflow.com/questions/1478765/location-coordinates-on-computer-showing-x-32000-y-32000
So when we exit and save the `Location` property while minimized, we're saving that value.
Now we ignore `Location` if the window state isn't normal (i.e., we're minimized or maximized), and instead we check `RestoreBounds.Location`, which is where the window's former location to which it will be returned lives. This mirrors how we handle the window size on the next line of code (though in that case the problem was with …
> Save restore position when minimized

- GUI/Main.cs
- GUI/MainModList.cs
If you do any of the following:
- Press Home on the mod list
- Press End on the mod list
- Invoke the URL handler
- Start typing a mod name on the mod list
- Double click a mod in the mod info dependency tree
... this exception occurs:
```
System.InvalidOperationException: Die aktuelle Zelle kann nicht auf eine unsichtbare Zelle festgelegt werden. (Rough translation: the current cell can't be set to an invisible cell)
bei System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
bei CKAN.Main.ModList_KeyDown(Object sender, KeyEventArgs e)
bei System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
bei System.Windows.Forms.DataGridView.OnKeyDown(KeyEventArgs e)
bei System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
bei …
```
> Fix home/end, url handler, typing nav, and dependency double click

- GUI/MainModInfo.Designer.cs
The relationships tree doesn't fit in the available space:
#2592 moved the top of the tree control down 92 pixels without changing its height, so the bottom slid down as well, past the bottom of the available space. The parent control starts at 502 pixels tall, while the tree's top is 96 and height is 489, so the bottom is at 96+489 =585:
https://github.com/KSP-CKAN/CKAN/blob/3bc537637e8f4452c9787699045d61b4d869061f/GUI/MainModInfo.Designer.cs#L471-L484
Now the relationships tree is 400 pixels tall, which allows it to fit in the available space since 96+400 < 502:
Fixes #2722.
> Fix size of relationships list

- GUI/MainInstall.cs
If you install a module, and then install a different version of it by double clicking in the Versions tab of mod info, its Installed checkbox becomes unchecked even though it's still installed.
`UpdateModsList` has a change set parameter to keep the mod list in sync with the active change set. If you pass a change set in this parameter, the function will apply each change in it to the freshly loaded mod list. When you install by double clicking an older version, we don't go through the main change set, but instead jump directly to installing the module.
We were passing the just-completed change set to `UpdateModsList` after installation. This isn't necessary because the changes will be picked up directly from the registry, but until recently it was at least benign since the boxes it …
> Don't apply previous change set to checkboxes after successful install

- GUI/AboutDialog.cs
- GUI/MainModInfo.cs
- GUI/Util.cs
It may sometimes be desirable to access a mod's home page URL without opening it in the default browser, for instance you might want to open it in another browser or paste it into a forum post.
Currently right clicking the links works just like left clicking, the URL is opened in the system default browser.
Now if you right click one of the mod info links, a context menu appears with a "Copy link address" option. Clicking this option copies the URL to the clipboard.
Fixes #2698.
> Right click copy option for mod info links

- GUI/YesNoDialog.Designer.cs
- GUI/YesNoDialog.cs
If the `YesNoDialog` needs to display a long string, it can be truncated:
It's just a statically sized form, so only short strings will fit.
Now the form is resizable, so if it's unreadable, the user has the option to resize it. The controls have the `Anchor` property set to make them move correctly.
Now when a message is set, the form uses `Graphics.MeasureString` to determine the required height of the label, and uses this to set the size of the form. This ensures that the full message will be visible.
`YesNoDialog` no longer inherits from `FormCompatibility` because it wasn't calling `ApplyFormCompatibilityFixes` anyway. This will have no effect.
Fixes #2718.
> Auto size yes no dialog

- Core/Net/Repo.cs
- Core/Types/CkanModule.cs
@Poodmund reported an issue on the forum where this popup appears every time CKAN is launched, even after you click Yes to reinstall:
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1260-baikonur/&do=findComment&comment=3586115
At the top level, `Repo.RelationshipsAreEquivalent` uses `RelationshipDescriptor.Same` to compare the relationships of an installed module with those of its freshly updated available counterpart:
https://github.com/KSP-CKAN/CKAN/blob/5331bf9344f6729a6b96f52bea45bdec245a3bb3/Core/Net/Repo.cs#L321-L330
Child class `ModuleRelationshipDescriptor` implements `Same` as a comparison of the name and versions:
https://github.com/KSP-CKAN/CKAN/blob/5331bf9344f6729a6b96f52bea45bdec245a3bb3/Core/Types/CkanModule.cs#L15 …
> Compare RelationshipDescriptors with Equals instead of Same

- Core/Net/Net.cs
- Netkan/Transformers/AvcKrefTransformer.cs
- Netkan/Transformers/AvcTransformer.cs
- Netkan/Transformers/MetaNetkanTransformer.cs
When KSP-CKAN/NetKAN#7050 tried this:
```json
"$kref"         : "#/ckan/netkan/https://github.com/PorktoberRevolution/ReStocked/blob/prod/CKAN/ReStock.netkan"
```
It got this error:
```
Running NetKAN for NetKAN/ReStock.netkan
1426 [1] FATAL CKAN.NetKAN.Program (null) - Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Build step 'Execute shell' marked build as failure
```
That URL points to the rich GitHub page about that file rather than the raw JSON file contents. We have some special logic in place to translate such URLs, but it's only applied to KSP-AVC files' `URL` property:
https://github.com/KSP-CKAN/CKAN/blob/6b4cd143996f029b94162ec89a2e0cb86f9a7c3f/Netkan/Transformers/AvcTransformer.cs#L209-L256
Now the logic that was previously used only by …
> Handle non-raw GitHub URLs for metanetkans and avc krefs

- GUI/MainInstall.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
If you have repository auto updates enabled, then the Newly Compatible filter will show all modules:
Before #2694, GUI performed two mod list updates at startup if repository auto updates were enabled: one with the existing registry data (which the user will never see), and one with the registry data after the repo update. This is not great because mod list updates are one of our slower operations.
After #2694, GUI performed only one mod list update at startup, using the data after the repo update. This improved performance, but it broke the Newly Compatible filter because that filter was based on a comparison of the mod list before and after the repo update. With only do one mod list update, the "before" list in the comparison is empty, and every mod seems to be newly added.
Now the …
> Fix Newly Compatible filter with repo autoupdate

- GUI/Main.cs
- GUI/MainAllModVersions.cs
- GUI/MainDialogs.cs
- GUI/MainInstall.cs
- GUI/YesNoDialog.cs
Currently if CKAN needs to confirm certain actions with the user, it uses a Yes/No popup:
This is not great for usability, since it requires the user to read the text carefully in order to understand the exact meaning of "Yes" and "No". For all the user knows, we might be asking whether to continue, or we might be asking whether to abort.
Now we have the ability to override the labels of the Yes and No buttons in order to make the choice you're making more clear. The following dialogs are updated to take advantage:
- Unapplied changes: Quit / Go Back
- Incompatible installed: Launch / Go Back
- Install specific module version: Install / Cancel
- Add an auth token for GitHub: Open Settings / No
Note that this is not done for **all** questions, because some of them come from inside Core and …
> Relabel Yes/No buttons for some questions

- Cmdline/Action/Search.cs
- Cmdline/Options.cs
- ConsoleUI/ModListScreen.cs
- Core/Registry/AvailableModule.cs
- Core/Types/CkanModule.cs
- GUI/CKAN-GUI.csproj
- GUI/GUIMod.cs
- GUI/MainModInfo.cs
- GUI/MainModList.cs
- GUI/SelectionDialog.cs
If you want to search the mod list (in GUI, commandline or consoleUI), you have to know the name/identifier/author/description exactly, even spaces and special character.
There are **a lot** of mods with spaces and special characters in their name, sometimes even in the identifier indexed in the CKAN.
Examples:
* aati-flags (name) - AATI-Flags (identifier)
(special char)
* [1.3] Capsule Corporation Endeavour (Mars Base Camp)
(special chars and spaces)
* BetterBurnTime
(no spaces)
* and on and on
It's nearly impossible to find a mod on the first try right now, if you don't know the exact name including all spaces, hyphens, brackets, dots...
On startup, more precisely during the deserialization of `CkanModule`s on load of registry, 'Searchables' are calculated for every mo and mod version, …
> Ignore spaces and special chars in mod search

- GUI/MainModList.cs
Since #2617 errors which are thrown during startup, that means in `UpdateModLists()`, are 'swallowed', and the GUI just stopps working and is stuck in a infinite loop-like state.
#2617 changed the call of `_UpdateModsList()` to a `Task`.
Because the main thread waits for the Task to finish, but the Task in fact stopped executing if an error happened, CKAN is stuck.
Only if you add an `await` operator in front of Tasks (and thus an `async` in the method declaration) the errors are finally thrown in the main thread. This way CKAN crashes properly on fatal/not catched errors, and the stack trace and error message are shown to the user.
> Throw errors happening in UpdateModsList()

- Core/Net/NetFileCache.cs
Some users reported that CKAN freezes while trying to load the registry at startup.
This exception is thrown:
```
System.ArgumentOutOfRangeException: 인덱스 및 길이는 문자열 내의 위치를 참조해야 합니다.
매개 변수 이름: length (Rough translation: The index and length must refer to the position within the string. Parameter name: length)
위치: System.String.Substring(Int32 startIndex, Int32 length)
위치: System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
위치: System.Linq.GroupedEnumerable`3.GetEnumerator()
위치: System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
위치: System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 …
```
> Fix freeze on non CKAN files in cache folder

- GUI/Main.Designer.cs
- GUI/MainInstall.cs
- GUI/MainRecommendations.cs
*(a.k.a., "Rewrite recommendations... again")*
If you import a .ckan file that recommends CustomBarnKit, it'll try to install two mods by default:
- CustomBarnKit
- CustomBarnKit-RO
These conflict with one another, so if the user simply accepts the recommendation, the install will fail with an error.
CustomBarnKit-RO `provides` CustomBarnKit, so recommending one pulls in both.
This is important for something like FerramAerospaceResearchContinued, which we want to match a recommendation for FAR.
We need the ability to present a recommendation as unchecked. This is impossible within the current code structure, since all recommendations are handled the same way in one big group, and there's no conduit through which we could pass an indication of whether to check the checkbox.
Now the …
> Combine recommendation and suggestion screens

- Core/Registry/AvailableModule.cs
- On a completely fresh install, AstronomersVisualPack shows as compatible
- If you install Scatterer, AstronomersVisualPack (which depends on Scatterer) shows as incompatible
That doesn't make sense. Installing a dependency shouldn't ever mark the depending module as incompatible.
- AstronomersVisualPack depends on Scatterer
- Scatterer conflicts with itself (see KSP-CKAN/NetKAN#4541 and #1870)
Scatterer's self-conflict relationship trips this check:
https://github.com/KSP-CKAN/CKAN/blob/2119b5802494a8e1fa7f9250dfe834a27da64fdf/Core/Registry/AvailableModule.cs#L123-L133
... but only when it's installed, via this block:
https://github.com/KSP-CKAN/CKAN/blob/2119b5802494a8e1fa7f9250dfe834a27da64fdf/Core/Registry/AvailableModule.cs#L99-L102
... passed from here: …
> Ignore dependency self conflicts

- Cmdline/Action/AuthToken.cs
- Cmdline/Action/List.cs
- Cmdline/Action/Mark.cs
- Cmdline/CKAN-cmdline.csproj
- Cmdline/Main.cs
- Cmdline/Options.cs
- ConsoleUI/ModListHelpDialog.cs
- ConsoleUI/ModListScreen.cs
- ConsoleUI/Toolkit/Keys.cs
- ConsoleUI/Toolkit/Symbols.cs
- Core/ModuleInstaller.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/InstalledModule.cs
- Core/Registry/Registry.cs
- Core/Relationships/RelationshipResolver.cs
- GUI/GUIMod.cs
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainChangeset.cs
- GUI/MainModList.cs
- Tests/GUI/GH1866.cs
- Tests/GUI/GUIMod.cs
- Tests/GUI/MainModList.cs
Installing a module pulls in its dependencies automatically. If the user later uninstalls that module, they may wish to remove the dependencies as well, but there's no easy way to identify them.
Debian's APT package management system has a concept of "automatically installed packages," which handles this situation nicely:
> To install one package, it is often necessary to install several others (to fulfill its dependencies). For instance, if you wish to install the clanbomber package, you must also install the package libclanlib2. If you remove clanbomber again, you probably no longer need the libclanlib2 package; aptitude will attempt to detect this and automatically remove the libclanlib2 package.
> 
> It works like this: when you install a package, aptitude will automatically install …
> Auto-uninstall auto-installed modules

- Core/KSP.cs
If you run a `ckan scan` command and Ctrl-C out of it at just the right time (towards the end, I had to add a `WriteLine` to get the timing correct), you can end up with a truncated `registry.json` file:
```
-rw-r--r-- 1 16933954 May  7 17:13  registry.json
-rw-r--r-- 1  9207808 May  7 17:11  registry.json_BROKEN
```
Anything you try to do after this will throw exceptions and generally not work.
`RegistryManager.Save` is transaction-aware:
https://github.com/KSP-CKAN/CKAN/blob/f2209e215a7e54409b0c2a6f2a2968d347961a9c/Core/Registry/RegistryManager.cs#L413-L455
... but `KSP.ScanGameData` calls it *outside* of its transaction:
https://github.com/KSP-CKAN/CKAN/blob/f2209e215a7e54409b0c2a6f2a2968d347961a9c/Core/KSP.cs#L409-L445
When a `TxFileManager` is used outside of a transaction, it falls …
> Save registry inside of scan transaction

- Cmdline/Action/Replace.cs
- Cmdline/Action/Upgrade.cs
- ConsoleUI/InstallScreen.cs
- ConsoleUI/ModInfoScreen.cs
- Core/ModuleInstaller.cs
- Core/Net/IDownloader.cs
- Core/Net/Net.cs
- Core/Net/NetAsyncDownloader.cs
- Core/Net/NetAsyncModulesDownloader.cs
- Core/Net/Repo.cs
- GUI/MainInstall.cs
- GUI/MainModInfo.cs
- Tests/Core/Net/NetAsyncModulesDownloader.cs
- Tests/GUI/GH1866.cs
If you select many uncached mods to install, they're all downloaded to temp files in your temp folder before being moved to the CKAN download cache. The temp files remain until *all* of the downloads fail or finish. This consumes disk space in the temp folder for longer than strictly necessary and delays the insertion of individual files into the cache.
`NetAsyncModulesDownloader` and `NetAsyncDownloader` communicate via a callback function that's only called at the end of the download process. So `NetAsyncModulesDownloader` waits for all downloads to complete before ever calling `cache.Store`.
- `NetAsyncDownloader.onCompleted ` is replaced by `onOneCompleted`, which is called once per individual download, when that download fails or finishes
- …
> Cache downloads individually upon completion

- GUI/MainModList.cs
Loose end from #2753; "AD" mods have the auto-detected checkbox enabled. This doesn't make sense because CKAN didn't install them and can't uninstall them.
Now the disabled "-" state of the auto-installed column is used instead for "AD" mods.
> Hide auto-installed checkbox for auto-detected mods

- GUI/MainModInfo.Designer.cs
The metadata is the only tab of the mod info panel that doesn't display scrollbars if its content is to big.
On low-res / small monitors or if you don't want to shrink your modlist / upper mod info panel some mod infos may be out of screen.
Make the tab scrollable, horizontally and vertically.
This also fixes the problem that links are mostly unreadable. Now they are all oneliners and if they are longer than the panel is wide, a scrollbar appears.
> Add scrollbars to metadata tab

- Core/KSP.cs
- Core/Registry/RegistryManager.cs
- GUI/MainRepo.cs
If you install a DLL manually while GUI is running, clicking Refresh will not mark that mod as AD.
As of #2682, we avoid refreshing the mod list if the repos have not changed.
The DLC/DLL scanning functions are fire-and-forget; they don't tell us whether their data has changed. So either we refresh everything every time, or we miss scan changes. Currently it's the latter.
- Now `KSP.ScanGameData` returns a boolean, true if changed and false if same
- Now we call `ScanGameData` from the repo update's background worker, with a status message describing its function
- Now the background worker reports `RepoUpdateResult.Updated` if the scan found changes but the repos were the same, which will cause a mod list update
Fixes #2761.
> Update GUI modlist if scan detects changes

- Core/ModuleInstaller.cs
- Tests/Core/ModuleInstaller.cs
CmdLine's `ckan install identifier=version` syntax is broken:
```
$ ../CKAN/_build/ckan install Astrogator=v0.9.0
Continue? [Y/n]
```
(The list of modules to install is missing.)
This also affects the `ckan install -c localfile.ckan` syntax:
```
$ ../CKAN/_build/ckan install -c KerbalAircraftExpansion-3-2.8.0.1.ckan
Continue? [Y/n]
```
Which also breaks pull request validation:
https://ci.ksp-ckan.space/job/NetKAN/8294/console
```
Running ckan install -c built/KerbalAircraftExpansion-3-2.8.0.1.ckan
Updating registry
Committing filesystem changes
Rescanning GameData
Done!
```
(Nothing gets installed.)
Noticed while checking validation of KSP-CKAN/NetKAN#7194.
This line from #2753 assumed that the list of strings passed to …
> Don't assume string params to Install are identifiers

- Core/Net/Net.cs
If you use a metanetkan URL in this format:
- https://github.com/ChrisAdderley/NearFutureConstruction/raw/master/CKAN/NearFutureConstruction.netkan
Netkan will say this:
```
297 [1] WARN CKAN.Net (null) - Remote non-raw GitHub URL is in an unknown format, using as is.
```
This warning is incorrect. That URL **is** in raw format; that's what the "raw" segment means.
Noticed while reviewing KSP-CKAN/NetKAN#7204.
Now when the third segment is "raw/", that warning is replaced with a `--verbose` level message:
```
275 [1] INFO CKAN.Net (null) - Remote GitHub URL is in raw format, using as is.
```
> Don't warn that a raw URL is non-raw

- Core/CKAN-core.csproj
- Core/DLC/BreakingGroundDlcDetector.cs
- Core/DLC/MakingHistoryDlcDetector.cs
- Core/DLC/StandardDlcDetectorBase.cs
- Core/Registry/RegistryManager.cs
(Probably) Fixes #2765
Refactors the common logic of `MakingHistoryDlcDetector` into a `StandardDlcDetectorBase` and creates a new `BreakingGroundDlcDetector`.
Quoting from the documentation comment:
> Base class for DLC Detectors that follow standard conventions.
>
> "Standard conventions" is defined as detecting installation by the presence of directory with the name `IdentifierBaseName` in the `[GameData]/SquadExpansion` directory, detecting version by parsing a version line in a `readme.txt` file in the same directory, and having an identifier of `IdentifierBaseName-DLC`.
Assuming Breaking Ground in fact does follow these conventions then this should be all that's required to support it. This can probably be merged after Breaking Ground is released and we confirm that it does follow …
> Detect Breaking Ground DLC

- Core/Relationships/RelationshipResolver.cs
- GUI/Main.cs
If you try to select both RealismOverhaul and KerbalJointReinforcementNext to be installed, this exception is thrown:
```
CKAN.DependencyNotSatisfiedKraken: Exception of type 'CKAN.DependencyNotSatisfiedKraken' was thrown.
at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
at CKAN.RelationshipResolver..ctor(IEnumerable`1 modulesToInstall, IEnumerable`1 modulesToRemove, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
at …
```
> Don't throw exceptions for dependency conflicts

- .gitignore
CKAN's .gitignore file currently ignores two directories that have files committed in them:
```
bin
├── changes-since-last-release.pl
├── ckan-build-info.py
├── ckan-build.py
├── ckan_github_utils.py
├── ckan-release-maker.py
├── ckan-release-promoter.py
├── ckan-validate.py
├── close-old-support-tickets.pl
├── outdated_metadata.pl
└── requirements.txt
Screenshots
├── ckan-main-1.22.1.png
└── KSP1.18.0.png
```
`bin` is caught by the attempt to ignore Bin folders created by the compiler. Now we re-include the root-level bin folder after that, since it contains scripts rather than compiled C# code.
`Screenshots` just doesn't need to be in there. Now it's removed.
> Unignore version controlled folders

- Core/KSPManager.cs
- Core/Registry/Registry.cs
- Core/Types/CkanModule.cs
- Core/Win32Registry.cs
- Netkan/Transformers/EpochTransformer.cs
- Tests/Core/FakeWin32Registry.cs
- Tests/Core/KSPManager.cs
- Tests/Core/Net/Net.cs
- Tests/NetKAN/MainClass.cs
If your auto start instance is not valid and you run `ckan compare 1.2.3 4.5.6`, you get an extra warning message in addition to the expected output:
```
342 [1] WARN CKAN.KSPManager (null) - Auto-start instance was invalid: Exception of type 'CKAN.InvalidKSPInstanceKraken' was thrown.
"1.2.3" is lower than "4.5.6".
```
This isn't useful because we're not trying to do anything with auto start instances, we're just comparing version strings.
The same message is printed by many of the tests.
When we instantiate a `KSPManager`, its constructor calls `LoadInstancesFromRegistry`, which sets `AutoStartInstance`:
https://github.com/KSP-CKAN/CKAN/blob/00211bd8f288b5a2ea8054f953b184d632640c58/Core/KSPManager.cs#L422-L430
However, the value passed is what `AutoStartInstance` would already return! …
> Suppress autostart warning

- Tests/Core/KSPManager.cs
Running `.\build.ps1 test` on Windows:
```
1) Error : Tests.Core.KSPManagerTests.CloneInstance_ToNotEmptyFolder_ThrowsIOException
System.IO.IOException : The process cannot access the file 'shouldntbehere.txt' because it is being used by another process.
at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
at Tests.Core.KSPManagerTests.CloneInstance_ToNotEmptyFolder_ThrowsIOException() in C:\Users\Paul\github\CKAN\Tests\Core\KSPManager.cs:line 144
2) Error : Tests.Core.KSPManagerTests.FakeInstance_InNotEmptyFolder_ThrowsBadInstallLocationKraken
System.IO.IOException : The process cannot …
```
> Fix fake/clone tests on Windows

- Tests/Core/Cache.cs
If your Windows computer's locale is non-English, this test will fail:
```
1) Failed : Tests.Core.Cache.ZipValid_ContainsFilenameWithBadChars_NoException
Expected string length 26 but was 27. Strings differ at index 7.
Expected: "Illegales Zeichen im Pfad."
But was:  "Illegal characters in path."
------------------^
bei Tests.Core.Cache.ZipValid_ContainsFilenameWithBadChars_NoException() in C:\path\to\ckan-git\Tests\Core\Cache.cs:Zeile 195.
```
(I was able to reproduce this on an English computer by installing the German language pack for .NET and setting `Thread.CurrentThread.CurrentUICulture = new CultureInfo("de-DE");` within the test.)
That error message is localized. It will appear in whatever language is selected in `Thread.CurrentThread.CurrentUICulture`.
Now we set …
> Fix ZipValid test on non-English Windows systems

- CKAN.schema
- Core/Types/CkanModule.cs
- Netkan/CKAN-netkan.csproj
- Netkan/Services/IModuleService.cs
- Netkan/Services/ModuleService.cs
- Netkan/Transformers/LocalizationsTransformer.cs
- Netkan/Transformers/NetkanTransformer.cs
- Netkan/Transformers/PropertySortTransformer.cs
- Spec.md
#2113 suggested filtering mods by language. To achieve that, we would need to acquire metadata tracking modules' translations. That would be pretty tedious to do manually.
Now Netkan will examine the .cfg files in each download to see if they have translation data using some fancy regular expressions. If any translations are found, their locale names will be added to the module's `localizations` property. This is a list of strings that flows through to the `CkanModules.localizations` property in the application and could be used to implement displays and filters in the future. No UI changes are made yet.
I'm mainly seeking feedback on this at this point. Did I miss anything that would prevent this from working? Would we need additional data to implement filters?
> Extract locales from downloads

- Netkan/Transformers/LocalizationsTransformer.cs
- Locale configs with comments aren't always parsed correctly, see #2782 for examples
- Locale strings with capital letters aren't parsed correctly, again see #2782
- If the `localizations` property is set in the netkan (none are yet), we still parse all the cfg files but then throw away the result
- Now we make sure that between the beginning of the line and the locale descriptor is only whitespace (since `//` isn't whitespace, comments are ignored)
- Now we allow capital letters in locale strings
- Now if the `localizations` property is already set, we don't parse anything and just move on to the next transformer
Fixes #2782.
> Skip comments and allow capital letters in locale extractor

- Netkan/Transformers/LocalizationsTransformer.cs
Right now some mods that should be re-indexing with localizations metadata are failing in the bot.
```
$ wget -O - http://status.ksp-ckan.space/status/netkan.json | python -m json.tool | grep 'Schema validation failed' -A 3 -B 3
...
"AntennaHelper": {
"failed": true,
"last_checked": "2019-06-15T00:02:53Z",
"last_error": "Schema validation failed",
"last_indexed": "2018-10-30T20:02:41Z",
"last_inflated": "2019-06-15T00:02:56Z"
},
--
"BDArmoryContinued": {
"failed": true,
"last_checked": "2019-06-15T00:05:55Z",
"last_error": "Schema validation failed",
"last_indexed": "2019-05-12T12:04:54Z",
"last_inflated": "2019-06-15T00:05:59Z"
},
--
"CommunityPartsTitles": {
"failed": true,
"last_checked": "2019-06-15T00:10:45Z",
"last_error": "Schema validation failed",
"last_indexed": …
```
> Only list each locale once

- Netkan/Transformers/LocalizationsTransformer.cs
The localization metadata has been rolling in, and it's mostly good (https://github.com/KSP-CKAN/CKAN-meta/compare/3df71eeb09...331d41132b)! I've found two modules with bad metadata so far:
https://github.com/KSP-CKAN/CKAN-meta/blob/331d41132bd87ba029927468475c1c1eaf76b087/Kerbalism/Kerbalism-3.0.2.ckan
```json
"localizations": [
"de-de",
"ru",
"pt-br",
"en-us",
"version",
"VERSION"
],
```
https://github.com/KSP-CKAN/CKAN-meta/blob/331d41132bd87ba029927468475c1c1eaf76b087/NehemiahEngineeringOrbitalScience/NehemiahEngineeringOrbitalScience-0.8.0.ckan
```json
"localizations": [
"de-de",
"en-us",
"es-es",
"model",
"MODULE"
],
```
These modules have cfg files with the word `Localization` as part of a string value rather than as a keyword, and the next BLOCK{} after that is interpreted as a …
> Only react to Localization keyword at start of line

- GUI/CKAN-GUI.csproj
- GUI/Localization/en-US/AboutDialog.en-US.resx
- GUI/Localization/en-US/MainModInfo.en-US.resx
- GUI/MainModInfo.resx
CKAN uses the word "license" as a noun twice in the GUI:
Today I learned that this is a US-ism; [in the UK and Australia, "license" is a verb and "licence" is a noun](https://grammarist.com/spelling/licence-license/).
*Noah Webster urges you to deal with it*
Now the default spelling in our `.resx` files is changed to licence, and `.en-US.resx` files are added to override it to license in the en_US locale.
> Fix UK spelling of licence

- GUI/MainInstall.cs
If you install a module from a .ckan file, its dependencies will be marked as manually installed instead of auto-installed (see #2753).
When installing from the mod list, we use `ComputeChangeSetFromModList` to calculate the change set to display, but `ComputeUserChangeSet` generates the change set to install, so `ModuleInstaller.InstallList` can determine which modules were selected by the user:
https://github.com/KSP-CKAN/CKAN/blob/91c5bf4109ab6dee87f6a6647e9cec580cea5918/GUI/Main.cs#L707
https://github.com/KSP-CKAN/CKAN/blob/74ff9af074e8ea129cd36786a7d8fc7f3749bc63/GUI/MainChangeset.cs#L140-L145
However, when installing from a .ckan file, we pass `ComputeChangeSetFromModList`'s change set as if it was selected by the user:
https://github.com/KSP-CKAN/CKAN/blob/74ff9af074e8ea129cd36786a7 …
> Mark auto-install correctly when installing from .ckan file

- GUI/Localization/de-DE/Main.de-DE.resx
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/Main.resx
Problem
---
Currently you can only report issues in the NetKAN repository in the `Help` menu.
If someone wants to report an error with the client, he either does this in the NetKAN repo, which isn't really the place where those issues should be,
or has to find his way over to the CKAN repo, but there's no hint anywhere to do so.
Solution
---
Create a new menu option, and relabel the existing one:
`Report an issue with the CKAN client` and `Report an issue with mod metadata`, where each one leads to the right repository.
Fixes #2801
> Add menu option to report issues in the CKAN repo

- Netkan/Transformers/LocalizationsTransformer.cs
[A few mods do this](https://github.com/TiktaalikDreaming/KOOSE/blob/master/Localization/dictionary.cfg):
```json
zh-ch
{}
ja
{}
```
Currently we "give them credit" for that by including such locales in their `localizations` property. But if a user installed such a module expecting it to be localized into one of those languages, they'd be rightfully disappointed.
Now we make sure there's at least one "=" between the "{" and "}". This will filter out locales that don't set any strings.
> Ignore locales with no strings

- Netkan/Validators/MatchesKnownGameVersionsValidator.cs
After #2788, lots of modules report this error:
[![image](https://user-images.githubusercontent.com/1559108/60145436-a110ec80-978b-11e9-8e04-5f312de45292.png)](http://status.ksp-ckan.space/)
We use `KspBuildMap` to generate the list of known game versions. This class loads the list of known game version from the Win32Registry. If the list isn't in the registry, then it will try downloading the remote build map from:
- https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json
In the regular client, a forced refresh call occurs here when updating the registry, via that weird code-obfuscating `Autofac` stuff that some people like for some reason:
https://github.com/KSP-CKAN/CKAN/blob/9d8c3ed13d464ad009904ab607be39c160db4714/Core/Net/Repo.cs#L100-L103
There's currently no …
> Refresh builds.json when validating netkans

- Netkan/Transformers/HttpTransformer.cs
Currently some modules are failing with this error:
```
3470 [1] FATAL CKAN.NetKAN.Program (null) - Object must implement IConvertible.
3471 [1] FATAL CKAN.NetKAN.Program (null) -   at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) <0x7f7b13af7110 + 0x004d1> in <6649516e5b3542319fb262b421af0adb>:0 
at Newtonsoft.Json.Linq.Extensions.Convert[T,U] (T token) [0x000f7] in <840a99bb54b8423b94f0716f18cfa664>:0 
at Newtonsoft.Json.Linq.Extensions.Value[T,U] (System.Collections.Generic.IEnumerable`1[T] value) [0x0000b] in <840a99bb54b8423b94f0716f18cfa664>:0 
at Newtonsoft.Json.Linq.Extensions.Value[U] (System.Collections.Generic.IEnumerable`1[T] value) [0x00000] in <840a99bb54b8423b94f0716f18cfa664>:0 
at …
```
> Fix http kref validation

- Core/GameVersionProviders/IKspBuildMap.cs
- Core/GameVersionProviders/KspBuildMap.cs
- Netkan/Validators/MatchesKnownGameVersionsValidator.cs
As of #2808, we now load the remote build map every time netkan.exe runs in order to validate that generated metadata matches at least one known game version. This means that per bot pass, we download https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json 1800 times. This is much more frequent than necessary considering that weeks or months typically pass between KSP versions.
Now `KspBuildMap` is rearranged to allow client code to choose the Remote, Cached, or Embedded build map. The default is the same as before: load Cached with Remote and then Embedded as fallbacks if nothing special is done, otherwise load Remote with Cached and then Embedded as fallbacks if `Refresh` is called. However, now there's also the option to **only** load the Embedded build map, which is …
> Use embedded buildmap in Netkan

- GUI/Localization/de-DE/MainModInfo.de-DE.resx
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainModInfo.Designer.cs
- GUI/MainModInfo.cs
- GUI/MainModInfo.resx
- GUI/Properties/Resources.Designer.cs
- GUI/Properties/Resources.de-DE.resx
- GUI/Properties/Resources.resx
This pull request satisfies three minor GUI requests that came in recently.
Now if a module has a description (most don't), it will have a vertical scroll bar in case it's longer than the available space:
Fixes #2795.
Now the status bar will show the game instance name and version:
German translation: Spielinstanz: whatever (KSP whatever)
Fixes #2807.
Now the Download button has an Open ZIP button next to it:
It becomes enabled when the module is cached:
Clicking it opens the ZIP file from the cache in your OS's archive browser (in this screenshot, whatever GNOME Shell uses):
German translation: ZIP öffnen
Fixes #2800.
> Open ZIP button, instance name in status bar, description scroll bar

- Cmdline/Action/Compare.cs
- Cmdline/Action/KSP.cs
- Cmdline/Options.cs
- Core/DLC/BreakingGroundDlcDetector.cs
- Core/DLC/IDlcDetector.cs
- Core/DLC/MakingHistoryDlcDetector.cs
- Core/DLC/StandardDlcDetectorBase.cs
- Core/KSP.cs
- Core/KSPManager.cs
- Core/Types/Kraken.cs
- Core/Utilities.cs
- Core/Versioning/KspVersion.cs
- GUI/CloneFakeKspDialog.Designer.cs
- GUI/CloneFakeKspDialog.cs
- GUI/CloneFakeKspDialog.resx
- GUI/Localization/de-DE/CloneFakeKspDialog.de-DE.resx
- GUI/Properties/Resources.Designer.cs
- GUI/Properties/Resources.de-DE.resx
- GUI/Properties/Resources.resx
- Tests/Core/KSPManager.cs
Got a bit bigger than I thought.
(And it's getting bigger and bigger)
Changes
-----
Important stuff first:
Console command for faking changed!
It is now `ckan ksp fake <name> <path> <version> [--MakingHistory <version>] [--BreakingGround <version>]`
instead of previous `ckan ksp fake <name> <path> <version> [MakingHistoryVersion]`.
I think this is more future-proof.
I am going to try my luck adjusting KSP-CKAN/xKAN-meta_testing.
**`IDlcDetector`**:
I added `string InstallPath()`, it returns the install path relative to the GameDir, that means for example `"GameData/SquadExpansion/Serenity"`.
Depending on how [this idea of mine](https://github.com/KSP-CKAN/CKAN/issues/2770#issuecomment-498413897) will be implemented (if at all), we might restructure the whole thing again. But I think this …
> Support BreakingGround-DLC in instance faking

- Netkan/CKAN-netkan.csproj
The embedded schema is given a weird name when compiling on Windows:
This makes `netkan.exe` fail to run.
Now we set the `LogicalName` to be what it already is on Mono, `CKAN.NetKAN.CKAN.schema`.
> Fix Netkan schema resource name on Windows

- Netkan/Processors/Inflator.cs
- Netkan/Transformers/LocalizationsTransformer.cs
This netkan hangs for a long time, maybe indefinitely:
```bash
mono netkan.exe NetKAN/PolishTranslation.netkan
```
This is inhibiting the functioning of the bot.
I think we're experiencing [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html). The regex for parsing a `Localization` block has several instances of the same character potentially being matchable by multiple consecutive pieces of the regex.
A `{` could match the first or second part of this:
```
.*?{
```
A letter could match the first or second part of this:
```
.*?([-a-zA-Z]+
```
And so on. This results in a lot of retries when it reaches the end of the string without a match. In the case of PolishTranslation, I think the issue is simply that its `Localization` blocks are very, very long, so the …
> Fix Netkan localization parser performance

- GUI/MainModInfo.cs
It was noted in #2796 that line breaks in module descriptions work on Mono but not Windows:
Mono uses "\n" to split lines because it runs on Unix.
Windows uses "\r\n" to split lines because CP/M did in 1974.
The `TextBox` implementations carry this difference through to 2019.
Now we will replace both `\r\n` and `\n` with `Environment.Newline`, which contains the string used by the current platform to break lines. This way authors may include either `\r\n` or `\n` in descriptions and it will always display correctly.
Note that this is not a fix for #2796 because that issue also requests bold and italic.
> Support newlines in GUI description field

- Core/Types/GameComparator/StrictGameComparator.cs
- Netkan/Transformers/AvcTransformer.cs
The bot says Protractor doesn't match any game versions:
This module has an interesting .version file:
```json
"KSP_VERSION": {
"MAJOR": 1,
"MINOR": 0,
"PATCH": 2
},
"KSP_VERSION_MIN": {
"MAJOR": 1,
"MINOR": 0,
"PATCH": 0
},
"KSP_VERSION_MAX": {
"MAJOR": 1,
"MINOR": 0,
"PATCH": -1
}
```
That `-1` is supposed to mean unbounded, so all 1.0 versions are included.
[Netkan translates this into](https://github.com/KSP-CKAN/CKAN-meta/blob/aacf14a51a603764ddc2cfa4a90db1be7df81fbf/Protractor/Protractor-v2.5.1.ckan#L13-L14):
```json
"ksp_version_min": "1.0.0",
"ksp_version_max": "1.0",
```
Internally, CKAN models an undefined value as `-1`, and then blindly compares it to defined values here:
https://github.com/KSP-CKAN/CKAN/blob/cfa28939d68fc983bc77b1e2bfbbd5cf71590684/Core/Versioning/KspVersion.cs …
> Fix comparison of 1.0.0 to 1.0

- Netkan/CmdLineOptions.cs
- Netkan/Processors/Inflator.cs
- Netkan/Processors/QueueHandler.cs
- Netkan/Program.cs
https://github.com/KSP-CKAN/xKAN-meta_testing/pull/51#issuecomment-506614403
> Also, in theory NetKAN can consume a CKAN and output a validated CKAN. Maybe md5 before/after and we can catch when a CKAN is handcrafted (which we never want to do).
This would help to unify our pull request validation logic, as the CKAN-meta script could use `netkan.exe` for validation just as the NetKAN script does.
Now a new command format is supported:
```bash
mono netkan.exe --validate-ckan Astrogator/Astrogator-v0.9.2.ckan
```
This will load the indicated .ckan file and run Netkan's standard validators on it (see #2788). If there are any problems, the usual error will be printed and the process will exit with a failure code.
If the .ckan file is valid, it will be printed with standard pretty formatting …
> Netkan option to validate .ckan file

- Netkan/Transformers/ForcedVTransformer.cs
`x_netkan_force_v` prepends a `v` onto a module's version during inflation. This is helpful for when a mod author releases "v1.1" followed by "1.2", which would otherwise mess up CKAN's version sorting.
If a mod author freely switches between lowercase 'v' with capital 'V', we end up with almost as bad of a mess:
https://github.com/KSP-CKAN/CKAN-meta/tree/master/xScience
Now `x_netkan_force_v` removes a capital 'V' prefix if found. The above becomes `xScience-v5.17.ckan` as intended.
> Override V to v with x_netkan_force_v

- Netkan/Sources/Curse/CurseFile.cs
Curse-hosted modules aren't inflating:
This URL is a 404 as of some recent change to Curse or its API or something:
https://github.com/KSP-CKAN/CKAN/blob/5323e54cee3279e85ad199cc172f6488b8ae8cfd/Netkan/Sources/Curse/CurseFile.cs#L39
In #2189, this was briefly changed to:
https://github.com/KSP-CKAN/CKAN/blob/b643d129b242081fbfe3742bea0d802ffc61274f/Netkan/Sources/Curse/CurseFile.cs#L32
... which still works! But this was reverted during code review.
Now we use that `url + "/file"` formula again.
Fixes KSP-CKAN/NetKAN#7268. (I didn't think it was possible!)
> Fix Curse API download URLs

- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainModList.cs
If you open GUI and press ctrl-F, focus goes to the filter boxes. To get back to the mod list, you have to press tab **twelve times**, cycling through many other controls first. This is a detriment to keyboard usability.
While you're editing the filters, it's not easy to tell that the mod list doesn't have focus. There's a small blinking cursor in the text box, but meanwhile the mod list has its big active-looking row highlight. Then when you tab to the mod list, nothing about its appearance changes, so you can't tell that you've made it there. Other WinForms controls commonly gray out their selection highlight when inactive.
If you focus the mod list and press tab or shift-tab, it goes into this weird mode where you are tabbing through individual cells and the row highlight goes away. …
> Improve focus interactions of GUI filters and mod list

- Cmdline/Action/Install.cs
- GUI/MainDialogs.cs
- GUI/MainModList.cs
- Tests/GUI/MainModList.cs
If a module `provides` another module and then later we remove that property, installing a mod that depends on the provided mod can prompt you to make the same decision multiple times and raise exceptions like this:
```
Unhandled Exception: System.ArgumentException: Already contains module:TextureReplacerReplaced
at CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
at CKAN.RelationshipResolver..ctor(IEnumerable`1 modulesToInstall, IEnumerable`1 modulesToRemove, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
at CKAN.RelationshipResolver..ctor(IEnumerable`1 modulesToInstall, IEnumerable`1 modulesToRemove, RelationshipResolverOptions options, …
```
> Fix issues when `provides` is removed

- Core/ModuleInstaller.cs
- GUI/GUIMod.cs
- GUI/Main.cs
- GUI/MainAllModVersions.Designer.cs
- GUI/MainAllModVersions.cs
- GUI/MainChangeset.cs
- GUI/MainInstall.cs
- GUI/MainModInfo.cs
- GUI/MainModList.cs
- GUI/MainRecommendations.cs
- GUI/ModChange.cs
- GUI/Properties/Resources.de-DE.resx
- GUI/Properties/Resources.resx
- Tests/GUI/GH1866.cs
Originally, each row in the GUI mod list only allowed the user to install one version of the corresponding module: the most recent version compatible with the user's game version. Installing incompatible modules was completely impossible. Change sets could only handle installing the latest compatible version, because `ModChange` holds a reference to `GUIMod`, which represents **all** versions of a module rather than a particular version.
Later, #2364 added a double click option to compatible versions in the mod info version list to install older versions. To get around the version limitations of change sets, it prompted the user for confirmation and then jumped to the progress screen of the installation flow, skipping the change set confirmation and other early steps. In keeping with the …
> Queue module version changes in change set

- GUI/GUIMod.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
If you install mods in current master HEAD GUI, the change set is not cleared after installation. You can try applying the same change set again if you want to see some errors. If you toggle another checkbox instead, the change set will fix itself and show the correct changes.
First, as of #2821, `GUIMod`'s constructor for installed modules was setting `SelectedMod`. This is a public property, and setting it causes its change-reaction code to run, which can trigger changes in the grid and updates of the change set. During post-install, this happens via `UpdateModsList`, but it happens before the mod list is fully updated, so there is interaction between the "old" and "new" copies of a mod's `GUIMod` instances. This has the effect of regenerating the change set based on the old mod list. …
> Fix clearing of changeset after install

- packages.config
With the new release of Visual Studio 2019 it broke the ability to build the project with `ToolsVersion="15.0"` on Windows. This changes the building process to use Cake 0.34.1 so it can build again.
This change will print the following error on building:
```
The assembly 'Cake.SemVer, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.33.0.
```
Because the fix is released in 0.34.0, we need to ignore that warning.
> Fix for building with VS 2019

- GUI/Localization/de-DE/ManageKSPInstances.de-DE.resx
- GUI/Main.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
- GUI/ManageKSPInstances.resx
- GUI/ManageKspInstances.Designer.cs
- GUI/ManageKspInstances.cs
- GUI/Properties/Resources.Designer.cs
- GUI/Properties/Resources.de-DE.resx
- GUI/Properties/Resources.resx
- GUI/TabController.cs
Problem
-----
The current behavior of `ManageKspInstances` is really weird.
* As soon as you open the dialog, the current `AutostartInstance` is reset to null.
* It saves that instance as default/autostart, that is selected when you click the `Select` button, and not the one where you activate the checkbox, against all intuition.
* What this means is that you can never ever select one instance as your default one, but use a different one for now. You'll always end up setting either the wrong one or none at all as autostart.
* As a result the two checkboxes in `CloneFakeKspDialog` don't work at all.
Solution
------
* Don't call `Instance.Manager.ClearAutoStart()` before opening the instance management dialog.
* Update autostart instance on checkbox click, not on button click.
* Update the …
> Fix 'ManageKspInstances' dialog logic

- Netkan/Model/Metadata.cs
- Netkan/Processors/QueueHandler.cs
- Spec.md
In https://github.com/KSP-CKAN/CKAN/issues/2789#issuecomment-513427895, @techman83 pointed out that the SQS queue code in #2798 does not handle the `x_netkan_staging_reason` property from KSP-CKAN/NetKAN-bot#88.
Now the `x_netkan_staging_reason` property flows through into a `Metadata.StagingReason` property, which will be passed to a new message attribute if set:
```
Attr StagingReason: The reason that staging is enabled for this module (if it is enabled), to help pull request reviewers determine whether to merge
```
Notes:
- If the module is staged but `x_netkan_staging_reason` is not set, the attribute will not be set
- If the module is **not** staged but `x_netkan_staging_reason` **is** set, the attribute will **not** be set
So the downstream code should be prepared to handle a staged …
> Send staging reason to SQS queue

- .travis.yml
- bin/build_netkan_container.sh
- build.cake
#2838 is setting up build triggers to rebuild an inflator container for #2789. This pull request targets that PR's branch with a suggestion for changing it.
Currently it:
- Relies on a bash script
- Uses the `_build/repack/Release` folder as its working folder
- Hard-codes paths that are defined as variables in other places, meaning extra maintenance if those ever change
Now the bash script is replaced with a new task in the `build.cake` file, which:
- Uses the standard variables to get the path to `netkan.exe` and `_build`
- Works out of `_build/docker/inflator`
- Might work on systems without bash, depending on how portable `Cake.Docker` is
- Otherwise does the same things the bash script did
The Travis config is updated to rebuild the container with `./build docker-inflator`.
This way …
> Replace bash script with Cake.Docker task

- .travis.yml
- Dockerfile.netkan
- bin/build_netkan_container.sh
This is in support of #2789, building and pushing the NetKAN Inflator container to Docker Hub when changes are pushed to master, keeping our container up to date.
A future PR will contain the service redeployment as well, but that requires a few more things to be finished off first and can be easily added.
> Add Dockerfile + Deployment for NetKAN Inflator

- build.cake
#2838 added a build process to rebuild and push a Docker inflator container, but it failed:
https://travis-ci.org/KSP-CKAN/CKAN/jobs/569174846#L4638-L4642
```
========================================
docker-inflator
========================================
unable to prepare context: the Dockerfile (/home/travis/build/KSP-CKAN/CKAN/Dockerfile.netkan) must be within the build context
An error occurred when executing task 'docker-inflator'.
```
Prior to docker/cli#886, the Dockerfile specified by the `-f` parameter had to be in the build directory for... *some* reason.
That requirement was removed in Docker 18.03.0-ce. Travis has 17.09.0-ce. I have 18.09.7. So when I tested #2839 locally, it worked fine, then failed when pushed to master.
Now we copy `Dockerfile.netkan` into …
> Put Dockerfile.netkan in build context

- .travis.yml
- build.cake
- rpm/Makefile
- rpm/ckan.spec
We generate .deb files as of #2187, but users of Linux distributions that aren't Debian-derived have to use the plain `ckan.exe` file. This means they miss out on:
- Having ckan in the system `$PATH`
- Having a ckan icon in the system app menus
- An out of date man page
- Falling back to ConsoleUI if `$DISPLAY` isn't defined
Some users may even assume that the lack of an .rpm file means they can't use CKAN, even though they can.
Now we also generate .rpm files, so Fedora users can enjoy the above benefits. This is done with a simple `Makefile` and a .spec file, sharing a few files with the .deb package. The build system is updated to include the .rpm file as a release asset.
To try it via the command line:
```sh
./build rpm
```
Fixes #2748.
> Generate RPM packages

- .travis.yml
The NetCore builds are failing:
https://api.travis-ci.org/v3/job/571858879/log.txt
```
[0K$ sh -e /etc/init.d/xvfb start
sh: 0: Can't open /etc/init.d/xvfb
travis_time:end:0d500080:start=1565794793416049556,finish=1565794793421102477,duration=5052921
[0K[31;1mThe command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .[0m
Your build has been stopped.
```
The Travis syntax for starting xvfb is different in trusty vs xenial; now it's a proper service rather than a command that we have to run ourselves. Apparently Travis is migrating the default build environment from trusty to xenial, but they're doing it "gradually":
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
> Since Ubuntu 14.04 reaches End of Life on April 30th, 2019, we’ll be gradually …
> Switch to new Travis xvfb syntax

- debian/copyright
As discussed under #2851, we aren't aware of any standard tool that parses the `copyright` file from inside a .deb package. But the CKAN metadata specification references the list of well-known license names from the Debian machine-readable license spec (https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/), so it seems like good citizenship to follow the upstream spec ourselves.
Fixes #2851.
> Use Debian machine-readable copyright format

- GUI/Main.cs
1. Install `EnvironmentalVisualEnhancements-HR` (or any other module providing `EnvironmentalVisualEnhancements-Config` other than AVP)
2. Filter by mod names containing "astrono"
3. Check the box for Astronomers Visual Pack
4. An exception is thrown
When you try to install a mod that conflicts with one that's already installed, we highlight both of their rows red. This is done by setting the row's background and then calling `ModList.InvalidateRow` to force the GUI to obey that change immediately.
In this case, one of the rows is not visible due to the filter; the thrown exception indicates that `InvalidateRow` is being called for a row that isn't in the grid, and .NET doesn't like that.
In #2766 we specifically updated this code to cover hidden conflicts. How was this missed? My guess …
> Don't invalidate invisible rows

- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- GUI/MainModList.cs
If you install many mods (200+) and click the checkbox to queue up one more to install, GUI takes a while to respond. I observed about 4.5 seconds with 282 mods, and a user reports 10-15 seconds with 363 mods.
A few `Console.WriteLine` statements revealed the following upon clicking:
```
2019-08-27T00:36:28.1441350+00:00 UpdateChangeSetAndConflicts
2019-08-27T00:36:28.1441350+00:00 ComputeUserChangeSet
2019-08-27T00:36:29.2111960+00:00 ComputeUserChangeSet after FindRemovableAutoInstalled
2019-08-27T00:36:29.2131961+00:00 UpdateChangeSetAndConflicts after ComputeUserChangeSet
2019-08-27T00:36:29.2131961+00:00 ComputeChangeSetFromModList
2019-08-27T00:36:29.2141962+00:00 ComputeChangeSetFromModList before FindReverseDependencies
2019-08-27T00:36:29.2141962+00:00 ComputeChangeSetFromModList …
```
> Speed up autoremove search

- Core/Net/NetFileCache.cs
A user mentioned this exception with a "portable" install:
```
System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
at CKAN.NetFileCache.EnforceSizeLimit(Int64 bytes, Registry registry)
at CKAN.ModuleInstaller.EnforceCacheSizeLimit()
at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader, Boolean ConfirmPrompt)
at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1264-orion/&do …
> Find portable installs when enforcing cache limits

- rpm/ckan.spec
Our wiki instructions for installing on Fedora say to install `libcurl-devel` manually:
https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Fedora#libcurl
If this is needed, the RPM should handle it as a dependency. Now it will.
> Add libcurl dependency to RPM

- Netkan/Processors/QueueHandler.cs
If the queue inflator from #2798 encounters an error while inflating a netkan, an exception is thrown while trying to process the error:
```
544 [1] INFO CKAN.NetKAN.Processors.Inflator (null) - Using user-supplied cache at ckan_cache
1773837 [1] INFO CKAN.NetKAN.Processors.QueueHandler (null) - Inflating CustomDesignSpacesuits-Steampunk
1773840 [1] INFO CKAN.NetKAN.Validators.HasIdentifierValidator (null) - Validating that metadata contains an identifier
1773840 [1] INFO CKAN.NetKAN.Validators.KrefValidator (null) - Validating that metadata contains valid or null $kref
1773848 [1] INFO CKAN.NetKAN.Processors.Inflator (null) - Input successfully passed pre-validation
1774796 [1] INFO CKAN.NetKAN.Processors.QueueHandler (null) - Inflation failed, sending error: Ssl error:1000007d:SSL …
```
> Fix NRE on failed queue inflate

- Dockerfile.netkan
When testing the status page with the status data generated from DynamoDB, I noticed a bunch of errors complaining about `libcurl`.
This adds the dependency to the container.
> Add Missing libcurl Dependency for NetKAN

- GUI/GUIMod.cs
- GUI/MainModList.cs
In #2821 we added the ability to select a specific version of a module to install in GUI rather than only installing the latest compatible. As part of this, incompatible versions were allowed as well.
However, you could only install an incompatible version if at least one other version of the module was compatible. Modules with **no** compatible versions (let's call them "totally incompatible") could be selected but would not show up in the changeset and could not be installed.
Totally incompatible modules were excluded in two ways, in line with the old assumptions about installability:
- `MainModList.ComputeUserChangeSet` only checked modules for which `IsInstallable` is true (it's false for totally incompatible modules)
- `GUIMod.GetRequestedChanges` only allowed installing a new module …
> Allow totally incompatible modules in changeset

- Netkan/Processors/QueueHandler.cs
Small typo fix for Queue Batch deletes, noticed when investigating #2876
> Set 'MessageId' attribute for batch delete

- Core/Net/Net.cs
The NetKAN Inflator service fails from time to time at some mods with the error message
```
Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.
```
for GitHub hosted mods. It appears to happen in batches.
It must be this line that throws:
https://github.com/KSP-CKAN/CKAN/blob/05406ba478f63dc61e8c0155ca04755d19db0948/Netkan/Sources/Github/GithubApi.cs#L42-L46
So the answer the bot gets for the API call is not what it expects (a JSON array).
I suspect the answer it gets is a 403 status code telling that the bot is throttled by GitHub (see https://developer.github.com/v3/#rate-limiting).
However, I can't be sure, because errors that might be thrown during/after the download are hidden by the curl fallback mechanism.
.NETs …
> Fail on http status codes >=300 for cURL downloads

- Core/ModuleInstaller.cs
- Core/Net/Repo.cs
- Core/Types/ModuleInstallDescriptor.cs
- Netkan/Validators/InstallValidator.cs
If you install a module with an `install_to` that ends with a slash (`/`), you will receive the changed-metadata and reinstallation prompt every time you perform a non-redundant refresh (i.e., something has actually changed in CKAN-meta).
All such extant paths were normalized in KSP-CKAN/NetKAN#7419 and KSP-CKAN/CKAN-meta#1510, but now we will address the root causes.
1. The client downloads the non-normalized metadata from CKAN-meta:
| Available module | Installed module |
| --- | --- |
| `GameData/002_CommunityPartsTitles/Extras/` | (none) |
2. The user installs the module, and `ModuleInstaller` normalizes the `install_to` at installation, which affects the instance of the `CkanModule` stored in the registry:
| Available module | Installed module |
| --- | --- |
| …
> Normalize install paths

- Core/KSP.cs
- Core/KSPPathUtils.cs
- Core/Registry/RegistryManager.cs
- GUI/Main.cs
- GUI/MainModInfo.cs
- GUI/ManageKspInstances.cs
- Tests/Core/KSPPathUtils.cs
If you install KSP into the root folder of a Windows drive (for example a RAM drive) and add that instance to CKAN, installing modules throws an exception:
```
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "R:\ameData" konnte nicht gefunden werden.
bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
bei System.IO.Directory.EnumerateFileSystemEntries(String path)
bei CKAN.ModuleInstaller.Uninstall(String modName)
bei CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove, Boolean …
```
> Fixes for KSP in Windows drive root

- .travis.yml
- build.cake
Currently the Inflator's image is rebuilt after commits to master, but it still has to be redeployed manually. It would be quicker and more convenient to redeploy automatically.
Now @techman83's command to redeploy the Inflator is added after the image rebuild. It pulls the Docker image for the NetKAN-Infra project and uses it to run the `redeploy-service` command. Ideally we might do this without downloading the image, but there is no Cake package for ECS.
These environment variables should be set on Travis:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_DEFAULT_REGION`
> Redeploy Inflator after builds

- Cmdline/Action/Available.cs
- Cmdline/Action/Search.cs
- Cmdline/Action/Update.cs
- ConsoleUI/ModInfoScreen.cs
- Core/Registry/AvailableModule.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- GUI/GUIMod.cs
- GUI/MainModList.cs
- Tests/Core/Registry/Registry.cs
If a module's compatibility metadata changes after you install it, the GUI filters will always reflect the compatibility at time of install. For example, AblativeAirbrakes 0.3.0 only supported KSP 1.3.1 in March 2018, but now supports 1.2.2–1.7.3. If you installed it back then and kept it installed to the present, it would only be counted as compatible in GUI if you have 1.3.1 marked as compatible, but if you uninstall and/or reinstall, it will be considered compatible with all of 1.2.2–1.7.3.
`GUIMod` has multiple layered constructors; at the bottom level you can create a `GUIMod` if you only know the identifier, above that you can create a `GUIMod` from a `CkanModule`, and at the top you can create a `GUIMod` using an `InstalledModule`. Each layer calls the level below it and then fills …
> Use current metadata for installed module compatibility

- Core/Net/NetAsyncDownloader.cs
If a mod fails to download but it has a redistributable license, we silently fall back to its archive.org URL. Going by the messages printed, it looks like we're still downloading the original URL. While our file hashes ensure that only the proper ZIP will be installed, it would be nice to inform users when this happens.
Now we print a message when we start a fallback URL.
```
$ _build/ckan.exe install opentree --allow-incompatible
* OpenTree 2.5 (spacedock.info, 62.3 KiB)
* Module Manager 4.0.3 (cached)
Downloading "https://spacedock.info/mod/1623/OpenTree/download/2.5"
Failed to download "https://spacedock.info/mod/1623/OpenTree/download/2.5", trying fallback "https://archive.org/download/OpenTree-2.5/8BD18970-OpenTree-2.5.zip"
0 B/sec - downloading …
```
> Notify when falling back to archive.org URL

- macosx/CKAN
The release of macOS Catalina marked the death of 32-bit applications on Apple's platform.
This means, our GUI is no longer runnable on macOS due to Mono's WinForms implementation being 32-bit only: 
#2270 hardcoded `--arch=32` as argument for Mono, which now prevents users from using the CUI or TUI, if they want to.
Now there's a check for arguments in the launch script for macOS. If it's none or `gui`, the flag `--arch=32` is used for Mono, else it's `--arch=64`.
Mono's man page says the following, just FYI:
```
--arch=32, --arch=64
(Mac  OS  X only): Selects the bitness of the Mono binary used, if available.
If the binary used is already for the selected bitness, nothing changes.
If not, the execution switches to a binary with the selected bitness suffix installed side by side
(for …
```
> [macOS] Only run Mono in 32bit mode when the GUI is launched

- Core/KSPPathUtils.cs
- Core/Net/Repo.cs
@DasSkelett found two bugs while investigating #2895:
```
System.NullReferenceException: Object reference not set to an instance of an object
at CKAN.KSPPathUtils.NormalizePath (System.String path) [0x00001] in <192bdff602a04c98ba5c3e8f7028e03e>:0 
at CKAN.ModuleInstallDescriptor.Equals (System.Object other) [0x00017] in <192bdff602a04c98ba5c3e8f7028e03e>:0 
at CKAN.Repo.MetadataEquals (CKAN.CkanModule metadata, CKAN.CkanModule oldMetadata) [0x00057] in <192bdff602a04c98ba5c3e8f7028e03e>:0 
at CKAN.Repo.GetChangedInstalledModules (CKAN.Registry registry) [0x000ac] in <192bdff602a04c98ba5c3e8f7028e03e>:0 
at CKAN.Repo.UpdateAllRepositories (CKAN.RegistryManager registry_manager, CKAN.KSP ksp, CKAN.NetModuleCache cache, CKAN.IUser user) [0x00153] in …
```
> Fix minor errors in registry updating

- Netkan/Services/CachingHttpService.cs
These ZIP file format errors include temp file names, which are not useful for investigation because we can't access the temp files on the bot server:
They are also different every time. Ideally an error message should be consistent. As of KSP-CKAN/NetKAN-Infra#68, these messages will be sent to Discord when they change, so it will be more annoying to have them re-sent every time when the underlying error condition is the same.
Now the message will print the source URL instead of the temp file name:
`2755 [1] FATAL CKAN.NetKAN.Program (null) - https://github.com/formicant/TrimIndicator/releases/download/1.8.0.0/TrimIndicator-1.8.0.0.zip is not a valid ZIP file: Error in step EntryHeader for TrimIndicator/TrimIndicator.dll: Exception during test - 'Central header and local header file name …
> Replace temp filename with URL in netkan ZIP error

- GUI/CKAN-GUI.csproj
I'm trying out JetBrain's .NET IDE, "Idea" (thanks free student license ;) )
I couldn't run CKAN built with it, it always threw `MissingManifestResourceException` exceptions.
When Rider builds the GUI, it uses a different naming scheme for generated .resources file (.resources files are generated from .resx files before bundling them in the final assembly). To be exact, it appears that it uses `AssemblyName.ResourceFileNameBase` instead of `FullNamespace.ResourceFileNameBase` > `CKAN.Resources*.resources` instead of `CKAN.Properties.Resources*.resources`.
But not for all .resx/.resources files, only for those in the `CKAN-GUI/Properties/` directory, so `CKAN-GUI/Properties/Resources*.resx`.
However, this only affects runtime, not compile time.
When the first resource (ksp.png) should be …
> Force logical name for generated resources

- GUI/GUIMod.cs
- GUI/Main.cs
- GUI/MainAllModVersions.cs
- GUI/MainChangeset.cs
- GUI/MainInstall.cs
- GUI/MainModList.cs
- GUI/MainRecommendations.cs
- GUI/ManageKspInstances.cs
- GUI/ModChange.cs
When you upgrade a module, the change set says it is going to "upgrade [...] to" the version that's already installed. That's wrong.
The change set is a sequence of `ModChange` objects, each of which holds a reference to just one `CkanModule` object, which is always the one that's currently installed or will be installed. For upgrades, the target version is known inside `GUIMod` (it's `SelectedMod`), but is lost in the shuffle when the change set is generated until it's finally recalculated in `ModuleInstaller`. Since the `ModChange` representing an upgrade only has a reference to the version that's installed, that's what displays on screen.
Now `GUIMod.GetRequestedChanges` is replaced with `GUIMod.GetModChanges` which directly returns a sequence of `ModChange` objects. This allows …
> Show target version for upgrades in change set

- macosx/CKAN
#2272 is now a live issue. MacOSX Catalina users who download CKAN.dmg and double click CKAN.app will just get errors.
- CKAN's GUI uses WinForms.
- Mono only implemented WinForms in 32 bit mode for MacOSX (see mono/mono#6701).
- Apple decided to stop supporting 32 bit applications.
Now the launch script attempts to check the OS version; if 10.15 or later, if the user gives no command line parameters, instead of launching the GUI, it will launch `consoleui` in Terminal.
I don't have a Mac (this work is based on StackExchange answers), so we will need to find a volunteer Mac user to test this.
Test build:
- [CKAN.zip](https://github.com/KSP-CKAN/CKAN/files/3800610/CKAN.zip)
> Default to consoleui on MacOSX Catalina

- Netkan/Processors/Inflator.cs
KerbalAtomics-1-1.1.0.ckan used `any_of` with a `spec_version` of `v1.4`: https://github.com/KSP-CKAN/CKAN-meta/commit/967423fbfe09bdd1d8af4a42ea46fa716b2d92bb
This means this module loads in CKAN versions that don't support `any_of` and crashes them, see #2914.
This should have failed with this error:
> spec_version v1.26+ required for 'any_of'
But it got through.
When we inflate a module, we:
1. Load the netkan
2. Apply the netkan validators
3. Inflate
4. Apply the ckan validators
The `any_of` check is in the netkan validators, so any netkan with a `spec_version` below `v1.26` that tries to use `any_of` will be flagged.
But KerbalAtomics' relationships aren't in its netkan, they're in its *meta*netkan! Metanetkans are loaded and applied in the inflation stage, after netkan validators …
> Apply netkan validators to ckans

- CKAN.schema
- Core/Types/CkanModule.cs
- Netkan/Extensions/JObjectExtensions.cs
- Netkan/Transformers/InternalCkanTransformer.cs
- Netkan/Transformers/MetaNetkanTransformer.cs
- Spec.md
In KSP-CKAN/NetKAN-Infra#70 we are saving the `resources` object from mod metadata into the status page's JSON objects, and in KSP-CKAN/NetKAN-status#9 these will be rendered as links on the status page for more convenient investigation of inflation errors.
Currently most `$kref` variants populate a property in `resources` (e.g. `spacedock`, `repository`, `curse`), except for `netkan`, the kref source for metanetkans. This info would be nice to have as well since metanetkans have a big impact on how issues are investigated and fixed.
Astrogator defines its `resources` in an ["internal ckan"](https://github.com/KSP-CKAN/CKAN/blob/master/Netkan/Transformers/InternalCkanTransformer.cs), but all that appears in its .ckan file is "repository".
- …
> Merge resources and include metanetkan

- GUI/MainRecommendations.cs
Sometimes (inconsistently) on Mono, the headers of the recommendations list view do not appear. This prevents the user from resizing the columns to read longer cells.
Installing SmartTank:
Same as #2684. Mono seems to have a bug with these headers, but I hadn't noticed it with this listview up till now.
Now the headers are always shown using the `EndUpdate` workaround from #2685.
> Force redraw of recommendation listview headers on Mono

- Netkan/Extensions/JObjectExtensions.cs
- Netkan/Sources/Github/GithubRepo.cs
- Netkan/Transformers/CurseTransformer.cs
- Netkan/Transformers/GithubTransformer.cs
- Tests/NetKAN/Extensions/JObjectExtensionsTests.cs
The `author` property of a module can be a string or an array of strings. It's courteous to credit everyone who has maintained a mod over the years by listing them in an array.
It is somewhat common for a mod on GitHub to go out of maintenance and be adopted by a new maintainer on a fork of the original repo. When this happens, we switch the `$kref` to the new repo, and in order to preserve the full list of authors, we have to manually edit the `author` property to include them. It's better to rely on automatic data generation where possible, or at least to have the option.
Now if a repo is a fork-of-a-fork-of-a-fork-of..., we will traverse the parent repository chain all the way to the root and add all of the repository owners as co-authors. This will give a more accurate picture of who …
> Add owners of parent GitHub repos to authors

- Core/Net/Curl.cs
- Core/Net/Net.cs
- Core/Net/NetAsyncDownloader.cs
- Core/Types/Kraken.cs
- Netkan/Program.cs
- Netkan/Sources/Curse/CurseApi.cs
- Netkan/Sources/Github/GithubApi.cs
- Netkan/Sources/Spacedock/SpaceDockApi.cs
- Netkan/Transformers/CurseTransformer.cs
#2879 tried to get better insights why calls to GitHub by the bot were failing.
It was a partial success, we got the returned status code, but it also broke the custom error handling for SpaceDock for example.
First, I enabled the possibility to pass a header writeback function to CurlSharp. This allows catching the header of the response for logging purposes.
Passing it is optional.
Secondly, I created a new Kraken, `NativeAndCurlDownloadFailedKraken`. This one is used in both above mentioned download methods. It has some nice additions to a plain Kraken/Exception (like accessing the response (header and/or content) or the status code) and is more usable than `WebException`s.
Thirdly, I added some logging to the two download methods. If the debug-flag is set, the entire header and the …
> Restructure Net.Download and Net.DownloadText

- Netkan/Transformers/CurseTransformer.cs
- Netkan/Transformers/GithubTransformer.cs
- Netkan/Transformers/JenkinsTransformer.cs
- Netkan/Transformers/SpacedockTransformer.cs
Currently Netkan requests mod lists from remote servers twice whenever it inflates a mod hosted on GitHub or Jenkins. The `--debug` flag shows two entries like this (separated by lots of other messages):
```
1199 [1] DEBUG CKAN.Net (null) - About to download https://api.github.com/repos/messierr/SMHPContinued/releases?per_page=100
1383 [1] DEBUG CKAN.Net (null) - About to download https://api.github.com/repos/messierr/SMHPContinued/releases?per_page=100
```
This *might* be related to the "GitHub API rate limit exceeded." errors that we've been tracking for some time. (It might in fact be the exact and sole cause, since GitHub has every reason to think that rapid-fire accesses of the same URL from the same IP aren't legitimate.)
I misunderstood (or had an incomplete understanding of) how …
> Eliminate duplicate network calls in Netkan

- Tests/NetKAN/Sources/Curse/CurseApiTests.cs
See https://github.com/KSP-CKAN/NetKAN/issues/7446
Failing CurseForge tests are no longer caused by our code, but by CurseForges anti-bot actions.
Add `[Explicit]` tag to Curse's test class, so it no longer runs during a normal test run, but only if you specifically run them.
They haven't affected the PR validation, because Jenkins is set to ignore all network tests.
> Ignore CurseForge tests

- Core/Configuration/IConfiguration.cs
- Core/Configuration/JsonConfiguration.cs
- Core/Configuration/Win32RegistryConfiguration.cs
- Core/Utilities.cs
- GUI/GUIConfiguration.cs
- GUI/Localization/de-DE/SettingsDialog.de-DE.resx
- GUI/Main.cs
- GUI/SettingsDialog.Designer.cs
- GUI/SettingsDialog.cs
- GUI/SettingsDialog.resx
- Tests/Core/Configuration/FakeConfiguration.cs
Quite a few forum users asked for an option to change the language in CKAN after the release that introduced localization.
I added a combobox to the settings that allows changing the language.
The selected language is saved in the "Core's" configuration (so the JSON config and also the Win32Registry, although the second one is no longer in use, but it was easy and fast to do).
It is saved in the [RFC 5646](https://tools.ietf.org/html/rfc5646) / [RFC 4647](https://tools.ietf.org/html/rfc4647) format, the same that is used as appendix for the resource files (=`de-DE`,`en-US`,`en-GB`).
By default, the `Language` field in the config is `null`.
When the CKAN GUI starts, it checks the currently saved language. If it's null, it'll try to save whatever language CKAN was launched in the config.
If …
> Add language selection option to settings

- ConsoleUI/ModListScreen.cs
- ConsoleUI/Toolkit/ConsolePopupMenu.cs
- ConsoleUI/Toolkit/ConsoleTheme.cs
A MacOSX ConsoleUI user [left some feedback on Reddit](https://www.reddit.com/r/KerbalSpaceProgram/comments/dz8j9a/ckan_mac/f8708sm/) which suggests some possible confusion around the Upgrade All option:
> 7. Restarted, selected update all. No noticeable progress bar or indicator that anything is happening.
> 8. Left it for 5 minutes thinking it may have been a static background. Noticed the instructions to hit F9 to apply. Hit F9, and stuff started installing.
When I first read this, I thought he or she may have selected that menu option when there were no upgrades to install, which would close the menu and do nothing. The full text indicates that the problem was something else, but this is still a possible point of confusion worth addressing.
Now if you open the mod list menu while …
> Disable Upgrade All ConsoleUI menu option when nothing to upgrade

- build.ps1
Forgot about `built.ps1` in #2921...
This PR updates it for Windows too to keep it consistent.
> Bump nuget to 5.3.1 on Windows

- .travis.yml
The `#travis-builds` channel is really spammy, and probably all of us have muted it.
This PR removed the `after_success` hook, so only build failures will be send to the Discord webhook and into the channel.
> Don't send notification to Discord if build succeeds

- GUI/ErrorDialog.Designer.cs
- GUI/ErrorDialog.cs
- GUI/ErrorDialog.resx
- GUI/Localization/de-DE/ErrorDialog.de-DE.resx
If you start downloading multiple modules in GUI and more than one of them fail, you'll get an unhandled exception like this:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The form is already displayed as a modal dialog.
at System.Windows.Forms.Form.ShowDialog (System.Windows.Forms.IWin32Window owner) [0x00081] in <f73fa304d089422f9e23b25394111843>:0 
at System.Windows.Forms.Form.ShowDialog () [0x00000] in <f73fa304d089422f9e23b25394111843>:0 
at CKAN.ErrorDialog.ShowErrorDialog (System.String text, System.Object[] args) [0x00071] in <ea98fd2118b84fc7ad1a2141a259ca95>:0 
```
In KSP-CKAN/CKAN#2756 we started handling individual module download success or failure immediately, regardless of …
> Handle multiple errors in same ErrorDialog

- Core/Net/NetAsyncDownloader.cs
- Core/Net/NetAsyncModulesDownloader.cs
- Core/Net/NetModuleCache.cs
- GUI/Localization/de-DE/Main.de-DE.resx
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/Main.resx
- GUI/MainModInfo.cs
- GUI/MainModList.cs
- GUI/Properties/Resources.Designer.cs
- GUI/Properties/Resources.de-DE.resx
- GUI/Properties/Resources.resx
When you click the Download button in the mod info pane or right click a row and choose Download Contents, the GUI switches to the progress tab and begins downloading the module. The tabstrip is not locked down.
If you switch back to the mod list and initiate a second manual download while the first is still in progress, CKAN crashes with an exception like this:
```
System.InvalidOperationException: This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.
at System.ComponentModel.BackgroundWorker.RunWorkerAsync (System.Object argument) [0x00008] in <3310c48c8d57467d8dc60ad91e20e6c6>:0 
at (wrapper remoting-invoke-with-check) System.ComponentModel.BackgroundWorker.RunWorkerAsync(object)
at CKAN.MainModInfo.StartDownload (CKAN.GUIMod module) [0x00039] in …
```
> Multiple manual downloads, uncached filter, purge option

- Core/Versioning/ModuleVersion.cs
- Netkan/Processors/Inflator.cs
- Netkan/Processors/QueueHandler.cs
- Netkan/Program.cs
- Netkan/Transformers/EpochTransformer.cs
- Netkan/Transformers/ITransformer.cs
- Spec.md
- Tests/NetKAN/MainClass.cs
- Tests/NetKAN/NetkanOverride.cs
- Tests/NetKAN/Transformers/AvcKrefTransformerTests.cs
- Tests/NetKAN/Transformers/AvcTransformerTests.cs
- Tests/NetKAN/Transformers/CurseTransformerTests.cs
- Tests/NetKAN/Transformers/DownloadAttributeTransformerTests.cs
- Tests/NetKAN/Transformers/EpochTransformerTests.cs
- Tests/NetKAN/Transformers/GeneratedByTransformerTests.cs
- Tests/NetKAN/Transformers/GithubTransformerTests.cs
- Tests/NetKAN/Transformers/HttpTransformerTests.cs
- Tests/NetKAN/Transformers/InternalCkanTransformerTests.cs
- Tests/NetKAN/Transformers/MetaNetkanTransformerTests.cs
- Tests/NetKAN/Transformers/SpacedockTransformerTests.cs
- Tests/NetKAN/Transformers/StripNetkanMetadataTransformerTests.cs
- Tests/NetKAN/Transformers/VersionEditTransformerTests.cs
This PR grew out of a sidebar discussion on #2789. Please discuss it here instead of there, to allow that issue to stay focused on its main goals.
As things stand, CKAN-meta will inevitably accumulate inaccurate metadata every time a mod author releases an out-of-order version, which includes things like dropping a 'v' prefix or changing it to/from capital 'V', numbering like `["0.6", "0.65", "0.7"]`, accidentally dropping the `0.` prefix of a version, fat-fingering an extra '.' in a version number, etc, Users will get "stuck" on older versions because the newer release isn't considered newer by CKAN.
There are no safeguards against such things (and no alerts that it has happened), and all require manual clean-up in the form of updating the `x_netkan_epoch` property in .netkan files and …
> Auto-epoch based on queue message attribute

- .travis.yml
Travis was definitely a little spammy, but the lack having a notification post deployment success is useful.
This limits the notification to the conditions that match our deployment conditions. We could drop the check for master if we want to be notified once per set of builds. Though we should consider moving to [stages](https://docs.travis-ci.com/user/build-stages). Which I might do on NetKAN-infra as an example first.
> Notify on Deployment Success

- Netkan/Services/ModuleService.cs
If a module has a syntax error in its version file, the error in netkan looks like this:
> 2074 [1] FATAL CKAN.NetKAN.Program (null) - After parsing a value an unexpected character was encountered: ". Path 'KSP_VERSION_MAX', line 37, position 4.
It requires some guessing and/or experience to figure out that this is talking about trying to parse the version file.
Now we catch that exception and throw a new more descriptive Kraken that explains that it was parsing a version file and gives its path:
> 2046 [1] FATAL CKAN.NetKAN.Program (null) - Error parsing version file GameData/Severedsolo/OhScrap/OhScrap.version: After parsing a value an unexpected character was encountered: ". Path 'KSP_VERSION_MAX', line 37, position 4.
This should help netkan users to investigate errors, and makes it …
> Better parsing errors for version files

- Core/ModuleInstaller.cs
- Core/Net/NetFileCache.cs
- Core/Net/NetModuleCache.cs
- Netkan/Processors/Inflator.cs
- Netkan/Services/FileService.cs
- Netkan/Transformers/DownloadAttributeTransformer.cs
- Tests/NetKAN/Services/FileServiceTests.cs
We'd like to reduce the CPU usage of the Inflator component of the infrastructure. Toward that end, we added some more debug statements and observed `netkan.exe`'s output carefully, which turned up some surprising issues...
`NetFileCache` uses a `Dictionary` to map from the URL hash (first 8 characters of the download URL's SHA1 interpreted in hexadecimal) to the file path in cache. This is intended to find cached files quickly without checking every single file. To try to protect this mapping from unexpected changes, we listen to events from `FileSystemWatcher` and clear this dictionary whenever they fire, which results in it being regenerated the next time it's needed.
The `DownloadAttributeTransformer` is in charge of populating file hashes and other properties based on the contents of …
> Retain URL hash cache, cache file hashes

- Cmdline/Action/Prompt.cs
I want to use `ckan prompt` to speed up the PR validation scripts by combining multiple commands, see KSP-CKAN/xKAN-meta_testing#55.
Currently if a command executed via `ckan prompt` fails, errors are printed but the process keeps running and eventually returns success at exit. This makes sense for an interactive mode where a user is reading the errors and can try again, but for what I have in mind it means that failed installations would be ignored and marked as successful.
Now if a command fails within `ckan prompt`, and we're running in headless mode, the process will exit with the failed command's return value. This will allow it to be used in scripts that check for success or failure of operations.
> Return failure on failed commands for headless prompt

- Core/Net/Net.cs
- Netkan/Services/CachingHttpService.cs
- Netkan/Services/IHttpService.cs
- Netkan/Sources/Github/GithubApi.cs
- Netkan/Sources/Github/IGithubApi.cs
- Netkan/Transformers/AvcKrefTransformer.cs
- Netkan/Transformers/AvcTransformer.cs
- Netkan/Transformers/MetaNetkanTransformer.cs
- Netkan/Transformers/NetkanTransformer.cs
- Tests/NetKAN/Transformers/AvcKrefTransformerTests.cs
- Tests/NetKAN/Transformers/AvcTransformerTests.cs
- Tests/NetKAN/Transformers/MetaNetkanTransformerTests.cs
The bot intermittently reports "GitHub API rate limit exceeded" for various modules, most commonly Telemachus, but also recently many of the KerboKatz utilities and the Half/QuarterRSS textures. This is a custom error message created in #2904 that indicates the server headers include `X-RateLimit-Remaining: 0`.
As @techman83 noted in #2945, the rate limit API reported 0 remaining unauthenticated API usages (but we are nowhere near the limit for *authenticated* usages):
```
{
"resources": {
"core": {
"limit": 60,
"remaining": 0,
"reset": 1576563098
},
"search": {
"limit": 10,
"remaining": 10,
"reset": 1576561641
},
"graphql": {
"limit": 0,
"remaining": 0,
"reset": 1576565181
},
"integration_manifest": {
"limit": 5000,
"remaining": 5000,
"reset": 1576565181
}
},
"rate": {
"limit": 60, …
```
> Coerce GitHub URLs into the authenticated API in Netkan

- Netkan/Services/CachingHttpService.cs
- Netkan/Sources/Github/GithubApi.cs
```
New inflation error for HalfRSS-Textures2048: GitHub API rate limit exceeded.
New inflation error for HalfRSS-Textures4096: GitHub API rate limit exceeded.
New inflation error for HalfRSS-Textures8192: GitHub API rate limit exceeded.
New inflation error for KerboKatzSmallUtilities-Afterburner: GitHub API rate limit exceeded.
New inflation error for KerboKatzSmallUtilities-AutoBalancingLandingLeg: GitHub API rate limit exceeded.
New inflation error for KerboKatzSmallUtilities-DisableTempGauges: GitHub API rate limit exceeded.
New inflation error for KerboKatzSmallUtilities: GitHub API rate limit exceeded.
New inflation error for KerboKatzSmallUtilities-DailyFunds: GitHub API rate limit exceeded.
New inflation error for KerboKatzSmallUtilities-DestroyAll: GitHub API rate limit exceeded. …
```
> Request fewer GitHub releases and cache string URLs in Netkan

- GUI/URLHandlers.cs
Discovered this on Ubuntu Server 16.04, where I didn't have this directory.
`Directory.CreateDirectory` creates directories recursively, so it should be fine.
> Create ~/.local/share/applications/ if it doesn't exist (Linux)

- CKAN.schema
At one point in KSP-CKAN/NetKAN#7600, a confusing error happened because one module had this:
```json
"provides": [ "AIES-Antenna_Patches" ],
```
And this conflict:
```json
{ "name": "AIES-Antenna-Patches" }
```
`AIES-Antenna-Patches` is depended on by a dependency of this module, but since the `provides` had an underscore, it tried to pull in a conflicting module and got all confused.
The schema just has `provides` as a list of strings! But it has to be identifiers to be useful, so this is a missing guardrail that would have helped in this case.
Now the schema is updated to consider `provides` a list of identifiers. This will help with validating pull requests; if an element of `provides` has an invalid format, an error will be raised specifically about that.
> Make provides a list of identifiers in the schema

- Netkan/ConsoleUser.cs
- Netkan/Services/IModuleService.cs
- Netkan/Services/ModuleService.cs
- Netkan/Validators/InstallsFilesValidator.cs
- Netkan/Validators/LicensesValidator.cs
#2788 created Netkan validation checks based on the legacy Perl bot and the pull request validation scripts. There's one remaining check that isn't migrated yet:
https://github.com/KSP-CKAN/xKAN-meta_testing/blob/73cd8a319ae8833e40b52b49976afe49d00db30b/NetKAN/build.sh#L455-L462
```bash
gamedata=($(find dummy_ksp/GameData/. -name GameData -exec sh -c 'if test -d "{}"; then echo "{}";fi' \;))
if (( ${#gamedata[@]} > 0 ))
then
echo "GameData directory found within GameData"
printf '%s\n' "Path: ${gamedata[@]}"
exit 1;
fi
```
In KSP-CKAN/NetKAN#7587 we discovered that MoreHabPlanets' current latest version was blocked by this check. Presumably it was fine when first indexed, then the format of the ZIP changed later. This could have been caught by the bot as soon as that release was inflated …
> Catch nested GameData folders in Netkan

- Core/Extensions/DictionaryExtensions.cs
- Core/Registry/Registry.cs
- Core/Registry/Tags/ModuleTag.cs
- Core/Registry/Tags/ModuleTagList.cs
- Core/Types/CkanModule.cs
- GUI/CKAN-GUI.csproj
- GUI/EditLabelsDialog.Designer.cs
- GUI/EditLabelsDialog.cs
- GUI/EditLabelsDialog.resx
- GUI/GUIConfiguration.cs
- GUI/GUIMod.cs
- GUI/Labels/ModuleLabel.cs
- GUI/Labels/ModuleLabelList.cs
- GUI/Localization/de-DE/EditLabelsDialog.de-DE.resx
- GUI/Localization/de-DE/Main.de-DE.resx
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/Main.resx
- GUI/MainAllModVersions.Designer.cs
- GUI/MainChangeset.cs
- GUI/MainInstall.cs
- GUI/MainLabels.cs
- GUI/MainModInfo.Designer.cs
- GUI/MainModInfo.cs
- GUI/MainModList.cs
- GUI/Properties/Resources.Designer.cs
- GUI/Properties/Resources.de-DE.resx
- GUI/Properties/Resources.resx
- Tests/GUI/GH1866.cs
- Tests/GUI/MainModList.cs
A longstanding common request is to provide additional tools for organizing and managing mods. Some of the use cases from various issue descriptions:
- we may have to remove some mods from our list due to their incompatibilities, but we don't want to forget about it or would like to get and alert when they're updated
- for checking about release new version
- keep tabs on a mod that hasn't been updated yet
- a particular mod that we really want to try out, but just don't feel ready yet for all of their complications, settings, or learning curves
- for look into it later
- for testing in the future
- for keep in list nearby
- single out mods they use for particular playstyles
- mods that I ended up preferring not to have installed
- avoid reevaluating a mod they've already rejected
In …
> Custom mod labels, favorites, hiding

- Netkan/CmdLineOptions.cs
- Netkan/Program.cs
- Netkan/Transformers/EpochTransformer.cs
A lot of auto-epoching pull requests have been updates for versions that were created in previous PRs, see KSP-CKAN/CKAN-meta#1621 and KSP-CKAN/CKAN-meta#1694 for an example. In this case we have already confirmed in the first PR that the version should exist, so manual review isn't needed for later ones.
Now we only enable staging if the resulting version after auto-epoching is greater than the previous highest version. If we're updating a version that already exists, staging isn't needed.
> Only stage auto-epoch when creating new file

- GUI/CKAN-GUI.csproj
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/MainAllModVersions.Designer.cs
- GUI/MainModInfo.Designer.cs
- GUI/MainModInfo.cs
- GUI/MainModList.cs
- GUI/MainRecommendations.cs
- GUI/MainTabControl.cs
- GUI/ManageKspInstances.Designer.cs
- GUI/SettingsDialog.Designer.cs
- GUI/ThemedListView.cs
- GUI/ThemedTabControl.cs
You can configure the legacy system colors on Windows to change how WinForms apps display. In Windows 7:
1. Right click desktop
2. Personalize
3. Window Color (in the bottom middle)
4. Advanced appearance settings...
5. Choose the colors that you want to use
CKAN doesn't look very good in this mode:
Note that it looks OK if you choose one of the more extreme "high contrast" themes, but these also change your window borders and everything else, so it's not a great solution:
- A number of the WinForms controls default to a hard coded style instead of obeying the system theme
- The status bar needed its BackColor/ForeColor properties set
- The mod list has visual styles turned off and its header color set to obey the system colors
- `ThemedListView` and `ThemedTabControl` classes are created …
> Obey system colors for dark theme support

- ConsoleUI/ModInfoScreen.cs
- Core/Utilities.cs
- GUI/Main.cs
- GUI/MainInstall.cs
- GUI/MainModInfo.cs
- GUI/MainModList.cs
- GUI/ManageKspInstances.cs
- GUI/SettingsDialog.cs
- GUI/Util.cs
The homepage and repository links in GUI used to work fine, but recently they stopped working for me. Some investigation revealed that this exception was being thrown:
```
System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file
at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00102] in <dfe42095fd31410e95d8021f755c3557>:0 
at System.Diagnostics.Process.Start () [0x00032] in <dfe42095fd31410e95d8021f755c3557>:0 
at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <dfe42095fd31410e95d8021f755c3557>:0 
at CKAN.Util.TryOpenWebPage (System.String url, System.Collections.Generic.IEnumerable`1[T] …
```
> Workaround to launch URLs

- Core/Extensions/EnumerableExtensions.cs
- Core/ModuleInstaller.cs
- Core/Registry/AvailableModule.cs
- Core/Registry/Registry.cs
- Core/Relationships/RelationshipResolver.cs
- Core/Relationships/SanityChecker.cs
- GUI/GUIMod.cs
- GUI/MainChangeset.cs
- GUI/MainInstall.cs
- GUI/MainLabels.cs
- GUI/MainRecommendations.cs
- Netkan/Transformers/LocalizationsTransformer.cs
In #2928 I learned how `yield return` works; yes, it pauses execution of the function until we request the next element of the sequence, but if you try to access *earlier* members of the sequence, the whole function will start over again from the beginning, re-running any expensive logic that we were hoping to skip. In other words, it's lazily-evaluated but not memoizing.
This is particularly inconvenient when we want to retrieve and use a sequence and take a special action when it's empty. The idiomatic approach is to use `.Any()` followed by a `foreach`, but this suffers from the duplicate execution problem described above; any expensive steps that we take at the start of the function will be repeated (including network requests!). #2928 worked around this with a `bool foundAny`, which …
> Memoize lazily evaluated sequences

- Core/ModuleInstaller.cs
- GUI/MainModInfo.cs
When scrolling through the mod list with the arrow keys with the file contents tab opened, the GUI will freeze when you encounter biggish cached mods with a lot of files.
It is noticeable with zips around 3 MiB (depending on count of contained files and PC of course) and really disruptive with mods above 50 MiB.
I traced the issue down to the health checks of the zip files done in `NetFileCache.GetCachedZip()`.
Use `GetCachedFilename()` instead of `GetCachedZip()` in `ModuleInstaller.GetModuleContentsList()`, which does the same (searching the file and returning the file name if it is cached) without the checks.
To account for the possibility of bit flips and other data degradation problems, catch possible exceptions when opening the zip and return `null`, which would also be returned if …
> Don't check ZIP health in ModuleInstaller.GetModuleContentsList()

- ConsoleUI/Toolkit/ConsolePopupMenu.cs
- Core/Registry/Tags/ModuleTagList.cs
- Core/Types/ModuleInstallDescriptor.cs
- GUI/EditLabelsDialog.Designer.cs
- GUI/EditLabelsDialog.cs
- GUI/Labels/ModuleLabelList.cs
- GUI/Localization/de-DE/Main.de-DE.resx
- GUI/Main.Designer.cs
- GUI/Main.cs
- GUI/Main.resx
- GUI/MainChangeset.cs
- GUI/MainInstall.cs
- GUI/MainRecommendations.cs
- GUI/MainWait.cs
- GUI/TabController.cs
The spec includes a [`supports`] relationship for indicating compatibility with another mod, but not a recommendation or suggestion that the mod be installed. For example, a parts mod that includes cfg files that enable its parts to be scaled with TweakScale might do this:
[`supports`]: https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#supports
```json
"supports": [
{ "name": "TweakScale" }
],
```
Other examples include mods that add parts to specific tech trees, mods that create props or multi-function display pages for IVAs, etc.
Currently this relationship does not drive any functionality; it's only displayed in the Relationships tab of mod info, as a smiley face:
Since mod authors do sometimes fill in this relationship, it would be nice if it did something (sensible). I think it …
> Add "supports" relationships to recommendations screen

- .travis.yml
- Cmdline/Action/Available.cs
- Cmdline/Action/Search.cs
- Cmdline/Action/Show.cs
- Cmdline/Action/Update.cs
- ConsoleUI/ModInfoScreen.cs
- ConsoleUI/ModListScreen.cs
- Core/Net/Repo.cs
- Core/Registry/CompatibilitySorter.cs
- Core/Registry/IRegistryQuerier.cs
- Core/Registry/Registry.cs
- Core/Types/GameComparator/BaseGameComparator.cs
- Core/Types/GameComparator/GrasGameComparator.cs
- Core/Versioning/KspVersionCriteria.cs
- GUI/Main.cs
- GUI/MainAllModVersions.cs
- GUI/MainModList.cs
- GUI/MainRepo.cs
- Tests/Core/ModuleInstaller.cs
- Tests/Core/Registry/Registry.cs
The Compatible and Incompatible filters in GUI check dependencies, but only one level. For example, OuterPlanetsMod depends on Kopernicus depends on ModularFlightIntegrator; if the first two are compatible and the third isn't, then OuterPlanetsMod appears to be installable but will fail.
We do extra work when loading the GUI filters, since `Registry.Available` and `Registry.Incompatible` both loop over all modules and check their dependencies, and the results are not re-used. Similarly, various operations that refresh the mod list are slower than they need to be because we re-check all those same relationships over again even if they haven't changed.
Sometimes "Available" includes incompatible modules:
- `Registry.available_modules`
- `Registry.AllAvailable`
- `Registry.SetAllAvailable`
- …
> Check all dependencies for compatibility checking

- .travis.yml
- Tests/Tests.csproj
- build
- build.cake
- packages.config
Recent net-core builds have been failing.
```
Error: The assembly name is invalid.
```
Today my Ubuntu upgraded from Mono 6.6 to Mono 6.8, and suddenly I was affected locally by the same problem for *all* builds.
See cake-build/cake#2695, it looks like a check was added to Mono in mono/mono#16446 to reject full pathnames for assemblies, but unfortunately parts of `Microsoft.CodeAnalysis` (closed source?) appear to pass full pathnames, which breaks Cake. This will probably need to be fixed on the Mono side, but I don't yet have enough information for a useful report.
The net-core builds were set to `mono: latest` instead of a specific version like everything else, so when this (apparently) broken version shipped we started using it immediately.
To fix the error:
- Now our net-core builds …
> Use Mono 6.6 and more recent versions of everything else

- Netkan/CKAN-netkan.csproj
- Netkan/Transformers/NetkanTransformer.cs
- Netkan/Transformers/StagingTransformer.cs
Currently we have 29 netkans with `x_netkan_staging` enabled because the KSP version compatibility info is hard coded in the netkan, and hence might be out of date anytime a new version is released. This has been a bit tedious to set manually for each such netkan, and it is pretty much the same thing every time, hence it would be nice to automate.
Now a new `StagingTransformer` does this automatically. It runs first so it can see the raw netkan data without interference by other transformers, and if it finds `ksp_version`, `ksp_version_min`, or `ksp_version_max`, it enables staging and sets the reason to a string explaining what keys were found, their values, and how to proceed. This way, **any** netkan with hard coded compatibility info will automatically be staged every time, and we can …
> Stage modules with hardcoded game versions

- CKAN.schema
- Core/Exporters/DelimeterSeparatedValueExporter.cs
- Core/Exporters/Exporter.cs
- Core/Registry/RegistryManager.cs
- Core/Types/CkanModule.cs
- Core/Types/Identifier.cs
- Core/Types/License.cs
- GUI/CKAN-GUI.csproj
- GUI/Controls/Changeset.cs
- GUI/Controls/ChooseProvidedMods.cs
- GUI/Controls/ChooseRecommendedMods.cs
- GUI/Controls/EditModpack.Designer.cs
- GUI/Controls/EditModpack.cs
- GUI/Controls/EditModpack.resx
- GUI/Localization/de-DE/EditModpack.de-DE.resx
- GUI/Localization/de-DE/Main.de-DE.resx
- GUI/Localization/en-US/EditModpack.en-US.resx
- GUI/Main/Main.Designer.cs
- GUI/Main/Main.cs
- GUI/Main/Main.resx
- GUI/Main/MainExport.cs
- GUI/Properties/Resources.Designer.cs
- GUI/Properties/Resources.de-DE.resx
- GUI/Properties/Resources.resx
- Netkan/Validators/AlphaNumericIdentifierValidator.cs
- Netkan/Validators/RelationshipsValidator.cs
Currently the File menu has an option called "Export installed mods..." that brings up a save window with several options:
Two of the options are for .ckan files, with the "modpack" option including mod versions and the favorites/favourites option omitting them. Also one of them treats the mods as dependencies and the other as recommendations; which is which? I don't know and neither do you, because that UI doesn't mention this!
The generated metadata of the .ckan options looks something like this:
```json
{
"kind": "metapackage",
"abstract": "A list of modules installed on the ksp-1.8.1 KSP instance",
"name": "installed-ksp-1.8.1",
"license": "unknown",
"version": "2020.01.24.09.25.48",
"identifier": "installed-ksp-1.8.1",
"spec_version": "v1.6",
"recommends": [
{
"name": …
```
> Edit modpack before export

- .travis.yml
The latest release (1.26.8) on Windows:
```
Unhandled Exception: System.ArgumentException: Object of type 'System.Globalization.CalendarId[]' cannot be converted to type 'System.Int32[]'.
at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
at System.Reflection.RtFieldInfo.UnsafeSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
at System.Runtime.Serialization.FormatterServices.SerializationSetValue(MemberInfo fi, Object target, Object value)
at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
at …
```
> Downgrade to building on Mono 5.20

- macosx/Makefile
The package for 1.26.8 on OSX apparently includes the right EXE, but the app bundle property says 1.26.6:
We had a snafu with Mono 6.6.0 in #2972, so all builds were regenerated by hand by @DasSkelett and replaced. Most likely he already had a file at `_build/osx/dmg/CKAN.app/Contents/Info.plist` generated previously with 1.26.6 in it. When he checked out the commit for 1.26.8 and recompiled, this file was not regenerated.
The `Makefile` directive for `Info.plist` uses both `Info.plist.in` and `CHANGELOG.md` (indirectly via the `$(VERSION)` variable) to generate its output, but only `Info.plist.in` is checked for changes currently.
Now `Info.plist` also depends on `CHANGELOG.md`, so it will be regenerated when we build a new version.
Fixes #2977.
> Refresh Info.plist if changelog has changed

- Core/Registry/Registry.cs
- Tests/Core/Registry/Registry.cs
When you check the mod list checkbox to install a mod, the latest version is chosen regardless of compatibility:
In #2963 we renamed `Registry.Available` to `Registry.CompatibleModules` and rewrote it to share a persistent data structure with `Registry.IncompatibleModules` that stores all the compatible `AvailableModule`s in one list and the incompatible ones in another list. Then all we have to do is return one `CkanModule` per `AvailableModule` in a list.
Previously we returned the latest `CkanModule` regardless of its compatibility. This meant that when a `GUIMod` got constructed for a given row, its `Mod` property could be set to an incompatible `CkanModule`, and this is what is used for the default version to install.
Now we pass the version criteria to `AvailableModule.Latest()` …
> Filter compatible modules by compatibility

- Core/Relationships/RelationshipResolver.cs
- GUI/Controls/ChooseRecommendedMods.Designer.cs
- GUI/Controls/ChooseRecommendedMods.cs
- GUI/Main/Main.Designer.cs
- GUI/Main/MainInstall.cs
- GUI/Main/MainRecommendations.cs
On the main mod list, if you select two mods to install that conflict, they'll be highlighted red and a message appears in the status bar.
In the recommendations list, if you select two mods to install that conflict, nothing special happens and you can proceed through to the install screen, where you'll receive an error message. This is frustrating and inconsistent.
Now:
- conflicting checked rows on the recommendations screen will be highlighted red
- the conflict will be explained in the status bar
- the Continue button is disabled until the conflict is resolved
- `RelationshipResolver.ConflictList` merges multiple conflicts per module and no longer returns useless information about their reasons for selection which was not used anywhere, so the message can be used in the status bar
- …
> Detect conflicts on recommendations screen

- GUI/Controls/ChooseRecommendedMods.cs
When loading the recommendations screen when it would contain multiple options:
```
at CKAN.ChooseRecommendedMods.RecommendedModsListView_ItemChecked(Object sender, EventArgs e)
at System.Windows.Forms.ListView.OnItemChecked(ItemCheckedEventArgs e)
at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
at System.Windows.Forms.ListView.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
I have no idea how I didn't encounter this during development of #2981, since that inherently required loading this screen with multiple options to test. Maybe there's a race condition?
Apparently `ListView.Items` can contain `null`, specifically …
> Fix null reference in recommendations

- ConsoleUI/CKAN-ConsoleUI.csproj
- ConsoleUI/Toolkit/ConsoleTextBox.cs
```
Downloading "https://github.com/shadowmage45/TexturesUnlimited/releases/download/1.5.8.23/TexturesUnlimited-1.5.8.23.zip"                                                            ^ │
│ Downloading "https://github.com/raidernick/BDAnimationModules/releases/download/v0.6.5.7/BDanim_v0.6.5.7.zip"                                                                        ▒ │
│ Downloading "https://github.com/blowfishpro/B9PartSwitch/releases/download/v2.11.1/B9PartSwitch_v2.11.1.zip"                                                                         ▒ │
│ Downloading "https://github.com/linuxgurugamer/PatchManager/releases/download/0.0.16.4/PatchManager-0.0.16.4.zip"                                                                    ▒ │
│ Failed to download …
```
> Fix NRE on download errors in ConsoleUI

- GUI/Controls/ChooseProvidedMods.cs
- GUI/Controls/ChooseProvidedMods.resx
- GUI/Localization/de-DE/ChooseProvidedMods.de-DE.resx
- GUI/Localization/de-DE/Main.de-DE.resx
- GUI/Main/Main.resx
- GUI/Main/MainInstall.cs
- GUI/Main/MainProvides.cs
```
$ mono ./ckan.exe 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Windows.Forms.ListView.GetItemLocation (System.Int32 index) [0x00018] in <91b18fcffc5e47d3a5d52c9f469a1a52>:0 
at System.Windows.Forms.ListView.get_LastVisibleIndex () [0x00043] in <91b18fcffc5e47d3a5d52c9f469a1a52>:0 
at (wrapper remoting-invoke-with-check) System.Windows.Forms.ListView.get_LastVisibleIndex()
at System.Windows.Forms.ThemeWin32Classic.DrawListViewItems (System.Drawing.Graphics dc, System.Drawing.Rectangle clip, System.Windows.Forms.ListView control) [0x00011] in <91b18fcffc5e47d3a5d52c9f469a1a52>:0 
at System.Windows.Forms.ListView+ItemControl.OnPaintInternal (System.Windows.Forms.PaintEventArgs pe) [0x00011] in <91b18fcffc5e47d3a5d52c9f469a1a52>:0 
at …
```
> Only update provides tab from GUI thread

- Core/ModuleInstaller.cs
If you have a lot of modules installed, ConsoeUI's "audit recommendations" option can throw an exception:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: An item with the same key has already been added. Key: NearFutureConstruction 1.1.4
at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x0015a] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <c4bddbfe864a4b8191bb818d6b204e9d>:0 
at CKAN.ConsoleUI.DependencyScreen.generateList (System.Collections.Generic.HashSet`1[T] inst) [0x001f4] in <ce28b1fd8caa4b339aed683ae3b21ffc>:0 
at CKAN.ConsoleUI.DependencyScreen..ctor (CKAN.KSPManager mgr, …
```
> Fix ArgumentException in ConsoleUI recommendations
